
CREATE TABLE "SIGASR"."SR_PESQUISA"
	(
		"ID_PESQUISA" NUMBER(19,0) NOT NULL,
		"HIS_ATIVO"            NUMBER(10,0),
		"HIS_DT_FIM" TIMESTAMP (6),
		"HIS_DT_INI" TIMESTAMP (6) NOT NULL,
		"HIS_ID_INI"               NUMBER(19,0),
		"NOME_PESQUISA" VARCHAR2(255 CHAR) NOT NULL,
		"DESCR_PESQUISA"  VARCHAR2(255 CHAR),
		PRIMARY KEY ("ID_PESQUISA")
	);
CREATE SEQUENCE SR_PESQUISA_SEQ;

CREATE TABLE "SIGASR"."SR_TIPO_PERGUNTA"
	(
		"ID_TIPO_PERGUNTA" NUMBER(19,0) NOT NULL,
		"NOME_TIPO_PERGUNTA" VARCHAR2(255 CHAR) NOT NULL,
		"DESCR_TIPO_PERGUNTA"  VARCHAR2(255 CHAR),
		PRIMARY KEY ("ID_TIPO_PERGUNTA")
	);
	
CREATE TABLE "SIGASR"."SR_PERGUNTA"
	(
		"ID_PERGUNTA" NUMBER(19,0) NOT NULL,
		"HIS_ATIVO"            NUMBER(10,0),
		"HIS_DT_FIM" TIMESTAMP (6),
		"HIS_DT_INI" TIMESTAMP (6) NOT NULL,
		"HIS_ID_INI"               NUMBER(19,0),
		"DESCR_PERGUNTA"  VARCHAR2(255 CHAR),
		"ORDEM_PERGUNTA"      NUMBER(19,0),
		"ID_TIPO_PERGUNTA" NUMBER(19,0) NOT NULL,
		"ID_PESQUISA" NUMBER(19,0),
		PRIMARY KEY ("ID_PERGUNTA"),
		CONSTRAINT "PERGUNTA_PESQUISA_FK" 
			FOREIGN KEY ("ID_PESQUISA") 
			REFERENCES "SIGASR"."SR_PESQUISA" ("ID_PESQUISA"),
		CONSTRAINT "PERGUNTA_TIPO_FK" 
			FOREIGN KEY ("ID_TIPO_PERGUNTA") 
			REFERENCES "SIGASR"."SR_TIPO_PERGUNTA" ("ID_TIPO_PERGUNTA")
	);
CREATE SEQUENCE SR_PERGUNTA_SEQ;

CREATE TABLE "SIGASR"."SR_RESPOSTA"
	(
		"ID_RESPOSTA" NUMBER(19,0) NOT NULL,
		"DESCR_RESPOSTA"  VARCHAR2(255 CHAR),
		"VALOR_RESPOSTA"      NUMBER(19,0),
		"ID_PERGUNTA" NUMBER(19,0),
		"ID_AVALIACAO" NUMBER(19,0),
		PRIMARY KEY ("ID_RESPOSTA"),
		CONSTRAINT "RESPOSTA_PERGUNTA_FK" 
			FOREIGN KEY ("ID_PERGUNTA") 
			REFERENCES "SIGASR"."SR_PERGUNTA" ("ID_PERGUNTA"),
		CONSTRAINT "RESPOSTA_AVALIACAO_FK" 
			FOREIGN KEY ("ID_AVALIACAO") 
			REFERENCES "SIGASR"."SR_MOVIMENTACAO" ("ID_MOVIMENTACAO")
	);
CREATE SEQUENCE SR_RESPOSTA_SEQ;

alter table sigasr.sr_movimentacao add 
(
	ID_PESQUISA				NUMBER(19,0),
	CONSTRAINT SR_MOV_PESQUISA_FK FOREIGN KEY (ID_PESQUISA) REFERENCES SR_PESQUISA(ID_PESQUISA)
);

alter table sigasr.sr_configuracao
rename column pesquisa_satisfacao to id_pesquisa;

alter table sigasr.sr_configuracao
modify (id_pesquisa number (19,0));


insert into sigasr.sr_tipo_pergunta values (1, 'Texto Livre', null);
insert into sigasr.sr_tipo_pergunta values (2, 'Nota de 1 a 5', null);
commit;