--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Abril-04-2018   
--------------------------------------------------------
-- Não é possível renderizar a DLL TABLE para o objeto SIGAPMP.AGENDAMENTOS com o DBMS_METADATA tentando um gerador interno.
COMMENT ON COLUMN SIGAPMP.AGENDAMENTOS.MATRICULA IS 'matrícula do usuário que agendou.';
COMMENT ON COLUMN SIGAPMP.AGENDAMENTOS.SESB_PESSOA IS 'T2 Quando segunda instância, RJ quando primeira instância e ES quando primeira instância';
CREATE TABLE SIGAPMP.AGENDAMENTOS 
(
  HORA_AG VARCHAR2(4 CHAR) NOT NULL 
, DATA_AG TIMESTAMP(6) NOT NULL 
, MATRICULA CHAR(6 BYTE) DEFAULT null 
, ORGAO VARCHAR2(15 CHAR) 
, PERICIADO VARCHAR2(50 CHAR) 
, PERITO_JUIZO VARCHAR2(50 CHAR) 
, PERITO_PARTE VARCHAR2(50 CHAR) 
, PROCESSO VARCHAR2(50 CHAR) 
, COD_LOCAL VARCHAR2(3 CHAR) NOT NULL 
, SESB_PESSOA CHAR(2 BYTE) DEFAULT NULL 
, CONSTRAINT AGENDAMENTOS_PK PRIMARY KEY 
  (
    COD_LOCAL 
  , HORA_AG 
  , DATA_AG 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)ALTER TABLE SIGAPMP.AGENDAMENTOS
ADD CONSTRAINT COD_LOCAL_NOTNULL CHECK 
(COD_LOCAL IS NOT NULL)
ENABLE
ALTER TABLE SIGAPMP.AGENDAMENTOS
ADD CONSTRAINT DATA_AG_NOTNULL CHECK 
(DATA_AG IS NOT NULL)
ENABLE
ALTER TABLE SIGAPMP.AGENDAMENTOS
ADD CONSTRAINT HORA_AG_NOTNULL CHECK 
(HORA_AG IS NOT NULL)
ENABLEALTER TABLE SIGAPMP.AGENDAMENTOS
ADD CONSTRAINT LOCAIS_AGENDAMENTOS_FK FOREIGN KEY
(
  COD_LOCAL 
)
REFERENCES SIGAPMP.LOCAIS
(
  COD_LOCAL 
)
ENABLE
-- Não é possível renderizar a DLL TABLE para o objeto SIGAPMP.FORUNS com o DBMS_METADATA tentando um gerador interno.
CREATE TABLE SIGAPMP.FORUNS 
(
  COD_FORUM NUMBER(10, 0) NOT NULL 
, DESCRICAO_FORUM VARCHAR2(40 CHAR) 
, MURAL VARCHAR2(1000 BYTE) 
, CONSTRAINT FORUNS_PK PRIMARY KEY 
  (
    COD_FORUM 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Não é possível renderizar a DLL TABLE para o objeto SIGAPMP.LOCAIS com o DBMS_METADATA tentando um gerador interno.
CREATE TABLE SIGAPMP.LOCAIS 
(
  COD_LOCAL VARCHAR2(3 CHAR) NOT NULL 
, DIAS VARCHAR2(40 CHAR) 
, ENDERECO VARCHAR2(100 CHAR) 
, EXIBIR NUMBER(10, 0) NOT NULL 
, HORA_FIM VARCHAR2(8 CHAR) 
, HORA_INI VARCHAR2(8 CHAR) 
, INTERVALO_ATENDIMENTO NUMBER(10, 0) 
, LOCAL VARCHAR2(30 CHAR) 
, ORDEM_APRESENTACAO NUMBER(10, 0) NOT NULL 
, COD_FORUM NUMBER(10, 0) 
, CONSTRAINT SYS_C00161510 PRIMARY KEY 
  (
    COD_LOCAL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)ALTER TABLE SIGAPMP.LOCAIS
ADD CONSTRAINT FK87FAFA2B57400B4F FOREIGN KEY
(
  COD_FORUM 
)
REFERENCES SIGAPMP.FORUNS
(
  COD_FORUM 
)
ENABLE
-- Não é possível renderizar a DLL TABLE para o objeto SIGAPMP.PERITOS com o DBMS_METADATA tentando um gerador interno.
CREATE TABLE SIGAPMP.PERITOS 
(
  CPF_PERITO CHAR(50 BYTE) NOT NULL 
, NOME_PERITO CHAR(200 BYTE) 
, CONSTRAINT "peritosPk" PRIMARY KEY 
  (
    CPF_PERITO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)ALTER TABLE SIGAPMP.PERITOS
ADD CONSTRAINT CPF_PERITOS01 CHECK 
(CPF_PERITO IS NOT NULL)
ENABLE
-- Não é possível renderizar a DLL TABLE para o objeto SIGAPMP.USUARIOFORUM com o DBMS_METADATA tentando um gerador interno.
COMMENT ON COLUMN SIGAPMP.USUARIOFORUM.MATRICULA_USU IS 'Matrícula numérica do usuário que pode agendar perícias.';
COMMENT ON COLUMN SIGAPMP.USUARIOFORUM.NOME_USU IS 'Nome do
usuário que pode agendar perícias.';
COMMENT ON COLUMN SIGAPMP.USUARIOFORUM.COD_FORUM IS 'Código do
forum onde o usuário vai agendar a perícia.';
COMMENT ON COLUMN SIGAPMP.USUARIOFORUM.SESB_PESSOA IS 'T2
quando segunda instância, RJ quando primeira instância, ES
quando primeira instância. x quando desconhecido';
CREATE TABLE SIGAPMP.USUARIOFORUM 
(
  MATRICULA_USU VARCHAR2(6 CHAR) NOT NULL 
, NOME_USU VARCHAR2(50 CHAR) 
, COD_FORUM NUMBER(10, 0) NOT NULL 
, SESB_PESSOA CHAR(2 BYTE) DEFAULT 'x' NOT NULL 
, CONSTRAINT USUARIOFORUM_PK PRIMARY KEY 
  (
    SESB_PESSOA 
  , MATRICULA_USU 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)ALTER TABLE SIGAPMP.USUARIOFORUM
ADD CONSTRAINT FORUNS_USUARIOFORUM_FK FOREIGN KEY
(
  COD_FORUM 
)
REFERENCES SIGAPMP.FORUNS
(
  COD_FORUM 
)
ENABLE
-- Não é possível renderizar a DLL INDEX para o objeto SIGAPMP.peritosPk com o DBMS_METADATA tentando um gerador interno.
CREATE UNIQUE INDEX SIGAPMP."peritosPk" ON SIGAPMP.PERITOS (CPF_PERITO) 
LOGGING 
TABLESPACE "SIGAPMP" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Não é possível renderizar a DLL INDEX para o objeto SIGAPMP.SYS_C00161506 com o DBMS_METADATA tentando um gerador interno.
CREATE INDEX SIGAPMP.SYS_C00161506 ON ()
-- Não é possível renderizar a DLL INDEX para o objeto SIGAPMP.SYS_C00161510 com o DBMS_METADATA tentando um gerador interno.
CREATE INDEX SIGAPMP.SYS_C00161510 ON ()
-- Não é possível renderizar a DLL INDEX para o objeto SIGAPMP.SYS_C00161520 com o DBMS_METADATA tentando um gerador interno.
CREATE INDEX SIGAPMP.SYS_C00161520 ON ()
-- Não é possível renderizar a DLL INDEX para o objeto SIGAPMP.SYS_C00189937 com o DBMS_METADATA tentando um gerador interno.
CREATE INDEX SIGAPMP.SYS_C00189937 ON ()
