-------------------------------------------
--	SCRIPT:Grant para VISUALIZACAO
-------------------------------------------

--SET DEFINE OFF;

ALTER SESSION SET CURRENT_SCHEMA=corporativo;

GRANT INSERT, SELECT, UPDATE , DELETE ON CORPORATIVO.DP_VISUALIZACAO TO SIGAWF;
GRANT SELECT ON CORPORATIVO.DP_VISUALIZACAO_SEQ TO SIGAWF;
GRANT INSERT, SELECT, UPDATE , DELETE ON CORPORATIVO.DP_VISUALIZACAO_ACESSO TO SIGAWF;
GRANT SELECT ON CORPORATIVO.DP_VISUALIZACAO_ACESSO_SEQ TO SIGAWF;
