--DROP TABLE SIGAWF.WF_CONFIGURACAO;

CREATE TABLE SIGAWF.WF_CONFIGURACAO (
  CONF_ID number(10) NOT NULL,
  DEFP_ID number(10) DEFAULT NULL
);

ALTER TABLE SIGAWF.WF_CONFIGURACAO
   ADD PRIMARY KEY (CONF_ID);

ALTER TABLE SIGAWF.WF_CONFIGURACAO
  ADD FOREIGN KEY (DEFP_ID)
  REFERENCES SIGAWF.WF_DEF_PROCEDIMENTO (DEFP_ID);