ALTER TABLE sigawf.wf_def_procedimento ADD DEFP_TP_PRINCIPAL VARCHAR(45) DEFAULT 'DOCUMENTO' NOT NULL;

ALTER TABLE sigawf.wf_def_procedimento ADD DEFP_TP_VINCULO_PRINCIPAL VARCHAR(45) DEFAULT 'OBRIGATORIO_E_EXCLUSIVO' NULL;

UPDATE sigawf.wf_procedimento SET PROC_TP_PRINCIPAL = 'DOCUMENTO' WHERE PROC_TP_PRINCIPAL = 'DOC';
