  CREATE TABLE siga.ex_sequencia
   (	ID_SEQ INT UNSIGNED NOT NULL AUTO_INCREMENT,  
		ANO_EMISSAO INT UNSIGNED NOT NULL, 
		NUMERO INT UNSIGNED NOT NULL, 
		NR_INICIAL INT UNSIGNED NOT NULL DEFAULT 1, 
		NR_FINAL INT UNSIGNED, 
		FL_ATIVO tinyint(4) DEFAULT 1,
		TIPO_SEQUENCIA  tinyint(4),
		ZERAR_INICIO_ANO CHAR(1) DEFAULT 1,
        CONSTRAINT EX_SEQUENCIA_PK PRIMARY KEY (ID_SEQ)
   ) ;

 CREATE TABLE siga.ex_protocolo
   (	
		ID_PROTOCOLO INT UNSIGNED NOT NULL AUTO_INCREMENT, 
		ID_DOC INT UNSIGNED NOT NULL,
		NUMERO INT UNSIGNED NOT NULL,		
		DATA DATE NOT NULL,
        CONSTRAINT EX_PROTOCOLO_PK PRIMARY KEY (ID_PROTOCOLO)
   ) ;

ALTER TABLE siga.ex_documento ADD (ID_PROTOCOLO INT UNSIGNED);
