INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) values (75,'Reordenar');
INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) values (76,'Ordenar');

ALTER TABLE SIGA.EX_DOCUMENTO ADD ORDENACAO_DOC VARCHAR2(200);