CREATE SEQUENCE "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER  NOCYCLE;

--------------------------------------------------------
--  DDL for Table ABASTECIMENTO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ABASTECIMENTO" 
   (	"ID" NUMBER(19,0), 
	"CONSUMOMEDIOEMKMPORLITRO" FLOAT(126), 
	"DATAHORA" TIMESTAMP (6), 
	"DISTANCIAPERCORRIDAEMKM" FLOAT(126), 
	"NIVELDECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"NUMERODANOTAFISCAL" VARCHAR2(255 CHAR), 
	"ODOMETROEMKM" FLOAT(126), 
	"PRECOPORLITRO" FLOAT(126), 
	"QUANTIDADEEMLITROS" FLOAT(126), 
	"TIPODECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"VALORTOTALDANOTAFISCAL" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"FORNECEDOR_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"ID_TITULAR" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."ABASTECIMENTO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("FORNECEDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("VALORTOTALDANOTAFISCAL" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("TIPODECOMBUSTIVEL" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("QUANTIDADEEMLITROS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("PRECOPORLITRO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("ODOMETROEMKM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("DISTANCIAPERCORRIDAEMKM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("CONSUMOMEDIOEMKMPORLITRO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ABASTECIMENTO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ABASTECIMENTO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CONSUMOMEDIOEMKMPORLITRO" FLOAT(126), 
	"DATAHORA" TIMESTAMP (6), 
	"DISTANCIAPERCORRIDAEMKM" FLOAT(126), 
	"NIVELDECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"NUMERODANOTAFISCAL" VARCHAR2(255 CHAR), 
	"ODOMETROEMKM" FLOAT(126), 
	"PRECOPORLITRO" FLOAT(126), 
	"QUANTIDADEEMLITROS" FLOAT(126), 
	"TIPODECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"VALORTOTALDANOTAFISCAL" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"FORNECEDOR_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"ID_TITULAR" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."ABASTECIMENTO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."ABASTECIMENTO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ABASTECIMENTO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AFASTAMENTO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AFASTAMENTO" 
   (	"ID" NUMBER(19,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"CONDUTOR_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."AFASTAMENTO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."AFASTAMENTO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AFASTAMENTO" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AFASTAMENTO" MODIFY ("DATAHORAINICIO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AFASTAMENTO" MODIFY ("DATAHORAFIM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AFASTAMENTO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AFASTAMENTO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AFASTAMENTO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"CONDUTOR_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."AFASTAMENTO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."AFASTAMENTO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AFASTAMENTO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ANDAMENTO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ANDAMENTO" 
   (	"ID" NUMBER(19,0), 
	"DATAANDAMENTO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"ESTADOREQUISICAO" VARCHAR2(255 CHAR), 
	"MISSAO_ID" NUMBER(19,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"RESPONSAVEL_ID_PESSOA" NUMBER(19,0), 
	"DATANOTIFICACAOWORKFLOW" TIMESTAMP (6)
   ) ;

  ALTER TABLE "SIGATP"."ANDAMENTO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ANDAMENTO" MODIFY ("RESPONSAVEL_ID_PESSOA" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ANDAMENTO" MODIFY ("REQUISICAOTRANSPORTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ANDAMENTO" MODIFY ("ESTADOREQUISICAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ANDAMENTO" MODIFY ("DATAANDAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ANDAMENTO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ANDAMENTO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ANDAMENTO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAANDAMENTO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"ESTADOREQUISICAO" VARCHAR2(255 CHAR), 
	"MISSAO_ID" NUMBER(19,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"RESPONSAVEL_ID_PESSOA" NUMBER(19,0), 
	"DATANOTIFICACAOWORKFLOW" TIMESTAMP (6)
   ) ;

  ALTER TABLE "SIGATP"."ANDAMENTO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."ANDAMENTO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ANDAMENTO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AUTODEINFRACAO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AUTODEINFRACAO" 
   (	"ID" NUMBER(19,0), 
	"DATADEPAGAMENTO" TIMESTAMP (6), 
	"DATADEVENCIMENTO" TIMESTAMP (6), 
	"DATADOPROCESSO" TIMESTAMP (6), 
	"DATAHORA" TIMESTAMP (6), 
	"DATALIMITEAPRESENTACAO" TIMESTAMP (6), 
	"FOIRECEBIDO" VARCHAR2(255 CHAR), 
	"LOCAL" VARCHAR2(255 CHAR), 
	"MEMORANDO" VARCHAR2(255 CHAR), 
	"NUMERODOPROCESSO" VARCHAR2(255 CHAR), 
	"VALOR" FLOAT(126), 
	"VALORCOMDESCONTO" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"PENALIDADE_ID" NUMBER(19,0), 
	"TIPODENOTIFICACAO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."AUTODEINFRACAO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("VALORCOMDESCONTO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" MODIFY ("PENALIDADE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AUTODEINFRACAO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AUTODEINFRACAO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATADEPAGAMENTO" TIMESTAMP (6), 
	"DATADEVENCIMENTO" TIMESTAMP (6), 
	"DATADOPROCESSO" TIMESTAMP (6), 
	"DATAHORA" TIMESTAMP (6), 
	"DATALIMITEAPRESENTACAO" TIMESTAMP (6), 
	"FOIRECEBIDO" VARCHAR2(255 CHAR), 
	"LOCAL" VARCHAR2(255 CHAR), 
	"MEMORANDO" VARCHAR2(255 CHAR), 
	"NUMERODOPROCESSO" VARCHAR2(255 CHAR), 
	"VALOR" FLOAT(126), 
	"VALORCOMDESCONTO" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"PENALIDADE_ID" NUMBER(19,0), 
	"TIPODENOTIFICACAO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."AUTODEINFRACAO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."AUTODEINFRACAO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AUTODEINFRACAO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AVARIA
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AVARIA" 
   (	"ID" NUMBER(19,0), 
	"DATADEREGISTRO" TIMESTAMP (6), 
	"DATADESOLUCAO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"VEICULO_ID" NUMBER(19,0), 
	"PODECIRCULAR" VARCHAR2(255 CHAR) DEFAULT 'SIM'
   ) ;

  ALTER TABLE "SIGATP"."AVARIA" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."AVARIA" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AVARIA" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table AVARIA_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."AVARIA_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATADEREGISTRO" TIMESTAMP (6), 
	"DATADESOLUCAO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"VEICULO_ID" NUMBER(19,0), 
	"PODECIRCULAR" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."AVARIA_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."AVARIA_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."AVARIA_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CONDUTOR
--------------------------------------------------------

  CREATE TABLE "SIGATP"."CONDUTOR" 
   (	"ID" NUMBER(19,0), 
	"CATEGORIACNH" VARCHAR2(255 CHAR), 
	"CELULARINSTITUCIONAL" VARCHAR2(255 CHAR), 
	"CELULARPESSOAL" VARCHAR2(255 CHAR), 
	"DATAVENCIMENTOCNH" TIMESTAMP (6), 
	"TELEFONEINSTITUCIONAL" VARCHAR2(255 CHAR), 
	"TELEFONEPESSOAL" VARCHAR2(255 CHAR), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"DPPESSOA_ID_PESSOA" NUMBER(19,0), 
	"OBSERVACAO" VARCHAR2(255 CHAR), 
	"EMAILPESSOAL" VARCHAR2(255 CHAR), 
	"CONTEUDOIMAGEMBLOB" BLOB DEFAULT EMPTY_BLOB(), 
	"NUMEROCNH" VARCHAR2(11 CHAR), 
	"ENDERECO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."CONDUTOR" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."CONDUTOR" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CONDUTOR_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."CONDUTOR_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CATEGORIACNH" VARCHAR2(255 CHAR), 
	"CELULARINSTITUCIONAL" VARCHAR2(255 CHAR), 
	"CELULARPESSOAL" VARCHAR2(255 CHAR), 
	"DATAVENCIMENTOCNH" TIMESTAMP (6), 
	"TELEFONEINSTITUCIONAL" VARCHAR2(255 CHAR), 
	"TELEFONEPESSOAL" VARCHAR2(255 CHAR), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"DPPESSOA_ID_PESSOA" NUMBER(19,0), 
	"OBSERVACAO" VARCHAR2(255 CHAR), 
	"EMAILPESSOAL" VARCHAR2(255 CHAR), 
	"CONTEUDOIMAGEMBLOB" BLOB DEFAULT EMPTY_BLOB(), 
	"NUMEROCNH" VARCHAR2(11 CHAR), 
	"ENDERECO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."CONDUTOR_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."CONDUTOR_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONDUTOR_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CONTROLEGABINETE
--------------------------------------------------------

  CREATE TABLE "SIGATP"."CONTROLEGABINETE" 
   (	"ID" NUMBER(19,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORASAIDA" TIMESTAMP (6), 
	"DATAHORARETORNO" TIMESTAMP (6), 
	"ITINERARIO" VARCHAR2(255 CHAR), 
	"ODOMETROEMKMRETORNO" FLOAT(126), 
	"ODOMETROEMKMSAIDA" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"NATUREZADOSERVICO" VARCHAR2(255 CHAR), 
	"OCORRENCIAS" VARCHAR2(255 CHAR), 
	"ID_TITULAR" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."CONTROLEGABINETE" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("ID_SOLICITANTE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("ODOMETROEMKMSAIDA" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("ODOMETROEMKMRETORNO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CONTROLEGABINETE_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."CONTROLEGABINETE_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORASAIDA" TIMESTAMP (6), 
	"DATAHORARETORNO" TIMESTAMP (6), 
	"ITINERARIO" VARCHAR2(255 CHAR), 
	"ODOMETROEMKMRETORNO" FLOAT(126), 
	"ODOMETROEMKMSAIDA" FLOAT(126), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"NATUREZADOSERVICO" VARCHAR2(255 CHAR), 
	"OCORRENCIAS" VARCHAR2(255 CHAR), 
	"ID_TITULAR" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."CONTROLEGABINETE_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."CONTROLEGABINETE_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."CONTROLEGABINETE_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table COR
--------------------------------------------------------

  CREATE TABLE "SIGATP"."COR" 
   (	"ID" NUMBER(19,0), 
	"NOME" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."COR" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."COR" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table COR_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."COR_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"NOME" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."COR_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."COR_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."COR_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table DIADETRABALHO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."DIADETRABALHO" 
   (	"ID" NUMBER(19,0), 
	"DIAENTRADA" VARCHAR2(255 CHAR), 
	"DIASAIDA" VARCHAR2(255 CHAR), 
	"HORAENTRADA" TIMESTAMP (6), 
	"HORASAIDA" TIMESTAMP (6), 
	"ESCALADETRABALHO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."DIADETRABALHO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."DIADETRABALHO" MODIFY ("ESCALADETRABALHO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."DIADETRABALHO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table DIADETRABALHO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."DIADETRABALHO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DIAENTRADA" VARCHAR2(255 CHAR), 
	"DIASAIDA" VARCHAR2(255 CHAR), 
	"HORAENTRADA" TIMESTAMP (6), 
	"HORASAIDA" TIMESTAMP (6), 
	"ESCALADETRABALHO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."DIADETRABALHO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."DIADETRABALHO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."DIADETRABALHO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ESCALADETRABALHO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ESCALADETRABALHO" 
   (	"ID" NUMBER(19,0), 
	"DATAVIGENCIAFIM" TIMESTAMP (6), 
	"DATAVIGENCIAINICIO" TIMESTAMP (6), 
	"CONDUTOR_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."ESCALADETRABALHO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ESCALADETRABALHO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ESCALADETRABALHO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ESCALADETRABALHO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."ESCALADETRABALHO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAVIGENCIAFIM" TIMESTAMP (6), 
	"DATAVIGENCIAINICIO" TIMESTAMP (6), 
	"CONDUTOR_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."ESCALADETRABALHO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."ESCALADETRABALHO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."ESCALADETRABALHO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table FINALIDADEREQUISICAO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."FINALIDADEREQUISICAO" 
   (	"ID" NUMBER(19,0), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"ID_ORGAO_ORI" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO" ADD UNIQUE ("DESCRICAO") ENABLE;
  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table FINALIDADEREQUISICAO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."FINALIDADEREQUISICAO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"ID_ORGAO_ORI" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table FORNECEDOR
--------------------------------------------------------

  CREATE TABLE "SIGATP"."FORNECEDOR" 
   (	"ID" NUMBER(19,0), 
	"BAIRRO" VARCHAR2(255 CHAR), 
	"CEP" VARCHAR2(255 CHAR), 
	"CNPJ" VARCHAR2(255 CHAR), 
	"COMPLEMENTO" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"ENDERECOVIRTUAL" VARCHAR2(255 CHAR), 
	"FAX" VARCHAR2(255 CHAR), 
	"LOCALIDADE" VARCHAR2(255 CHAR), 
	"LOGRADOURO" VARCHAR2(255 CHAR), 
	"NOMECONTATO" VARCHAR2(255 CHAR), 
	"RAMODEATIVIDADE" VARCHAR2(255 CHAR), 
	"RAZAOSOCIAL" VARCHAR2(255 CHAR), 
	"TELEFONE" VARCHAR2(255 CHAR), 
	"UF" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."FORNECEDOR" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."FORNECEDOR" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table FORNECEDOR_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."FORNECEDOR_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"BAIRRO" VARCHAR2(255 CHAR), 
	"CEP" VARCHAR2(255 CHAR), 
	"CNPJ" VARCHAR2(255 CHAR), 
	"COMPLEMENTO" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"ENDERECOVIRTUAL" VARCHAR2(255 CHAR), 
	"FAX" VARCHAR2(255 CHAR), 
	"LOCALIDADE" VARCHAR2(255 CHAR), 
	"LOGRADOURO" VARCHAR2(255 CHAR), 
	"NOMECONTATO" VARCHAR2(255 CHAR), 
	"RAMODEATIVIDADE" VARCHAR2(255 CHAR), 
	"RAZAOSOCIAL" VARCHAR2(255 CHAR), 
	"TELEFONE" VARCHAR2(255 CHAR), 
	"UF" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."FORNECEDOR_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."FORNECEDOR_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."FORNECEDOR_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table GRUPOVEICULO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."GRUPOVEICULO" 
   (	"ID" NUMBER(19,0), 
	"CARACTERISTICAS" VARCHAR2(255 CHAR), 
	"FINALIDADE" VARCHAR2(255 CHAR), 
	"LETRA" VARCHAR2(255 CHAR), 
	"NOME" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."GRUPOVEICULO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."GRUPOVEICULO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table GRUPOVEICULO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."GRUPOVEICULO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CARACTERISTICAS" VARCHAR2(255 CHAR), 
	"FINALIDADE" VARCHAR2(255 CHAR), 
	"LETRA" VARCHAR2(255 CHAR), 
	"NOME" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."GRUPOVEICULO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."GRUPOVEICULO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."GRUPOVEICULO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table LOTACAOATDREQUISICAO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."LOTACAOATDREQUISICAO" 
   (	"ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_LOTA_SOLICITANTE" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO" MODIFY ("ID_LOTA_SOLICITANTE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table LOTACAOATDREQUISICAO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."LOTACAOATDREQUISICAO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_LOTA_SOLICITANTE" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table LOTACAOVEICULO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."LOTACAOVEICULO" 
   (	"ID" NUMBER(19,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"ID_LOTA_SOLICITANTE" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"ODOMETROEMKM" FLOAT(126)
   ) ;

  ALTER TABLE "SIGATP"."LOTACAOVEICULO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."LOTACAOVEICULO" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOVEICULO" MODIFY ("ID_LOTA_SOLICITANTE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOVEICULO" MODIFY ("DATAHORAINICIO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOVEICULO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table LOTACAOVEICULO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."LOTACAOVEICULO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"ID_LOTA_SOLICITANTE" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"ODOMETROEMKM" FLOAT(126)
   ) ;

  ALTER TABLE "SIGATP"."LOTACAOVEICULO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."LOTACAOVEICULO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."LOTACAOVEICULO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table MISSAO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."MISSAO" 
   (	"ID" NUMBER(19,0), 
	"AVARIASAPARENTESRETORNO" VARCHAR2(255 CHAR), 
	"AVARIASAPARENTESSAIDA" VARCHAR2(255 CHAR), 
	"CARTAOABASTECIMENTO" VARCHAR2(255 CHAR), 
	"CARTAOSAIDA" VARCHAR2(255 CHAR), 
	"CARTAOSEGURO" VARCHAR2(255 CHAR), 
	"CONSUMOEMLITROS" FLOAT(126), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORARETORNO" TIMESTAMP (6), 
	"DATAHORASAIDA" TIMESTAMP (6), 
	"ESTADOMISSAO" VARCHAR2(255 CHAR), 
	"ESTEPE" VARCHAR2(255 CHAR), 
	"EXTINTOR" VARCHAR2(255 CHAR), 
	"FERRAMENTAS" VARCHAR2(255 CHAR), 
	"ITINERARIOCOMPLETO" VARCHAR2(255 CHAR), 
	"JUSTIFICATIVA" VARCHAR2(255 CHAR), 
	"LICENCA" VARCHAR2(255 CHAR), 
	"LIMPEZA" VARCHAR2(255 CHAR), 
	"NIVELCOMBUSTIVELRETORNO" VARCHAR2(255 CHAR), 
	"NIVELCOMBUSTIVELSAIDA" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"OCORRENCIAS" VARCHAR2(255 CHAR), 
	"ODOMETRORETORNOEMKM" FLOAT(126), 
	"ODOMETROSAIDAEMKM" FLOAT(126), 
	"TRIANGULOS" VARCHAR2(255 CHAR), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"INICIORAPIDO" VARCHAR2(3 CHAR), 
	"ID_COMPLEXO" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."MISSAO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("ODOMETROSAIDAEMKM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("ODOMETRORETORNOEMKM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("DATAHORASAIDA" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("CONSUMOEMLITROS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table MISSAO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."MISSAO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"AVARIASAPARENTESRETORNO" VARCHAR2(255 CHAR), 
	"AVARIASAPARENTESSAIDA" VARCHAR2(255 CHAR), 
	"CARTAOABASTECIMENTO" VARCHAR2(255 CHAR), 
	"CARTAOSAIDA" VARCHAR2(255 CHAR), 
	"CARTAOSEGURO" VARCHAR2(255 CHAR), 
	"CONSUMOEMLITROS" FLOAT(126), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORARETORNO" TIMESTAMP (6), 
	"DATAHORASAIDA" TIMESTAMP (6), 
	"ESTADOMISSAO" VARCHAR2(255 CHAR), 
	"ESTEPE" VARCHAR2(255 CHAR), 
	"EXTINTOR" VARCHAR2(255 CHAR), 
	"FERRAMENTAS" VARCHAR2(255 CHAR), 
	"ITINERARIOCOMPLETO" VARCHAR2(255 CHAR), 
	"JUSTIFICATIVA" VARCHAR2(255 CHAR), 
	"LICENCA" VARCHAR2(255 CHAR), 
	"LIMPEZA" VARCHAR2(255 CHAR), 
	"NIVELCOMBUSTIVELRETORNO" VARCHAR2(255 CHAR), 
	"NIVELCOMBUSTIVELSAIDA" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"OCORRENCIAS" VARCHAR2(255 CHAR), 
	"ODOMETRORETORNOEMKM" FLOAT(126), 
	"ODOMETROSAIDAEMKM" FLOAT(126), 
	"TRIANGULOS" VARCHAR2(255 CHAR), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0), 
	"INICIORAPIDO" VARCHAR2(3 CHAR), 
	"ID_COMPLEXO" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."MISSAO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."MISSAO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO_AUD" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table MISSAO_REQUISTRANSPORTE
--------------------------------------------------------

  CREATE TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE" 
   (	"MISSAO_ID" NUMBER(19,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE" MODIFY ("REQUISICAOTRANSPORTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE" MODIFY ("MISSAO_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table MISSAO_REQUISTRANSPORTE_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" 
   (	"REV" NUMBER(10,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"MISSAO_ID" NUMBER(19,0), 
	"REVTYPE" NUMBER(3,0)
   ) ;

  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" ADD PRIMARY KEY ("REV", "MISSAO_ID", "REQUISICAOTRANSPORTE_ID") ENABLE;
  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" MODIFY ("MISSAO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" MODIFY ("REQUISICAOTRANSPORTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" MODIFY ("REV" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PARAMETRO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PARAMETRO" 
   (	"ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_LOTACAO" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"ID_COMPLEXO" NUMBER(19,0), 
	"NOMEPARAMETRO" VARCHAR2(255 CHAR), 
	"VALORPARAMETRO" VARCHAR2(255 CHAR), 
	"DATAINICIO" TIMESTAMP (6), 
	"DATAFIM" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."PARAMETRO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."PARAMETRO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PARAMETRO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PARAMETRO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_LOTACAO" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"ID_COMPLEXO" NUMBER(19,0), 
	"NOMEPARAMETRO" VARCHAR2(255 CHAR), 
	"VALORPARAMETRO" VARCHAR2(255 CHAR), 
	"DATAINICIO" TIMESTAMP (6), 
	"DATAFIM" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."PARAMETRO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."PARAMETRO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PARAMETRO_AUD" MODIFY ("ID" NOT NULL ENABLE);
   
--------------------------------------------------------
--  DDL for Table PENALIDADE
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PENALIDADE" 
   (	"ID" NUMBER(19,0), 
	"CODIGOINFRACAO" VARCHAR2(255 CHAR), 
	"ARTIGOCTB" VARCHAR2(255 CHAR), 
	"CLASSIFICACAO" VARCHAR2(255 CHAR), 
	"DESCRICAOINFRACAO" VARCHAR2(255 CHAR), 
	"INFRATOR" VARCHAR2(255 CHAR), 
	"VALOR" FLOAT(126)
   ) ;

  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("INFRATOR" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("DESCRICAOINFRACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("CLASSIFICACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("ARTIGOCTB" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" ADD UNIQUE ("CODIGOINFRACAO") ENABLE;
  ALTER TABLE "SIGATP"."PENALIDADE" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("CODIGOINFRACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PENALIDADE_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PENALIDADE_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CODIGOINFRACAO" VARCHAR2(255 CHAR), 
	"ARTIGOCTB" VARCHAR2(255 CHAR), 
	"CLASSIFICACAO" VARCHAR2(255 CHAR), 
	"DESCRICAOINFRACAO" VARCHAR2(255 CHAR), 
	"INFRATOR" VARCHAR2(255 CHAR), 
	"VALOR" FLOAT(126)
   ) ;

  ALTER TABLE "SIGATP"."PENALIDADE_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."PENALIDADE_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PENALIDADE_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PLANTAO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PLANTAO" 
   (	"ID" NUMBER(19,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"REFERENCIA" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."PLANTAO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."PLANTAO" MODIFY ("CONDUTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PLANTAO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PLANTAO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."PLANTAO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"CONDUTOR_ID" NUMBER(19,0), 
	"REFERENCIA" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."PLANTAO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."PLANTAO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."PLANTAO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table RELATORIODIARIO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."RELATORIODIARIO" 
   (	"ID" NUMBER(19,0), 
	"CARTOES" VARCHAR2(255 CHAR), 
	"DATA" TIMESTAMP (6), 
	"EQUIPAMENTOOBRIGATORIO" VARCHAR2(255 CHAR), 
	"NIVELDECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"OBSERVACAO" VARCHAR2(255 CHAR), 
	"ODOMETROEMKM" FLOAT(126), 
	"VEICULO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."RELATORIODIARIO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."RELATORIODIARIO" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."RELATORIODIARIO" MODIFY ("ODOMETROEMKM" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."RELATORIODIARIO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table RELATORIODIARIO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."RELATORIODIARIO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CARTOES" VARCHAR2(255 CHAR), 
	"DATA" TIMESTAMP (6), 
	"EQUIPAMENTOOBRIGATORIO" VARCHAR2(255 CHAR), 
	"NIVELDECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"OBSERVACAO" VARCHAR2(255 CHAR), 
	"ODOMETROEMKM" FLOAT(126), 
	"VEICULO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."RELATORIODIARIO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."RELATORIODIARIO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."RELATORIODIARIO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table REQUISICAO_TIPOPASSAGEIRO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO" 
   (	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"TIPOPASSAGEIRO" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO" MODIFY ("TIPOPASSAGEIRO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO" MODIFY ("REQUISICAOTRANSPORTE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table REQUISICAO_TIPOPASSAGEIRO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" 
   (	"REV" NUMBER(10,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"TIPOPASSAGEIRO" VARCHAR2(255 CHAR), 
	"REVTYPE" NUMBER(3,0)
   ) ;

  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" ADD PRIMARY KEY ("REV", "REQUISICAOTRANSPORTE_ID", "TIPOPASSAGEIRO") ENABLE;
  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" MODIFY ("TIPOPASSAGEIRO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" MODIFY ("REQUISICAOTRANSPORTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" MODIFY ("REV" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table REQUISICAOTRANSPORTE
--------------------------------------------------------

  CREATE TABLE "SIGATP"."REQUISICAOTRANSPORTE" 
   (	"ID" NUMBER(19,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORARETORNOPREVISTO" TIMESTAMP (6), 
	"DATAHORASAIDAPREVISTA" TIMESTAMP (6), 
	"FINALIDADE" VARCHAR2(255 CHAR), 
	"ITINERARIOS" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"PASSAGEIROS" VARCHAR2(255 CHAR), 
	"TIPOREQUISICAO" VARCHAR2(255 CHAR), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"ID_FINALIDADE" NUMBER(19,0), 
	"ID_COMPLEXO" NUMBER(19,0), 
	"NUMERODEPASSAGEIROS" NUMBER(5,0), 
	"ORIGEMEXTERNA" NUMBER(1,0) DEFAULT 0
   ) ;

  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE" MODIFY ("ORIGEMEXTERNA" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table REQUISICAOTRANSPORTE_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."REQUISICAOTRANSPORTE_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORARETORNOPREVISTO" TIMESTAMP (6), 
	"DATAHORASAIDAPREVISTA" TIMESTAMP (6), 
	"FINALIDADE" VARCHAR2(255 CHAR), 
	"ITINERARIOS" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"PASSAGEIROS" VARCHAR2(255 CHAR), 
	"TIPOREQUISICAO" VARCHAR2(255 CHAR), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_SOLICITANTE" NUMBER(19,0), 
	"ID_FINALIDADE" NUMBER(19,0), 
	"ID_COMPLEXO" NUMBER(19,0), 
	"NUMERODEPASSAGEIROS" NUMBER(5,0), 
	"ORIGEMEXTERNA" NUMBER(1,0)
   ) ;

  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table REVINFO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."REVINFO" 
   (	"REV" NUMBER(10,0), 
	"REVTSTMP" NUMBER(19,0), 
	"ENDERECOIP" VARCHAR2(20 CHAR), 
	"MATRICULA" VARCHAR2(10 CHAR), 
	"MOTIVOLOG" VARCHAR2(255 CHAR)
   ) ;

  ALTER TABLE "SIGATP"."REVINFO" ADD PRIMARY KEY ("REV") ENABLE;
  ALTER TABLE "SIGATP"."REVINFO" MODIFY ("REV" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table SERVICOVEICULO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."SERVICOVEICULO" 
   (	"ID" NUMBER(19,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAFIMPREVISTO" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"DATAHORAINICIOPREVISTO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"MOTIVOCANCELAMENTO" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"SITUACAOSERVICO" VARCHAR2(255 CHAR), 
	"TIPOSDESERVICO" VARCHAR2(255 CHAR), 
	"ULTIMAALTERACAO" TIMESTAMP (6), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."SERVICOVEICULO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."SERVICOVEICULO" MODIFY ("VEICULO_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."SERVICOVEICULO" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table SERVICOVEICULO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."SERVICOVEICULO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DATAHORA" TIMESTAMP (6), 
	"DATAHORAFIM" TIMESTAMP (6), 
	"DATAHORAFIMPREVISTO" TIMESTAMP (6), 
	"DATAHORAINICIO" TIMESTAMP (6), 
	"DATAHORAINICIOPREVISTO" TIMESTAMP (6), 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"MOTIVOCANCELAMENTO" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER(19,0), 
	"SITUACAOSERVICO" VARCHAR2(255 CHAR), 
	"TIPOSDESERVICO" VARCHAR2(255 CHAR), 
	"ULTIMAALTERACAO" TIMESTAMP (6), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"ID_PESSOA" NUMBER(19,0), 
	"REQUISICAOTRANSPORTE_ID" NUMBER(19,0), 
	"VEICULO_ID" NUMBER(19,0)
   ) ;

  ALTER TABLE "SIGATP"."SERVICOVEICULO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."SERVICOVEICULO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."SERVICOVEICULO_AUD" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table VEICULO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."VEICULO" 
   (	"ID" NUMBER(19,0), 
	"ANOFABRICACAO" NUMBER(10,0), 
	"ANOMODELO" NUMBER(10,0), 
	"CATEGORIACNH" VARCHAR2(255 CHAR), 
	"CHASSI" VARCHAR2(255 CHAR), 
	"DATAALIENACAO" TIMESTAMP (6), 
	"DATAAQUISICAO" TIMESTAMP (6), 
	"DATAGARANTIA" TIMESTAMP (6), 
	"DIRECAO" VARCHAR2(255 CHAR), 
	"DPVAT" VARCHAR2(255 CHAR), 
	"LICENCIAMENTOANUAL" VARCHAR2(255 CHAR), 
	"MARCA" VARCHAR2(255 CHAR), 
	"MODELO" VARCHAR2(255 CHAR), 
	"MOTOR" VARCHAR2(255 CHAR), 
	"NUMEROCARTAOABASTECIMENTO" VARCHAR2(255 CHAR), 
	"NUMEROCARTAOSEGURO" VARCHAR2(255 CHAR), 
	"OUTROS" VARCHAR2(255 CHAR), 
	"PATRIMONIO" VARCHAR2(255 CHAR), 
	"PLACA" VARCHAR2(255 CHAR), 
	"PNEUMEDIDA" VARCHAR2(255 CHAR), 
	"PNEUPRESSAODIANTEIRA" VARCHAR2(255 CHAR), 
	"PNEUPRESSAOTRASEIRA" VARCHAR2(255 CHAR), 
	"POTENCIA" VARCHAR2(255 CHAR), 
	"PROCESSOALIENACAO" VARCHAR2(255 CHAR), 
	"RENAVAM" VARCHAR2(255 CHAR), 
	"SITUACAO" VARCHAR2(255 CHAR), 
	"TANQUE" VARCHAR2(255 CHAR), 
	"TEMABS" NUMBER(1,0), 
	"TEMAIRBAG" NUMBER(1,0), 
	"TEMBANCOSEMCOURO" NUMBER(1,0), 
	"TEMCAMERADEMARCHARE" NUMBER(1,0), 
	"TEMCDPLAYER" NUMBER(1,0), 
	"TEMCONTROLEDETRACAO" NUMBER(1,0), 
	"TEMDVDPLAYER" NUMBER(1,0), 
	"TEMEBD" NUMBER(1,0), 
	"TEMFREIOADISCONASQUATRORODAS" NUMBER(1,0), 
	"TEMGPS" NUMBER(1,0), 
	"TEMOUTROS" NUMBER(1,0), 
	"TEMPILOTOAUTOMATICO" NUMBER(1,0), 
	"TEMRODADELIGALEVE" NUMBER(1,0), 
	"TEMSENSORDEMARCHARE" NUMBER(1,0), 
	"TEMTELALCDPAPOIOCABECA" NUMBER(1,0), 
	"TERMOALIENACAO" VARCHAR2(255 CHAR), 
	"TIPODEBLINDAGEM" VARCHAR2(255 CHAR), 
	"TIPODECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"TRANSMISSAO" VARCHAR2(255 CHAR), 
	"USOCOMUM" VARCHAR2(255 CHAR), 
	"VALIDADECARTAOABASTECIMENTO" TIMESTAMP (6), 
	"VALIDADECARTAOSEGURO" TIMESTAMP (6), 
	"VALORAQUISICAO" FLOAT(126), 
	"COR_ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"FORNECEDOR_ID" NUMBER(19,0), 
	"GRUPO_ID" NUMBER(19,0), 
	"TEMARCONDICIONADO" NUMBER(1,0) DEFAULT 0
   ) ;

  ALTER TABLE "SIGATP"."VEICULO" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMTELALCDPAPOIOCABECA" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMSENSORDEMARCHARE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMRODADELIGALEVE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMPILOTOAUTOMATICO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMOUTROS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMGPS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMFREIOADISCONASQUATRORODAS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMEBD" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMDVDPLAYER" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMCONTROLEDETRACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMCDPLAYER" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMCAMERADEMARCHARE" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMBANCOSEMCOURO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMAIRBAG" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("TEMABS" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("ANOMODELO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("ANOFABRICACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO" MODIFY ("ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table VEICULO_AUD
--------------------------------------------------------

  CREATE TABLE "SIGATP"."VEICULO_AUD" 
   (	"ID" NUMBER(19,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ANOFABRICACAO" NUMBER(10,0), 
	"ANOMODELO" NUMBER(10,0), 
	"CATEGORIACNH" VARCHAR2(255 CHAR), 
	"CHASSI" VARCHAR2(255 CHAR), 
	"DATAALIENACAO" TIMESTAMP (6), 
	"DATAAQUISICAO" TIMESTAMP (6), 
	"DATAGARANTIA" TIMESTAMP (6), 
	"DIRECAO" VARCHAR2(255 CHAR), 
	"DPVAT" VARCHAR2(255 CHAR), 
	"LICENCIAMENTOANUAL" VARCHAR2(255 CHAR), 
	"MARCA" VARCHAR2(255 CHAR), 
	"MODELO" VARCHAR2(255 CHAR), 
	"MOTOR" VARCHAR2(255 CHAR), 
	"NUMEROCARTAOABASTECIMENTO" VARCHAR2(255 CHAR), 
	"NUMEROCARTAOSEGURO" VARCHAR2(255 CHAR), 
	"OUTROS" VARCHAR2(255 CHAR), 
	"PATRIMONIO" VARCHAR2(255 CHAR), 
	"PLACA" VARCHAR2(255 CHAR), 
	"PNEUMEDIDA" VARCHAR2(255 CHAR), 
	"PNEUPRESSAODIANTEIRA" VARCHAR2(255 CHAR), 
	"PNEUPRESSAOTRASEIRA" VARCHAR2(255 CHAR), 
	"POTENCIA" VARCHAR2(255 CHAR), 
	"PROCESSOALIENACAO" VARCHAR2(255 CHAR), 
	"RENAVAM" VARCHAR2(255 CHAR), 
	"SITUACAO" VARCHAR2(255 CHAR), 
	"TANQUE" VARCHAR2(255 CHAR), 
	"TEMABS" NUMBER(1,0), 
	"TEMAIRBAG" NUMBER(1,0), 
	"TEMBANCOSEMCOURO" NUMBER(1,0), 
	"TEMCAMERADEMARCHARE" NUMBER(1,0), 
	"TEMCDPLAYER" NUMBER(1,0), 
	"TEMCONTROLEDETRACAO" NUMBER(1,0), 
	"TEMDVDPLAYER" NUMBER(1,0), 
	"TEMEBD" NUMBER(1,0), 
	"TEMFREIOADISCONASQUATRORODAS" NUMBER(1,0), 
	"TEMGPS" NUMBER(1,0), 
	"TEMOUTROS" NUMBER(1,0), 
	"TEMPILOTOAUTOMATICO" NUMBER(1,0), 
	"TEMRODADELIGALEVE" NUMBER(1,0), 
	"TEMSENSORDEMARCHARE" NUMBER(1,0), 
	"TEMTELALCDPAPOIOCABECA" NUMBER(1,0), 
	"TERMOALIENACAO" VARCHAR2(255 CHAR), 
	"TIPODEBLINDAGEM" VARCHAR2(255 CHAR), 
	"TIPODECOMBUSTIVEL" VARCHAR2(255 CHAR), 
	"TRANSMISSAO" VARCHAR2(255 CHAR), 
	"USOCOMUM" VARCHAR2(255 CHAR), 
	"VALIDADECARTAOABASTECIMENTO" TIMESTAMP (6), 
	"VALIDADECARTAOSEGURO" TIMESTAMP (6), 
	"VALORAQUISICAO" FLOAT(126), 
	"COR_ID" NUMBER(19,0), 
	"ID_ORGAO_USU" NUMBER(19,0), 
	"FORNECEDOR_ID" NUMBER(19,0), 
	"GRUPO_ID" NUMBER(19,0), 
	"TEMARCONDICIONADO" NUMBER(1,0)
   ) ;

  ALTER TABLE "SIGATP"."VEICULO_AUD" ADD PRIMARY KEY ("ID", "REV") ENABLE;
  ALTER TABLE "SIGATP"."VEICULO_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "SIGATP"."VEICULO_AUD" MODIFY ("ID" NOT NULL ENABLE);

  
-----------------------------------------------------------------------------------
------------------ FOREIGN KEYS ---------------------------------------------------
-----------------------------------------------------------------------------------
  
  
--------------------------------------------------------
--  Ref Constraints for Table CONDUTOR_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."CONDUTOR_AUD" ADD CONSTRAINT "FKAB0AAED5DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVARIA
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AVARIA" ADD CONSTRAINT "FK7597A6DE18C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEICULO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."VEICULO_AUD" ADD CONSTRAINT "FK4DC06640DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUISICAOTRANSPORTE_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE_AUD" ADD CONSTRAINT "FKFD52BBF6DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICOVEICULO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."SERVICOVEICULO" ADD CONSTRAINT "FK6E00887018C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."SERVICOVEICULO" ADD CONSTRAINT "FK6E008870AEBDA4DE" FOREIGN KEY ("REQUISICAOTRANSPORTE_ID")
	  REFERENCES "SIGATP"."REQUISICAOTRANSPORTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUISICAO_TIPOPASSAGEIRO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO_AUD" ADD CONSTRAINT "FKF9785F13DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELATORIODIARIO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."RELATORIODIARIO" ADD CONSTRAINT "FKDD7F8E3118C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTROLEGABINETE_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."CONTROLEGABINETE_AUD" ADD CONSTRAINT "FKCA9D70C2DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOTACAOVEICULO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."LOTACAOVEICULO_AUD" ADD CONSTRAINT "FKF363B91FDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELATORIODIARIO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."RELATORIODIARIO_AUD" ADD CONSTRAINT "FKD9E73B82DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORNECEDOR_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."FORNECEDOR_AUD" ADD CONSTRAINT "FKB5E860D6DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSAO_REQUISTRANSPORTE
--------------------------------------------------------

  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE" ADD CONSTRAINT "FK488F75B2AEBDA4DE" FOREIGN KEY ("REQUISICAOTRANSPORTE_ID")
	  REFERENCES "SIGATP"."REQUISICAOTRANSPORTE" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE" ADD CONSTRAINT "FK488F75B2F99AC59E" FOREIGN KEY ("MISSAO_ID")
	  REFERENCES "SIGATP"."MISSAO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEICULO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."VEICULO" ADD CONSTRAINT "FK77A7C7EF2DB35256" FOREIGN KEY ("COR_ID")
	  REFERENCES "SIGATP"."COR" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."VEICULO" ADD CONSTRAINT "FK77A7C7EFD2AA1C76" FOREIGN KEY ("GRUPO_ID")
	  REFERENCES "SIGATP"."GRUPOVEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."VEICULO" ADD CONSTRAINT "FK77A7C7EFD56685BE" FOREIGN KEY ("FORNECEDOR_ID")
	  REFERENCES "SIGATP"."FORNECEDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARAMETRO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."PARAMETRO_AUD" ADD CONSTRAINT "FKPARAMETROREV" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COR_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."COR_AUD" ADD CONSTRAINT "FK9C1E1437DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFASTAMENTO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AFASTAMENTO" ADD CONSTRAINT "FK9F72316D3BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSAO_REQUISTRANSPORTE_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."MISSAO_REQUISTRANSPORTE_AUD" ADD CONSTRAINT "FKE3C57A83DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUISICAO_TIPOPASSAGEIRO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."REQUISICAO_TIPOPASSAGEIRO" ADD CONSTRAINT "FK140B2242AEBDA4DE" FOREIGN KEY ("REQUISICAOTRANSPORTE_ID")
	  REFERENCES "SIGATP"."REQUISICAOTRANSPORTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOTACAOVEICULO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."LOTACAOVEICULO" ADD CONSTRAINT "FK886D624E18C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCALADETRABALHO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ESCALADETRABALHO_AUD" ADD CONSTRAINT "FK4093D504DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANDAMENTO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ANDAMENTO_AUD" ADD CONSTRAINT "FK3AE559D8DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANDAMENTO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ANDAMENTO" ADD CONSTRAINT "FK9DC64787AEBDA4DE" FOREIGN KEY ("REQUISICAOTRANSPORTE_ID")
	  REFERENCES "SIGATP"."REQUISICAOTRANSPORTE" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ANDAMENTO" ADD CONSTRAINT "FK9DC64787F99AC59E" FOREIGN KEY ("MISSAO_ID")
	  REFERENCES "SIGATP"."MISSAO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABASTECIMENTO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ABASTECIMENTO" ADD CONSTRAINT "FK229DBC718C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ABASTECIMENTO" ADD CONSTRAINT "FK229DBC73BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."ABASTECIMENTO" ADD CONSTRAINT "FK229DBC7D56685BE" FOREIGN KEY ("FORNECEDOR_ID")
	  REFERENCES "SIGATP"."FORNECEDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSAO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."MISSAO" ADD CONSTRAINT "FK8962CE4A18C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."MISSAO" ADD CONSTRAINT "FK8962CE4A3BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFASTAMENTO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AFASTAMENTO_AUD" ADD CONSTRAINT "FK4F1DE0BEDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANTAO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."PLANTAO_AUD" ADD CONSTRAINT "FKB44390ADF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTODEINFRACAO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AUTODEINFRACAO" ADD CONSTRAINT "FKD80212D118C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" ADD CONSTRAINT "FKD80212D13BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."AUTODEINFRACAO" ADD CONSTRAINT "FK_AUTINF_PEN" FOREIGN KEY ("PENALIDADE_ID")
	  REFERENCES "SIGATP"."PENALIDADE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPOVEICULO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."GRUPOVEICULO_AUD" ADD CONSTRAINT "FKA9DDEE57DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVARIA_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AVARIA_AUD" ADD CONSTRAINT "FK1B935AFDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTROLEGABINETE
--------------------------------------------------------

  ALTER TABLE "SIGATP"."CONTROLEGABINETE" ADD CONSTRAINT "FK3222637118C04BB6" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES "SIGATP"."VEICULO" ("ID") ENABLE;
  ALTER TABLE "SIGATP"."CONTROLEGABINETE" ADD CONSTRAINT "FK322263713BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOTACAOATDREQUISICAO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."LOTACAOATDREQUISICAO_AUD" ADD CONSTRAINT "FKAB96B70ADF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSAO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."MISSAO_AUD" ADD CONSTRAINT "FK638AC71BDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICOVEICULO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."SERVICOVEICULO_AUD" ADD CONSTRAINT "FKF0D2FE41DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCALADETRABALHO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ESCALADETRABALHO" ADD CONSTRAINT "FK3DE938B33BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTODEINFRACAO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."AUTODEINFRACAO_AUD" ADD CONSTRAINT "FK10567022DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIADETRABALHO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."DIADETRABALHO_AUD" ADD CONSTRAINT "FKA20CF1FFDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIADETRABALHO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."DIADETRABALHO" ADD CONSTRAINT "FK9F560B2ED10E8C3E" FOREIGN KEY ("ESCALADETRABALHO_ID")
	  REFERENCES "SIGATP"."ESCALADETRABALHO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINALIDADEREQUISICAO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."FINALIDADEREQUISICAO_AUD" ADD CONSTRAINT "FK54F9930BDF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABASTECIMENTO_AUD
--------------------------------------------------------

  ALTER TABLE "SIGATP"."ABASTECIMENTO_AUD" ADD CONSTRAINT "FKDEE4CE18DF74E053" FOREIGN KEY ("REV")
	  REFERENCES "SIGATP"."REVINFO" ("REV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANTAO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."PLANTAO" ADD CONSTRAINT "FK45C88FB93BF35A5E" FOREIGN KEY ("CONDUTOR_ID")
	  REFERENCES "SIGATP"."CONDUTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUISICAOTRANSPORTE
--------------------------------------------------------

  ALTER TABLE "SIGATP"."REQUISICAOTRANSPORTE" ADD CONSTRAINT "FK450568A580C02ED3" FOREIGN KEY ("ID_FINALIDADE")
	  REFERENCES "SIGATP"."FINALIDADEREQUISICAO" ("ID") ENABLE;

	  
----------------------------------------------------------------------------------
-----------             GRANTS DO OWNER                       --------------------
----------------------------------------------------------------------------------

GRANT ALL PRIVILEGES ON SIGATP.ABASTECIMENTO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.ABASTECIMENTO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AFASTAMENTO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AFASTAMENTO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.ANDAMENTO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.ANDAMENTO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AUTODEINFRACAO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AUTODEINFRACAO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AVARIA TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.AVARIA_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.CONDUTOR TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.CONDUTOR_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.CONTROLEGABINETE TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.CONTROLEGABINETE_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.COR TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.COR_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.DIADETRABALHO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.DIADETRABALHO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.ESCALADETRABALHO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.ESCALADETRABALHO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.FINALIDADEREQUISICAO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.FINALIDADEREQUISICAO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.FORNECEDOR TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.FORNECEDOR_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.GRUPOVEICULO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.GRUPOVEICULO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.LOTACAOATDREQUISICAO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.LOTACAOATDREQUISICAO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.LOTACAOVEICULO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.LOTACAOVEICULO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.MISSAO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.MISSAO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.MISSAO_REQUISTRANSPORTE TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.MISSAO_REQUISTRANSPORTE_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PARAMETRO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PARAMETRO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PENALIDADE TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PENALIDADE_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PLANTAO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.PLANTAO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.RELATORIODIARIO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.RELATORIODIARIO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.REQUISICAO_TIPOPASSAGEIRO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.REQUISICAO_TIPOPASSAGEIRO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.REQUISICAOTRANSPORTE TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.REQUISICAOTRANSPORTE_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.REVINFO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.SERVICOVEICULO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.SERVICOVEICULO_AUD TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.VEICULO TO SIGATP;
GRANT ALL PRIVILEGES ON SIGATP.VEICULO_AUD TO SIGATP;
