ALTER TABLE MISSAO RENAME COLUMN ODOMETOSAIDAEMKM TO ODOMETROSAIDAEMKM;

ALTER TABLE MISSAO RENAME COLUMN ODOMETORETORNOEMKM TO ODOMETRORETORNOEMKM;

ALTER TABLE MISSAO_AUD RENAME COLUMN ODOMETOSAIDAEMKM TO ODOMETROSAIDAEMKM;

ALTER TABLE MISSAO_AUD RENAME COLUMN ODOMETORETORNOEMKM TO ODOMETRORETORNOEMKM;
