
-- CREATE USER SIGATP_CON IDENTIFIED BY xxxxxxxx;

--Comentado para ser utilizado somente em homologação e produção

GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.ABASTECIMENTO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.ABASTECIMENTO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.AFASTAMENTO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.AFASTAMENTO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.ANDAMENTO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.ANDAMENTO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.AUTODEINFRACAO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.AUTODEINFRACAO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.AVARIA TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.AVARIA_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.CONDUTOR TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.CONDUTOR_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.COR TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.COR_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.DIADETRABALHO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.DIADETRABALHO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.ESCALADETRABALHO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.ESCALADETRABALHO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.FORNECEDOR TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.FORNECEDOR_AUD TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.DIADETRABALHO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.GRUPOVEICULO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.GRUPOVEICULO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.LOTACAOATDREQUISICAO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.LOTACAOATDREQUISICAO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.LOTACAOVEICULO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.LOTACAOVEICULO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.MISSAO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.MISSAO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.MISSAO_REQUISTRANSPORTE TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.MISSAO_REQUISTRANSPORTE_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.PLANTAO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.PLANTAO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.RELATORIODIARIO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.RELATORIODIARIO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.REQUISICAOTRANSPORTE TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.REQUISICAOTRANSPORTE_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.REVINFO TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.SERVICOVEICULO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.SERVICOVEICULO_AUD TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.USUARIOTESTE TO SIGATP_CON;
GRANT SELECT,INSERT,UPDATE,DELETE  ON  SIGATP.VEICULO TO SIGATP_CON;
GRANT SELECT,INSERT  ON  SIGATP.VEICULO_AUD TO SIGATP_CON;
GRANT SELECT  ON  SIGATP.HIBERNATE_SEQUENCE TO SIGATP_CON; 