Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (1,'VEÍCULOS DE MÉDIO PORTE, TIPO SEDAN, COR PRETA, COM  
CAPACIDADE DE TRANSPORTE DE ATÉ 5 (CINCO) PASSAGEIROS, MOTOR DE POTÊNCIA MÍNIMA  
DE 116 CV E MÁXIMA DE 159 CV (GASOLINA) E ITENS DE SEGURANÇA CONDIZENTES COM  
O SERVIÇO','TRANSPORTE DOS PRESIDENTES, DOS VICE-PRESIDENTES E DOS  
CORREGEDORES DOS TRIBUNAIS REGIONAIS FEDERAIS','A','REPRESENTAÇÃO');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (2,'VEÍCULOS DE MÉDIO PORTE, TIPO SEDAN, COR PRETA, COM
CAPACIDADE DE TRANSPORTE DE ATÉ 5 (CINCO) PASSAGEIROS, MOTOR DE POTÊNCIA MÍNIMA
DE 116 CV E MÁXIMA DE 159 CV (GASOLINA) E ITENS DE SEGURANÇA CONDIZENTES COM
O SERVIÇO','TRANSPORTE, EM OBJETO DE SERVIÇO, DOS JUÍZES DE SEGUNDO GRAU E
DOS JUÍZES DIRETORES DE FORO E DIRETORES DE SUBSEÇÕES JUDICIÁRIAS','B','TRANSPORTE INSTITUCIONAL');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (3,'VEÍCULOS DE PEQUENO PORTE, COM CAPACIDADE DE ATÉ 5 (CINCO)
OCUPANTES, MOTOR COM POTÊNCIA MÍNIMA DE 80 CV E MÁXIMA DE 112 CV (GASOLINA)
E ITENS DE SEGURANÇA CONDIZENTES COM O SERVIÇO','TRANSPORTE, EM OBJETO DE SERVIÇO, DE JUÍZES DE PRIMEIRO GRAU E
SERVIDORES NO DESEMPENHO DE ATIVIDADES EXTERNAS DE INTERESSE DA ADMINISTRAÇÃO','C','SERVIÇO COMUM');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (4,'PICK-UPS CABINE DUPLA, VANS COM CAPACIDADE MÍNIMA DE 12  
(DOZE) OCUPANTES, MICROÔNIBUS E ÔNIBUS, MOTOR COM POTÊNCIA CONDIZENTE COM O  
SERVIÇO','TRANSPORTE, EM OBJETO DE SERVIÇO, DE MAGISTRADOS E SERVIDORES NO','D','TRANSPORTE COLETIVO');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (5,'FURGÕES, PICK-UPS DE CABINE SIMPLES, REBOQUES E SEMIREBOQUES,  
MOTOR DE POTÊNCIA CONDIZENTE COM O SERVIÇO','TRANSPORTE DE CARGAS LEVES NO DESEMPENHO DE ATIVIDADES EXTERNAS  
DE INTERESSE DA ADMINISTRAÇÃO','E','CARGA LEVE');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (6,'VEÍCULOS TIPO CAMINHÃO, MOTOR DE POTÊNCIA CONDIZENTE COM O','TRANSPORTE DE CARGAS PESADAS','F','CARGA PESADA');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (7,'AMBULÂNCIAS E VEÍCULOS COM DISPOSITIVO DE ALARME E LUZ','ATENDIMENTO, EM CARÁTER DE SOCORRO MÉDICO OU DE APOIO ÀS','G','APOIO ESPECIAL');
Insert into GRUPOVEICULO (ID,CARACTERISTICAS,FINALIDADE,LETRA,NOME) values (8,'TRANSPORTE DO TIPO BLINDADO','ATENDIMENTO DE AUTORIDADES','H','BLINDADO');