CREATE SEQUENCE "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1477 CACHE 20 NOORDER  NOCYCLE;

create table Abastecimento (id number(19,0) not null, consumoMedioEmKmPorLitro double precision not null, dataHora timestamp, distanciaPercorridaEmKm double precision not null, nivelDeCombustivel varchar2(255 char), numeroDaNotaFiscal varchar2(255 char), odometroEmKm double precision not null, precoPorLitro double precision not null, quantidadeEmLitros double precision not null, tipoDeCombustivel varchar2(255 char) not null, valorTotalDaNotaFiscal double precision not null, condutor_id number(19,0) not null, fornecedor_id number(19,0) not null, veiculo_id number(19,0) not null, primary key (id));

create table Abastecimento_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), consumoMedioEmKmPorLitro double precision, dataHora timestamp, distanciaPercorridaEmKm double precision, nivelDeCombustivel varchar2(255 char), numeroDaNotaFiscal varchar2(255 char), odometroEmKm double precision, precoPorLitro double precision, quantidadeEmLitros double precision, tipoDeCombustivel varchar2(255 char), valorTotalDaNotaFiscal double precision, condutor_id number(19,0), fornecedor_id number(19,0), veiculo_id number(19,0), primary key (id, REV));

create table Afastamento (id number(19,0) not null, dataHoraFim timestamp not null, dataHoraInicio timestamp not null, descricao varchar2(255 char) not null, condutor_id number(19,0) not null, primary key (id));

create table Afastamento_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataHoraFim timestamp, dataHoraInicio timestamp, descricao varchar2(255 char), condutor_id number(19,0), primary key (id, REV));

create table Andamento (id number(19,0) not null, dataAndamento timestamp not null, descricao varchar2(255 char) not null, estadoRequisicao varchar2(255 char) not null, missao_id number(19,0), requisicaoTransporte_id number(19,0) not null, responsavel_ID_PESSOA number(19,0) not null, primary key (id));

create table Andamento_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataAndamento timestamp, descricao varchar2(255 char), estadoRequisicao varchar2(255 char), missao_id number(19,0), requisicaoTransporte_id number(19,0), responsavel_ID_PESSOA number(19,0), primary key (id, REV));

create table AutoDeInfracao (id number(19,0) not null, codigoDaAutuacao varchar2(255 char), codigoDaPenalidade varchar2(255 char), dataDePagamento timestamp, dataDeVencimento timestamp, dataDoProcesso timestamp, dataHora timestamp, dataLimiteApresentacao timestamp, descricao varchar2(255 char), enquadramento varchar2(255 char), foiRecebido varchar2(255 char), gravidade varchar2(255 char), local varchar2(255 char), memorando varchar2(255 char), numeroDoProcesso varchar2(255 char), quantidadeDePontos number(10,0) not null, valor double precision not null, valorComDesconto double precision not null, condutor_id number(19,0) not null, veiculo_id number(19,0) not null, primary key (id));

create table AutoDeInfracao_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), codigoDaAutuacao varchar2(255 char), codigoDaPenalidade varchar2(255 char), dataDePagamento timestamp, dataDeVencimento timestamp, dataDoProcesso timestamp, dataHora timestamp, dataLimiteApresentacao timestamp, descricao varchar2(255 char), enquadramento varchar2(255 char), foiRecebido varchar2(255 char), gravidade varchar2(255 char), local varchar2(255 char), memorando varchar2(255 char), numeroDoProcesso varchar2(255 char), quantidadeDePontos number(10,0), valor double precision, valorComDesconto double precision, condutor_id number(19,0), veiculo_id number(19,0), primary key (id, REV));

create table Avaria (id number(19,0) not null, dataDeRegistro timestamp, dataDeSolucao timestamp, descricao varchar2(255 char), veiculo_id number(19,0) not null, primary key (id));

create table Avaria_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataDeRegistro timestamp, dataDeSolucao timestamp, descricao varchar2(255 char), veiculo_id number(19,0), primary key (id, REV));

create table Condutor (id number(19,0) not null, categoriaCNH varchar2(255 char), celularInstitucional varchar2(255 char), celularPessoal varchar2(255 char), dataVencimentoCNH timestamp, telefoneInstitucional varchar2(255 char), telefonePessoal varchar2(255 char), ID_ORGAO_USU number(19,0), dpPessoa_ID_PESSOA number(19,0), primary key (id));

create table Condutor_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), categoriaCNH varchar2(255 char), celularInstitucional varchar2(255 char), celularPessoal varchar2(255 char), dataVencimentoCNH timestamp, telefoneInstitucional varchar2(255 char), telefonePessoal varchar2(255 char), ID_ORGAO_USU number(19,0), dpPessoa_ID_PESSOA number(19,0), primary key (id, REV));
create table Cor (id number(19,0) not null, nome varchar2(255 char), primary key (id));
create table Cor_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), nome varchar2(255 char), primary key (id, REV));
create table DiaDeTrabalho (id number(19,0) not null, diaEntrada varchar2(255 char), diaSaida varchar2(255 char), horaEntrada timestamp, horaSaida timestamp, escalaDeTrabalho_id number(19,0) not null, primary key (id));
create table DiaDeTrabalho_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), diaEntrada varchar2(255 char), diaSaida varchar2(255 char), horaEntrada timestamp, horaSaida timestamp, escalaDeTrabalho_id number(19,0), primary key (id, REV));
create table EscalaDeTrabalho (id number(19,0) not null, dataVigenciaFim timestamp, dataVigenciaInicio timestamp, condutor_id number(19,0) not null, primary key (id));
create table EscalaDeTrabalho_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataVigenciaFim timestamp, dataVigenciaInicio timestamp, condutor_id number(19,0), primary key (id, REV));
create table Fornecedor (id number(19,0) not null, bairro varchar2(255 char), cep varchar2(255 char), cnpj varchar2(255 char), complemento varchar2(255 char), eMail varchar2(255 char), enderecoVirtual varchar2(255 char), fax varchar2(255 char), localidade varchar2(255 char), logradouro varchar2(255 char), nomeContato varchar2(255 char), ramoDeAtividade varchar2(255 char), razaoSocial varchar2(255 char), telefone varchar2(255 char), uf varchar2(255 char), primary key (id));
create table Fornecedor_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), bairro varchar2(255 char), cep varchar2(255 char), cnpj varchar2(255 char), complemento varchar2(255 char), eMail varchar2(255 char), enderecoVirtual varchar2(255 char), fax varchar2(255 char), localidade varchar2(255 char), logradouro varchar2(255 char), nomeContato varchar2(255 char), ramoDeAtividade varchar2(255 char), razaoSocial varchar2(255 char), telefone varchar2(255 char), uf varchar2(255 char), primary key (id, REV));
create table GRUPOVEICULO (id number(19,0) not null, caracteristicas varchar2(255 char), finalidade varchar2(255 char), letra varchar2(255 char), nome varchar2(255 char), primary key (id));
create table GRUPOVEICULO_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), caracteristicas varchar2(255 char), finalidade varchar2(255 char), letra varchar2(255 char), nome varchar2(255 char), primary key (id, REV));
create table LotacaoAtdRequisicao (id number(19,0) not null, ID_ORGAO_USU number(19,0), ID_LOTA_SOLICITANTE number(19,0) not null, primary key (id));
create table LotacaoAtdRequisicao_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), ID_ORGAO_USU number(19,0), ID_LOTA_SOLICITANTE number(19,0), primary key (id, REV));
create table LotacaoVeiculo (id number(19,0) not null, dataHoraFim timestamp, dataHoraInicio timestamp not null, ID_LOTA_SOLICITANTE number(19,0) not null, veiculo_id number(19,0) not null, primary key (id));
create table LotacaoVeiculo_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataHoraFim timestamp, dataHoraInicio timestamp, ID_LOTA_SOLICITANTE number(19,0), veiculo_id number(19,0), primary key (id, REV));
create table Missao (id number(19,0) not null, avariasAparentesRetorno varchar2(255 char), avariasAparentesSaida varchar2(255 char), cartaoAbastecimento varchar2(255 char), cartaoSaida varchar2(255 char), cartaoSeguro varchar2(255 char), consumoEmLitros double precision not null, dataHora timestamp, dataHoraRetorno timestamp, dataHoraSaida timestamp not null, estadoMissao varchar2(255 char), estepe varchar2(255 char), extintor varchar2(255 char), ferramentas varchar2(255 char), itinerarioCompleto varchar2(255 char), justificativa varchar2(255 char), licenca varchar2(255 char), limpeza varchar2(255 char), nivelCombustivelRetorno varchar2(255 char), nivelCombustivelSaida varchar2(255 char), numero number(19,0), ocorrencias varchar2(255 char), odometoRetornoEmKm double precision not null, odometoSaidaEmKm double precision not null, triangulos varchar2(255 char), condutor_id number(19,0) not null, ID_ORGAO_USU number(19,0), ID_PESSOA number(19,0), veiculo_id number(19,0), primary key (id));
create table Missao_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), avariasAparentesRetorno varchar2(255 char), avariasAparentesSaida varchar2(255 char), cartaoAbastecimento varchar2(255 char), cartaoSaida varchar2(255 char), cartaoSeguro varchar2(255 char), consumoEmLitros double precision, dataHora timestamp, dataHoraRetorno timestamp, dataHoraSaida timestamp, estadoMissao varchar2(255 char), estepe varchar2(255 char), extintor varchar2(255 char), ferramentas varchar2(255 char), itinerarioCompleto varchar2(255 char), justificativa varchar2(255 char), licenca varchar2(255 char), limpeza varchar2(255 char), nivelCombustivelRetorno varchar2(255 char), nivelCombustivelSaida varchar2(255 char), numero number(19,0), ocorrencias varchar2(255 char), odometoRetornoEmKm double precision, odometoSaidaEmKm double precision, triangulos varchar2(255 char), condutor_id number(19,0), ID_ORGAO_USU number(19,0), ID_PESSOA number(19,0), veiculo_id number(19,0), primary key (id, REV));
create table Plantao (id number(19,0) not null, dataHoraFim timestamp, dataHoraInicio timestamp, condutor_id number(19,0) not null, primary key (id));
create table Plantao_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataHoraFim timestamp, dataHoraInicio timestamp, condutor_id number(19,0), primary key (id, REV));
create table REVINFO (REV number(10,0) not null, REVTSTMP number(19,0), primary key (REV));
create table RelatorioDiario (id number(19,0) not null, cartoes varchar2(255 char), data timestamp, equipamentoObrigatorio varchar2(255 char), nivelDeCombustivel varchar2(255 char), observacao varchar2(255 char), odometroEmKm double precision not null, veiculo_id number(19,0) not null, primary key (id));
create table RelatorioDiario_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), cartoes varchar2(255 char), data timestamp, equipamentoObrigatorio varchar2(255 char), nivelDeCombustivel varchar2(255 char), observacao varchar2(255 char), odometroEmKm double precision, veiculo_id number(19,0), primary key (id, REV));
create table RequisicaoTransporte (id number(19,0) not null, dataHora timestamp, dataHoraRetornoPrevisto timestamp, dataHoraSaidaPrevista timestamp, finalidade varchar2(255 char), itinerarios varchar2(255 char), numero number(19,0), passageiros varchar2(255 char), tipoRequisicao varchar2(255 char), ID_ORGAO_USU number(19,0), ID_SOLICITANTE number(19,0), primary key (id));
create table RequisicaoTransporte_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataHora timestamp, dataHoraRetornoPrevisto timestamp, dataHoraSaidaPrevista timestamp, finalidade varchar2(255 char), itinerarios varchar2(255 char), numero number(19,0), passageiros varchar2(255 char), tipoRequisicao varchar2(255 char), ID_ORGAO_USU number(19,0), ID_SOLICITANTE number(19,0), primary key (id, REV));
create table ServicoVeiculo (id number(19,0) not null, dataHora timestamp, dataHoraFim timestamp, dataHoraFimPrevisto timestamp, dataHoraInicio timestamp, dataHoraInicioPrevisto timestamp, descricao varchar2(255 char), motivoCancelamento varchar2(255 char), numero number(19,0) unique, situacaoServico varchar2(255 char), tiposDeServico varchar2(255 char), ultimaAlteracao timestamp, ID_ORGAO_USU number(19,0), ID_PESSOA number(19,0), requisicaoTransporte_id number(19,0), VEICULO_ID number(19,0) not null, primary key (id));
create table ServicoVeiculo_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), dataHora timestamp, dataHoraFim timestamp, dataHoraFimPrevisto timestamp, dataHoraInicio timestamp, dataHoraInicioPrevisto timestamp, descricao varchar2(255 char), motivoCancelamento varchar2(255 char), numero number(19,0), situacaoServico varchar2(255 char), tiposDeServico varchar2(255 char), ultimaAlteracao timestamp, ID_ORGAO_USU number(19,0), ID_PESSOA number(19,0), requisicaoTransporte_id number(19,0), VEICULO_ID number(19,0), primary key (id, REV));
create table UsuarioTeste (id number(19,0) not null, bairro varchar2(255 char), endereco varchar2(255 char), nome varchar2(255 char), numero number(10,0) not null, primary key (id));
create table Veiculo (id number(19,0) not null, anoFabricacao number(10,0) not null, anoModelo number(10,0) not null, categoriaCNH varchar2(255 char), chassi varchar2(255 char), dataAlienacao timestamp, dataAquisicao timestamp, dataGarantia timestamp, direcao varchar2(255 char), dpvat varchar2(255 char), licenciamentoAnual varchar2(255 char), marca varchar2(255 char), modelo varchar2(255 char), motor varchar2(255 char), numeroCartaoAbastecimento varchar2(255 char), numeroCartaoSeguro varchar2(255 char), outros varchar2(255 char), patrimonio varchar2(255 char), placa varchar2(255 char), pneuMedida varchar2(255 char), pneuPressaoDianteira varchar2(255 char), pneuPressaoTraseira varchar2(255 char), potencia varchar2(255 char), processoAlienacao varchar2(255 char), renavam varchar2(255 char), situacao varchar2(255 char), tanque varchar2(255 char), temABS number(1,0) not null, temAIRBAG number(1,0) not null, temBANCOSEMCOURO number(1,0) not null, temCAMERADEMARCHARE number(1,0) not null, temCDPLAYER number(1,0) not null, temCONTROLEDETRACAO number(1,0) not null, temDVDPLAYER number(1,0) not null, temEBD number(1,0) not null, temFREIOADISCONASQUATRORODAS number(1,0) not null, temGPS number(1,0) not null, temOUTROS number(1,0) not null, temPILOTOAUTOMATICO number(1,0) not null, temRODADELIGALEVE number(1,0) not null, temSENSORDEMARCHARE number(1,0) not null, temTELALCDPAPOIOCABECA number(1,0) not null, termoAlienacao varchar2(255 char), tipoDeBlindagem varchar2(255 char), tipoDeCombustivel varchar2(255 char), transmissao varchar2(255 char), usoComum varchar2(255 char), validadeCartaoAbastecimento timestamp, validadeCartaoSeguro timestamp, valorAquisicao double precision, cor_id number(19,0), ID_ORGAO_USU number(19,0), fornecedor_id number(19,0), grupo_id number(19,0), primary key (id));
create table Veiculo_AUD (id number(19,0) not null, REV number(10,0) not null, REVTYPE number(3,0), anoFabricacao number(10,0), anoModelo number(10,0), categoriaCNH varchar2(255 char), chassi varchar2(255 char), dataAlienacao timestamp, dataAquisicao timestamp, dataGarantia timestamp, direcao varchar2(255 char), dpvat varchar2(255 char), licenciamentoAnual varchar2(255 char), marca varchar2(255 char), modelo varchar2(255 char), motor varchar2(255 char), numeroCartaoAbastecimento varchar2(255 char), numeroCartaoSeguro varchar2(255 char), outros varchar2(255 char), patrimonio varchar2(255 char), placa varchar2(255 char), pneuMedida varchar2(255 char), pneuPressaoDianteira varchar2(255 char), pneuPressaoTraseira varchar2(255 char), potencia varchar2(255 char), processoAlienacao varchar2(255 char), renavam varchar2(255 char), situacao varchar2(255 char), tanque varchar2(255 char), temABS number(1,0), temAIRBAG number(1,0), temBANCOSEMCOURO number(1,0), temCAMERADEMARCHARE number(1,0), temCDPLAYER number(1,0), temCONTROLEDETRACAO number(1,0), temDVDPLAYER number(1,0), temEBD number(1,0), temFREIOADISCONASQUATRORODAS number(1,0), temGPS number(1,0), temOUTROS number(1,0), temPILOTOAUTOMATICO number(1,0), temRODADELIGALEVE number(1,0), temSENSORDEMARCHARE number(1,0), temTELALCDPAPOIOCABECA number(1,0), termoAlienacao varchar2(255 char), tipoDeBlindagem varchar2(255 char), tipoDeCombustivel varchar2(255 char), transmissao varchar2(255 char), usoComum varchar2(255 char), validadeCartaoAbastecimento timestamp, validadeCartaoSeguro timestamp, valorAquisicao double precision, cor_id number(19,0), ID_ORGAO_USU number(19,0), fornecedor_id number(19,0), grupo_id number(19,0), primary key (id, REV));
create table missao_requisTransporte (missao_Id number(19,0) not null, requisicaoTransporte_Id number(19,0) not null);
create table missao_requisTransporte_AUD (REV number(10,0) not null, requisicaoTransporte_Id number(19,0) not null, missao_Id number(19,0) not null, REVTYPE number(3,0), primary key (REV, missao_Id, requisicaoTransporte_Id));
alter table Abastecimento add constraint FK229DBC718C04BB6 foreign key (veiculo_id) references Veiculo;
alter table Abastecimento add constraint FK229DBC7D56685BE foreign key (fornecedor_id) references Fornecedor;
alter table Abastecimento add constraint FK229DBC73BF35A5E foreign key (condutor_id) references Condutor;
alter table Abastecimento_AUD add constraint FKDEE4CE18DF74E053 foreign key (REV) references REVINFO;
alter table Afastamento add constraint FK9F72316D3BF35A5E foreign key (condutor_id) references Condutor;
alter table Afastamento_AUD add constraint FK4F1DE0BEDF74E053 foreign key (REV) references REVINFO;
alter table Andamento add constraint FK9DC64787F99AC59E foreign key (missao_id) references Missao;
alter table Andamento add constraint FK9DC64787AEBDA4DE foreign key (requisicaoTransporte_id) references RequisicaoTransporte;
alter table Andamento_AUD add constraint FK3AE559D8DF74E053 foreign key (REV) references REVINFO;
alter table AutoDeInfracao add constraint FKD80212D118C04BB6 foreign key (veiculo_id) references Veiculo;
alter table AutoDeInfracao add constraint FKD80212D13BF35A5E foreign key (condutor_id) references Condutor;
alter table AutoDeInfracao_AUD add constraint FK10567022DF74E053 foreign key (REV) references REVINFO;
alter table Avaria add constraint FK7597A6DE18C04BB6 foreign key (veiculo_id) references Veiculo;
alter table Avaria_AUD add constraint FK1B935AFDF74E053 foreign key (REV) references REVINFO;
alter table Condutor_AUD add constraint FKAB0AAED5DF74E053 foreign key (REV) references REVINFO;
alter table Cor_AUD add constraint FK9C1E1437DF74E053 foreign key (REV) references REVINFO;
alter table DiaDeTrabalho add constraint FK9F560B2ED10E8C3E foreign key (escalaDeTrabalho_id) references EscalaDeTrabalho;
alter table DiaDeTrabalho_AUD add constraint FKA20CF1FFDF74E053 foreign key (REV) references REVINFO;
alter table EscalaDeTrabalho add constraint FK3DE938B33BF35A5E foreign key (condutor_id) references Condutor;
alter table EscalaDeTrabalho_AUD add constraint FK4093D504DF74E053 foreign key (REV) references REVINFO;
alter table Fornecedor_AUD add constraint FKB5E860D6DF74E053 foreign key (REV) references REVINFO;
alter table GRUPOVEICULO_AUD add constraint FKA9DDEE57DF74E053 foreign key (REV) references REVINFO;
alter table LotacaoAtdRequisicao_AUD add constraint FKAB96B70ADF74E053 foreign key (REV) references REVINFO;
alter table LotacaoVeiculo add constraint FK886D624E18C04BB6 foreign key (veiculo_id) references Veiculo;
alter table LotacaoVeiculo_AUD add constraint FKF363B91FDF74E053 foreign key (REV) references REVINFO;
alter table Missao add constraint FK8962CE4A18C04BB6 foreign key (veiculo_id) references Veiculo;
alter table Missao add constraint FK8962CE4A3BF35A5E foreign key (condutor_id) references Condutor;
alter table Missao_AUD add constraint FK638AC71BDF74E053 foreign key (REV) references REVINFO;
alter table Plantao add constraint FK45C88FB93BF35A5E foreign key (condutor_id) references Condutor;
alter table Plantao_AUD add constraint FKB44390ADF74E053 foreign key (REV) references REVINFO;
alter table RelatorioDiario add constraint FKDD7F8E3118C04BB6 foreign key (veiculo_id) references Veiculo;
alter table RelatorioDiario_AUD add constraint FKD9E73B82DF74E053 foreign key (REV) references REVINFO;
alter table RequisicaoTransporte_AUD add constraint FKFD52BBF6DF74E053 foreign key (REV) references REVINFO;
alter table ServicoVeiculo add constraint FK6E008870AEBDA4DE foreign key (requisicaoTransporte_id) references RequisicaoTransporte;
alter table ServicoVeiculo add constraint FK6E00887018C04BB6 foreign key (VEICULO_ID) references Veiculo;
alter table ServicoVeiculo_AUD add constraint FKF0D2FE41DF74E053 foreign key (REV) references REVINFO;
alter table Veiculo add constraint FK77A7C7EFD2AA1C76 foreign key (grupo_id) references GRUPOVEICULO;
alter table Veiculo add constraint FK77A7C7EFD56685BE foreign key (fornecedor_id) references Fornecedor;
alter table Veiculo add constraint FK77A7C7EF2DB35256 foreign key (cor_id) references Cor;
alter table Veiculo_AUD add constraint FK4DC06640DF74E053 foreign key (REV) references REVINFO;
alter table missao_requisTransporte add constraint FK488F75B2F99AC59E foreign key (missao_Id) references Missao;
alter table missao_requisTransporte add constraint FK488F75B2AEBDA4DE foreign key (requisicaoTransporte_Id) references RequisicaoTransporte;
alter table missao_requisTransporte_AUD add constraint FKE3C57A83DF74E053 foreign key (REV) references REVINFO;