/*******************************************************************************
 * Copyright (c) 2006 - 2011 SJRJ.
 * 
 *     This file is part of SIGA.
 * 
 *     SIGA is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     SIGA is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with SIGA.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package br.gov.jfrj.siga.cd.ac;


import java.io.ByteArrayInputStream;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.TrustAnchor;
import java.security.cert.X509Certificate;

import org.apache.axis.encoding.Base64;


/**
 * Enumerador de Certificados de Autoridades Certificadoras (AC)
 * 
 * Sempre que um novo certificado deva ser tratado pelo(s) sistema(s) que
 * utilizam o siga-cd deva ser considerado, o mesmo deve ser inserido neste
 * enumerador
 * 
 * @author aym
 * 
 */
public enum CertificadoACEnum {

	AC_RAIZ_ICPBRASIL_ERRADO(
			"AC_RAIZ_ICPBRASIL_ERRADO",
			Base64.decode("MIIEPjCCAyagAwIBAgIBEDANBgkqhkiG9w0BAQUFADCBtDELMAkGA1UEBhMCQlIxEzARBgNVBAoT"
					+ "CklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25hbCBkZSBUZWNub2xvZ2lhIGRh"
					+ "IEluZm9ybWFjYW8gLSBJVEkxETAPBgNVBAcTCEJyYXNpbGlhMQswCQYDVQQIEwJERjExMC8GA1UE"
					+ "AxMoQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFJhaXogQnJhc2lsZWlyYTAeFw0wNDExMjYxMjIw"
					+ "MDBaFw0xMTExMjYyMzU5MDBaMFYxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMRgw"
					+ "FgYDVQQLEw9BQyBDZXJ0aVNpZ24gVjMxGDAWBgNVBAMTD0FDIENlcnRpU2lnbiBWMzCCASIwDQYJ"
					+ "KoZIhvcNAQEBBQADggEPADCCAQoCggEBAK17G0+cTG8qjqwPidslvptoaCpUCEZn+Xp3sggJVeN/"
					+ "A7JVccy1hXum9/uJX2nvlNbXu0G/nmADwHP7YeunPtkk3Ah2IuFHPU/f1KodJI9IbX7qLPuEoBtr"
					+ "od0g7uE2XPBnSjxIFMwtpIs1Sp9AQSzaAezq63gKP9qkvIKiAB3r0rwo5jRP9Tey8oo79OPcNHam"
					+ "7l0DfkKutSaO/oCgWyMunYmmPxx56dUTQWz0HFsLiRnetve4EHisH8vfPmBpaTQY845120K4MofB"
					+ "dpzSb7Vj4j5WrStx/+5+r/gNcWDY9pJa9a9M5Sy5rvPA4gdgK8TbfRir00mZ0qF7cOr4EW0CAwEA"
					+ "AaOBtzCBtDA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3YuYnIv"
					+ "TENSYWNyYWl6LmNybDASBgNVHSAECzAJMAcGBWBMAQEFMB0GA1UdDgQWBBRkXeNVqD8sfj2lpUVc"
					+ "h/+6cUXWwDAfBgNVHSMEGDAWgBSK+vFXhBETNZBC+ldJVGkNpMTwNzAOBgNVHQ8BAf8EBAMCAQYw"
					+ "DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAB4oeFtBfWe3eN57jMjD+gfpk/PGd"
					+ "QTs67/njYGSeaowwMcdrS7/Hb0FvjcEB4FmMAFyXOFK7XtBEMoHKRdu4X655LlzemvB+euWkJZ8r"
					+ "M8WWVvQKsKKEOrh+tCWNhpdYFQ91lKKu5kkAlabmD0G4bXfLYX5i0ypNXw/16n7NNMfKO1rrVxp1"
					+ "k7gmDcsBOXl7787yVFY/yt4vr9Ok28fB6P4c0u8t7jVjSQ5gFUXOWlv1DgstfX+Nv3hmoX3AzCrO"
					+ "Hs8cSAEKnhcRwzA/nsJN4+zoSqpYT/171XFD50TUtrjSVgHOrPMnKGS1sByYx5gzonchTO9zi1f6"
					+ "G1ZAlMOHCw==")),

	AC_BR_RFB_G3(
			"AC_BR_RFB_G3",
			Base64.decode("MIIG1zCCBL+gAwIBAgIBBzANBgkqhkiG9w0BAQ0FADCBkDELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIxNjA0BgNVBAMTLUFDIFNlY3JldGFy"
					+ "aWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCB2MzAeFw0xMTEyMjYxODA4"
					+ "MDRaFw0xOTEyMjYxODA4MDRaMHExCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1At"
					+ "QnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBk"
					+ "byBCcmFzaWwgLSBSRkIxFTATBgNVBAMTDEFDIEJSIFJGQiBHMzCCAiIwDQYJKoZI"
					+ "hvcNAQEBBQADggIPADCCAgoCggIBALltWQdgVMI7O2gLVawXcEEd6uZPwHqRROvg"
					+ "7bSdgDDRGfKpqV2KeW+vWBzeUsWpPYGIKDSVrNuvLXPACNcVZFok15tNODZdV2G8"
					+ "pcGhEbp74eA0lKCXKCr7gBPaYsfHxiccTNuRo+Mi3iL/g8Sse9Eew8QXleJlgdMc"
					+ "MADhLiWqNNERq+9e0XyLZNV0Tb8ZCvnUUvqurVMJJmtSZK4bePBVEJpZfQcMWLB4"
					+ "WgepHYvnTDStedt7Mb0gKoUJgVmw/oq21JDEtdtcsP/4NvkrMstulw0b3Offoxp4"
					+ "a2/DpzxSYewxAvZkywsbLfUKJYk/Qg0Wnvsy3vLjS1uWsgVxKP3W4ug48xIB94aw"
					+ "mlk2HAiTNZRGWe4XsH/U83Zr49Zl6x7LusvkKzAtT/fUUfWQMUgY6GPIjfz0FDX4"
					+ "3c0WTqGCG1jgywvgLDKw+le3PzQJ8UiN0PGJBRPwI1XNNUqzD1VJvdgu12RGFx82"
					+ "DtsVRVcq9D+afgXcTJRhrDN7+sbu0dd6w1HtZ9QVZDWFFVPlW4TNW/ig6fNso9ed"
					+ "5fOgiw2SEVY/yElNknUvi6JOJ23V4X/Od5EOqgCBGea0qPu88lNC2beWSskxXGoA"
					+ "kgI+TWosF0QH7/FFzxnMzUjK3IC+xkTHDYyPPj2+QNR2Li+izALyLwAAT2OaxzS3"
					+ "UO2YiYZrAgMBAAGjggFYMIIBVDCBpwYDVR0gBIGfMIGcMEwGBmBMAQIBGzBCMEAG"
					+ "CCsGAQUFBwIBFjRodHRwOi8vd3d3LnJlY2VpdGEuZmF6ZW5kYS5nb3YuYnIvYWNy"
					+ "ZmIvZHBjYWNyZmIucGRmMEwGBmBMAQIDGDBCMEAGCCsGAQUFBwIBFjRodHRwOi8v"
					+ "d3d3LnJlY2VpdGEuZmF6ZW5kYS5nb3YuYnIvYWNyZmIvZHBjYWNyZmIucGRmMEQG"
					+ "A1UdHwQ9MDswOaA3oDWGM2h0dHA6Ly93d3cucmVjZWl0YS5mYXplbmRhLmdvdi5i"
					+ "ci9hY3JmYi9hY3JmYnYzLmNybDAfBgNVHSMEGDAWgBR1y7qQ0c5Mp5LwcbDLvrh7"
					+ "MwayKDAdBgNVHQ4EFgQUTvuocXG/6qm9kT1NumSs+dLi5KQwEgYDVR0TAQH/BAgw"
					+ "BgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIBAIEmU+Uh"
					+ "uezewH85I4K2cpVQaDvNYMhlsGzgdoJbBEyNGLc9KCfKDZBI2TKFYFo+mu/U1Gcw"
					+ "zSE1BU6JakHRRo6K1WMkum0PrZu6irBwDyDxZp6+HtbHNaEWmbw3YbDb+SkoshzC"
					+ "eTn4QRWh2m/4Zr7bRWsAR/C6E5BZf9lgYJ48sq0BfuXhlxDv+dn3Ea6Kt/bwkrID"
					+ "EuDHh0IcfbeMEI9rwXnky41PcnvmfDlM/Rk9arrJHPJUy8Qaz0ZJwGLNwoKT3M49"
					+ "8GY26CT8zDe3TObg2tW7eRqnqiaZbkRXZYWM0ObNXhaMChWE3w8fw0KWdIu0uUtk"
					+ "qgG+Y3VqH/JSxXyZXkaemlC/ZiUjrat0JmZHpLTHMFnPCCdALMP4PBsHxPlSVDF1"
					+ "GqzDoeih84q2G8choNxTd0uwlud/GvSd+ocA/treC9uzZSuY6YxhlalIzXTcYYm7"
					+ "ZL0yXSaRsZbQO5fw6aQJ7XZO5Ka/aw7vdN7sfCWaCdobMgiPfSZjle9ektqZ1zmE"
					+ "b+b3dvM5th+hE6+YPbS8b3L0Vk1t4Zz5hBRd8aQMdd2OKFd3Xb6p/pLJ/Y9TfSqv"
					+ "lmwFnuGuXNfPFCmI81U1DeBN90X4i1lIt96i90aP2vm8Ju2cs6ncD5I/USzxUmTe"
					+ "8Hp3xOMEFYC9EoDhuL89x1Fe4Q0kjkwD1BER")),

	AC_RAIZ_ICPBRASIL(
			"AC_RAIZ_ICPBRASIL",
			Base64.decode("MIIEuDCCA6CgAwIBAgIBBDANBgkqhkiG9w0BAQUFADCBtDELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxETAPBgNVBAcTCEJy"
					+ "YXNpbGlhMQswCQYDVQQIEwJERjExMC8GA1UEAxMoQXV0b3JpZGFkZSBDZXJ0aWZp"
					+ "Y2Fkb3JhIFJhaXogQnJhc2lsZWlyYTAeFw0wMTExMzAxMjU4MDBaFw0xMTExMzAy"
					+ "MzU5MDBaMIG0MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE9MDsG"
					+ "A1UECxM0SW5zdGl0dXRvIE5hY2lvbmFsIGRlIFRlY25vbG9naWEgZGEgSW5mb3Jt"
					+ "YWNhbyAtIElUSTERMA8GA1UEBxMIQnJhc2lsaWExCzAJBgNVBAgTAkRGMTEwLwYD"
					+ "VQQDEyhBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhMIIB"
					+ "IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwPMudwX/hvm+Uh2b/lQAcHVA"
					+ "isamaLkWdkwP9/S/tOKIgRrL6Oy+ZIGlOUdd6uYtk9Ma/3pUpgcfNAj0vYm5gsyj"
					+ "Qo9emsc+x6m4VWwk9iqMZSCK5EQkAq/Ut4n7KuLE1+gdftwdIgxfUsPt4CyNrY50"
					+ "QV57KM2UT8x5rrmzEjr7TICGpSUAl2gVqe6xaii+bmYR1QrmWaBSAG59LrkrjrYt"
					+ "bRhFboUDe1DK+6T8s5L6k8c8okpbHpa9veMztDVC9sPJ60MWXh6anVKo1UcLcbUR"
					+ "yEeNvZneVRKAAU6ouwdjDvwlsaKydFKwed0ToQ47bmUKgcm+wV3eTRk36UOnTwID"
					+ "AQABo4HSMIHPME4GA1UdIARHMEUwQwYFYEwBAQAwOjA4BggrBgEFBQcCARYsaHR0"
					+ "cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJyL0RQQ2FjcmFpei5wZGYwPQYDVR0f"
					+ "BDYwNDAyoDCgLoYsaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJyL0xDUmFj"
					+ "cmFpei5jcmwwHQYDVR0OBBYEFIr68VeEERM1kEL6V0lUaQ2kxPA3MA8GA1UdEwEB"
					+ "/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBBQUAA4IBAQAZA5c1"
					+ "U/hgIh6OcgLAfiJgFWpvmDZWqlV30/bHFpj8iBobJSm5uDpt7TirYh1Uxe3fQaGl"
					+ "YjJe+9zd+izPRbBqXPVQA34EXcwk4qpWuf1hHriWfdrx8AcqSqr6CuQFwSr75Fos"
					+ "SzlwDADa70mT7wZjAmQhnZx2xJ6wfWlT9VQfS//JYeIc7Fue2JNLd00UOSMMaiK/"
					+ "t79enKNHEA2fupH3vEigf5Eh4bVAN5VohrTm6MY53x7XQZZr1ME7a55lFEnSeT0u"
					+ "mlOAjR2mAbvSM5X5oSZNrmetdzyTj2flCM8CC7MLab0kkdngRIlUBGHF1/S5nmPb"
					+ "K+9A46sd33oqK8n8")),

	AC_RAIZ_ICPBRASIL_V1(
			"AC_RAIZ_ICPBRASIL_V1",
			Base64.decode("MIIEgDCCA2igAwIBAgIBATANBgkqhkiG9w0BAQUFADCBlzELMAkGA1UEBhMCQlIxEzARBgNVBAoT"
					+ "CklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25hbCBkZSBUZWNub2xvZ2lhIGRh"
					+ "IEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6"
					+ "IEJyYXNpbGVpcmEgdjEwHhcNMDgwNzI5MTkxNzEwWhcNMjEwNzI5MTkxNzEwWjCBlzELMAkGA1UE"
					+ "BhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25hbCBk"
					+ "ZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1dG9yaWRhZGUgQ2Vy"
					+ "dGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK"
					+ "AoIBAQDOHOi+kzTOybHkVO4J9uykCIWgP8aKxnAwp4CM7T4BVAeMGSM7n7vHtIsgseL3QRYtXodm"
					+ "urAH3W/RPzzayFkznRWwn5LIVlRYijonojQem3i1t83lm+nALhKecHgH+o7yTMD45XJ8HqmpYANX"
					+ "Jkfbg3bDzsgSu9H/766zYn2aoOS8bn0BLjRg3IfgX38FcFwwFSzCdaM/UANmI2Ys53R3eNtmF9/5"
					+ "Hw2CaI91h/fpMXpTT89YYrtAojTPwHCEUJcV2iBL6ftMQq0raI6j2a0FYv4IdMTowcyFE86tKDBQ"
					+ "3d7AgcFJsF4uJjjpYwQzd7WAds0qf/I8rF2TQjn0onNFAgMBAAGjgdQwgdEwTgYDVR0gBEcwRTBD"
					+ "BgVgTAEBADA6MDgGCCsGAQUFBwIBFixodHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3YuYnIvRFBD"
					+ "YWNyYWl6LnBkZjA/BgNVHR8EODA2MDSgMqAwhi5odHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3Yu"
					+ "YnIvTENSYWNyYWl6djEuY3JsMB0GA1UdDgQWBBRCsixcdAEHvpv/VTM77im7XZG/BjAPBgNVHRMB"
					+ "Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAWWyKdukZcVeD/qf0"
					+ "eg+egdDPBxwMI+kkDVHLM+gqCcN6/w6jgIZgwXCX4MAKVd2kZUyPp0ewV7fzq8TDGeOY7A2wG1GR"
					+ "ydkJ1ulqs+cMsLKSh/uOTRXsEhQZeAxi6hQ5GArFVdtThdx7KPoVcaPKdCWCD2cnNNeuUhMC+8Xv"
					+ "moAlpVKeOQ7tOvR4B1/VKHoKSvXQw2f3jFgXbwoAoyYQtGAiOkpIpdrgqYTeQ9ufQ6c/KARHki/3"
					+ "52R1IdJPgc6qPmQO4w6tVZp+lJs0wdCuaU4eo9mzh1facMJafYfN+b833u1WNfe3Ig5Pkrg/CN+c"
					+ "nphe8m+5+pss+M1F2HKyIA==")),

	AC_RAIZ_ICPBRASIL_V2(
			"AC_RAIZ_ICPBRASIL_V2",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdvVENDQkltZ0F3SUJBZ0lCQVRBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCbHpFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eFBUQTdCZ05WQkFzVE5FbHVjM1JwZEhWMGJ5Qk9ZV05wYjI1aApiQ0JrWlNCVVpXTnVi"
					+ "Mnh2WjJsaElHUmhJRWx1Wm05eWJXRmpZVzhnTFNCSlZFa3hOREF5QmdOVkJBTVRLMEYxCmRHOXlh"
					+ "V1JoWkdVZ1EyVnlkR2xtYVdOaFpHOXlZU0JTWVdsNklFSnlZWE5wYkdWcGNtRWdkakl3SGhjTk1U"
					+ "QXcKTmpJeE1Ua3dORFUzV2hjTk1qTXdOakl4TVRrd05EVTNXakNCbHpFTE1Ba0dBMVVFQmhNQ1Fs"
					+ "SXhFekFSQmdOVgpCQW9UQ2tsRFVDMUNjbUZ6YVd3eFBUQTdCZ05WQkFzVE5FbHVjM1JwZEhWMGJ5"
					+ "Qk9ZV05wYjI1aGJDQmtaU0JVClpXTnViMnh2WjJsaElHUmhJRWx1Wm05eWJXRmpZVzhnTFNCSlZF"
					+ "a3hOREF5QmdOVkJBTVRLMEYxZEc5eWFXUmgKWkdVZ1EyVnlkR2xtYVdOaFpHOXlZU0JTWVdsNklF"
					+ "SnlZWE5wYkdWcGNtRWdkakl3Z2dJaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUNEd0F3Z2dJS0Fv"
					+ "SUNBUUM2UnFRTzNlZEE4cldnZkZLVlYwWDhiWVR6aGdISmhRT3RtS3ZTCjhsNEZtY203YjJKbi9Y"
					+ "ZEV1UU1IUE5JYkFHTFVjQ3hDZzNsbXE1bFdyb0c4YWttOTgzUVBZcmZyV3dkbWxFSWsKblVhc21r"
					+ "SVlNUEFrcUZGQjZxdVY4YWdyQW5ocHRTa25YcHd1YzhiK0k2WGpwczc5YkJ0ckFGVHJBSzFQT2t3"
					+ "OAo1d3FJVzlwZW1ndFc1TFZVT0IzeUNwTmtUc05Ca2xNZ0tzLzhkRzdVMnpNNFl1VCtqa3hZSFBl"
					+ "UEtrMy94WkxaCkNWSzl6M0FBbldtYU0ycUloMFVobVJaUkRUVGZncjIwYWFoOGZOVGQwL0lWWEV2"
					+ "RldCRHFoUm5MTmlKWUtuSU0KbXBiZXlzOElVV0cvdEFVcEJpdUdrUDdwVGNNRUJVZkx6M2JaZjNH"
					+ "bWgzc1ZRT1F6Z0hnSEhhVHlqcHRBTzhseQpVTjlwdnZBc2xoK1F0ZFd1ZE9ObHRJd2E2V29iKzNK"
					+ "Y3hZSlU2dUJUQjhUTUV1bjMzdGN2MUVndlJ6OG1ZUVN4CkVwb3phN1dHU3hNcjBJYWRSKzFwKy95"
					+ "RUVtYjRWdVVPaW14MnhHc2Flc0tnV2hMUkk0bFlBWHdJV05vVmpoWFoKZm4wM3RxUkY5UU9GekVm"
					+ "NmkzbEZ1R1ppTTlNbVN0NGM2ZFIvNW0wbXVUeDl6UThvQ2lrUG05MWpxN21tUnhxRQoxNFdrQTJV"
					+ "R0JFdFNqWU0wUW44eGpoRXU1ck5ubFVCK2wzcEFBUGtSYklNNFdLMERNMXVteE1IRnNLd05xUWJ3"
					+ "CnBta0JOTGJwK0pSSVR6Nm1kUW5zU3NVNzRNbGVzREwvbjJsWnp6d3didzNPSjFmc1dodG8vK3hQ"
					+ "YjNneVBubkYKdEYyVmZ3SURBUUFCbzRIMU1JSHlNRTRHQTFVZElBUkhNRVV3UXdZRllFd0JBUUF3"
					+ "T2pBNEJnZ3JCZ0VGQlFjQwpBUllzYUhSMGNEb3ZMMkZqY21GcGVpNXBZM0JpY21GemFXd3VaMjky"
					+ "TG1KeUwwUlFRMkZqY21GcGVpNXdaR1l3ClB3WURWUjBmQkRnd05qQTBvREtnTUlZdWFIUjBjRG92"
					+ "TDJGamNtRnBlaTVwWTNCaWNtRnphV3d1WjI5MkxtSnkKTDB4RFVtRmpjbUZwZW5ZeUxtTnliREFm"
					+ "QmdOVkhTTUVHREFXZ0JRTU9TQTZ0d0VmeTljb2ZVR2d4L3BLclRJawp2akFkQmdOVkhRNEVGZ1FV"
					+ "RERrZ09yY0JIOHZYS0gxQm9NZjZTcTB5Skw0d0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU9CZ05W"
					+ "SFE4QkFmOEVCQU1DQVFZd0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dJQkFGbWFGR2tZYlgwcFEzQjkK"
					+ "ZHB0aDMzZU9HbmJrcWRiTGRxUVdERXlVRXNhUTBZRUR4YTBHMlMxRXZMSUpkZ21BT1djQUdEUnRC"
					+ "Z3JtdFJCWgpTTHAxWVB3L2poMFlWWEFybmt1VnJJbXJDbmNrZTJIRXg1RW1qa1lUVVRlMmpDY0sw"
					+ "dzN3bWlzaWc0T3p2WU0xCnJaczh2SGlES1RWaE52Z1JjVE1nVkdOVFJRSFlFMXFFTzlkbUV5UzN4"
					+ "RWJGSXRoekpPNGNFeGVXeUNYb0d4N1AKMzRWUWJUenE5MUNlRzVmZXAydmIxblBTejN4UXdMQ001"
					+ "Vk1TZW9ZNXJEVmJaOGZxMVB2UndsM3FEcGR6bUs0cAp2K1E2OHdRMlVDenQzaDdiaGVnZGhBbnU4"
					+ "NmFETTF0dlIzbFBTTFg4dUNZVHE2cXo5R0VSKzBWbjh4MCtidjRxClN5WkVHcCt4b3VBODJ1RGtC"
					+ "VHA0clB1b29VMi9YU3gzS1pETkV4M3ZCaWpZdHhUelc4akpucWQrTVJLS2VHTEUKMFFXOEJnSmpC"
					+ "Q3NOaWQza1hGc3lnRVRVUXV3cTgvSkFoekhWUHVJS01nd1VqZFZ5YlF2bS9ZM2txUE1GalhVWApk"
					+ "NXNLdWZxUWtwbGxpREpuUXdXT0xRc1Z1elh4WWVqWlozZnRGdVhvQVMxck5EK09nN1AzNmc5S0hq"
					+ "NDFoSjJNCmdEUS9xWlhvdzYzRXpaN0tGQllzR1o3a05vdTV1YU5DSlFjK3crWFZhRStnWmh5bXM3"
					+ "WnpISkFhUDBDNUdsWkMKY0lmL2J5MFBFZjBlLy9lRk1CVU80eGN4N2llVnpNbnBtUjZYeDIxYkI3"
					+ "VUZhajN5UmQrNmdua2tjQzZiZ2g5bQpxYVZ0Sjh6MktxTFJYNFZ2NEVhZHF0S2xUbFVPCi0tLS0t"
					+ "RU5EIENFUlRJRklDQVRFLS0tLS0K")),

	AC_RAIZ_ICPBRASIL_V2_NOVO(
			"AC_RAIZ_ICPBRASIL_V2_NOVO",
			Base64.decode("MIIGoTCCBImgAwIBAgIBATANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwHhcNMTAw"
					+ "NjIxMTkwNDU3WhcNMjMwNjIxMTkwNDU3WjCBlzELMAkGA1UEBhMCQlIxEzARBgNV"
					+ "BAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25hbCBkZSBU"
					+ "ZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1dG9yaWRh"
					+ "ZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwggIiMA0GCSqGSIb3"
					+ "DQEBAQUAA4ICDwAwggIKAoICAQC6RqQO3edA8rWgfFKVV0X8bYTzhgHJhQOtmKvS"
					+ "8l4Fmcm7b2Jn/XdEuQMHPNIbAGLUcCxCg3lmq5lWroG8akm983QPYrfrWwdmlEIk"
					+ "nUasmkIYMPAkqFFB6quV8agrAnhptSknXpwuc8b+I6Xjps79bBtrAFTrAK1POkw8"
					+ "5wqIW9pemgtW5LVUOB3yCpNkTsNBklMgKs/8dG7U2zM4YuT+jkxYHPePKk3/xZLZ"
					+ "CVK9z3AAnWmaM2qIh0UhmRZRDTTfgr20aah8fNTd0/IVXEvFWBDqhRnLNiJYKnIM"
					+ "mpbeys8IUWG/tAUpBiuGkP7pTcMEBUfLz3bZf3Gmh3sVQOQzgHgHHaTyjptAO8ly"
					+ "UN9pvvAslh+QtdWudONltIwa6Wob+3JcxYJU6uBTB8TMEun33tcv1EgvRz8mYQSx"
					+ "Epoza7WGSxMr0IadR+1p+/yEEmb4VuUOimx2xGsaesKgWhLRI4lYAXwIWNoVjhXZ"
					+ "fn03tqRF9QOFzEf6i3lFuGZiM9MmSt4c6dR/5m0muTx9zQ8oCikPm91jq7mmRxqE"
					+ "14WkA2UGBEtSjYM0Qn8xjhEu5rNnlUB+l3pAAPkRbIM4WK0DM1umxMHFsKwNqQbw"
					+ "pmkBNLbp+JRITz6mdQnsSsU74MlesDL/n2lZzzwwbw3OJ1fsWhto/+xPb3gyPnnF"
					+ "tF2VfwIDAQABo4H1MIHyME4GA1UdIARHMEUwQwYFYEwBAQAwOjA4BggrBgEFBQcC"
					+ "ARYsaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJyL0RQQ2FjcmFpei5wZGYw"
					+ "PwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJy"
					+ "L0xDUmFjcmFpenYyLmNybDAfBgNVHSMEGDAWgBQMOSA6twEfy9cofUGgx/pKrTIk"
					+ "vjAdBgNVHQ4EFgQUDDkgOrcBH8vXKH1BoMf6Sq0yJL4wDwYDVR0TAQH/BAUwAwEB"
					+ "/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIBAFmaFGkYbX0pQ3B9"
					+ "dpth33eOGnbkqdbLdqQWDEyUEsaQ0YEDxa0G2S1EvLIJdgmAOWcAGDRtBgrmtRBZ"
					+ "SLp1YPw/jh0YVXArnkuVrImrCncke2HEx5EmjkYTUTe2jCcK0w3wmisig4OzvYM1"
					+ "rZs8vHiDKTVhNvgRcTMgVGNTRQHYE1qEO9dmEyS3xEbFIthzJO4cExeWyCXoGx7P"
					+ "34VQbTzq91CeG5fep2vb1nPSz3xQwLCM5VMSeoY5rDVbZ8fq1PvRwl3qDpdzmK4p"
					+ "v+Q68wQ2UCzt3h7bhegdhAnu86aDM1tvR3lPSLX8uCYTq6qz9GER+0Vn8x0+bv4q"
					+ "SyZEGp+xouA82uDkBTp4rPuooU2/XSx3KZDNEx3vBijYtxTzW8jJnqd+MRKKeGLE"
					+ "0QW8BgJjBCsNid3kXFsygETUQuwq8/JAhzHVPuIKMgwUjdVybQvm/Y3kqPMFjXUX"
					+ "d5sKufqQkplliDJnQwWOLQsVuzXxYejZZ3ftFuXoAS1rND+Og7P36g9KHj41hJ2M"
					+ "gDQ/qZXow63EzZ7KFBYsGZ7kNou5uaNCJQc+w+XVaE+gZhyms7ZzHJAaP0C5GlZC"
					+ "cIf/by0PEf0e//eFMBUO4xcx7ieVzMnpmR6Xx21bB7UFaj3yRd+6gnkkcC6bgh9m"
					+ "qaVtJ8z2KqLRX4Vv4EadqtKlTlUO")),

	AC_CLEPSIDRE_TIME_STAMP(
			"AC_CLEPSIDRE_TIME_STAMP",
			Base64.decode("MIIDYDCCAkigAwIBAgIIAQI3JEZlEXgwDQYJKoZIhvcNAQEFBQAwcDELMAkGA1UEBhMCRlIxFTAT"
					+ "BgNVBAoTDEVkZWxXZWIgUy5BLjEoMCYGA1UECxMfQ2xlcHN5ZHJlIERlbW9uc3RyYXRpb24gU2Vy"
					+ "dmljZTEgMB4GA1UEAxMXVGltZSBTdGFtcGluZyBBdXRob3JpdHkwHhcNMDIwNjEwMTU1NDMyWhcN"
					+ "MjIwNjA1MTU1NDMyWjBwMQswCQYDVQQGEwJGUjEVMBMGA1UEChMMRWRlbFdlYiBTLkEuMSgwJgYD"
					+ "VQQLEx9DbGVwc3lkcmUgRGVtb25zdHJhdGlvbiBTZXJ2aWNlMSAwHgYDVQQDExdUaW1lIFN0YW1w"
					+ "aW5nIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPrDF67rt53rq70F"
					+ "fjlDbQRFWHQFpczzbC+Mjnd+wp8SEVx9274jKJqQ0qvGorq9o36ZppkhpdiQuc+nI06gVqDBCkaJ"
					+ "jjyRZzf9m6tJF/xKpfLkTG7jahySlwRvfwxc+3TLlX5Mw1gS6KnW8N0SRBXniy6vUcAMX6hl/Eeh"
					+ "yZgf1OHqvBwaJ7uLVvESVRD0jtifGZwegffbY92INz9xeVuW4l+C1RIZBQ3hPaVtZuQsHu3HTLjf"
					+ "qjjIFWquJX1GKgf5g3fEUe6Q3AXQw/DxX+jU7V00cJGdnwhVfVvljV81WYNOchm7nIjRevwjpYSZ"
					+ "tBeKTWyd0KY1gF/K+ySLVB0CAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAvSFryCfr5SdnJz8w5vYU"
					+ "oSQZSVJ3kkRzkTXG9058zG+ND5xVoxhjTvrhUM9klOFfOsy8HFeqNSO2OfN8uOCXD3VxVV/bMGpm"
					+ "lOX0igNJWbvivv7FbkaRVsFP5BWCrBuML9xkd/H53O1eJo0RhstQPOZ8A0bOlkCsOnq+33vKJ3er"
					+ "ABuKdg3BjQVI4pDBgIBxnGUjizw/+N4n3dq6WD2Xiz5T3HYZ3DkbuzCg0I/SlM79d+kkbiuPesea"
					+ "LRZoDtxylK2Ul7sxdAZVihNQ4wVaEDulY7ZNtDNYeV4/lnqGKLB6zB9IFcjn5hNPB0EfLBqbeWkk"
					+ "P6FmoXNdZPAoqD6DPg==")),

	AC_SZIKSZI_TIME_STAMP(
			"AC_SZIKSZI_TIME_STAMP",
			Base64.decode("MIIDUzCCArygAwIBAgIBBDANBgkqhkiG9w0BAQUFADCBvzELMAkGA1UEBhMCQVQx"
					+ "DzANBgNVBAgTBlN0eXJpYTENMAsGA1UEBxMER3JhejEmMCQGA1UEChMdR1JBWiBV"
					+ "TklWRVJTSVRZIE9GIFRFQ0hOT0xPR1kxSDBGBgNVBAsTP0luc3RpdHV0ZSBmb3Ig"
					+ "QXBwbGllZCBJbmZvcm1hdGlvbiBQcm9jZXNzaW5nIGFuZCBDb21tdW5pY2F0aW9u"
					+ "czEeMBwGA1UEAxMVSUFJSy1UU1AgREVNTyBTZXJ2aWNlMB4XDTA4MDMwNTA5MTA1"
					+ "MloXDTE2MDMwNTA5MTA1Mlowgb8xCzAJBgNVBAYTAkFUMQ8wDQYDVQQIEwZTdHly"
					+ "aWExDTALBgNVBAcTBEdyYXoxJjAkBgNVBAoTHUdSQVogVU5JVkVSU0lUWSBPRiBU"
					+ "RUNITk9MT0dZMUgwRgYDVQQLEz9JbnN0aXR1dGUgZm9yIEFwcGxpZWQgSW5mb3Jt"
					+ "YXRpb24gUHJvY2Vzc2luZyBhbmQgQ29tbXVuaWNhdGlvbnMxHjAcBgNVBAMTFUlB"
					+ "SUstVFNQIERFTU8gU2VydmljZTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA"
					+ "6dq6Fox+glq0Q5Vr9wnlwcqNkVCkqxjjXpSaxBZx9eBsVz94sN2IjxPOAvmrBkIS"
					+ "qc0JJAINoauIxotRJF+yHxsIuV9yUWcc95COqEOblfsTQAJ3EKj4x8v5gQivMvB3"
					+ "lEmoQcDJBlyYkjuUFoTSEDqqly18Sv1edBykM+ETbIsCAwEAAaNdMFswDgYDVR0P"
					+ "AQH/BAQDAgeAMBIGA1UdEwEB/wQIMAYBAf8CAQAwFgYDVR0lAQH/BAwwCgYIKwYB"
					+ "BQUHAwgwHQYDVR0OBBYEFKw7i135Eoilmr9A1FZROfjcLLzNMA0GCSqGSIb3DQEB"
					+ "BQUAA4GBAL0k0hSvPsv3Nu7CnqM3Q90uAG6fwTkMIhD0LOgYW2pLKMbPn/o+dk2P"
					+ "3OowmXjuNGw4lLwsd8YiZ/3RTXGTkSvGcWjZRDoHm9pe3UK3EdGcaV0g946jJQZt"
					+ "q8akf0kPib8a3ur9y8xmXbMx4/P62qe+qLNV9BwUVgcpZfQJIsCv")),

	AC_JUS(
			"AC_JUS",
			Base64.decode("MIIEODCCAyCgAwIBAgIBFTANBgkqhkiG9w0BAQUFADCBtDELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxETAPBgNVBAcTCEJy"
					+ "YXNpbGlhMQswCQYDVQQIEwJERjExMC8GA1UEAxMoQXV0b3JpZGFkZSBDZXJ0aWZp"
					+ "Y2Fkb3JhIFJhaXogQnJhc2lsZWlyYTAeFw0wNTEyMTkxMzAwMDBaFw0xMTA2MTky"
					+ "MzU5MDBaMFAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMSwwKgYD"
					+ "VQQDEyNBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYTCCASIwDQYJ"
					+ "KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMZdinSE3Ly323/o9QhmoXxj58rV88m8"
					+ "nNzlBPjs84dSB4nvaYTwCwZtbhk+NEbCzs8ydDL5JveYNqIP1sBtqxVz+nfEdDHV"
					+ "WdwJuPwrX+q5+zkv91C/nUDfvp6ZcKh2ufGeAdI6YjDiqiPJL8wUxOd4W/KAbejp"
					+ "6yynu6X3uUFaK4ziBEsTV5WwSnoh569KSJoDGr1Gyeo/2Di48UdAT3eEemW8l56G"
					+ "nwnXX+ZwDKwPMp4rn4nq9n+7VUxlProo+xEe3OUNe8iVXftRLjTp5nrvkXMwJ/g8"
					+ "Pu3CpsQUJgDl/GRpuUCB0Tb4c9zVVqu+DTToEytyV47VxJwLOFS76esCAwD3v6OB"
					+ "tzCBtDA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vYWNyYWl6LmljcGJyYXNpbC5n"
					+ "b3YuYnIvTENSYWNyYWl6LmNybDASBgNVHSAECzAJMAcGBWBMAQETMB0GA1UdDgQW"
					+ "BBS+OdrawXcl4K69Gs6kW5/AemD8ZTAfBgNVHSMEGDAWgBSK+vFXhBETNZBC+ldJ"
					+ "VGkNpMTwNzAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG"
					+ "9w0BAQUFAAOCAQEAu22EJMIck6Q5E/piA3I26+JjChyuwU4UOWdk1GxqJ2AiI11N"
					+ "ZrjoEHc8W0gFTKZFFaywwBZYVqHvWao7iyRCDCXi4q2iVnPdA3GpMpuM69E2a5sf"
					+ "lH5Xd4VUoLpbozdio6hqjRSChX47MiIGu+B2b0DvtejdIIhkElnI2yysa0FhP7af"
					+ "qqr/FjH4Z1nDFxfJPIPQ3+u+nVICIGF7Fx/RCefIxo7+1/7e4IPsOdgCaJnsAE3x"
					+ "Kr1tz8mC+Wd8WR8ieeWwcEDt7frV1vXHSeqA8n0QwaNWfYneDWqklcr7Z9Z6bu6B"
					+ "yQfHRF6V/bSFpw6nZkYHZs7JO3w+3wmyJvc7Tg==")),

	AC_CAIXA_JUS(
			"AC_CAIXA_JUS",
			Base64.decode("MIIFlTCCBH2gAwIBAgISMjAwNjA0MDcxNTM2NDYwMDAxMA0GCSqGSIb3DQEBBQUA"
					+ "MFAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMSwwKgYDVQQDEyNB"
					+ "dXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYTAeFw0wNjA0MDcxNTUz"
					+ "MzZaFw0xMTA1MzExNTUzMzZaMHAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1At"
					+ "QnJhc2lsMTUwMwYDVQQLEyxBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVz"
					+ "dGljYSAtIEFDLUpVUzEVMBMGA1UEAxMMQUMgQ0FJWEEtSlVTMIIBIjANBgkqhkiG"
					+ "9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPeks/OhVO9rsPjWGLmx0wb0B5MfDsOsoEOs"
					+ "nO/Yh6jAiJ0Br+fUCAIWq0ehN4AWMuiemNvGdJRqJW2I42ME5WPfgPgYNMLQAopo"
					+ "oipRo9S8C0BJm1ci0ATXbDvp68lsBHFVlo1ZmyQttnz7Vb1Mlruq6S5u6seezp2z"
					+ "STFjVwzp9XVaYnutz1uD1IeCEPIdkgBRTlXP95JjacX6xnG7g2hZ2DvY1E8wqNZq"
					+ "yyQB/qyQf1gQj7z93g51d5C1FUCSVQRarwI3zEQhfi5UrhACi4wZdBsNzk7GlTLc"
					+ "gKLKvxNLyPG804qj8hEeOUuc5FTU1visVIeNnknAGTxIHJ/DGQIDAQABo4ICRzCC"
					+ "AkMwEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBS+OdrawXcl4K69Gs6k"
					+ "W5/AemD8ZTAdBgNVHQ4EFgQUDNDX/gMFm70hiQQ/Esavo6rXni4wDgYDVR0PAQH/"
					+ "BAQDAgEGMIIBnwYDVR0gBIIBljCCAZIwQQYGYEwBAgEWMDcwNQYIKwYBBQUHAgEW"
					+ "KWh0dHA6Ly93d3cuYWNqdXMuZ292LmJyL2FjanVzL2RwY2FqdXMucGRmMEEGBmBM"
					+ "AQICBTA3MDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFjanVzLmdvdi5ici9hY2p1"
					+ "cy9kcGNhanVzLnBkZjBBBgZgTAECAxMwNzA1BggrBgEFBQcCARYpaHR0cDovL3d3"
					+ "dy5hY2p1cy5nb3YuYnIvYWNqdXMvZHBjYWp1cy5wZGYwQQYGYEwBAmUFMDcwNQYI"
					+ "KwYBBQUHAgEWKWh0dHA6Ly93d3cuYWNqdXMuZ292LmJyL2FjanVzL2RwY2FqdXMu"
					+ "cGRmMEEGBmBMAQJmBDA3MDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFjanVzLmdv"
					+ "di5ici9hY2p1cy9kcGNhanVzLnBkZjBBBgZgTAECZwYwNzA1BggrBgEFBQcCARYp"
					+ "aHR0cDovL3d3dy5hY2p1cy5nb3YuYnIvYWNqdXMvZHBjYWp1cy5wZGYwOgYDVR0f"
					+ "BDMwMTAvoC2gK4YpaHR0cDovL3d3dy5hY2p1cy5nb3YuYnIvYWNqdXMvYWNqdXN2"
					+ "MS5jcmwwDQYJKoZIhvcNAQEFBQADggEBAHJhUoT96zSCDM68Gc7u40gotmTFoxN3"
					+ "JFIBOhi7aO2qABGdyRTJUq4+LzwGXk0BljF4G+sMpBZRAuy2a3sfPYFQggnK2iMl"
					+ "acRaLMkxjxhYEAMvUTptatQvsyqJAZHh/a9VKwpv98b6y1N1ZzRxQaof55w/aC5Y"
					+ "rCzal8gUSl6qJOeDF9nbarbN7FT2B5NpE34hOfLctuJG8WKr4nF4eRQR8baxpiBe"
					+ "YaAQAK0TZ14JCLipeAnivAoR+7OsIT9gk6JF+C2fQDkAWd/GX+PPsnSGJvUntoz/"
					+ "CKCkL+YS/e1kh3EqUMEXYmTKZm9lwDpzZSPVdpRieCqQNtcjXm5R2L8=")),

	AC_CAIXA_JUS_V1(
			"AC_CAIXA_JUS_V1",
			Base64.decode("MIIE7jCCA9agAwIBAgIBBTANBgkqhkiG9w0BAQUFADCBkjELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxLzAtBgNVBAMTJkF1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHYzMB4XDTExMDExNDEy"
					+ "NTkzNFoXDTE5MDExNDEyNTkzNFowczELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklD"
					+ "UC1CcmFzaWwxNTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBK"
					+ "dXN0aWNhIC0gQUMtSlVTMRgwFgYDVQQDEw9BQyBDQUlYQS1KVVMgdjEwggEiMA0G"
					+ "CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEYNAcdu1HPO7pMb+RFHxdrpXFvaLO"
					+ "p9cwak3Ne8gpG50gc711JuLL4RInT3lp7TZbtZwWM1n1g9aahxkGeOxLlDIQaTTd"
					+ "gTFP+SYljVU0w9LR37GDJ7TzNlVHGx5pskNyVYU4ENwX8nJHTN/d9XObJyVojUDd"
					+ "rqjYLRismXkA7UlJ35HlWySTRzv6aCCu3OATlasD2fbKbBpYeNPJXraoj/mMrsLQ"
					+ "J51QyR4z4fqsr5K57MuBxLTE1HdAQzPfiw43FFJrMLogK397vlSpHCDLDpBOWfBU"
					+ "1EsOvZwdso+T3fXG15XK2b1KiMH3DtvXy5TtkUJ/1U7ttpFA3+2rbuxPAgMBAAGj"
					+ "ggFrMIIBZzCBkwYDVR0gBIGLMIGIMEIGBmBMAQIBFjA4MDYGCCsGAQUFBwIBFipo"
					+ "dHRwOi8vd3d3LmFjanVzLmp1cy5ici9hY2p1cy9kcGNhY2p1cy5wZGYwQgYGYEwB"
					+ "AgMTMDgwNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVz"
					+ "L2RwY2FjanVzLnBkZjBrBgNVHR8EZDBiMC+gLaArhilodHRwOi8vd3d3LmFjanVz"
					+ "Lmp1cy5ici9hY2p1cy9hY2p1c3YzLmNybDAvoC2gK4YpaHR0cDovL2xjci5hY2p1"
					+ "cy5qdXMuYnIvYWNqdXMvYWNqdXN2My5jcmwwHwYDVR0jBBgwFoAUP02gr3F4RFoe"
					+ "vgZsmus1wxley+MwHQYDVR0OBBYEFKnX6bXDwERDwyNv7b7oWNWQTsK0MBIGA1Ud"
					+ "EwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBBQUAA4IB"
					+ "AQC2Wx0D2I1MFMRyIFAe86ba+3pptFhY9qOmt0IleYdD88798jcXANki+kINnqMb"
					+ "xdkbQJvqEaeO3YvNrbkWQ2thv1RgHP3WkbFW8gPSGkTr/DkcrV1qr2o/J5NJVO99"
					+ "Mt7pecQhjYUDo1BXGPpsKnhPBYoSRcNtrrNFgpJQwzfgD+hpBOhSqHMRiQAHSFg8"
					+ "lL7OCCSIlH93gpyyDbSvl175FOm794LUo/oL9S58rXbmtrvtzWlrABh5RlXpjxGa"
					+ "TVHbmhD8ABXaiHDKbWOTYu652qymaXs1+bmfsMmHe+wUASMhP19tI7wmY8OdMvb2"
					+ "OCBPKf5ItbldH/TvrgZIuxvX")),

	AC_JUS_V3(
			"AC_JUS_V3",
			Base64.decode("MIIEYjCCA0qgAwIBAgIBCDANBgkqhkiG9w0BAQUFADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjEwHhcNMDkw"
					+ "NjEyMTkyMDMzWhcNMTkwNjEyMTkyMDMzWjCBkjELMAkGA1UEBhMCQlIxEzARBgNV"
					+ "BAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25hbCBkZSBU"
					+ "ZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxLzAtBgNVBAMTJkF1dG9yaWRh"
					+ "ZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHYzMIIBIjANBgkqhkiG9w0BAQEF"
					+ "AAOCAQ8AMIIBCgKCAQEAwfnKu1AlD1Y56afLxPDzv5Njus9hYhb87n/Uyjgmh14N"
					+ "tuhmw7EollEDlzceWOHq7+YdxRoBOZdZ21uFIaPxLbdszOGuWmFG5djULFqLBapv"
					+ "7oGs4gzhzFyzvdxBy+3taK3sOuUJxL3A2Ig37rHF75n1YQeS3pX6M0v9FVfuuiCS"
					+ "7rwK1px3e0g+RGqGeH3XidtQem4ysNEEnPiV3b6cBPWA3XIvOuvHaYqIT/g4T4Dw"
					+ "ut8ftgfB8QVa9JEsaxMDLLZ3WfygGo8nvXKgYP/5pVksSl0YQlnOH/mx1TK4ADMS"
					+ "QV8ZWEqQZ6AY5DoiouBdmLje/pTKhzfGBdQOHaZvjwIDAQABo4G7MIG4MA8GA1Ud"
					+ "EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMBQGA1UdIAQNMAswCQYFYEwBARMw"
					+ "ADA/BgNVHR8EODA2MDSgMqAwhi5odHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3Yu"
					+ "YnIvTENSYWNyYWl6djEuY3JsMB8GA1UdIwQYMBaAFEKyLFx0AQe+m/9VMzvuKbtd"
					+ "kb8GMB0GA1UdDgQWBBQ/TaCvcXhEWh6+Bmya6zXDGV7L4zANBgkqhkiG9w0BAQUF"
					+ "AAOCAQEAWepLGyigHBzfHNj5g3N37ac+wLFF4hAC6G1Uji7YTwvZEknnc/Nn2CyW"
					+ "w9LgBnFCSRdpztsuPaqMFKjNjUx80BsFGn38DUhqD3T6t0mv+3XCnFzyxnGj/TXG"
					+ "18MwMhi7z/w4FOiFrh2n2qgmomkL1hrzdYn5X/BmVktSnqcSOA/eZqPJpkAStMgb"
					+ "+SR5uOroSC2Fo7K+UpTsJYbEwRAQAcU3HgDlvd+w20NPI7AeD66LgDIUduGJTxWI"
					+ "qC+4J2wM3B0BFVGIjGHR6IqfHSS+NVJLhf5FEHQH/x0OrdOkEcNjHGPXeiRIn+f3"
					+ "hunSu/nP0gp3WIxbThbGeDW4SgruJw==")),

	AC_CERTISIGN_JUS_G2(
			"AC_CERTISIGN_JUS_G2",
			Base64.decode("MIIGjTCCBXWgAwIBAgIBBDANBgkqhkiG9w0BAQUFADCBkjELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxLzAtBgNVBAMTJkF1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHYzMB4XDTA5MDYxOTE1"
					+ "MjUwMVoXDTE3MDYxOTE1MjUwMVowdzELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklD"
					+ "UC1CcmFzaWwxNTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBK"
					+ "dXN0aWNhIC0gQUMtSlVTMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24tSlVTIEcyMIIB"
					+ "IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1fVOFmCrWbgadqfLRaTuxDdH"
					+ "MjSoSsT6fEnhZB4EqgQDpnh+YtAe54fbNrDdqU7gS/33+GmFEMAMU54REZbsoE7H"
					+ "qfaKd6ITJvncy8ME6t2mBS5J9JTyeF1ciD6N5PCBPomY3EoNE9JlUhptSRJNiqI/"
					+ "cQZrP9A71ajGxQBx2TAsMIjNwFotCk33JPeFHpLniEL1P18X9SXBQjclL1hOhzcp"
					+ "N8kayc7sUR0DTIZQRJFFa7dBdeKPL8t1NFwzGsClqcrXb36vbdboWKmY7mwJl0yw"
					+ "gJ5RZj1ihKaMhF03PAUlBgVokwDRvlUVyXWzbLQOii1gcX2rFxLPSUYW3qucXwID"
					+ "AQABo4IDBjCCAwIwggItBgNVHSAEggIkMIICIDBCBgZgTAECARgwODA2BggrBgEF"
					+ "BQcCARYqaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMvZHBjYWNqdXMucGRm"
					+ "MEIGBmBMAQICBjA4MDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFjanVzLmp1cy5i"
					+ "ci9hY2p1cy9kcGNhY2p1cy5wZGYwQgYGYEwBAgMVMDgwNgYIKwYBBQUHAgEWKmh0"
					+ "dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2RwY2FjanVzLnBkZjBCBgZgTAEC"
					+ "BAgwODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMv"
					+ "ZHBjYWNqdXMucGRmMEIGBmBMAQJlBjA4MDYGCCsGAQUFBwIBFipodHRwOi8vd3d3"
					+ "LmFjanVzLmp1cy5ici9hY2p1cy9kcGNhY2p1cy5wZGYwQgYGYEwBAmYFMDgwNgYI"
					+ "KwYBBQUHAgEWKmh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2RwY2FjanVz"
					+ "LnBkZjBCBgZgTAECZwcwODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hY2p1cy5q"
					+ "dXMuYnIvYWNqdXMvZHBjYWNqdXMucGRmMEIGBmBMAQJoBTA4MDYGCCsGAQUFBwIB"
					+ "FipodHRwOi8vd3d3LmFjanVzLmp1cy5ici9hY2p1cy9kcGNhY2p1cy5wZGYwawYD"
					+ "VR0fBGQwYjAvoC2gK4YpaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMvYWNq"
					+ "dXN2My5jcmwwL6AtoCuGKWh0dHA6Ly9sY3IuYWNqdXMuanVzLmJyL2FjanVzL2Fj"
					+ "anVzdjMuY3JsMB8GA1UdIwQYMBaAFD9NoK9xeERaHr4GbJrrNcMZXsvjMB0GA1Ud"
					+ "DgQWBBSPlvhiDOXJae+DUhMYTfbC8Nt4DjASBgNVHRMBAf8ECDAGAQH/AgEAMA4G"
					+ "A1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAfJWnJzdCUTXw+TPZN9qF"
					+ "x0Aj/TH30yWmY+RrK+5HdYaAxXVOJls/r8du9qiY+KJ9O13AgsnNrF335E36QGkB"
					+ "sVjBuavCMHI+Sa0h9nKYHkmBe7mggDiWFF1Roc99JMEGxtuFxp7HMuVnGjU8SKBE"
					+ "WwVKToCwRNUDrhTc0ZNRumrs4pr3UVcaZUWoP+eT5uKH4iUMfYg9ZU0tFBxmp57J"
					+ "TJYZ3yCaHbndOMn8yBS/LcyphEiVJ65BeLgkve2ZiLImXERE5pDm6dDbddEsDtIK"
					+ "+0rg/BCw41gH4blEK4xl7QlWegWPca0r2UM5q+7ovxW/GFj3udVWZygEeqbSAURU"
					+ "ug==")),

	AC_RFB_V2(
			"AC_RFB_V2",
			Base64.decode("MIIEEDCCAvigAwIBAgIBBTANBgkqhkiG9w0BAQUFADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjEwHhcNMDgx"
					+ "MDI0MTIzOTQ2WhcNMTgxMDI0MTIzOTQ2WjBXMQswCQYDVQQGEwJCUjETMBEGA1UE"
					+ "ChMKSUNQLUJyYXNpbDEzMDEGA1UEAxMqQUMgU2VjcmV0YXJpYSBkYSBSZWNlaXRh"
					+ "IEZlZGVyYWwgZG8gQnJhc2lsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC"
					+ "AQEA3o1phpOoNH/BA5ydDgeDndk7mItSVUK7t3PNjCkF/7lCSM3SiQxi/XsnvS3f"
					+ "4NCR5Vq/4yGrWa31FJi/XYRlLZH46L86S2hOBkV5sIxrr0EPN5q/EUTQCrcbcqgr"
					+ "V9QX2SSPqOO5+wS8+zygNfBAOPFSLpqwyzSYS+ZQdeDkuhFMikF07e7XwfRvc+/K"
					+ "eR0RU1p8GijtAtqsXGmq/8wunlySd7g+h2CfkILnY87GyB3UwOP7zSOaV2Un9/yz"
					+ "dBRduGpUZSx2yn8FrBB7mCfE58gJo5YZ1KZfcSfRNrAaQW6B7mDLsRnDdn5jYQnn"
					+ "0w/xf9Kwq3YFB1rZKRDBGLqhVwIDAQABo4GlMIGiMA8GA1UdEwEB/wQFMAMBAf8w"
					+ "DgYDVR0PAQH/BAQDAgEGMD8GA1UdHwQ4MDYwNKAyoDCGLmh0dHA6Ly9hY3JhaXou"
					+ "aWNwYnJhc2lsLmdvdi5ici9MQ1JhY3JhaXp2MS5jcmwwHwYDVR0jBBgwFoAUQrIs"
					+ "XHQBB76b/1UzO+4pu12RvwYwHQYDVR0OBBYEFBtdm3eNVCVtBaPCcqy/d/mxPDhL"
					+ "MA0GCSqGSIb3DQEBBQUAA4IBAQAfE0z7q9dicmpuK8TbkmFjb5NdR4xxy5n2H+hI"
					+ "S/mxAXXUxD1MHQltmFzjGjCVLKxfnLXDFPzfEuB1KCEACseAS1q2iAgDaEOAbVoG"
					+ "iSNZF5Tx8wCdkGXszBC8kdM4RUsLqVAAIkNxH+6K7I9r9Z5/8oNg/JZHCnNP5BLq"
					+ "1nKxplltISTTfNecUP2bY/7f24oGlYfoYwtzPZEDu1Zw01jHbT5K4vaMG4pV81d6"
					+ "exb+paeCVcZItAo8lxc35ago9RG5HyWO0Ep08CVzesO5CNVhFb5BQDKO/fDDyNPH"
					+ "DirDKnx6ZJAclztk6KtIJK9yjixYkBeG6J78eYMhnxJJmfRh")),

	AC_CERTISIGN_RFB_G3(
			"AC_CERTISIGN_RFB_G3",
			Base64.decode("MIIE8DCCA9igAwIBAgIBAzANBgkqhkiG9w0BAQUFADBXMQswCQYDVQQGEwJCUjET"
					+ "MBEGA1UEChMKSUNQLUJyYXNpbDEzMDEGA1UEAxMqQUMgU2VjcmV0YXJpYSBkYSBS"
					+ "ZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsMB4XDTA4MTAyOTE4MzM1M1oXDTE2MTAy"
					+ "OTE4MzM1M1oweDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0"
					+ "BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAt"
					+ "IFJGQjEcMBoGA1UEAxMTQUMgQ2VydGlzaWduIFJGQiBHMzCCASIwDQYJKoZIhvcN"
					+ "AQEBBQADggEPADCCAQoCggEBAKbdyy+BUmEaNq8A7PyWX8C6xRGkdn8K8TRgAPUm"
					+ "ncAUEpLZhqdu5l66Tf6cEdkiMxityVIAIUKQPnc2fqUqhHgLJXb4ALQlCx0T3VgV"
					+ "9QhTO/dDr7zH+Kbi3r1Wq/alJPcnm3mb8ttINpJ+FaAaSK9MkAMwCFopcNsxfH+m"
					+ "Jp3AcUjK68RzUjsOaIbZ5h6CjYF2EJMtQXEJ8Da97IFCjOsafRbbojtL5vkO1Hdo"
					+ "zbqIN2vGVeqeCC3maycjTsNxIHmELtVUQDG1xwK1jce+Ghjs16YR7V3PT/x6ENzo"
					+ "8MktDheYl4/0U/xvnBS9TsERqW6Z4hY8TAeSLkogc9H3IkcCAwEAAaOCAaQwggGg"
					+ "MIH1BgNVHSAEge0wgeowTAYGYEwBAgEMMEIwQAYIKwYBBQUHAgEWNGh0dHA6Ly93"
					+ "d3cucmVjZWl0YS5mYXplbmRhLmdvdi5ici9hY3JmYi9kcGNhY3JmYi5wZGYwTAYG"
					+ "YEwBAgMGMEIwQAYIKwYBBQUHAgEWNGh0dHA6Ly93d3cucmVjZWl0YS5mYXplbmRh"
					+ "Lmdvdi5ici9hY3JmYi9kcGNhY3JmYi5wZGYwTAYGYEwBAgQEMEIwQAYIKwYBBQUH"
					+ "AgEWNGh0dHA6Ly93d3cucmVjZWl0YS5mYXplbmRhLmdvdi5ici9hY3JmYi9kcGNh"
					+ "Y3JmYi5wZGYwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL3d3dy5yZWNlaXRhLmZh"
					+ "emVuZGEuZ292LmJyL2FjcmZiL2FjcmZiLmNybDAfBgNVHSMEGDAWgBQbXZt3jVQl"
					+ "bQWjwnKsv3f5sTw4SzAdBgNVHQ4EFgQU/IBr1U3R/HjYbGQvYUs4p4Lw3J0wEgYD"
					+ "VR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQEFBQAD"
					+ "ggEBANgf9Wcg8eKwMFznk2ibOjhp5PGip0/c5bcBe2WYPi/h7Bi5NsHXYyoQQV7b"
					+ "KHS5yrqEg7uvsid5X8ZhHN/aIeiaiUP/bZnQidtuRM2dZOwfUr8dW1agOdfxwwcz"
					+ "BaOx6CNo/TEysDiuINb46c+xzbFI8xDPtONXWlelx0s1wiUt2RJNHusby6XBGbHM"
					+ "Oh4BRIVe+C/qC/pY9gj1c5pzG+Sa18T9XxEfsWEZRXcDHwrlI3+61ZLwe7fM7OcA"
					+ "LXHZCfefx/Xqs8wkb46uNetJuASVkFgn6/OlesJ9yeyHRuKz3LHNRyKbPHGfAA5y"
					+ "lwHLCVPhSeF1oJ8Y9YrPlo8nVBs=")),

	AC_CAIXA_JUS_V2(
			"AC_CAIXA_JUS_V2",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUc1VENDQk0yZ0F3SUJBZ0lCQXpBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCaVRFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eE5EQXlCZ05WQkFzVEswRjFkRzl5YVdSaFpHVWdRMlZ5ZEdsbQphV05oWkc5eVlTQlNZ"
					+ "V2w2SUVKeVlYTnBiR1ZwY21FZ2RqSXhMekF0QmdOVkJBTVRKa0YxZEc5eWFXUmhaR1VnClEyVnlk"
					+ "R2xtYVdOaFpHOXlZU0JrWVNCS2RYTjBhV05oSUhZME1CNFhEVEV4TVRJeU9ERXpNRE15TVZvWERU"
					+ "RTUKTVRJeU9ERXpNRE15TVZvd2N6RUxNQWtHQTFVRUJoTUNRbEl4RXpBUkJnTlZCQW9UQ2tsRFVD"
					+ "MUNjbUZ6YVd3eApOVEF6QmdOVkJBc1RMRUYxZEc5eWFXUmhaR1VnUTJWeWRHbG1hV05oWkc5eVlT"
					+ "QmtZU0JLZFhOMGFXTmhJQzBnClFVTXRTbFZUTVJnd0ZnWURWUVFERXc5QlF5QkRRVWxZUVMxS1ZW"
					+ "TWdkakl3Z2dJaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNhM2VpUVF2"
					+ "SktwMGRueU5zOVpvNE9VYVFsVUtmMlJSL2wxOVg2MUkrdApMdjdRMVg1UW05Z09UdGJHMWU1a1ky"
					+ "VWpQVXZaaHE4cC9iRkRzQThFQ0lFR0Z3RGVhSWdWZGlnbkxZd3J1eElNCjQ3NjlFN21oaTJrNjcy"
					+ "Q2tpd1ZvdDRPNHZHYjh2UzV2VVhlWUs5ZzlzdzBtY21mRTVBcWlQUFFQSXhGZm5WMDYKOE9uRTA2"
					+ "dTdIT2tvY0wrdm96dDZRQ1lhem16dDcrRkpCY3R2QnBvdXo5UXplRzVTMHQwcGlwdldZZFdjVmtw"
					+ "TApPd1lSOVoyekhtMmpnV2dIM0xVK01rL205eGRNM0RsbWR6bi9sb254RjVKQ2VvV2xXc3lwSG1G"
					+ "YVNMalRiNjNMCmlyT2Q3NnpWdkZpWnBaa0w4c3JXN2pwKzJ0WklmSTdmWi8xMzNob0tQUDBNTHhm"
					+ "K0VIbitKTUJVbDBtbldiclEKMXFMckY4UzMrYUZBRlMvM3dCZHA2Wk9VVXl5c29qVFBUSlRVRXor"
					+ "TldTYVNjK0ZGT3VXREZxb0w5QUl6cko3ZgpJb2dwVjcrbC9FSGx1bE9XMXVObXhNV3hwZW9tZFNX"
					+ "WkN2M0I3UFJTeFBsbDNhT3djdno0WThDNHllQVNDaGE1Cld4QXBLOHBtU2xDV0x3TlFWM0d1aTYr"
					+ "aGNBRDdXWVhyQzZYaVM4N0RNeXprMEtTOU1oQjJjVHpKK0sxZHZUbUQKK2Vjb0tacEVtSkQ0T2tC"
					+ "R1dEWFFDalA1RlR2YnlZd0VEdmtlT0U2N0NRR0FLc3Z2d1dhRjFEbWNOTmxqSGFSdwpaM29HMVVV"
					+ "cEVpWnBWZ2V6ekZlR0l6U1JPZm5VNXcyY05NQkxMVlljS1VGeWZONnJSQzZ0bG9TanFoQ0ZVb2h1"
					+ "CjVRSURBUUFCbzRJQmF6Q0NBV2N3Z1pNR0ExVWRJQVNCaXpDQmlEQkNCZ1pnVEFFQ0FSWXdPREEy"
					+ "QmdnckJnRUYKQlFjQ0FSWXFhSFIwY0RvdkwzZDNkeTVoWTJwMWN5NXFkWE11WW5JdllXTnFkWE12"
					+ "WkhCallXTnFkWE11Y0dSbQpNRUlHQm1CTUFRSURFekE0TURZR0NDc0dBUVVGQndJQkZpcG9kSFJ3"
					+ "T2k4dmQzZDNMbUZqYW5WekxtcDFjeTVpCmNpOWhZMnAxY3k5a2NHTmhZMnAxY3k1d1pHWXdhd1lE"
					+ "VlIwZkJHUXdZakF2b0MyZ0s0WXBhSFIwY0RvdkwzZDMKZHk1aFkycDFjeTVxZFhNdVluSXZZV05x"
					+ "ZFhNdllXTnFkWE4yTkM1amNtd3dMNkF0b0N1R0tXaDBkSEE2THk5cwpZM0l1WVdOcWRYTXVhblZ6"
					+ "TG1KeUwyRmphblZ6TDJGamFuVnpkalF1WTNKc01COEdBMVVkSXdRWU1CYUFGUGc1CkFLWCs2N0lu"
					+ "bWdhTFlaWUMrdEtRa08yK01CMEdBMVVkRGdRV0JCVFVzY01wU1pldFRtWTIyK2xPQUVwcTJNUGEK"
					+ "eERBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1BNEdBMVVkRHdFQi93UUVBd0lCQmpBTkJna3Fo"
					+ "a2lHOXcwQgpBUTBGQUFPQ0FnRUFyRXdjVFRyYTl0Zm5VcTVZWThGNHErN3o1UUQzbkx2bDQyc1J0"
					+ "cVllcDllazJqZlU5OUtUCmgzOG9HNmdyTHVHb0FuUkdyRVBMb2Q2Zlo0c1c2VW1tZWphYzRTSzAr"
					+ "UTN3bnpaZklXUXFJeXQxQ2kyOGppTGwKSzRmWk5lMnJKNTNXeHA5YWlkb3QzMSsrdGJuM0lUeWJn"
					+ "ZlJ2Z1o5bVBDRmYrdW5iL1ZWdmFiRFNFVTlYT3ZFZgo1K296OXZJbVBoUG5EUW5FZkVuM1VraVdM"
					+ "Y2hSY1E1VXpZYVlqTmxheVlJc29CSVpsanZtdjZBK1JUYy9MWU9OCko4UGZWVnJjS1loL3VBNDZx"
					+ "b2pGbitvcUxKYkxXVGYvQlQrOGtqVjBGR0x5eEl4SllRVDRQQ1hNTCtHUTBaa0gKRlZiL2ZVdE5H"
					+ "YVBZZ3FXQmR3aXJqQUlmRUUzRnNsWGpmblZsNTZZL1U4WnRjNWd5VXJZWEIwRTBvcFRUUWErUgpn"
					+ "Z242Q3Brcm9Ib092Y3pWdVEvT29yV0lobXVEdTlNVmgybmpRNlhrNzFKd1BGMGJVb0lqTFZncWll"
					+ "d3BGeFBNCkFLME9UVnF6LzNVa1lVajdvQTRIeU12VnFjbnZDb09FbWM4dk9hd3hLeUlCQVB0VUlt"
					+ "elZqdkFvQmpra25iMTQKS1AyQ3grNzduN0JoUEJmZ1JnR251UFBrMCt1ZG1hTUhreTNmVFVIVWNY"
					+ "RlcxaktlaDlUSWIzRW0wYTA2dHJZTQpLSVp0YXN3bDZraW5md2ExdnRwTE5GYmVpZERqR3VXei9Q"
					+ "dXk3SDJZQnpsUjVoTEFvYi8wbGlIeUQrSnNqdW14CkxiZmVPYlVvanM5bUpVcEdOUkRVLzB2U3pN"
					+ "b002WGdUSEl1WTJVT1RuNmJ4enlZb0NtWDRaME09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K")),

	AC_CERTISIGN_JUS_G3(
			"AC_CERTISIGN_JUS_G3",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUc2VENDQk5HZ0F3SUJBZ0lCQVRBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCaVRFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eE5EQXlCZ05WQkFzVEswRjFkRzl5YVdSaFpHVWdRMlZ5ZEdsbQphV05oWkc5eVlTQlNZ"
					+ "V2w2SUVKeVlYTnBiR1ZwY21FZ2RqSXhMekF0QmdOVkJBTVRKa0YxZEc5eWFXUmhaR1VnClEyVnlk"
					+ "R2xtYVdOaFpHOXlZU0JrWVNCS2RYTjBhV05oSUhZME1CNFhEVEV4TVRJeU16RXpNRE15TTFvWERU"
					+ "RTUKTVRJeU16RXpNRE15TTFvd2R6RUxNQWtHQTFVRUJoTUNRbEl4RXpBUkJnTlZCQW9UQ2tsRFVD"
					+ "MUNjbUZ6YVd3eApOVEF6QmdOVkJBc1RMRUYxZEc5eWFXUmhaR1VnUTJWeWRHbG1hV05oWkc5eVlT"
					+ "QmtZU0JLZFhOMGFXTmhJQzBnClFVTXRTbFZUTVJ3d0dnWURWUVFERXhOQlF5QkRaWEowYVhOcFoy"
					+ "NHRTbFZUSUVjek1JSUNJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXhy"
					+ "bE5TRVpRUlBITkg4NWtrejJNd3E3bGZnYUFNR2RqeWtRRgpIRE9uU0c3WEhWWEw1b2psRW1HTWpC"
					+ "OHlVZGp1VjRMRXBESmVBcDRtbk9oWnFiZHZtUmhxTFVJOWVWSXFZNnNOCmpaSXc0eE9SV0cvSEFQ"
					+ "M0kyRGdKazdWSm01MWFqdTR5UnZnbFh3MVlDSDRzUGhjanAwZnZDNGMzRzUyT1V4TkUKdXRYcWo5"
					+ "Tk1hQnRPcHNzUFZ5b3hSZkpVZVBnSU5TbWtDcEJLUkJqM2xlajZZbnpwek5mWVRVcVByTFg5OW91"
					+ "eQpYYlFITHRxQlIvNWROOExEbS9OcU9JNm03bk9XZDc1Z29JNHpOVWR4MkpBbnVqU1c0UEc2OFVD"
					+ "Mm9RR3M3OS9DCm1KeGNmV0hXSmpOcVFzYmQ1c29GbUVXU3dmYXgycTBXWEl6QXZoRmlUSWVBNk9l"
					+ "VzM4UlZ1bnd4VUVWRTkvRVgKSTNvWG9yd293aW1TbmZYeU1GQ0xmYktmcUFXT2ZVa040QjZ3Yks5"
					+ "RVVXWXpLeEZYVURtS21BSVFublZuTWt6TQp6Rng5TUpnSm1lZXpDM0dpZ0dpOTI4OUozYmdGSXQr"
					+ "em9rWWtETzRWWWxHVitHc1I1eUdtSGUxc0xVK3R6RFhNCmVqbVdvWjg1dmZKbk40UlNzcVVtZEUz"
					+ "aUlvQUxPR3k2TGVsYkV3SGdUdlNmNUpBS2xYNUJYbTNkSWZTbWZVN2oKS3VFTHdtLy9uc3UrRWF3"
					+ "U1pVMFpMLytIOThnYk5IOW1nWlhPL3MzbkN2THhXUjNQNXlzT0dieVpBa1FyelFvSgpLYS9lSGhY"
					+ "ZXppUkV3ekdhdHRMdEt4NHZRZWplUzcwaC9LNlFMSThIRkFxTXRTS2VuQmRHdUh5dFpQdi9BVDNJ"
					+ "Ckw0TDBoQjBDQXdFQUFhT0NBV3N3Z2dGbk1JR1RCZ05WSFNBRWdZc3dnWWd3UWdZR1lFd0JBZ0VZ"
					+ "TURnd05nWUkKS3dZQkJRVUhBZ0VXS21oMGRIQTZMeTkzZDNjdVlXTnFkWE11YW5WekxtSnlMMkZq"
					+ "YW5WekwyUndZMkZqYW5WegpMbkJrWmpCQ0JnWmdUQUVDQXhVd09EQTJCZ2dyQmdFRkJRY0NBUllx"
					+ "YUhSMGNEb3ZMM2QzZHk1aFkycDFjeTVxCmRYTXVZbkl2WVdOcWRYTXZaSEJqWVdOcWRYTXVjR1Jt"
					+ "TUdzR0ExVWRId1JrTUdJd0w2QXRvQ3VHS1doMGRIQTYKTHk5M2QzY3VZV05xZFhNdWFuVnpMbUp5"
					+ "TDJGamFuVnpMMkZqYW5WemRqUXVZM0pzTUMrZ0xhQXJoaWxvZEhSdwpPaTh2YkdOeUxtRmphblZ6"
					+ "TG1wMWN5NWljaTloWTJwMWN5OWhZMnAxYzNZMExtTnliREFmQmdOVkhTTUVHREFXCmdCVDRPUUNs"
					+ "L3V1eUo1b0dpMkdXQXZyU2tKRHR2akFkQmdOVkhRNEVGZ1FVYlcrQUdpVEVCeW16SjJnUXlFbTUK"
					+ "YnViQ0pjSXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdE"
					+ "UVlKS29aSQpodmNOQVFFTkJRQURnZ0lCQUlTVDZkNFArbE5WZ1JhL1BFQ3dROTRwaWcxVW5iUUtP"
					+ "Zm84WlFDUHp2ZG1rQWRHCnl5V3NXMDFUb0gwbUh3VVJIa2JpZlBQL3NKdXY0UE5aS3kxdkRPMXNQ"
					+ "RDIxbkYwNlUxbnFJV1AyM3dxNnhTUk0KR3M2TXAyelF2RHQrWitxdkhWUUdWeVZaTnJsOUJsRXBi"
					+ "TkNjWmE1bVRmWC9mMEhWVk9OcWFHenF2cDNKRURWNgpSTVBPZXdhdDdXd0RHUXlCeldKQUNDcjhE"
					+ "NFltSGVWZVphYURmWEhnR3A1RFpmMC82K1h2c3dlY2htdHB1blJnCmhZdXEzMXlwc3ZCWVVKWmd0"
					+ "ZzZTYXNjVzU1U3ppaWJlcksyY2lURWp0a1dNVTV2VVpvOGJiWjJHNzFaVTRVOVgKcHpDaEhQMFVx"
					+ "WW1NTWIrQk1paXJ5ZnlZV2RzempJNnR5NXNqcjJOMW1aYnRwQUZtOEw3eW45TEhvUWNTM2pLQgpL"
					+ "ekVUVVlDdXB3aXVaMnUzUCtCQnVvYUJ5TTJGSm1uYnlQK1NpR050Q0tZanptMisvUzhWTUd3MGdr"
					+ "MkhLL1FSCnk0WUMyaWkxa1B6YUNKL25IREcrblhqSTJYWmEycHVwa0NpZWJaVFdlMDhMbldTd3FM"
					+ "NW9Nd3pGaURuencxNDMKWlFtdXNoR2F5dEhtSTlzQ3FrS1RNMGVhR0hTTEFqY2c0d2JUQ3lFV2k3"
					+ "VCtkd2lDSDZWaURqZ0RzdnZFY3ZHbwphZWFJVGVCYWdCbUdxUVhiSEdmeXB4R2RuRUhxeGNZa2JJ"
					+ "bDNJa3IyUHZtdjlvaHRIUDlJc0NKcU1yYlp3emR4CkY2U2hWcjNiTUh0bDZnOWRHU1lTVHIzdjlN"
					+ "RjdRck5USDZwMnBPaGFqRlJWaTkrQ3VvSE9QbXZCZUFneAotLS0tLUVORCBDRVJUSUZJQ0FURS0t"
					+ "LS0tCg==")),

	AC_CERTISIGN_JUS_G3_NOVO(
			"AC_CERTISIGN_JUS_G3_NOVO",
			Base64.decode("MIIG6TCCBNGgAwIBAgIBATANBgkqhkiG9w0BAQ0FADCBiTELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIxLzAtBgNVBAMTJkF1dG9yaWRhZGUg"
					+ "Q2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHY0MB4XDTExMTIyMzEzMDMyM1oXDTE5"
					+ "MTIyMzEzMDMyM1owdzELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwx"
					+ "NTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIC0g"
					+ "QUMtSlVTMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24tSlVTIEczMIICIjANBgkqhkiG"
					+ "9w0BAQEFAAOCAg8AMIICCgKCAgEAxrlNSEZQRPHNH85kkz2Mwq7lfgaAMGdjykQF"
					+ "HDOnSG7XHVXL5ojlEmGMjB8yUdjuV4LEpDJeAp4mnOhZqbdvmRhqLUI9eVIqY6sN"
					+ "jZIw4xORWG/HAP3I2DgJk7VJm51aju4yRvglXw1YCH4sPhcjp0fvC4c3G52OUxNE"
					+ "utXqj9NMaBtOpssPVyoxRfJUePgINSmkCpBKRBj3lej6YnzpzNfYTUqPrLX99ouy"
					+ "XbQHLtqBR/5dN8LDm/NqOI6m7nOWd75goI4zNUdx2JAnujSW4PG68UC2oQGs79/C"
					+ "mJxcfWHWJjNqQsbd5soFmEWSwfax2q0WXIzAvhFiTIeA6OeW38RVunwxUEVE9/EX"
					+ "I3oXorwowimSnfXyMFCLfbKfqAWOfUkN4B6wbK9EUWYzKxFXUDmKmAIQnnVnMkzM"
					+ "zFx9MJgJmeezC3GigGi9289J3bgFIt+zokYkDO4VYlGV+GsR5yGmHe1sLU+tzDXM"
					+ "ejmWoZ85vfJnN4RSsqUmdE3iIoALOGy6LelbEwHgTvSf5JAKlX5BXm3dIfSmfU7j"
					+ "KuELwm//nsu+EawSZU0ZL/+H98gbNH9mgZXO/s3nCvLxWR3P5ysOGbyZAkQrzQoJ"
					+ "Ka/eHhXeziREwzGattLtKx4vQejeS70h/K6QLI8HFAqMtSKenBdGuHytZPv/AT3I"
					+ "L4L0hB0CAwEAAaOCAWswggFnMIGTBgNVHSAEgYswgYgwQgYGYEwBAgEYMDgwNgYI"
					+ "KwYBBQUHAgEWKmh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2RwY2FjanVz"
					+ "LnBkZjBCBgZgTAECAxUwODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hY2p1cy5q"
					+ "dXMuYnIvYWNqdXMvZHBjYWNqdXMucGRmMGsGA1UdHwRkMGIwL6AtoCuGKWh0dHA6"
					+ "Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2FjanVzdjQuY3JsMC+gLaArhilodHRw"
					+ "Oi8vbGNyLmFjanVzLmp1cy5ici9hY2p1cy9hY2p1c3Y0LmNybDAfBgNVHSMEGDAW"
					+ "gBT4OQCl/uuyJ5oGi2GWAvrSkJDtvjAdBgNVHQ4EFgQUbW+AGiTEBymzJ2gQyEm5"
					+ "bubCJcIwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZI"
					+ "hvcNAQENBQADggIBAIST6d4P+lNVgRa/PECwQ94pig1UnbQKOfo8ZQCPzvdmkAdG"
					+ "yyWsW01ToH0mHwURHkbifPP/sJuv4PNZKy1vDO1sPD21nF06U1nqIWP23wq6xSRM"
					+ "Gs6Mp2zQvDt+Z+qvHVQGVyVZNrl9BlEpbNCcZa5mTfX/f0HVVONqaGzqvp3JEDV6"
					+ "RMPOewat7WwDGQyBzWJACCr8D4YmHeVeZaaDfXHgGp5DZf0/6+XvswechmtpunRg"
					+ "hYuq31ypsvBYUJZgtg6SascW55SziiberK2ciTEjtkWMU5vUZo8bbZ2G71ZU4U9X"
					+ "pzChHP0UqYmMMb+BMiiryfyYWdszjI6ty5sjr2N1mZbtpAFm8L7yn9LHoQcS3jKB"
					+ "KzETUYCupwiuZ2u3P+BBuoaByM2FJmnbyP+SiGNtCKYjzm2+/S8VMGw0gk2HK/QR"
					+ "y4YC2ii1kPzaCJ/nHDG+nXjI2XZa2pupkCiebZTWe08LnWSwqL5oMwzFiDnzw143"
					+ "ZQmushGaytHmI9sCqkKTM0eaGHSLAjcg4wbTCyEWi7T+dwiCH6ViDjgDsvvEcvGo"
					+ "aeaITeBagBmGqQXbHGfypxGdnEHqxcYkbIl3Ikr2Pvmv9ohtHP9IsCJqMrbZwzdx"
					+ "F6ShVr3bMHtl6g9dGSYSTr3v9MF7QrNTH6p2pOhajFRVi9+CuoHOPmvBeAgx")),

	AC_SERASA_JUS_V2(
			"AC_SERASA_JUS_V2",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhjVENDQlZtZ0F3SUJBZ0lCQkRBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCaVRFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eE5EQXlCZ05WQkFzVEswRjFkRzl5YVdSaFpHVWdRMlZ5ZEdsbQphV05oWkc5eVlTQlNZ"
					+ "V2w2SUVKeVlYTnBiR1ZwY21FZ2RqSXhMekF0QmdOVkJBTVRKa0YxZEc5eWFXUmhaR1VnClEyVnlk"
					+ "R2xtYVdOaFpHOXlZU0JrWVNCS2RYTjBhV05oSUhZME1CNFhEVEV4TVRJeU9ERXpNemt6T0ZvWERU"
					+ "RTUKTVRJeU9ERXpNemt6T0Zvd2RERUxNQWtHQTFVRUJoTUNRbEl4RXpBUkJnTlZCQW9UQ2tsRFVD"
					+ "MUNjbUZ6YVd3eApOVEF6QmdOVkJBc1RMRUYxZEc5eWFXUmhaR1VnUTJWeWRHbG1hV05oWkc5eVlT"
					+ "QmtZU0JLZFhOMGFXTmhJQzBnClFVTXRTbFZUTVJrd0Z3WURWUVFERXhCQlF5QlRSVkpCVTBFdFNs"
					+ "VlRJSFl5TUlJQ0lqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBb1JOWWFU"
					+ "bDdRZHU4VS9zZFdocjgxUWpXdmZSOHRodWt0QktnNjYxcQpXZlNIUGExbnprRWJkcEc0UE81TmlD"
					+ "TTFIZVdvY1lFRmU1OTRSQ3A2cG9rTFY1TG5BMGdPc1ZyRTYzL3pDZFMwCmJKZ0pBZ1ZvQWQveFlp"
					+ "TE9YeXFLTktpTG1aVzhFU3UvN24xdTFnajVhMTdDbXBoVzd5QzNraktHUk1WU0RMRmwKajlDME1T"
					+ "K2I0R3hLaFZqRml4NnA0RWFaNk9CNUhJenRrMENlblZ1Mlo1eC9oSWhjc3RubHdHMitWR3lNUkR4"
					+ "TgpCbzhjcEU3QlRxQUJLbVhGb1pDNDBsQW5kaEdJelptOU1KT2Y4d3VUbW9kSGZ1M01VbitXMjNu"
					+ "cFZQTGliWGlECmIrRXp4dUhDS29MTkY1NjAxbEdSOWNoeVRobFRkVkxuZFFBNW9Pand5TkNvRE1w"
					+ "cXBnaWdIMklmK21mTG9pZkwKSk1seDMxdEJ3TE0zSkhqUHVoWlNob0hnaEFPY3RlczQxWHQxVUJj"
					+ "aDNOUGlyQWtGdFg2U1RaS0tkSmZLR29FSgpKZWo4MjVYZDdlYW95V1VHSG1xUmU4TGd5SktlKzA5"
					+ "M1NIbytPQ1MvQkU5Vm9QWE5wbU5DbUVYNTdTUFpkVUJaCnJGT25TekM0a205Tzh5Y0lsYzlBNU9q"
					+ "T1Z2QXVyRFFTc1lrT1AvUjE2YVFUSXVlOHJ2NTd6OTMrRUlnMW5SM3IKYmpCNCtYNnppUVBHdUpt"
					+ "OVRMem1WZ1dOOENQb0tPejltR1dQODQ1SktPMnZ0Q3NvVWNGaHRKSVVzeTc3aHhzdwpTZlliNWRQ"
					+ "MW9FS3FPNWhkM0phUEhkWTRha1ZBdVYvWDdmTzZFdUhRQXl3cU5aUGpPdTY1QlYxZkJmVFlreThl"
					+ "CnBOc0NBd0VBQWFPQ0FmWXdnZ0h5TUlJQkhRWURWUjBnQklJQkZEQ0NBUkF3UWdZR1lFd0JBZ0Va"
					+ "TURnd05nWUkKS3dZQkJRVUhBZ0VXS21oMGRIQTZMeTkzZDNjdVlXTnFkWE11YW5WekxtSnlMMkZq"
					+ "YW5WekwyUndZMkZqYW5WegpMbkJrWmpCQ0JnWmdUQUVDQWdjd09EQTJCZ2dyQmdFRkJRY0NBUllx"
					+ "YUhSMGNEb3ZMM2QzZHk1aFkycDFjeTVxCmRYTXVZbkl2WVdOcWRYTXZaSEJqWVdOcWRYTXVjR1Jt"
					+ "TUVJR0JtQk1BUUlERmpBNE1EWUdDQ3NHQVFVRkJ3SUIKRmlwb2RIUndPaTh2ZDNkM0xtRmphblZ6"
					+ "TG1wMWN5NWljaTloWTJwMWN5OWtjR05oWTJwMWN5NXdaR1l3UWdZRwpZRXdCQWdRS01EZ3dOZ1lJ"
					+ "S3dZQkJRVUhBZ0VXS21oMGRIQTZMeTkzZDNjdVlXTnFkWE11YW5WekxtSnlMMkZqCmFuVnpMMlJ3"
					+ "WTJGamFuVnpMbkJrWmpCckJnTlZIUjhFWkRCaU1DK2dMYUFyaGlsb2RIUndPaTh2ZDNkM0xtRmoK"
					+ "YW5WekxtcDFjeTVpY2k5aFkycDFjeTloWTJwMWMzWTBMbU55YkRBdm9DMmdLNFlwYUhSMGNEb3ZM"
					+ "MnhqY2k1aApZMnAxY3k1cWRYTXVZbkl2WVdOcWRYTXZZV05xZFhOMk5DNWpjbXd3SHdZRFZSMGpC"
					+ "Qmd3Rm9BVStEa0FwZjdyCnNpZWFCb3RobGdMNjBwQ1E3YjR3SFFZRFZSME9CQllFRkQ0ajJaZlJn"
					+ "TW9RK1JPdWNONlVvRUd5Vm1Pek1CSUcKQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3RGdZRFZSMFBB"
					+ "UUgvQkFRREFnRUdNQTBHQ1NxR1NJYjNEUUVCRFFVQQpBNElDQVFCbHlKRmlaRHZzLzRNUDY3b08z"
					+ "aHNMeGxUS2xWWG9FTU9yM3ZYK1BjYUJjUDM4VFB1emNsL3YrTU1pCjRLVWo2K2d0VEFydmtONkZX"
					+ "QXFkRzV6R3Q0WWRIZWtMZEVjb01aQ3RmSEF6OUNreHpEYUpDTnMwZlBpejJsL3cKQ0JjZk9jSzJh"
					+ "VGN3OTJlcHdLYzNLdU45bHFhMXNKYUlhV3RsUkRaRXBtK2ROMFpISmkwUEZMeHVFRTZ4cXRnKwpv"
					+ "MXEyVXdKMmhEazVmSHR4VmJvQnlRMzh2cTNQS2NxeWpJZXFIOGxRUGRTSUxraGhlTHVNQTF5cFVM"
					+ "WXBBS2pLCkh5S2dUYUVwKzlDaWwrSVp4OFVvQTBIUHNXNEdPTE4yQjdCejQwRjV1SGp6aFg2YWdO"
					+ "RmpCVzJibW9WcFVRczUKM2tGdk9XYVVkUkFCVWRESGFMd1BzMVFJUS9uaFNUVGJqRmdsU2t3d2ZW"
					+ "MjFrN2ZGbjYza0dOUzdGbHQ1WUJpYQptRzhxeTZKQk9JTnl1OGduNFAyT3lOcEFsenBCUGN2UVBI"
					+ "VGJKSi85WHFic2VVNDRVNHNwcnZIVVIyUHBrYWMxCnRqSFdBTWNsOFpyQmx0L2pwMjJwYmE5WWRE"
					+ "Qm9FS0syUzBuQWFtV0RzN0xFQUFoQ2NvM3VYL215cjNJUTRSVlYKSTJWaURxbXhBeEZoeU9pdUpu"
					+ "UHg1dklnQWduQUtaWTlIVTR5NS80QUc5QmpqbHdxUDdlR3hFK3NkcWIwWWcrVgpUTjBicVdGME85"
					+ "UHRoVGdTT2ZCR2F5Y3prMER6SkRhS1p2RmZVMzR0YjhPSFFGSlZ3NXhmUmtVWWl6eE01TzBKCkN6"
					+ "bFM0SjNjRDMzNW1ScE5CMGNza1FUelZ3eHIrcS9tK29rT3VxVjBwbVZGK0Z2ZDFBPT0KLS0tLS1F"
					+ "TkQgQ0VSVElGSUNBVEUtLS0tLQo=")),
					AC_SERASA_JUS_V1(
							"AC_SERASA_JUS_V1",
							Base64.decode("MIIGijCCBXKgAwIBAgIBAzANBgkqhkiG9w0BAQUFADCBkjELMAkGA1UEBhMCQlIx"
+"EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
+"bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxLzAtBgNVBAMTJkF1"
+"dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHYzMB4XDTA5MDYxOTE0"
+"MTA1NFoXDTE3MDYxOTE0MTA1NFowdDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklD"
+"UC1CcmFzaWwxNTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBK"
+"dXN0aWNhIC0gQUMtSlVTMRkwFwYDVQQDExBBQyBTRVJBU0EtSlVTIHYxMIIBIjAN"
+"BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33zJZ2N/Rbg9ebxoTCmc7Jt2zHy+"
+"KSsgU1RKJkiXVaO6hXcc1a3DXSSiPkz2ewWl9LDnRxwI4AcPAzMWtI0dVX338NI1"
+"JVHSqdNYW+DmmZy32DXM/GW6nXoAvq8lDBsAghEfcn8eRibMdR1HA//9kk9F1VM0"
+"hTD5DJeJ9PoWpHodPhkfj1wONdLEf29zdSJFlLHlOJoq1lJBbdOoiD1VpU4mi/na"
+"5elkjt8I95fxMaO2niMWsY9u4qOHQlwYRLfmCaEAb1dllW+2aN7XHeNxr5yk8GAN"
+"l++lhypMilw54tck3FaET8orfpElp9SD7yuhawoP+QRJFR9neahReh7sVQIDAQAB"
+"o4IDBjCCAwIwggItBgNVHSAEggIkMIICIDBCBgZgTAECARkwODA2BggrBgEFBQcC"
+"ARYqaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMvZHBjYWNqdXMucGRmMEIG"
+"BmBMAQICBzA4MDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFjanVzLmp1cy5ici9h"
+"Y2p1cy9kcGNhY2p1cy5wZGYwQgYGYEwBAgMWMDgwNgYIKwYBBQUHAgEWKmh0dHA6"
+"Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2RwY2FjanVzLnBkZjBCBgZgTAECBAow"
+"ODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMvZHBj"
+"YWNqdXMucGRmMEIGBmBMAQJlBzA4MDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFj"
+"anVzLmp1cy5ici9hY2p1cy9kcGNhY2p1cy5wZGYwQgYGYEwBAmYGMDgwNgYIKwYB"
+"BQUHAgEWKmh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2RwY2FjanVzLnBk"
+"ZjBCBgZgTAECZwgwODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hY2p1cy5qdXMu"
+"YnIvYWNqdXMvZHBjYWNqdXMucGRmMEIGBmBMAQJoBjA4MDYGCCsGAQUFBwIBFipo"
+"dHRwOi8vd3d3LmFjanVzLmp1cy5ici9hY2p1cy9kcGNhY2p1cy5wZGYwawYDVR0f"
+"BGQwYjAvoC2gK4YpaHR0cDovL3d3dy5hY2p1cy5qdXMuYnIvYWNqdXMvYWNqdXN2"
+"My5jcmwwL6AtoCuGKWh0dHA6Ly9sY3IuYWNqdXMuanVzLmJyL2FjanVzL2FjanVz"
+"djMuY3JsMB8GA1UdIwQYMBaAFD9NoK9xeERaHr4GbJrrNcMZXsvjMB0GA1UdDgQW"
+"BBSQ8rMpZhMKP9/p1SY/R0O35b1UjDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1Ud"
+"DwEB/wQEAwIBBjANBgkqhkiG9w0BAQUFAAOCAQEAkbv7HvS9VLG3hCrn+/rUw1L8"
+"axzsY289h+Qnm7Obly2/PywdlgaTgmCIftXxb9OSpbe5SbApxa84rowkp1oGzQeZ"
+"9AzssdPFvoZ2K7xQrcfOy9u9vOApTw9sPLsaJ1Ed5zcvoXmRxnp194KRuPdMJmdi"
+"wb/kwqHfiFBGmarLRCzPJLxc/wfDuGcasgacq4+lx7fqKnW6XgAHBK0BRfepooad"
+"cANzZv5lTrEzW0Y2MHTtw+D2oCYHTxpnCcn8q556HPjCbYcDQV+EXeGUabFYiUmW"
+"s9Z9kcXNIxWBek4F6XOSymsU8FEaVKS7glJCI/rRaseO5S4vW5R7ILAjhbNOQA==")),
	AC_SERPRO_JUS_V4(
			"AC_SERPRO_JUS_V4",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUc1akNDQk02Z0F3SUJBZ0lCQWpBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCaVRFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eE5EQXlCZ05WQkFzVEswRjFkRzl5YVdSaFpHVWdRMlZ5ZEdsbQphV05oWkc5eVlTQlNZ"
					+ "V2w2SUVKeVlYTnBiR1ZwY21FZ2RqSXhMekF0QmdOVkJBTVRKa0YxZEc5eWFXUmhaR1VnClEyVnlk"
					+ "R2xtYVdOaFpHOXlZU0JrWVNCS2RYTjBhV05oSUhZME1CNFhEVEV4TVRJeU16RTBNRGcwTUZvWERU"
					+ "RTUKTVRJeU16RTBNRGcwTUZvd2RERUxNQWtHQTFVRUJoTUNRbEl4RXpBUkJnTlZCQW9UQ2tsRFVD"
					+ "MUNjbUZ6YVd3eApOVEF6QmdOVkJBc1RMRUYxZEc5eWFXUmhaR1VnUTJWeWRHbG1hV05oWkc5eVlT"
					+ "QmtZU0JLZFhOMGFXTmhJQzBnClFVTXRTbFZUTVJrd0Z3WURWUVFERXhCQlF5QlRSVkpRVWs4dFNs"
					+ "VlRJSFkwTUlJQ0lqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBdkxSUXVC"
					+ "T3JFdWE2azZqZUpjVDFTQUtQY3RFbVdFS1FKaHRIc2YyZQpzUndjQldpVFZKMGxyQzBsejJzWUoy"
					+ "TFBxSjJOdTFDbGErU3JmNFV1cHUxd3JNK3lSQS84b2ZLa0JsVHQ1eG5qClJ3dXJlZXorM2Zza1lP"
					+ "cFdhak81dHdMdTRNMHhoV3N2T0tCV0Vlc0Q2cnhVNTZ2YUZrQ0VrWGZNaCtyODRlQzEKT1VMTGFV"
					+ "QUNyN3FSWGRad3lYZ1JmR0UyM1BVU1JGREtXczRUUldGSmZNa1Z5ZFZZbHI4ZlZFWkp0RDNBTDhO"
					+ "Ngo5USt4SXRiYWp5TEFWU3Jtek1tb2NEOXp4Y2l2MU95a3I3cW9FMTB0RkxXM1lkb244U3ZNbWxr"
					+ "NmVQOTI5TEdqCjlNMFY5VFlVTGdiSGRNOHpvalpPOFF4Z2d3NEtxSlRGY1l3dk9Jd2lRNlZjeHdN"
					+ "akowM0xWYkFvQ1IwNjVISDEKQ2RwTVpZNXlYeDlFenBpQUlkZkdTNy9Jd29hNUNJT2p6bldJNlhk"
					+ "a1c4SEZEUStBRTBId2hFNnVkVXZMSzFZawo4bFR6MGV1RTRwUXE3WXRkNlJHblBaNTZPdmZxNksv"
					+ "SjcrZmV5dFVPU1J0SFlVWVhJclVINzQxUjNDTnF4VlkxCjV1NW1RK3h4U0dhZ2VxUlViSllJeURi"
					+ "Sis3c25lUUJSQy9zR1pJbzlKRDg5Z2p3WjZvaWk1OHlnKytOdW0vQW8KMndoaTBkdFFkVS8yRjVl"
					+ "eFdwckhxTWZOKzk4dDBhK0RxMEM4OXVBcSt3MWhKUzBTV0ljcktqMmgzYm1zRmhZbQpLS0tObFln"
					+ "b0pMcEVvWnNHb1NhNmM1V3lLSklqNmhCK3dPeGh5SkFRU1A3VWVRRDhiU2dRaDNoejlHN0NmV2Z3"
					+ "CnFmMENBd0VBQWFPQ0FXc3dnZ0ZuTUE0R0ExVWREd0VCL3dRRUF3SUJCakNCa3dZRFZSMGdCSUdM"
					+ "TUlHSU1FSUcKQm1CTUFRSUJGVEE0TURZR0NDc0dBUVVGQndJQkZpcG9kSFJ3T2k4dmQzZDNMbUZq"
					+ "YW5WekxtcDFjeTVpY2k5aApZMnAxY3k5a2NHTmhZMnAxY3k1d1pHWXdRZ1lHWUV3QkFnTVNNRGd3"
					+ "TmdZSUt3WUJCUVVIQWdFV0ttaDBkSEE2Ckx5OTNkM2N1WVdOcWRYTXVhblZ6TG1KeUwyRmphblZ6"
					+ "TDJSd1kyRmphblZ6TG5Ca1pqQnJCZ05WSFI4RVpEQmkKTUMrZ0xhQXJoaWxvZEhSd09pOHZkM2Qz"
					+ "TG1GamFuVnpMbXAxY3k1aWNpOWhZMnAxY3k5aFkycDFjM1kwTG1OeQpiREF2b0MyZ0s0WXBhSFIw"
					+ "Y0RvdkwyeGpjaTVoWTJwMWN5NXFkWE11WW5JdllXTnFkWE12WVdOcWRYTjJOQzVqCmNtd3dId1lE"
					+ "VlIwakJCZ3dGb0FVK0RrQXBmN3JzaWVhQm90aGxnTDYwcENRN2I0d0hRWURWUjBPQkJZRUZKUzIK"
					+ "WmFjbHE3VHlzTlAvc2hlcEpYbkVacFRHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFBd0RRWUpL"
					+ "b1pJaHZjTgpBUUVOQlFBRGdnSUJBRnBlZ0pEN1plZ21XalBXd0VhcFZNYVBVdHdqSVlzV0pEYXk5"
					+ "UGlQbGMrRU01SEVqTmRRCnRCKzc4MmJWajhrVC9HZ3RFQXVtcWVabGhRVmVHWnZRSHZFK1VZUDlS"
					+ "YVN6cU5WWUJ2V0JSYWUyUmhPVW00RFUKN3gyUUJhVjBmakhXc2pVMUxVRkZacTlieEhielFjNE0v"
					+ "dDBXaVlFcGNxTlQwUVNrem4za3d1Z05nUTNEcnhuTApGTmZFTXN4SnNkajBlNVRCZHY2WTBERVNw"
					+ "NHVvVjdsRVpRMkViMnZacG9rMWt6Z0VCc0ZzYklVV3hleEExUVhtCkx5VmxITGx4azZZMloySmw1"
					+ "QWFiK3VlNTE1c2drbS92RS9RMTJES0lpK1Z3STR0Z2N4Vm1oOUNZU09lQUJQSSsKZzNtazFvTDY2"
					+ "WFlJa0pTTG1mSmQxaXBHSHV5dXdSUnFEUVdvRVgyc1UxOGVya1RuNEZIMUNlMWJTNWt4TWQ3QQpP"
					+ "bzlpeUd5VVl2Y0pKK0JGVjRxaVNGdElLY3N5cUppZCtLT0dkQklyV2ZSMS9ReklGVjFlQzVNcVVm"
					+ "U1UxUEc1Clo2OTN3VDZLak9veGhxOVJEbDNVVVJsbTBQdFh0dmdDNm5TYnduTjNhRVkxOGpERmJM"
					+ "U0RvMWJyd1VqeHZaSjUKZWhrWWpvbFdZVmY3bzJVc1BjcXNicFd3cis2cFB2RE1zNUk1SnlTVzIv"
					+ "Ry9nWWtCL0lITHR3dUVTMW1uWmJxagpIMk5jSTNER0JBZ2p6MXVLUll1ZzhJNXlORmpLYi9vWmNa"
					+ "Q2NLZXMwMWlNNDY2OUt0UUtXaEd0cnJRdVZqYmxuCjN1Sm1TOXMreXNnd2NBSDhtZEgyWHIzSmtZ"
					+ "akgxcUxsbEF3UW4zWFZDM2VYdklUcmp3Z2NjSGhWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

			)),
			AC_SERPRO_JUS_V3(
                    "AC_SERPRO_JUS_V3",
                    Base64.decode("MIIE7zCCA9egAwIBAgIBAjANBgkqhkiG9w0BAQUFADCBkjELMAkGA1UEBhMCQlIx"
						       +"EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
						       +"bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxLzAtBgNVBAMTJkF1"
						       +"dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIHYzMB4XDTA5MDYxOTEy"
						       +"NTc0NVoXDTE3MDYxOTEyNTc0NVowdDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklD"
						       +"UC1CcmFzaWwxNTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBK"
						       +"dXN0aWNhIC0gQUMtSlVTMRkwFwYDVQQDExBBQyBTRVJQUk8tSlVTIHYzMIIBIjAN"
						       +"BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA338zFfCM8YgMs+RJbi7Edu+vjUEA"
						       +"Pw/cXmuyUYyl9TShKgJlfPFi/FVLbvcxPi+Wq3SXBQ/GI8PGf7e5rqqFvtZwzVNO"
						       +"kfhXLA2xVwlKoiHqiBkwOwMVxJeC5nm90bhzcjWETfuNs7ElfUu1yTNWnwKixKbt"
						       +"NclaqhQq8sWXTItqoMNoPZMg0Oyah1FQCb3CPFbH16+0U4r17qbGFVmprgGUebRd"
						       +"d5xWU5EuszqFoB4DXFX8BYV4jDks5G71KU2NewNHJG8zTjMdjQmJ3f0P500QktoJ"
						       +"W3UnsDk6IKVz+euCqeBfNoLazPSfKNNDSicO4svQbpd+4ugqpAKouDKpAwIDAOYn"
						       +"o4IBazCCAWcwDgYDVR0PAQH/BAQDAgEGMIGTBgNVHSAEgYswgYgwQgYGYEwBAgEV"
						       +"MDgwNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2Rw"
						       +"Y2FjanVzLnBkZjBCBgZgTAECAxIwODA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5h"
						       +"Y2p1cy5qdXMuYnIvYWNqdXMvZHBjYWNqdXMucGRmMGsGA1UdHwRkMGIwL6AtoCuG"
						       +"KWh0dHA6Ly93d3cuYWNqdXMuanVzLmJyL2FjanVzL2FjanVzdjMuY3JsMC+gLaAr"
						       +"hilodHRwOi8vbGNyLmFjanVzLmp1cy5ici9hY2p1cy9hY2p1c3YzLmNybDAfBgNV"
						       +"HSMEGDAWgBQ/TaCvcXhEWh6+Bmya6zXDGV7L4zAdBgNVHQ4EFgQUIQMIKvKDeAMv"
						       +"oyVM/VUZ9uV4E3swEgYDVR0TAQH/BAgwBgEB/wIBADANBgkqhkiG9w0BAQUFAAOC"
						       +"AQEAsnE5wtt7ri/yWt9Tg5Zn5R8bAoIaXHJ6NB608RmPf3Qf3/8jN+Tn7SnKXooK"
						       +"U6X0q+HhfXFMSvRxUWOMppT4Myux3A1F01/n25nx1AYREY7Tr1Judws4EtZIn+mY"
						       +"7msn1A59ur0u3MjL1eVULCCUBdle2jNKF+STUPRSdhFEejZUAhfEpbEzXy2nhYUY"
						       +"yHXteDmugdHsE9iGUXmzkUop5R4lqZ81/f2uFe2oCjje5pc6gVSL9e4WpY40iXWk"
						       +"ZDs05S4DdzxyIiFMnoa2zWWJOaZtN7N3/sIg5BJLJ/t49kwPTwHJqRi01Kocm/3+"
						       +"L+kyI1ZDFf38WRzCZoklIimB5A==")),
	AC_JUS_V4(
			"AC_JUS_V4",
			Base64.decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdXVENDQkVHZ0F3SUJBZ0lCQ1RBTkJna3Fo"
					+ "a2lHOXcwQkFRMEZBRENCbHpFTE1Ba0dBMVVFQmhNQ1FsSXgKRXpBUkJnTlZCQW9UQ2tsRFVDMUNj"
					+ "bUZ6YVd3eFBUQTdCZ05WQkFzVE5FbHVjM1JwZEhWMGJ5Qk9ZV05wYjI1aApiQ0JrWlNCVVpXTnVi"
					+ "Mnh2WjJsaElHUmhJRWx1Wm05eWJXRmpZVzhnTFNCSlZFa3hOREF5QmdOVkJBTVRLMEYxCmRHOXlh"
					+ "V1JoWkdVZ1EyVnlkR2xtYVdOaFpHOXlZU0JTWVdsNklFSnlZWE5wYkdWcGNtRWdkakl3SGhjTk1U"
					+ "RXgKTVRJeU1UY3hOVEF4V2hjTk1qRXhNVEl5TVRjeE5UQXhXakNCaVRFTE1Ba0dBMVVFQmhNQ1Fs"
					+ "SXhFekFSQmdOVgpCQW9UQ2tsRFVDMUNjbUZ6YVd3eE5EQXlCZ05WQkFzVEswRjFkRzl5YVdSaFpH"
					+ "VWdRMlZ5ZEdsbWFXTmhaRzl5CllTQlNZV2w2SUVKeVlYTnBiR1ZwY21FZ2RqSXhMekF0QmdOVkJB"
					+ "TVRKa0YxZEc5eWFXUmhaR1VnUTJWeWRHbG0KYVdOaFpHOXlZU0JrWVNCS2RYTjBhV05oSUhZME1J"
					+ "SUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQwpDZ0tDQWdFQTc2a05MVWZKN1BTT1Bp"
					+ "TGtKa3RGK0FOckNubnp3eVVnRStOWGgxMFdhRkxCQ0t5WVFER3E5eWszCmpsc21KN1A5YTRkUllq"
					+ "RE9HWE1FbXc1WFB1K1dDbjR3QWZuYUJGT3RVVVNBZUpyd3JhbVZ4Qmh2eDBpMTU4RHIKOUlPOGtl"
					+ "dzZVYUJyNWVWYXhFZlhUSU54cHVWVTJUWFJqMzZnK1RqT3BTd0VaZmt2ZHZuMXFLREFuYlVhOEFJ"
					+ "MgptV3QxLzhncCtzYVRaamk5NVZOUjBNbkluUXlSamw0VVhsV0pVK2haT3dZU2czUnRIUnc5aGRZ"
					+ "d1I4NENLaTBYCnpwNkQvTjBUY0ZZaTZoU1FXNkxuV3ZZT2lhUlNLUjBDKytpWmZSd3NjS2VxVDgr"
					+ "SG8wc3BLK2o2d3hGdG5FYk8KVnFBcGxLOE8wQWQyVVpQMEo5UFg0OWZqc1lZUTN3cVhyTFJ5STlI"
					+ "YXA5YTJwRVFNdmFzMnIwOHVwNEFqZWcrMApacUJQQ2FPd3VWektZYmlKckdCOGNxMVlFd0FjRy82"
					+ "bFBmRUFucEJnSXVnZUVDRUtOSUhBS3dkZExSMUFGM2xEClJlOWJETkdSeG1pR3FkaHRSMzR0bytZ"
					+ "NitOb0VsSTNQdXh4M3FhN2hmQ2lNYWxySUZ2R2FIZlFyRVNST281MmQKeThlRmE2RlIzVVFFbnRT"
					+ "Y0FXTDhLZndtSTFXbDNVVnRPbU1tbHVTUlFoYnJZRG1Pb051QXhEaDA4dFl3OGJZNQpvSTUwNzcr"
					+ "M2xzbSs5UDkzMktXOGJVUXZNN0FybzhhTGNDS2RsY0h2SlR3TGdVRWtPMVNnOFFSUEZveXpqMW5q"
					+ "CmtSM0NEaWxFVW1sQ1cvWDVmMXUrV3JQUGVjNUg4YVdYMmdMV0FOYndISGYvbnpQaGlMOENBd0VB"
					+ "QWFPQnV6Q0IKdURBZEJnTlZIUTRFRmdRVStEa0FwZjdyc2llYUJvdGhsZ0w2MHBDUTdiNHdEd1lE"
					+ "VlIwVEFRSC9CQVV3QXdFQgovekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdGQVlEVlIwZ0JBMHdDekFK"
					+ "QmdWZ1RBRUJFekFBTUQ4R0ExVWRId1E0Ck1EWXdOS0F5b0RDR0xtaDBkSEE2THk5aFkzSmhhWG91"
					+ "YVdOd1luSmhjMmxzTG1kdmRpNWljaTlNUTFKaFkzSmgKYVhwMk1pNWpjbXd3SHdZRFZSMGpCQmd3"
					+ "Rm9BVUREa2dPcmNCSDh2WEtIMUJvTWY2U3EweUpMNHdEUVlKS29aSQpodmNOQVFFTkJRQURnZ0lC"
					+ "QUJpYmJJMXNiZmRBb2crN1REcU1RTTNRUUEzZEhZSG5pRHB0RWJLRGtzbWVmUHlrCmI3dXpxbEJG"
					+ "dVJQa3RNSkFURWpIM0xERUVTOGlqTU1LVzhLT1hsTGdSQUNFT2dDb0VML0FQVXAwTE12b0hGTUsK"
					+ "UXE5enBUZkNZSTVFSUFQTVRlRG1vZ2ZjTUlWMWhKRVgrNW9WNlFVUnJReUxWTGVuTERLbDRHODBn"
					+ "MEJFaDUvTwpidyt2T0hYdGwvL0tPV2JHejZWWit2ZXRaSklOOVd5MFpKV1FxMW4zVGZSUlZwcllz"
					+ "b1B6TEtzZStEMXl6TWpRCkR5ZGdWWmZTNmp0VTJESU8vRm4wZVBKdys0cGdISHVEeVcySzFQQmdU"
					+ "VUR6aTg2VTlhVElLUkl6OEp3dW1XR1oKMFluUi9HSUhRTnlGVkg2YlJieFNBa1BEb0pMNVNKNWJo"
					+ "cEk2cVNHclNRS3BNZXNtQ3hsaFY3RG5GTTBkYm1pcAo3NTNZWEJJS0s5dkEyK0dUSE5kaFdoNW5D"
					+ "Q1FwOVhmWjAzRVJBMEYzcmdyL1F5eCtMTFZ4UHM4MlNQRlYyQzlNCnhGVTc0OFJQbGlTY1pRb0Zm"
					+ "TjYyK0lReDhOSEExdmIvdFFrZTQzb1Y2ZHc1RGhFdnNVVjVzeWxxRXN6VFc1N1UKQTBNSWNIVzRX"
					+ "VkkxV1p5MHk2dXRiQnhRMDB2ZmpNd1I3dXJFd2s0V01aWFQ2YTM3STh1NG1tbDg0dGs1UWZTRApM"
					+ "ZUhkL2hScmsyY2dWZ1Q1YnpjVEt4WExHckFOc3BZdTJlK3c1TEl5b3RpWDc3VlU2YTBjdEVySXda"
					+ "WUlkSFNMCkFiV3ZHQWtpeWhGcGVjSnB6S3ljSU9BVnA3cnAwc3FHR0FBRkFzd0pJTmx3QzJWUkhn"
					+ "MzB3REJiTGJsVgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

			)),

	AC_JUS_V4_NOVO(
			"AC_JUS_V4_NOVO",
			Base64.decode("MIIGWTCCBEGgAwIBAgIBCTANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwHhcNMTEx"
					+ "MTIyMTcxNTAxWhcNMjExMTIyMTcxNTAxWjCBiTELMAkGA1UEBhMCQlIxEzARBgNV"
					+ "BAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9y"
					+ "YSBSYWl6IEJyYXNpbGVpcmEgdjIxLzAtBgNVBAMTJkF1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBkYSBKdXN0aWNhIHY0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC"
					+ "CgKCAgEA76kNLUfJ7PSOPiLkJktF+ANrCnnzwyUgE+NXh10WaFLBCKyYQDGq9yk3"
					+ "jlsmJ7P9a4dRYjDOGXMEmw5XPu+WCn4wAfnaBFOtUUSAeJrwramVxBhvx0i158Dr"
					+ "9IO8kew6UaBr5eVaxEfXTINxpuVU2TXRj36g+TjOpSwEZfkvdvn1qKDAnbUa8AI2"
					+ "mWt1/8gp+saTZji95VNR0MnInQyRjl4UXlWJU+hZOwYSg3RtHRw9hdYwR84CKi0X"
					+ "zp6D/N0TcFYi6hSQW6LnWvYOiaRSKR0C++iZfRwscKeqT8+Ho0spK+j6wxFtnEbO"
					+ "VqAplK8O0Ad2UZP0J9PX49fjsYYQ3wqXrLRyI9Hap9a2pEQMvas2r08up4Ajeg+0"
					+ "ZqBPCaOwuVzKYbiJrGB8cq1YEwAcG/6lPfEAnpBgIugeECEKNIHAKwddLR1AF3lD"
					+ "Re9bDNGRxmiGqdhtR34to+Y6+NoElI3Puxx3qa7hfCiMalrIFvGaHfQrESROo52d"
					+ "y8eFa6FR3UQEntScAWL8KfwmI1Wl3UVtOmMmluSRQhbrYDmOoNuAxDh08tYw8bY5"
					+ "oI5077+3lsm+9P932KW8bUQvM7Aro8aLcCKdlcHvJTwLgUEkO1Sg8QRPFoyzj1nj"
					+ "kR3CDilEUmlCW/X5f1u+WrPPec5H8aWX2gLWANbwHHf/nzPhiL8CAwEAAaOBuzCB"
					+ "uDAdBgNVHQ4EFgQU+DkApf7rsieaBothlgL60pCQ7b4wDwYDVR0TAQH/BAUwAwEB"
					+ "/zAOBgNVHQ8BAf8EBAMCAQYwFAYDVR0gBA0wCzAJBgVgTAEBEzAAMD8GA1UdHwQ4"
					+ "MDYwNKAyoDCGLmh0dHA6Ly9hY3JhaXouaWNwYnJhc2lsLmdvdi5ici9MQ1JhY3Jh"
					+ "aXp2Mi5jcmwwHwYDVR0jBBgwFoAUDDkgOrcBH8vXKH1BoMf6Sq0yJL4wDQYJKoZI"
					+ "hvcNAQENBQADggIBABibbI1sbfdAog+7TDqMQM3QQA3dHYHniDptEbKDksmefPyk"
					+ "b7uzqlBFuRPktMJATEjH3LDEES8ijMMKW8KOXlLgRACEOgCoEL/APUp0LMvoHFMK"
					+ "Qq9zpTfCYI5EIAPMTeDmogfcMIV1hJEX+5oV6QURrQyLVLenLDKl4G80g0BEh5/O"
					+ "bw+vOHXtl//KOWbGz6VZ+vetZJIN9Wy0ZJWQq1n3TfRRVprYsoPzLKse+D1yzMjQ"
					+ "DydgVZfS6jtU2DIO/Fn0ePJw+4pgHHuDyW2K1PBgTUDzi86U9aTIKRIz8JwumWGZ"
					+ "0YnR/GIHQNyFVH6bRbxSAkPDoJL5SJ5bhpI6qSGrSQKpMesmCxlhV7DnFM0dbmip"
					+ "753YXBIKK9vA2+GTHNdhWh5nCCQp9XfZ03ERA0F3rgr/Qyx+LLVxPs82SPFV2C9M"
					+ "xFU748RPliScZQoFfN62+IQx8NHA1vb/tQke43oV6dw5DhEvsUV5sylqEszTW57U"
					+ "A0MIcHW4WVI1WZy0y6utbBxQ00vfjMwR7urEwk4WMZXT6a37I8u4mml84tk5QfSD"
					+ "LeHd/hRrk2cgVgT5bzcTKxXLGrANspYu2e+w5LIyotiX77VU6a0ctErIwZYIdHSL"
					+ "AbWvGAkiyhFpecJpzKycIOAVp7rp0sqGGAAFAswJINlwC2VRHg30wDBbLblV")),

	AC_CERTISIGN_G6(
			"AC_JUS_V4_NOVO",
			Base64.decode("MIIGQTCCBCmgAwIBAgIBBTANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwHhcNMTEw"
					+ "OTIwMTg1MTQwWhcNMjEwOTIwMTg1MTQwWjByMQswCQYDVQQGEwJCUjETMBEGA1UE"
					+ "ChMKSUNQLUJyYXNpbDE0MDIGA1UECxMrQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3Jh"
					+ "IFJhaXogQnJhc2lsZWlyYSB2MjEYMBYGA1UEAxMPQUMgQ2VydGlzaWduIEc2MIIC"
					+ "IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmG1gPG/50iiBd2xP4XShvyRe"
					+ "l6lgbfwIUwHvKIHs1LqOIsyE2L6SPbRo2A1KATeG3O3F2hVJ+nvvqHsCbdHkroAr"
					+ "wWEgiz8RVepmO5qQTLU97Macrx6ZO90GViy0IIhYA8n/fPCzA9P0PyRidDgo+Tms"
					+ "+27xPLvRlcNmA1kepSMg6z81hVGiNB7UXvWOIy5oxVq59JNQ2ppmqMW3CAXrk7Ir"
					+ "hTMbfhgRCFT4N1q9avAr1ltQ5zVpR/J3PpaI8wK21d+qWgzyY8jkjLv59RTaKNYo"
					+ "07p1TWHbC6NdHNZSUov7C2PuiNHf7UNuhts/JNxElpeE6ToXM0JVJSflxs9tnKKa"
					+ "JA78uA3CRTdyLNWDw5vaY29BcNwCyA0p0vcenapxHLA1pDGvQ5FrAkqc/MDZdR9H"
					+ "/MD9KdQ/Mgu/YYEQCOuc56+xW4lFDo2Rluq8x+jXixzgSA4zuD5P7jnrO799WTS/"
					+ "qcPcX01NU/SeRc4rSxEgyUbCKeBRzAHJcPvxWm3RMajLBDMbrf7Dt5Yrmo47Ux7O"
					+ "w6wF5dn94nmrWhK5GE5OB7pBGLAHYp1dKpIR0sZNA1vkYSBLdw7fXvewW9UcKMY/"
					+ "+JVRjL2hVW0PCHsRXxoI8P4L7XaOFrgGV6B8+y9N+cK6Y5BOfwGglq2cRdXhXLvt"
					+ "Go+9KdHtpsgFHyCsfxcCAwEAAaOBuzCBuDAUBgNVHSAEDTALMAkGBWBMAQEFMAAw"
					+ "PwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJy"
					+ "L0xDUmFjcmFpenYyLmNybDAfBgNVHSMEGDAWgBQMOSA6twEfy9cofUGgx/pKrTIk"
					+ "vjAdBgNVHQ4EFgQUQmeOlYwP+XDRUrw80Fqxh9idgDgwDwYDVR0TAQH/BAUwAwEB"
					+ "/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIBAKIgDXqL5JueJlsR"
					+ "DE0YaWlfuIzCgVBC1j62RbzDGcBR8rn/JkOp+zXRiQePivDA+rMlUecTpUG7O6M8"
					+ "UFKJqAnEURf8HVTQdYUr8TZs2XycVMaGCmL7lud6NsDTFvFNBKJU9RuJ8lj8k68S"
					+ "g2XlBl2Bxykm7KrtWfpNWFWq6gr/U60N7fYlCVBLRH6dcCuLNcruvKmPdCgDUQs6"
					+ "+7ilETF0m2GTGT/R85pBc2ldM0S9j3M8oGvWW7FAFruYozKGLWhHjmsj9LVNrfkJ"
					+ "DcQ4KG3M7Gx/px+a7b276ehXxzPSr6EjZQLonhtlVUWpQ+4Y1GUrhIekIQYky9Vz"
					+ "2CZ4MFs+2j9y6NMZa5Efy+GkIhJqdVRCRYWaL9B4dnTi4N2qO+odU4fURaOxcJhj"
					+ "r7XL9ptxJMrh2Y9c/O+NDU4BUsmdhLHPU3TXHFxQj6W5rO+1KKqyU3ZrBBq47YZ0"
					+ "kqaS/wPRg+1UwmRyuddceDnmsmx+2b7ocFYNmE0l7qsp8kw1z/PQcijXcp8Tlunu"
					+ "NYjdmgIThhgdue2Y4CKSHcjdB+sXsgAP9jx0OYdrRVgdAyMt/2LPGQNW3Lhb9B+y"
					+ "aw6Jcw8PUEIRFSrvhM3gz1S7VJELf0CEw1ED26MduNjPv4/ycpOfkriRYELHT/uF"
					+ "VURh6kJDAMVhhB5URXSnHhuGrKGi")),

	AC_RFB_V3(
			"AC_RFB_V3",
			Base64.decode(" MIIGYDCCBEigAwIBAgIBCDANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwHhcNMTEx"
					+ "MDIxMTIxNjI5WhcNMjExMDIxMTIxNjI5WjCBkDELMAkGA1UEBhMCQlIxEzARBgNV"
					+ "BAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9y"
					+ "YSBSYWl6IEJyYXNpbGVpcmEgdjIxNjA0BgNVBAMTLUFDIFNlY3JldGFyaWEgZGEg"
					+ "UmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCB2MzCCAiIwDQYJKoZIhvcNAQEBBQAD"
					+ "ggIPADCCAgoCggIBAMFyHLTC/E6bRxhdNYhePQ9um1dASSkb6+2i8Ss0kfSEAm3K"
					+ "fmWDUxLpHaAKP2xR2NT8ju1Kpq6Mns1tZmso3VzcacHS3X5nagP/I+jwJIV+GftJ"
					+ "Ep+iiPv1EkiF8hMksXk3vOaHPOA/TNpmmU/nyEB5jNSwEwwych2RTb0IvNr3bV62"
					+ "oJecNNJIu+ws7Z4Rs9Wot0F13lCrVm0KRLHj2llcgu67ArTsFlkDhKNZbS3ohFuc"
					+ "GIlVlkIg/B0E2MjARjos21QJHaYcRmr2w9rF1uZkylUtbn4wYWsj5kt9BCthcjgK"
					+ "Kl2oVZB9agIS0AgUcfaoia8tsl7F63l/aa2kQ9UcQewBbORR4TZPGJSKbItKylP8"
					+ "/EN86u3rPI7nsmJn6HuMVl53hhLKNupP7mtrUZHC3w2FBvD3/JNiKJaP08GFjLH6"
					+ "vEiaR2m9YhizvJUXnDL9yFbkRHU+1lDssdnVDRSNVQX1tK0IpeRAMTHz60e1yJq+"
					+ "SrGNypEOSlFdeD05xFzIjUbpKQe4Obml9wvBHF9FT2evGxknWOFxda0frZzl0UOK"
					+ "70++BSfe6BZ9UwHKXhyjOazPoXEzRK7w6fHYlGjY5XkQ6Y9qNCt6lu80zy6vAxQ/"
					+ "f1Y3w9b+ArawqyTVtb9AtcJsAxhtBf/9njiE1dSTYve5D5S94zNiIWtpDxzbAgMB"
					+ "AAGjgbswgbgwHQYDVR0OBBYEFHXLupDRzkynkvBxsMu+uHszBrIoMA8GA1UdEwEB"
					+ "/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMBQGA1UdIAQNMAswCQYFYEwBAQgwADA/"
					+ "BgNVHR8EODA2MDSgMqAwhi5odHRwOi8vYWNyYWl6LmljcGJyYXNpbC5nb3YuYnIv"
					+ "TENSYWNyYWl6djIuY3JsMB8GA1UdIwQYMBaAFAw5IDq3AR/L1yh9QaDH+kqtMiS+"
					+ "MA0GCSqGSIb3DQEBDQUAA4ICAQCJiamFONQFDtlBuOkqfglnGYufeillnVGeH6TW"
					+ "p7yPEuH9Hfdq/1oN38aJmpvoWnno3GY5U/wKPokFAIizK2kASwvWSpu9hRD1kS5F"
					+ "p4Qlqt1Zsm6bUOlcAD9wZylp7s1lebSj7XiO6epF4OSdeBtKl9OImeF8dhyqPnWb"
					+ "j2IrjxEzyrZ+U+Lb4bFcBI6Lp6r1NHyun+TWD3jbCkBRpJLQt7uO+5asMZYEO+L+"
					+ "fuexEb2Bb8difS4ujPpdMlctg4wm6NHTcB008C+cMkwDpeBvaWpMOZLvDvENDhQW"
					+ "4HBNHNDMdVoIsvvoxSVabrNxp02CATP0y9RubIgkmX40H+R8OXy8Cq3oipSm1t4v"
					+ "/Ihs4aCtoDLZue3Q12RgqHNaKcuwTNoK5BH5AfEYRE2LYxQ/JVrlf1hJAu0fUe2n"
					+ "hv42+i35AJVWpRrEmBk6GLejpJ/QAF1fRmdb0b1+lSLXgOfw3AzFW+e+8BdwCF/0"
					+ "6FPOvapilPMa+bsL7aabinBZ7a4Kc97cMHEW5gkQL0IL6yxYnzALHajvZrrLxwvp"
					+ "zW/os3P2ztINB12cYAkDKf5nmo2ymDHY34IUfi1hPA8EEPkhozhi5Or/W6qRABsH"
					+ "iSxrSEeSKLy4V34hkShPjDtl2Ob/aU1/8A5g5BSGPBpfm/TQJc7g7MrF67lRDoAh"
					+ "DikamA==")),

	AC_CERTISIGN_RFB_G4(
			"AC_CERTISIGN_RFB_G4",
			Base64.decode("MIIHLDCCBRSgAwIBAgIBBDANBgkqhkiG9w0BAQ0FADCBkDELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIxNjA0BgNVBAMTLUFDIFNlY3JldGFy"
					+ "aWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCB2MzAeFw0xMTEyMjIxMjU2"
					+ "MDlaFw0xOTEyMjIxMjU2MDlaMHgxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1At"
					+ "QnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBk"
					+ "byBCcmFzaWwgLSBSRkIxHDAaBgNVBAMTE0FDIENlcnRpc2lnbiBSRkIgRzQwggIi"
					+ "MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDaJ7RjbLaUJXVLr9fWMdtOudL7"
					+ "xD3uGs8or/9N/369fuDwzqiW1ZvhNNXCaiQbZ0KNexKQqXvZepE2lUAWYwswUF/J"
					+ "F6UzkNUFQbOT8lKioXC7BjmX/XFiCT2LeGLuvXAlIlroFKAzzFxz8v2/y0fQc+yt"
					+ "u6GWKLVuYecCh1rGaC080/IEkz7z096IMiN6oq19QjSv8xzKbxPUO2s5T4SaqzHs"
					+ "JNY6gORYG7fSfAePPWobXbNQZgsRWddPBY7c0MUgxpUB99LiiLvwwBJAnNXd/aMa"
					+ "BPp2kHSPEtJYTTerhBHZxoWbo1EakTivZOSOGlj/XCqbeHiOfXJnBsO/Q8L0CGpT"
					+ "OhEvqM3BzdcV8zMX/mw/B8T6HYoj5d4Y1bY4y7L57VyXA/bm+P7OPPtHSpoVvFZu"
					+ "RddLhklk2bypT5mPITdOgTmRN/rR6mhvkB6qNFrlld/dRZRU0jmo/CORtzttLe5y"
					+ "cxG4LySDR0u0q5yDqix6/PvHPY74XeR7ryrUv/vSxXaHz3/QQPd5RdvwG/fe7dle"
					+ "AubvDuSKA1/JoxF0bxeVSFuHHie4qlbM5CAQZwguhmc0ERNeYKiYFcpzmlhuvjtO"
					+ "rv75sHi0OjM+q97nzaEV74EbalpN8+6mpzVUOsJCNpqCMIiqH7D5aniby1jx/+/J"
					+ "lLLA3lm62+AG0UB/ZwIDAQABo4IBpjCCAaIwgfUGA1UdIASB7TCB6jBMBgZgTAEC"
					+ "AQwwQjBABggrBgEFBQcCARY0aHR0cDovL3d3dy5yZWNlaXRhLmZhemVuZGEuZ292"
					+ "LmJyL2FjcmZiL2RwY2FjcmZiLnBkZjBMBgZgTAECAwYwQjBABggrBgEFBQcCARY0"
					+ "aHR0cDovL3d3dy5yZWNlaXRhLmZhemVuZGEuZ292LmJyL2FjcmZiL2RwY2FjcmZi"
					+ "LnBkZjBMBgZgTAECBAQwQjBABggrBgEFBQcCARY0aHR0cDovL3d3dy5yZWNlaXRh"
					+ "LmZhemVuZGEuZ292LmJyL2FjcmZiL2RwY2FjcmZiLnBkZjBEBgNVHR8EPTA7MDmg"
					+ "N6A1hjNodHRwOi8vd3d3LnJlY2VpdGEuZmF6ZW5kYS5nb3YuYnIvYWNyZmIvYWNy"
					+ "ZmJ2My5jcmwwHwYDVR0jBBgwFoAUdcu6kNHOTKeS8HGwy764ezMGsigwHQYDVR0O"
					+ "BBYEFC6R6tZt5bJZgtw4hSl2NBZWPNA+MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYD"
					+ "VR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBDQUAA4ICAQBRr07O13wcl7y+2C0mbElr"
					+ "dG0+yyVMG2ArR8cohQLWHswxoWo2jk3FDxcSWj6rbLYD74hfeioFpHBPme6FmuoZ"
					+ "mxiLflAVCtZUUkbHckJbtti1AmjcwtLCJ4hJ+24I7X+RfuomzgRmU8unHdrCHS3G"
					+ "Gtt1Eegiyd+BD4uWsKa9Yxu9OuRtbcKurLX2gt7O8LcdWExbgUssBWkreGLIQcoZ"
					+ "Eqi0qwQO1ks6pKCsmt7EX23ItBl6Yae13KYz+JUfDNxvEE8T0sp5rAr5alshMoqa"
					+ "mn23MngclD5GortBSertCTVQHui6GRxj3HiDVwM453F7t41QXICEO+EUuohKk+MV"
					+ "fcgoPqfvve9IQt+pmek81QGuGSwnY6rGSV5VmMW2qr/FGcBFQhm0Y2ICkazQleWa"
					+ "TbBel5H9s1/bSSjSMcohycsP+nvhf+C1JKJVkw6syPmp0hrrFq0B3hsQXIA2KTXd"
					+ "oXZjQ/Azmb0fkE0JTgNx49GAm3/qBG+335QN/Aas0SuVSgsn39jqyyAPzyrul4Wi"
					+ "9R4g+Vq5hkN87iL5Mgu054wtdv/9c5mieor/WU6IVPV+Mub8k5BjTMxfQzntpYQD"
					+ "vsryQDoFsIDrY4+tc9qA/9bcS0jhspRKXzhSD4juKM69xbTEebwhRnIlQtAVdK8b"
					+ "S+gFeSgYQpHvMsI7skV05g==")),
					
	AC_SERPRO_V3(
			"AC_SERPRO_V3",
			Base64.decode("MIIGVTCCBD2gAwIBAgIBBzANBgkqhkiG9w0BAQ0FADCBlzELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxPTA7BgNVBAsTNEluc3RpdHV0byBOYWNpb25h"
					+ "bCBkZSBUZWNub2xvZ2lhIGRhIEluZm9ybWFjYW8gLSBJVEkxNDAyBgNVBAMTK0F1"
					+ "dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIwHhcNMTEx"
					+ "MDIxMTIwMjQ3WhcNMjExMDIxMTIwMjQ3WjCBhTELMAkGA1UEBhMCQlIxEzARBgNV"
					+ "BAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9y"
					+ "YSBSYWl6IEJyYXNpbGVpcmEgdjIxKzApBgNVBAMTIkF1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBTRVJQUk8gdjMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC"
					+ "AQDxb+z1eCFkAqtiDxv/Qyh/kyuyjnAWQKG47bumr+CvI6XYU9i3rgJCrsh3qh1Q"
					+ "aANDTxMi2IjUOsGop5rd1hvMS20KaBNgz8JKmsoaeJxtk2lQNX5jQMeJPXbW+qHg"
					+ "LpIHBe5UWAmkhNSg01RejukOndR13KpKXBRjfD1EuT8YrbVHItUKFacGUQdP3ud7"
					+ "ds6jGeDdVMywmKUIMbREnZQukMtN0COFiHMI+DeEhwupp1+8xRyCbOtD/yw7/Xea"
					+ "hGpDnpQPqpbkb9hT7cjAtjVsZZt/CwlqAUSgO2/fsFb4NWd5s76edq0qvfLv4AKj"
					+ "hzzB8LHAb0R+DMEDSfseJ/BDFkg9+EqWMDROSnVakQegUmx8sfOMF7aF66uNf7r6"
					+ "8rwVpch01UGPQqVFvJTLLUpOKPAHYMZ1zT9V39+X2NwmAFfjw5yjDQZ5rBYkm3V9"
					+ "/i65/nI4XKAEL6+a3kcEbZjTmX2EwCzvpTKWt6dE2L5LvdMHkp8jPpC72/25zPSM"
					+ "3xGQAGnQ9wkL3wQLu+ya2xHi4xDkP6T7ELTBZEN2Kqfk2/2ZKhjrs6ImjbI5KOqs"
					+ "//qqLQLkf9ij0AUiOIozbrWbHQmpOXI6SZzm32C8ES5+4HebILB9d6GVJva09hyG"
					+ "gesuaIWZe4tGnXm7QIqHBDu+iHOgVA7hWG9/K/meA+MqvQIDAQABo4G7MIG4MB0G"
					+ "A1UdDgQWBBTI1ur5g49MWDsc2YubmXdlr8lY2jAPBgNVHRMBAf8EBTADAQH/MA4G"
					+ "A1UdDwEB/wQEAwIBBjAUBgNVHSAEDTALMAkGBWBMAQECMAAwPwYDVR0fBDgwNjA0"
					+ "oDKgMIYuaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJyL0xDUmFjcmFpenYy"
					+ "LmNybDAfBgNVHSMEGDAWgBQMOSA6twEfy9cofUGgx/pKrTIkvjANBgkqhkiG9w0B"
					+ "AQ0FAAOCAgEAIybRY3G1KgJb33HvcDnNPEdFpC1J88C+hTWZuQyqamb85Eaiwl3Q"
					+ "tiw59W+7u4LMrZdJJuur4NYHUNzeHfs3Ce/sVULf2Ord1d7VvQPKSwrOdPIDuMbB"
					+ "vQRyZgSPy9kpPSQZ+h60+kqG8er39eNnqcCj1J17TpQZpWjKJn8hocqGCGeY7Tu8"
					+ "XaPKhzshDqPCwWEvQB0uj8Mt/OSKcarvzBpmPlcotH7dcdKP0Ur0UNfQLqD7Yu/E"
					+ "DSGQ/WqQ2nS3vIxeRL2ULn3Lq27EWaWmRD2mfQHyE5yCUUoWwDrJJrkE5u8dGG61"
					+ "VcNaKtZYwaHHTQuf8LiV7pK4NqcjCNXX9SvKvz1DydFAJheBlPaJ1xnzSbD4tPeR"
					+ "VqkXC6WlJBGXcREYt1EUpJ+LESkQy1j9ooerXUcNnZKipBYxFyB3WTKaGjrJ1JDx"
					+ "zHe7x402F3jQKDIILRekN0UrRjygDUaMmH/RikTVPFt2+f2c4FqdvVTdXJ7zjAgO"
					+ "92z0QzjSEZBSLaVvQSr2kEV9C2n0CsCuztHu6PycpwZeZS/eH/yk8LMZAH76TG0l"
					+ "Et+CKwNUUPgjK+fIedCs87sxU2QQ09pDptAkKQWm3fPotWaVD4NrHivZj4tX8W/I"
					+ "soDk7v6OV+H2B9eJ2Rsdszr0abUOIrf8cMtPG2wvDZ5wXAxy5jL73VM=")),

	AC_SERPRO_FINAL_V4(
			"AC_SERPRO_FINAL_V4",
			Base64.decode("MIIIdjCCBl6gAwIBAgIBBDANBgkqhkiG9w0BAQ0FADCBhTELMAkGA1UEBhMCQlIx"
					+ "EzARBgNVBAoTCklDUC1CcmFzaWwxNDAyBgNVBAsTK0F1dG9yaWRhZGUgQ2VydGlm"
					+ "aWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjIxKzApBgNVBAMTIkF1dG9yaWRhZGUg"
					+ "Q2VydGlmaWNhZG9yYSBTRVJQUk8gdjMwHhcNMTQwMTE1MTkzNDMxWhcNMjExMDA4"
					+ "MTkzNDMxWjCBpjELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxDzAN"
					+ "BgNVBAsTBkNTUEItMTE7MDkGA1UECxMyU2VydmljbyBGZWRlcmFsIGRlIFByb2Nl"
					+ "c3NhbWVudG8gZGUgRGFkb3MgLSBTRVJQUk8xNDAyBgNVBAMTK0F1dG9yaWRhZGUg"
					+ "Q2VydGlmaWNhZG9yYSBkbyBTRVJQUk8gRmluYWwgdjQwggIiMA0GCSqGSIb3DQEB"
					+ "AQUAA4ICDwAwggIKAoICAQDRS1z3cL2yn0fWpPRGEADhs4ubobOR9umUn4URGEYV"
					+ "H20TbNvkoOfUGHFepCuFvZwt2TAyo/nKUQSYvAB7MCOnuc9erQmAGkjEQYYWlv51"
					+ "h58fIAB4tsObCQfExZxHogXlUqidWABUZLPM/tfnxC8vfKmaPvaXYEbzDZu0oLD0"
					+ "nFhHr8sP0fWDb9ssqqGltFy67uqZ6jV6qtHeUz3fs0Me5X01q73oob02U5F9dj6B"
					+ "824B22i9ziUz8FdtRfq66JgHP562n7ROJrJ9lR/DBzR4KRSHJHUX7Z4t6OQvRqwv"
					+ "oUQpK5fpQhth8FwgcpihXnt0BsNujvBv5kaKhr1gAlcUjV8XSr7id8GW0Q+wo/RI"
					+ "Tytp/HUEuwJ5atuD8KPVuNiOUcaMJAHz25JYbyNBGrBELqekz0G/rt8Z22SDNdRC"
					+ "RA4SWbINRILI5JT7GTFlXs77bQgdIOAksDMnwoIwwJOeTfu7PxSedbJXo2DQFhz1"
					+ "X7IWn73YlZc8PCbU59Fo6OQNAO6WnxMfzAo+rR8gC/a/bu823vNkGDQ9/lqm3jXj"
					+ "2baAdd9ooi7dg6ERkCNR5IbxTbXJrD/hQS3uAIe8w3G9C8NgShf1YgdA9kfvarq7"
					+ "hFf1ybRllugVxL70GyzhJTebJQHaTyKQ0PZPp3Bo/3VrE62E8BrWTOJF/sm+Me28"
					+ "vQIDAQABo4ICzDCCAsgwggHuBgNVHSAEggHlMIIB4TBOBgZgTAECARAwRDBCBggr"
					+ "BgEFBQcCARY2aHR0cDovL2NjZC5zZXJwcm8uZ292LmJyL2Fjc2VycHJvL2RvY3Mv"
					+ "ZHBjYWNzZXJwcm8ucGRmME4GBmBMAQIDDTBEMEIGCCsGAQUFBwIBFjZodHRwOi8v"
					+ "Y2NkLnNlcnByby5nb3YuYnIvYWNzZXJwcm8vZG9jcy9kcGNhY3NlcnByby5wZGYw"
					+ "TgYGYEwBAgERMEQwQgYIKwYBBQUHAgEWNmh0dHA6Ly9jY2Quc2VycHJvLmdvdi5i"
					+ "ci9hY3NlcnByby9kb2NzL2RwY2Fjc2VycHJvLnBkZjBOBgZgTAECZQwwRDBCBggr"
					+ "BgEFBQcCARY2aHR0cDovL2NjZC5zZXJwcm8uZ292LmJyL2Fjc2VycHJvL2RvY3Mv"
					+ "ZHBjYWNzZXJwcm8ucGRmME4GBmBMAQJnCjBEMEIGCCsGAQUFBwIBFjZodHRwOi8v"
					+ "Y2NkLnNlcnByby5nb3YuYnIvYWNzZXJwcm8vZG9jcy9kcGNhY3NlcnByby5wZGYw"
					+ "TwYHYEwBAoIvAzBEMEIGCCsGAQUFBwIBFjZodHRwOi8vY2NkLnNlcnByby5nb3Yu"
					+ "YnIvYWNzZXJwcm8vZG9jcy9kcGNhY3NlcnByby5wZGYwcAYDVR0fBGkwZzAxoC+g"
					+ "LYYraHR0cDovL2NjZC5zZXJwcm8uZ292LmJyL2xjci9hY3NlcnByb3YzLmNybDAy"
					+ "oDCgLoYsaHR0cDovL2NjZDIuc2VycHJvLmdvdi5ici9sY3IvYWNzZXJwcm92My5j"
					+ "cmwwHwYDVR0jBBgwFoAUyNbq+YOPTFg7HNmLm5l3Za/JWNowHQYDVR0OBBYEFGTb"
					+ "Z1uzlRdShIm072cgsAiJfAdxMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/"
					+ "BAQDAgEGMA0GCSqGSIb3DQEBDQUAA4ICAQAt0bMqz2/dlnTcWXYbQ6qDOP16TvYg"
					+ "Wy5k8uGSMKut2sb/v6bBM4BD5agPjz6SekYLOy0+j24wZvdndoGNdZRoQDoQNZRS"
					+ "Y2VV2Y1dD8jS2TOwre7HhQou7afjpjumdS68kUAiRd9FX8I5Fhde0S4gm0nbfSLm"
					+ "HHmQ1hN5HkYH6ZVYfk8tlHnCjEkmDGWplGCbBwIenRF2IaZH2HSDCGmUzIlyYr9z"
					+ "V2RFltX/icsquvlHBfUpclKNYATkvlylDfgO7X6Mvx5VyazCwcQ5aDjqye/lQvU+"
					+ "RomI8Iun8TlBtGHPulwHVDTaTlx4wjicktnpWXYgR6huLP1p4wM/hU3v+hyN+Iqk"
					+ "GYK7QXQ4h8M+oM7uTi+I0Kvx2dqAI62kxRlz7whqArdrXl8vx3RZFpRhvQlJ33Hm"
					+ "9E94VORysU5JLY7IbYPTAniebudOeGl7drfo5iQPb3WaMoE1s8092FADWcdnmCSO"
					+ "zHebTUWfUbM9RhDwombNx2YsRDSj3m/g4crYEjME30ZA2OrosVHrMMpFBZMnOIqO"
					+ "lvH5jnjheiBxQYiG6ReWx/5omNV17daOaQQ0T0gnsQZie8ZETI01AJ5QX+69pmJr"
					+ "vSpH8kXeq2ohHxBfvuL2D+MiBwhn65tBGtraprHbentTCmh9ImmSwACqeG8okyX/"
					+ "SIdF97XslskCDQ=="))

	;

	private final String nome;
	private final byte[] certificado;

	CertificadoACEnum(String nome, byte[] certificado) {
		this.nome = nome;
		this.certificado = certificado;
	}

	public String getNome() {
		return nome;
	}

	public byte[] getCertificado() {
		return this.certificado;
	}

	public String toString() {
		return nome;
	}

	public boolean seHomonimaA(CertificadoACEnum outra) {
		if (outra == null)
			return false;
		return outra.getNome().equals(this.getNome());
	}

	public boolean seTemCertificadoIdenticoA(CertificadoACEnum outra) {
		if (outra == null)
			return false;
		if (outra.getCertificado().length != this.getCertificado().length)
			return false;
		for (int i = 0; i < outra.getCertificado().length; i++) {
			if (outra.getCertificado()[i] != this.getCertificado()[i])
				return false;
		}
		return true;
	}

	/**
	 * obtém o certificado como TrustAnchor (Certificado auto assinado
	 * confiável)
	 * 
	 * @return
	 */
	public TrustAnchor toTrustAnchor() {
		try {
			return new TrustAnchor(
					(X509Certificate) (CertificateFactory.getInstance("X.509")).generateCertificate(new ByteArrayInputStream(
							this.getCertificado())), null);
		} catch (CertificateException e) {
			return null;
		}

	}

	/**
	 * obtém o certificado como X509Certificate
	 * 
	 * @return
	 */
	public X509Certificate toX509Certificate() {
		try {
			return (X509Certificate) (CertificateFactory.getInstance("X.509"))
					.generateCertificate(new ByteArrayInputStream(this
							.getCertificado()));
		} catch (CertificateException e) {
			return null;
		}
	}
}
