
package com.ittru.ccws.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SignService", targetNamespace = "http://webservice.ccws.ittru.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "composeBodySha256", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ComposeBodySha256")
    @ResponseWrapper(localName = "composeBodySha256Response", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ComposeBodySha256Response")
    public String composeBodySha256(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashSignedAttribSha256", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.HashSignedAttribSha256")
    @ResponseWrapper(localName = "hashSignedAttribSha256Response", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.HashSignedAttribSha256Response")
    public String hashSignedAttribSha256(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "composeBodySha1", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ComposeBodySha1")
    @ResponseWrapper(localName = "composeBodySha1Response", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ComposeBodySha1Response")
    public String composeBodySha1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignature", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignature")
    @ResponseWrapper(localName = "extractSignatureResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignatureResponse")
    public String extractSignature(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashSignedAttribSha1", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.HashSignedAttribSha1")
    @ResponseWrapper(localName = "hashSignedAttribSha1Response", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.HashSignedAttribSha1Response")
    public String hashSignedAttribSha1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ittru.ccws.webservice.SignCompare
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignCompare", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignCompare")
    @ResponseWrapper(localName = "extractSignCompareResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignCompareResponse")
    public SignCompare extractSignCompare(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateSignatureByPolicy", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ValidateSignatureByPolicy")
    @ResponseWrapper(localName = "validateSignatureByPolicyResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ValidateSignatureByPolicyResponse")
    public boolean validateSignatureByPolicy(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignerCert", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignerCert")
    @ResponseWrapper(localName = "extractSignerCertResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ExtractSignerCertResponse")
    public String extractSignerCert(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertSubject", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.GetCertSubject")
    @ResponseWrapper(localName = "getCertSubjectResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.GetCertSubjectResponse")
    public String getCertSubject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertSubjectCn", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.GetCertSubjectCn")
    @ResponseWrapper(localName = "getCertSubjectCnResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.GetCertSubjectCnResponse")
    public String getCertSubjectCn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ittru.ccws.webservice.NameValue>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parseCertificate", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ParseCertificate")
    @ResponseWrapper(localName = "parseCertificateResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ParseCertificateResponse")
    public List<NameValue> parseCertificate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateSign", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ValidateSign")
    @ResponseWrapper(localName = "validateSignResponse", targetNamespace = "http://webservice.ccws.ittru.com/", className = "com.ittru.ccws.webservice.ValidateSignResponse")
    public boolean validateSign(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3)
        throws Exception_Exception
    ;

}
