
package br.gov.jfrj.siga.integracao.ws.siafem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "recebeMSGSoap", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecebeMSGSoap {


    /**
     * 
     * @param unidadeGestora
     * @param senha
     * @param usuario
     * @param anoBase
     * @param documentoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Mensagem", action = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/Mensagem")
    @WebResult(name = "MensagemResult", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
    @RequestWrapper(localName = "Mensagem", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", className = "br.gov.jfrj.siga.ex.ws.siafem.Mensagem")
    @ResponseWrapper(localName = "MensagemResponse", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", className = "br.gov.jfrj.siga.ex.ws.siafem.MensagemResponse")
    public String mensagem(
        @WebParam(name = "Usuario", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
        String senha,
        @WebParam(name = "AnoBase", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
        String anoBase,
        @WebParam(name = "UnidadeGestora", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
        String unidadeGestora,
        @WebParam(name = "DocumentoXML", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
        String documentoXML);
}
