
package br.gov.jfrj.siga.integracao.ws.siafem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "recebeMSGHttpPost", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecebeMSGHttpPost {


    /**
     * 
     * @param unidadeGestora
     * @param senha
     * @param usuario
     * @param anoBase
     * @param documentoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Mensagem")
    @WebResult(name = "string", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", partName = "Body")
    public String mensagem(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Senha")
        String senha,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AnoBase")
        String anoBase,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UnidadeGestora")
        String unidadeGestora,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DocumentoXML")
        String documentoXML);

    /**
     * 
     * @param unidadeGestora
     * @param senha
     * @param sIPEstimulo
     * @param usuario
     * @param anoBase
     * @param documentoXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Mensagem2")
    @WebResult(name = "string", targetNamespace = "https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", partName = "Body")
    public String mensagem2(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Senha")
        String senha,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AnoBase")
        String anoBase,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UnidadeGestora")
        String unidadeGestora,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DocumentoXML")
        String documentoXML,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sIP_Estimulo")
        String sIPEstimulo);

}
