ALTER TABLE CORPORATIVO.CP_APLICACAO_FERIADO MODIFY (ID_LOTACAO number(10,0));
ALTER TABLE CORPORATIVO.DP_PESSOA MODIFY (ID_LOTACAO number(10,0));
ALTER TABLE CORPORATIVO.CP_MARCADOR	MODIFY (ID_LOTACAO_INI number(10,0));
ALTER TABLE corporativo.dp_lotacao MODIFY (ID_LOTACAO number(10,0));
ALTER TABLE corporativo.dp_lotacao MODIFY (ID_LOTACAO_PAI number(10,0));
ALTER TABLE corporativo.dp_lotacao MODIFY (ID_LOTACAO_INI number(10,0));