---CADASTRO DO SERVICO SIGA-DOC-FE-PAINEL
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-FE-PAINEL-CORRIGEMOBIL','Corrige Documento sem Mobil de Via ou Volume',
	(select ID_SERVICO from CORPORATIVO.CP_SERVICO where SIGLA_SERVICO = 'SIGA-DOC-FE-PAINEL'),'2');