-- CADASTRO DOS SERVICOS DO MÓDULO SIGA-CEMAIL
INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL',' Módulo de notificação por email', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL');

INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL-DOCMARC','Notificações de marcadores destinados a minha unidade', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCMARC');

INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL-DOCTUN','Documento foi tramitado para a minha unidade', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCTUN');

INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL-DOCTUSU','Tramitar para o meu usuário', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCTUSU');

INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL-COSSIG','Fui incluído como cossignatário de um documento', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-COSSIG');

INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
SELECT CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-CEMAIL-RESPASSI','Fui incluído como responsável pela assinatura', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'),'2'
FROM DUAL
WHERE NOT EXISTS (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-RESPASSI');

-- PERMISSAO DEFAULT NAO PODE A TODOS PARA OS SERVICOS DO MÓDULO SIGA-CEMAIL
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL'), '1');
    
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCMARC'), '1');

INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCUN'), '1');
    
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-DOCUSU'), '1');
    
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-COSSIG'), '1');
    
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
    VALUES (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL, SYSDATE, '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-CEMAIL-RESPASSI'), '1');