
ALTER SESSION SET CURRENT_SCHEMA = CORPORATIVO;

UPDATE CORPORATIVO.CP_IDENTIDADE SET HIS_ATIVO = 0, HIS_DT_FIM = SYSDATE WHERE ID_IDENTIDADE NOT IN (
	SELECT MAX(ID_IDENTIDADE) FROM CORPORATIVO.CP_IDENTIDADE WHERE HIS_ATIVO = 1 AND ID_TP_IDENTIDADE = 1 GROUP BY LOGIN_IDENTIDADE) AND HIS_ATIVO = 1;

CREATE UNIQUE INDEX apenas_uma_id_ativa on CORPORATIVO.CP_IDENTIDADE (CASE WHEN HIS_ATIVO=1 THEN ID_TP_IDENTIDADE || LOGIN_IDENTIDADE END);

COMMIT;