/* Permissões para botão de exportar dados para CSV */

-- Cadastro de Pessoa
INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
    VALUES ("CORPORATIVO".CP_SERVICO_SEQ.nextval, 'SIGA-GI-CAD_PESSOA-EXP_DADOS', 'Exportar Dados', (SELECT max(id_servico) FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SIGA-GI-CAD_PESSOA') , '2');
    
-- Cadastro de Cargo
INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
    VALUES ("CORPORATIVO".CP_SERVICO_SEQ.nextval, 'SIGA-GI-CAD_CARGO-EXP_DADOS', 'Exportar Dados', (SELECT max(id_servico) FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SIGA-GI-CAD_CARGO') , '2');
    
-- Cadastro de Função de Confiança    
INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
    VALUES ("CORPORATIVO".CP_SERVICO_SEQ.nextval, 'SIGA-GI-CAD_FUNCAO-EXP_DADOS', 'Exportar Dados', (SELECT max(id_servico) FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SIGA-GI-CAD_FUNCAO') , '2');    
    
-- Cadastro de Lotação   
INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
    VALUES ("CORPORATIVO".CP_SERVICO_SEQ.nextval, 'SIGA-GI-CAD_LOTACAO-EXP_DADOS', 'Exportar Dados', (SELECT max(id_servico) FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SIGA-GI-CAD_LOTACAO') , '2');    
COMMIT;
