CREATE SEQUENCE "CORPORATIVO"."CP_ARQUIVO_SEQ" 
  MINVALUE 1 
  MAXVALUE 999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  CACHE 20 
  NOORDER 
  NOCYCLE; 

CREATE TABLE "CORPORATIVO"."CP_ARQUIVO" 
  ( 
     "ID_ARQ"            NUMBER NOT NULL, 
     "ID_ORGAO_USU"      NUMBER, 
     "CONTEUDO_TP_ARQ"   VARCHAR2(128),
     "TP_ARMAZENAMENTO"  VARCHAR2(20),
     "CAMINHO"           VARCHAR2(255),
     "TAMANHO_ARQ"       NUMBER NOT NULL
  ); 
  
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."ID_ARQ" IS 'Identificador do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."ID_ORGAO_USU" IS 'Identificador do órgão usuário dono deste arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."CONTEUDO_TP_ARQ" IS 'Content-Type do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."TP_ARMAZENAMENTO" IS 'Tipo de mecanismo de armazenamento do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."CAMINHO" IS 'Caminho do arquivo no mecanismo de armazenamento';

ALTER TABLE "CORPORATIVO"."CP_ARQUIVO" 
  ADD CONSTRAINT "ARQUIVO_PK" PRIMARY KEY ("ID_ARQ") ENABLE; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_SEQ" TO "SIGA"; 

GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT ON COMMIT refresh ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT query rewrite ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT debug ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT flashback ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 


CREATE TABLE "CORPORATIVO"."CP_ARQUIVO_BLOB" 
  ( 
     "ID_ARQ_BLOB"          NUMBER, 
     "CONTEUDO_ARQ_BLOB" 	BLOB 
  ); 
  
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO_BLOB"."ID_ARQ_BLOB" IS 'Identificador do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO_BLOB"."CONTEUDO_ARQ_BLOB" IS 'Bytes do arquivo';

GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT ON COMMIT refresh ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT query rewrite ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT debug ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

GRANT flashback ON "CORPORATIVO"."CP_ARQUIVO_BLOB" TO "SIGA"; 

