
ALTER TABLE CORPORATIVO.CP_IDENTIDADE 
ADD (TELEFONE_RECUPERACAO VARCHAR2(20) );

ALTER TABLE CORPORATIVO.CP_IDENTIDADE 
ADD (EMAIL_RECUPERACAO VARCHAR2(100) );

ALTER TABLE CORPORATIVO.CP_IDENTIDADE 
ADD (TOKEN_RECUPERACAO VARCHAR2(256) );

ALTER TABLE CORPORATIVO.CP_IDENTIDADE 
ADD (DATA_CONFIRMA_EMAIL_RECUPERA TIMESTAMP );

ALTER TABLE CORPORATIVO.CP_IDENTIDADE 
ADD (DATA_EXPIRA_TOKEN_RECUPERA TIMESTAMP );
