UPDATE CORPORATIVO.CP_MARCADOR set GRUPO_MARCADOR = 14 where ID_MARCADOR = 1008;
UPDATE CORPORATIVO.CP_MARCADOR set GRUPO_MARCADOR = 14 where ID_MARCADOR = 1009;
UPDATE CORPORATIVO.CP_MARCADOR set GRUPO_MARCADOR = 14 where ID_MARCADOR = 1010;
