-------------------------------------------------
--	SCRIPT: CRIACAO DE TABELA DE GERAÇÃO DE TOKENS GENÉRICO
--  Criação preliminar para gerar Token URL permanente: public/app/{TIPO}/{TOKEN}
-------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=corporativo;

/* Criação da tabela Tipo de Token */
CREATE TABLE "CORPORATIVO"."CP_TIPO_TOKEN"
(
   "ID_TP_TOKEN" NUMBER(15,0) NOT NULL 
  ,"DESCR_TP_TOKEN" VARCHAR2(30 BYTE) 
  ,CONSTRAINT "CP_TP_TOKEN_PK" PRIMARY KEY ("ID_TP_TOKEN") 
);

GRANT SELECT ON "CORPORATIVO"."CP_TIPO_TOKEN" TO "SIGA";
GRANT INSERT ON "CORPORATIVO"."CP_TIPO_TOKEN" TO "SIGA";
	
/* Criação do Tipo de Token - Siga Link Permanente */
INSERT INTO "CORPORATIVO"."CP_TIPO_TOKEN" values(1, 'SIGA Link Permanente');

/* Criação da tabela de Token genérica */
CREATE TABLE "CORPORATIVO"."CP_TOKEN" 
(	"ID_TOKEN" NUMBER(15,0) NOT NULL ENABLE, 
    "ID_REF" NUMBER(10,0) NOT NULL ENABLE, 
    "ID_TP_TOKEN" NUMBER(10,0) NOT NULL ENABLE, 
    "DT_IAT" DATE NOT NULL ENABLE, 
    "DT_EXP" DATE, 
    "TOKEN" VARCHAR2(256 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "CP_TOKEN_PK" PRIMARY KEY ("ID_TOKEN")
);
CREATE INDEX "CORPORATIVO"."CP_TOKEN_TP_IDX" ON "CORPORATIVO"."CP_TOKEN" ("ID_TP_TOKEN", "TOKEN");
CREATE SEQUENCE  "CORPORATIVO"."CP_TOKEN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE; 

GRANT SELECT ON "CORPORATIVO"."CP_TOKEN" TO "SIGA";
GRANT INSERT ON "CORPORATIVO"."CP_TOKEN" TO "SIGA";
GRANT SELECT ON "CORPORATIVO"."CP_TOKEN_SEQ" TO "SIGA";

ALTER TABLE "CORPORATIVO"."CP_TOKEN" 
ADD CONSTRAINT "CP_TOKEN_TP_FK"
    FOREIGN KEY ("ID_TP_TOKEN")
    REFERENCES "CORPORATIVO"."CP_TIPO_TOKEN"("ID_TP_TOKEN");
