-- -----------------------------------------------------------------------------------
-- CRIA COLUNAS, INDICES E SEQUENCE PARA PERMITIR MARCADORES PERSONALIZADOS DA LOTAÇÃO
-- -----------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=corporativo;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_LOTACAO_INI NUMBER(5, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD DESCR_DETALHADA VARCHAR2(255);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_COR NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_ICONE NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_APLICACAO_MARCADOR NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_DATA_PLANEJADA NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_DATA_LIMITE NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_OPCAO_EXIBICAO NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_TEXTO NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD ID_TP_INTERESSADO NUMBER(10, 0);
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_ID_INI NUMBER;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_DT_INI DATE;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_IDC_INI NUMBER;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_DT_FIM DATE;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_IDC_FIM NUMBER;
ALTER TABLE CORPORATIVO.CP_MARCADOR ADD HIS_ATIVO NUMBER(1, 0);

CREATE SEQUENCE  "CORPORATIVO"."CP_MARCADOR_LOTACAO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2000 NOCACHE NOORDER NOCYCLE;
CREATE INDEX "CORPORATIVO"."LOTA_ID_INI" ON "CORPORATIVO"."CP_MARCADOR" ("ID_LOTACAO_INI", "HIS_DT_FIM");
CREATE INDEX "CORPORATIVO"."HIS_ID_INI" ON "CORPORATIVO"."CP_MARCADOR" ("HIS_ID_INI");
 

COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_LOTACAO_INI" IS 'Id inicial da lotação que o marcador pertence (para marcas da lotação)';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_COR" IS 'Id da Cor (hexa) do marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_ICONE" IS 'Id do ícone do marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_APLICACAO_MARCADOR" IS 'Id do tipo de mobil em que será aplicado o Marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_DATA_PLANEJADA" IS 'Id do tipo de exibição da data planejada';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_DATA_LIMITE" IS 'Id do tipo de exibição da data limite';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_OPCAO_EXIBICAO" IS 'Id do tipo de exibição do Marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_TEXTO" IS 'Id do tipo de exibição do texto';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."ID_TP_INTERESSADO" IS 'Id do tipo de opção de exibição do interessado';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_ID_INI" IS 'Id do marcador inicial deste marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_DT_INI" IS 'Data de criação ou alteração do marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_IDC_INI" IS 'Id da identidade da pessoa que cadastrou o marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_DT_FIM" IS 'Data de finalização ou fim de determinada situação do marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_IDC_FIM" IS 'Id da identidade da pessoa que finalizou o marcador';
COMMENT ON COLUMN "CORPORATIVO"."CP_MARCADOR"."HIS_ATIVO" IS 'Identifica se está ativo ou não';