--ALTER TABLE CORPORATIVO.DP_LOTACAO ADD ID_LOCALIDADE NUMBER(5,0);

--ALTER TABLE CORPORATIVO.DP_LOTACAO ADD FOREIGN KEY (ID_LOCALIDADE) REFERENCES CORPORATIVO.CP_LOCALIDADE (ID_LOCALIDADE) ENABLE;

UPDATE CORPORATIVO.CP_LOCALIDADE SET NM_LOCALIDADE = 'Campo Grande', ID_UF = 19  WHERE ID_LOCALIDADE = 24;

insert into CORPORATIVO.CP_LOCALIDADE (ID_LOCALIDADE,NM_LOCALIDADE,ID_UF) values (25,'São Paulo',26);  