-- Remoção das FKs da CP_TIPO_CONFIGURACAO que virou ENUM

ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO"
DROP CONSTRAINT "CP_CONF_CP_TP_CONF_ID_FK";

ALTER TABLE "CORPORATIVO"."CP_TIPO_SERVICO"
DROP CONSTRAINT "CP_TP_SERV_ID_SIT_CONF_FK";