-- -----------------------------------------------------------------------------------------------
--	SCRIPT: ALTERA A QUANTIDADE DE CAMPOS SIGLA DE 20 PARA 30.
-- -----------------------------------------------------------------------------------------------

DROP INDEX DP_LOTACAO_IDX_006;
DROP INDEX SIGLA_LOTACAO_DP_LOTACAO_UK;

ALTER TABLE CORPORATIVO.DP_LOTACAO MODIFY (SIGLA_LOTACAO VARCHAR2(30));

CREATE INDEX DP_LOTACAO_IDX_006 ON DP_LOTACAO (ID_ORGAO_USU ASC, SIGLA_LOTACAO ASC, ID_LOTACAO ASC);
CREATE UNIQUE INDEX SIGLA_LOTACAO_DP_LOTACAO_UK ON DP_LOTACAO (SIGLA_LOTACAO ASC, ID_ORGAO_USU ASC, DATA_FIM_LOT ASC);