INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
    VALUES ("CORPORATIVO".CP_SERVICO_SEQ.nextval, 'SIGA-GI-CAD_PESSOA-ALT', 'Alterar Órgão Cadastro Pessoa', (SELECT max(id_servico) FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SIGA-GI-CAD_PESSOA') , '2');
 