ALTER SESSION SET current_schema=corporativo; 

CREATE SEQUENCE "CORPORATIVO"."CP_ARQUIVO_SEQ" 
  MINVALUE 1 
  MAXVALUE 999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  CACHE 20 
  NOORDER 
  NOCYCLE; 

CREATE TABLE "CORPORATIVO"."cp_arquivo" 
  ( 
     "ID_ARQ"            NUMBER, 
     "ID_ORGAO_USU"      NUMBER, 
     "CONTEUDO_TP_ARQ"   VARCHAR2(128), 
     "CONTEUDO_BLOB_ARQ" BLOB 
  ); 
  
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."ID_ARQ" IS 'Identificador do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."ID_ORGAO_USU" IS 'Identificador do órgão usuário dono deste arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."CONTEUDO_TP_ARQ" IS 'Content-Type do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO"."CONTEUDO_BLOB_ARQ" IS 'Bytes do arquivo';

ALTER TABLE "CORPORATIVO"."cp_arquivo" 
  ADD CONSTRAINT "ARQUIVO_PK" PRIMARY KEY ("ID_ARQ") ENABLE; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_SEQ" TO "SIGA"; 

GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT ON COMMIT refresh ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT query rewrite ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT debug ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT flashback ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 