Insert into CORPORATIVO.CP_TIPO_CONFIGURACAO (ID_TP_CONFIGURACAO,DSC_TP_CONFIGURACAO,ID_SIT_CONFIGURACAO) values (44,'Delegar Visualização', 2);

ALTER TABLE CORPORATIVO.DP_SUBSTITUICAO ADD (TP_SUBSTITUICAO char(1));

CREATE SEQUENCE  "CORPORATIVO"."DP_VISUALIZACAO_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE "CORPORATIVO"."DP_VISUALIZACAO" 
   (	"ID_VISUALIZACAO" NUMBER(10,0), 
	"ID_TITULAR" NUMBER(10,0), 
	"ID_DELEG" NUMBER(10,0), 
	"DT_INI_DELEG" DATE, 
	"DT_FIM_DELEG" DATE, 
	"DT_INI_REG" DATE, 
	"DT_FIM_REG" DATE, 
	"ID_REG_INI" NUMBER(10,0)
   ) ;
   
CREATE SEQUENCE  "CORPORATIVO"."DP_VISUALIZACAO_ACESSO_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE "CORPORATIVO"."DP_VISUALIZACAO_ACESSO" 
   (	
   	"ID_VISUALIZACAO_ACESSO" NUMBER(10,0),
   	"ID_VISUALIZACAO" NUMBER(10,0), 
	"ID_TITULAR" NUMBER(10,0), 
	"ID_DELEG" NUMBER(10,0), 
	"DT_ACESSO" DATE, 
	"ID_DOC" NUMBER(10,0)
   ) ;
   

grant select on CORPORATIVO.DP_VISUALIZACAO to siga;
grant select on CORPORATIVO.DP_VISUALIZACAO_ACESSO to siga;   