CREATE SEQUENCE  "CORPORATIVO"."CP_ARQUIVO_EXCLUIR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "CORPORATIVO"."CP_ARQUIVO_EXCLUIR2" AS SELECT * FROM "CORPORATIVO"."CP_ARQUIVO_EXCLUIR";

DROP TABLE "CORPORATIVO"."CP_ARQUIVO_EXCLUIR";

/* Tabela para registrar os arquivos a serem excluidos no servidor de aquivos e permitir um controle transacional caso haja um rollback da transação de banco */
CREATE TABLE "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" (
  "ID_ARQ_EXC" NUMBER PRIMARY KEY,
  "CAMINHO" VARCHAR2(255) NOT NULL 
);

COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO_EXCLUIR"."ID_ARQ_EXC" IS 'Identificador do arquivo';
COMMENT ON COLUMN "CORPORATIVO"."CP_ARQUIVO_EXCLUIR"."CAMINHO" IS 'Coluna com o caminho do arquivo binário para exclusão';

GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT ON COMMIT refresh ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT query rewrite ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT debug ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 
GRANT flashback ON "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" TO "SIGA"; 

INSERT INTO "CORPORATIVO"."CP_ARQUIVO_EXCLUIR" (ID_ARQ_EXC, CAMINHO) SELECT "CORPORATIVO"."CP_ARQUIVO_EXCLUIR_SEQ".NEXTVAL, CAMINHO FROM (SELECT * FROM "CORPORATIVO"."CP_ARQUIVO_EXCLUIR2");

DROP TABLE "CORPORATIVO"."CP_ARQUIVO_EXCLUIR2";
DROP SEQUENCE  "CORPORATIVO"."CP_ARQUIVO_EXCLUIR_SEQ";