-------------------------------------------
--	SCRIPT:CONSTRAINTS
-------------------------------------------

 ALTER TABLE "CORPORATIVO"."CAD_SIT_FUNCIONAL" ADD CONSTRAINT "CAD_SIT_FUNCIONAL_PK" PRIMARY KEY ("ID_CAD_SIT_FUNCIONAL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CAD_SIT_FUNCIONAL" MODIFY ("ID_CAD_SIT_FUNCIONAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_APLICACAO_FERIADO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_APLICACAO_FERIADO" ADD PRIMARY KEY ("ID_APLICACAO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_ID_CONFIGURACAO_PK" PRIMARY KEY ("ID_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" MODIFY ("ID_CONFIGURACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_FERIADO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_FERIADO" ADD CONSTRAINT "FERIADO_PK" PRIMARY KEY ("ID_FERIADO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_FERIADO" MODIFY ("ID_FERIADO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_FERIADO" MODIFY ("DSC_FERIADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_GRUPO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRUPO_PK" PRIMARY KEY ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" MODIFY ("ID_TP_GRUPO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" MODIFY ("HIS_DT_INI" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" MODIFY ("HIS_ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_IDENTIDADE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENTIDADE_PK" PRIMARY KEY ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" MODIFY ("HIS_DT_INI" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" MODIFY ("HIS_ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_LOCALIDADE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_LOCALIDADE" ADD CONSTRAINT "LOCALIDADE_FK" PRIMARY KEY ("ID_LOCALIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_LOCALIDADE" MODIFY ("ID_LOCALIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_LOCALIDADE" MODIFY ("NM_LOCALIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_LOCALIDADE" MODIFY ("ID_UF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_MARCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MARCA" ADD PRIMARY KEY ("ID_MARCA") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_MARCADOR
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MARCADOR" ADD PRIMARY KEY ("ID_MARCADOR") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_MODELO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MODELO" MODIFY ("HIS_DT_INI" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_MODELO" MODIFY ("HIS_ATIVO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_MODELO" ADD PRIMARY KEY ("ID_MODELO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_OCORRENCIA_FERIADO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_OCORRENCIA_FERIADO" ADD PRIMARY KEY ("ID_OCORRENCIA") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_ORGAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_ORGAO" ADD CONSTRAINT "ORGAO_PK" PRIMARY KEY ("ID_ORGAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_ORGAO" MODIFY ("NM_ORGAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_ORGAO" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_ORGAO_USUARIO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_ORGAO_USUARIO" ADD CONSTRAINT "ORGAO_USU_PK" PRIMARY KEY ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_ORGAO_USUARIO" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_ORGAO_USUARIO" MODIFY ("NM_ORGAO_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_PAPEL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_PK" PRIMARY KEY ("ID_PAPEL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("ID_TP_PAPEL" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("ID_LOTACAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("ID_CARGO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("HIS_DT_INI" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" MODIFY ("HIS_ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_PERSONALIZACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD PRIMARY KEY ("ID_PERSONALIZACAO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_SEDE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_SEDE" MODIFY ("ID_SEDE" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_SEDE" MODIFY ("NM_SEDE" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_SEDE" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_SEDE" ADD PRIMARY KEY ("ID_SEDE") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_SERVICO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_SERVICO" ADD CONSTRAINT "CP_SERVICO_ID_SERVICO_PK" PRIMARY KEY ("ID_SERVICO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_SERVICO" MODIFY ("ID_TP_SERVICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_SITUACAO_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" ADD CONSTRAINT "CP_SIT_CONF_ID_SIT_CONF_PK" PRIMARY KEY ("ID_SIT_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" MODIFY ("ID_SIT_CONFIGURACAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" MODIFY ("RESTRITIVIDADE_SIT_CONF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_TIPO_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_CONFIGURACAO" ADD CONSTRAINT "CP_TP_CONF_ID_TP_CONF_PK" PRIMARY KEY ("ID_TP_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_TIPO_CONFIGURACAO" MODIFY ("ID_TP_CONFIGURACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CP_TIPO_GRUPO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_GRUPO" ADD CONSTRAINT "CP_TIPO_GRUPO_PK" PRIMARY KEY ("ID_TP_GRUPO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_IDENTIDADE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_IDENTIDADE" ADD CONSTRAINT "CP_TIPO_IDENTIDADE_PK" PRIMARY KEY ("ID_TP_IDENTIDADE") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_LOTACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_LOTACAO" ADD CONSTRAINT "CP_TIPO_LOTACAO_PK" PRIMARY KEY ("ID_TP_LOTACAO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_MARCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_MARCA" ADD PRIMARY KEY ("ID_TP_MARCA") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_MARCADOR
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_MARCADOR" ADD PRIMARY KEY ("ID_TP_MARCADOR") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_PAPEL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_PAPEL" ADD CONSTRAINT "CP_TIPO_PAPEL_PK" PRIMARY KEY ("ID_TP_PAPEL") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_PESSOA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_PESSOA" ADD CONSTRAINT "CP_TIPO_PESSOA_PK" PRIMARY KEY ("ID_TP_PESSOA") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_TIPO_SERVICO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_SERVICO" ADD CONSTRAINT "CP_TIPO_SERVICO_PK" PRIMARY KEY ("ID_TP_SERVICO") ENABLE;
--------------------------------------------------------
--  Constraints for Table CP_UF
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_UF" MODIFY ("ID_UF" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_UF" MODIFY ("NM_UF" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."CP_UF" ADD CONSTRAINT "UF_PK" PRIMARY KEY ("ID_UF") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_CARGO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_CARGO" MODIFY ("ID_CARGO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_CARGO" MODIFY ("NOME_CARGO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_CARGO" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_CARGO" ADD PRIMARY KEY ("ID_CARGO") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_ESTADO_CIVIL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_ESTADO_CIVIL" ADD CONSTRAINT "ESTADO_CIVIL_PK" PRIMARY KEY ("ID_ESTADO_CIVIL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_ESTADO_CIVIL" MODIFY ("ID_ESTADO_CIVIL" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_ESTADO_CIVIL" MODIFY ("NM_ESTADO_CIVIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DP_FUNCAO_CONFIANCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" MODIFY ("ID_FUNCAO_CONFIANCA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" MODIFY ("NOME_FUNCAO_CONFIANCA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ADD PRIMARY KEY ("ID_FUNCAO_CONFIANCA") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_LOTACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" ADD CONSTRAINT "SIGLA_LOTACAO_DP_LOTACAO_UK" UNIQUE ("SIGLA_LOTACAO", "ID_ORGAO_USU", "DATA_FIM_LOT") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" MODIFY ("ID_LOTACAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" MODIFY ("DATA_INI_LOT" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" MODIFY ("NOME_LOTACAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" ADD PRIMARY KEY ("ID_LOTACAO") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_PADRAO_REFERENCIA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_PADRAO_REFERENCIA" ADD CONSTRAINT "PADRAO_REFERENCIA_PK" PRIMARY KEY ("ID_PADRAO_REFERENCIA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PADRAO_REFERENCIA" MODIFY ("ID_PADRAO_REFERENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PADRAO_REFERENCIA" MODIFY ("DSC_PADRAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PADRAO_REFERENCIA" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DP_PESSOA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("ID_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("DATA_INI_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("CPF_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("NOME_PESSOA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("MATRICULA" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("ID_LOTACAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" MODIFY ("ID_ORGAO_USU" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD PRIMARY KEY ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_PROVIMENTO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_PROVIMENTO" MODIFY ("ID_PROVIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PROVIMENTO" MODIFY ("DSC_PROVIMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_PROVIMENTO" ADD PRIMARY KEY ("ID_PROVIMENTO") ENABLE;
--------------------------------------------------------
--  Constraints for Table DP_SUBSTITUICAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" ADD CONSTRAINT "SUBSTITUICAO_FK" PRIMARY KEY ("ID_SUBSTITUICAO") DISABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" MODIFY ("ID_SUBSTITUICAO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" MODIFY ("ID_LOTA_TITULAR" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" MODIFY ("ID_LOTA_SUBSTITUTO" NOT NULL ENABLE);
 
  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" MODIFY ("DT_INI_SUBST" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CP_APLICACAO_FERIADO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_APLICACAO_FERIADO" ADD FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_APLICACAO_FERIADO" ADD FOREIGN KEY ("ID_LOTACAO") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_APLICACAO_FERIADO" ADD FOREIGN KEY ("ID_LOCALIDADE") REFERENCES "CORPORATIVO"."CP_LOCALIDADE" ("ID_LOCALIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_APLICACAO_FERIADO" ADD FOREIGN KEY ("ID_OCORRENCIA_FERIADO") REFERENCES "CORPORATIVO"."CP_OCORRENCIA_FERIADO" ("ID_OCORRENCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_GRUP_ID_GRP_FK" FOREIGN KEY ("ID_GRUPO") REFERENCES "CORPORATIVO"."CP_GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_IDENT_IDC_FIM_FK" FOREIGN KEY ("HIS_IDC_FIM") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_IDENT_IDC_INI_FK" FOREIGN KEY ("HIS_IDC_INI") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_IDENT_ID_IDENT_FK" FOREIGN KEY ("ID_IDENTIDADE") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_ORG_USU_ID_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_SERV_ID_SERVICO_FK" FOREIGN KEY ("ID_SERVICO") REFERENCES "CORPORATIVO"."CP_SERVICO" ("ID_SERVICO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_SIT_CONF_ID_FK" FOREIGN KEY ("ID_SIT_CONFIGURACAO") REFERENCES "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" ("ID_SIT_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_TPLOT_ID_TP_LOT_FK" FOREIGN KEY ("ID_TP_LOTACAO") REFERENCES "CORPORATIVO"."CP_TIPO_LOTACAO" ("ID_TP_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_CP_TP_CONF_ID_FK" FOREIGN KEY ("ID_TP_CONFIGURACAO") REFERENCES "CORPORATIVO"."CP_TIPO_CONFIGURACAO" ("ID_TP_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_DP_CARGO_ID_CARGO_FK" FOREIGN KEY ("ID_CARGO") REFERENCES "CORPORATIVO"."DP_CARGO" ("ID_CARGO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_DP_F_CONFIANCA_ID_FK" FOREIGN KEY ("ID_FUNCAO_CONFIANCA") REFERENCES "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ("ID_FUNCAO_CONFIANCA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_DP_LOT_ID_LOTACAO_FK" FOREIGN KEY ("ID_LOTACAO") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_CONFIGURACAO" ADD CONSTRAINT "CP_CONF_DP_PES_ID_PESSOA_FK" FOREIGN KEY ("ID_PESSOA") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_GRUPO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRP_CP_GRP_ID_INI_FK" FOREIGN KEY ("HIS_ID_INI") REFERENCES "CORPORATIVO"."CP_GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRP_CP_GRP_ID_PAI_FK" FOREIGN KEY ("ID_GRUPO_PAI") REFERENCES "CORPORATIVO"."CP_GRUPO" ("ID_GRUPO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRP_CP_IDENT_IDC_FIM_FK" FOREIGN KEY ("HIS_IDC_FIM") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRP_CP_IDENT_IDC_INI_FK" FOREIGN KEY ("HIS_IDC_INI") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_GRUPO" ADD CONSTRAINT "CP_GRP_CP_TP_GRP_ID_TP_GRP_FK" FOREIGN KEY ("ID_TP_GRUPO") REFERENCES "CORPORATIVO"."CP_TIPO_GRUPO" ("ID_TP_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_IDENTIDADE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_CPORGUSU_ID_ORGUSU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_CP_IDENT_IDC_FIM_FK" FOREIGN KEY ("HIS_IDC_FIM") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_CP_IDENT_IDC_INI_FK" FOREIGN KEY ("HIS_IDC_INI") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_CP_IDENT_ID_INI_FK" FOREIGN KEY ("HIS_ID_INI") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_CP_TPIDT_ID_TP_IDT_FK" FOREIGN KEY ("ID_TP_IDENTIDADE") REFERENCES "CORPORATIVO"."CP_TIPO_IDENTIDADE" ("ID_TP_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_IDENTIDADE" ADD CONSTRAINT "CP_IDENT_DP_PESS_ID_PESS_FK" FOREIGN KEY ("ID_PESSOA") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_LOCALIDADE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_LOCALIDADE" ADD CONSTRAINT "UF_LOCALIDADE_FK" FOREIGN KEY ("ID_UF") REFERENCES "CORPORATIVO"."CP_UF" ("ID_UF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_MARCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MARCA" ADD FOREIGN KEY ("ID_MARCADOR") REFERENCES "CORPORATIVO"."CP_MARCADOR" ("ID_MARCADOR") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_MARCA" ADD FOREIGN KEY ("ID_PESSOA_INI") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_MARCA" ADD FOREIGN KEY ("ID_LOTACAO_INI") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 

 
  ALTER TABLE "CORPORATIVO"."CP_MARCA" ADD FOREIGN KEY ("ID_TP_MARCA") REFERENCES "CORPORATIVO"."CP_TIPO_MARCA" ("ID_TP_MARCA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_MARCADOR
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MARCADOR" ADD FOREIGN KEY ("ID_TP_MARCADOR") REFERENCES "CORPORATIVO"."CP_TIPO_MARCADOR" ("ID_TP_MARCADOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_MODELO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_MODELO" ADD FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_MODELO" ADD FOREIGN KEY ("HIS_IDC_INI") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_MODELO" ADD FOREIGN KEY ("HIS_IDC_FIM") REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_MODELO" ADD FOREIGN KEY ("HIS_ID_INI") REFERENCES "CORPORATIVO"."CP_MODELO" ("ID_MODELO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_OCORRENCIA_FERIADO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_OCORRENCIA_FERIADO" ADD FOREIGN KEY ("ID_FERIADO") REFERENCES "CORPORATIVO"."CP_FERIADO" ("ID_FERIADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_ORGAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_ORGAO" ADD CONSTRAINT "ORGAO_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_PAPEL
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_CPORGUSU_IDORGUSU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_CPTPPAP_ID_TPPAP_FK" FOREIGN KEY ("ID_TP_PAPEL") REFERENCES "CORPORATIVO"."CP_TIPO_PAPEL" ("ID_TP_PAPEL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_CP_PAPEL_ID_INI_FK" FOREIGN KEY ("HIS_ID_INI") REFERENCES "CORPORATIVO"."CP_PAPEL" ("ID_PAPEL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_DP_CARGO_ID_CARGO_FK" FOREIGN KEY ("ID_CARGO") REFERENCES "CORPORATIVO"."DP_CARGO" ("ID_CARGO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_DP_FC_ID_FC_FK" FOREIGN KEY ("ID_FUNCAO_CONFIANCA") REFERENCES "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ("ID_FUNCAO_CONFIANCA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_DP_LOT_ID_LOT_FK" FOREIGN KEY ("ID_LOTACAO") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PAPEL" ADD CONSTRAINT "CP_PAPEL_DP_PESS_ID_PESS_FK" FOREIGN KEY ("ID_PESSOA") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_PERSONALIZACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD CONSTRAINT "CP_PERSON_CP_PAP_ID_ATIVO_FK" FOREIGN KEY ("ID_PAPEL_ATIVO") REFERENCES "CORPORATIVO"."CP_PAPEL" ("ID_PAPEL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD CONSTRAINT "CP_PERSON_CP_PAP_ID_SUBST_FK" FOREIGN KEY ("ID_SUBSTITUINDO_PAPEL") REFERENCES "CORPORATIVO"."CP_PAPEL" ("ID_PAPEL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD CONSTRAINT "CP_PERSON_DP_LOT_ID_SUBST_FK" FOREIGN KEY ("ID_SUBSTITUINDO_LOTACAO") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD CONSTRAINT "CP_PERSON_DP_PESS_ID_PESS_FK" FOREIGN KEY ("ID_PESSOA") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_PERSONALIZACAO" ADD CONSTRAINT "CP_PERSON_DP_PESS_ID_SUBST_FK" FOREIGN KEY ("ID_SUBSTITUINDO_PESSOA") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_SEDE
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_SEDE" ADD FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_SERVICO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_SERVICO" ADD CONSTRAINT "CP_SERV_CPTPSERV_ID_TPSERV_FK" FOREIGN KEY ("ID_TP_SERVICO") REFERENCES "CORPORATIVO"."CP_TIPO_SERVICO" ("ID_TP_SERVICO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_TIPO_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_CONFIGURACAO" ADD CONSTRAINT "CP_TP_CONF_CP_SIT_CONF_ID_FK" FOREIGN KEY ("ID_SIT_CONFIGURACAO") REFERENCES "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" ("ID_SIT_CONFIGURACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_TIPO_SERVICO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_SERVICO" ADD CONSTRAINT "CP_TP_SERV_ID_SIT_CONF_FK" FOREIGN KEY ("ID_SIT_CONFIGURACAO") REFERENCES "CORPORATIVO"."CP_TIPO_CONFIGURACAO" ("ID_TP_CONFIGURACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CP_TIPO_SERVICO_SITUACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."CP_TIPO_SERVICO_SITUACAO" ADD CONSTRAINT "CP_TPSERVSIT_ID_SITCONF_FK" FOREIGN KEY ("ID_SIT_CONFIGURACAO") REFERENCES "CORPORATIVO"."CP_SITUACAO_CONFIGURACAO" ("ID_SIT_CONFIGURACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."CP_TIPO_SERVICO_SITUACAO" ADD CONSTRAINT "CP_TPSRVSIT_IDTPSRV_FK" FOREIGN KEY ("ID_TP_SERVICO") REFERENCES "CORPORATIVO"."CP_TIPO_SERVICO" ("ID_TP_SERVICO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_CARGO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_CARGO" ADD CONSTRAINT "CARGO_INICIAL_CARGO_FK" FOREIGN KEY ("ID_CARGO_INICIAL") REFERENCES "CORPORATIVO"."DP_CARGO" ("ID_CARGO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_CARGO" ADD CONSTRAINT "CARGO_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_FUNCAO_CONFIANCA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ADD CONSTRAINT "FUN_CONF_INI_FUN_CONF_PK" FOREIGN KEY ("ID_FUN_CONF_INI") REFERENCES "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ("ID_FUNCAO_CONFIANCA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ADD CONSTRAINT "FUN_CONF_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ADD FOREIGN KEY ("ID_FUNCAO_CONFIANCA_PAI") REFERENCES "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ("ID_FUNCAO_CONFIANCA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_LOTACAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" ADD CONSTRAINT "DP_LOT_CP_TP_LOT_ID_TP_LOT_FK" FOREIGN KEY ("ID_TP_LOTACAO") REFERENCES "CORPORATIVO"."CP_TIPO_LOTACAO" ("ID_TP_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" ADD CONSTRAINT "LOTACAO_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_LOTACAO" ADD FOREIGN KEY ("ID_LOTACAO_PAI") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_PADRAO_REFERENCIA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_PADRAO_REFERENCIA" ADD CONSTRAINT "PADRAO_REF_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_PESSOA
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD CONSTRAINT "DP_PESS_CPTPPESS_ID_TPPESS_FK" FOREIGN KEY ("ID_TP_PESSOA") REFERENCES "CORPORATIVO"."CP_TIPO_PESSOA" ("ID_TP_PESSOA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD CONSTRAINT "PESSOA_ESTADO_CIVIL_FK" FOREIGN KEY ("ID_ESTADO_CIVIL") REFERENCES "CORPORATIVO"."DP_ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD CONSTRAINT "PESSOA_INICIAL_PESSOAL_FK" FOREIGN KEY ("ID_PESSOA_INICIAL") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD CONSTRAINT "PESSOA_ORGAO_USU_FK" FOREIGN KEY ("ID_ORGAO_USU") REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD FOREIGN KEY ("ID_CARGO") REFERENCES "CORPORATIVO"."DP_CARGO" ("ID_CARGO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD FOREIGN KEY ("ID_FUNCAO_CONFIANCA") REFERENCES "CORPORATIVO"."DP_FUNCAO_CONFIANCA" ("ID_FUNCAO_CONFIANCA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD FOREIGN KEY ("ID_LOTACAO") REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_PESSOA" ADD FOREIGN KEY ("ID_PROVIMENTO") REFERENCES "CORPORATIVO"."DP_PROVIMENTO" ("ID_PROVIMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DP_SUBSTITUICAO
--------------------------------------------------------

  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" ADD CONSTRAINT "SUBSTITUICAO_PESOA_SUBST_FK" FOREIGN KEY ("ID_SUBSTITUTO") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
 
  ALTER TABLE "CORPORATIVO"."DP_SUBSTITUICAO" ADD CONSTRAINT "SUBSTITUICAO_PESOA_TITULAR_FK" FOREIGN KEY ("ID_TITULAR") REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CP_FERIADO_INSERT_TRG
--------------------------------------------------------

