-- PERMISSAO DEFAULT DE ACESSO A TODOS PARA O SERVICO SIGA-WEB DE PESQUISA AVANCADA
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, HIS_DT_INI, ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI)
values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, sysdate, '1', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-PESQ'), '1');