-- Criacao dos campos para versionamento de cargo e funcao de confianca
ALTER SESSION SET CURRENT_SCHEMA=corporativo;

ALTER TABLE CORPORATIVO.DP_CARGO ADD (HIS_IDC_INI NUMBER);
COMMENT ON COLUMN "CORPORATIVO"."DP_CARGO"."HIS_IDC_INI" IS 'Id identidade da pessoa que cadastrou';
ALTER TABLE CORPORATIVO.DP_CARGO ADD (HIS_IDC_FIM NUMBER);
COMMENT ON COLUMN "CORPORATIVO"."DP_CARGO"."HIS_IDC_FIM" IS 'Id identidade da pessoa que finalizou';

ALTER TABLE CORPORATIVO.DP_FUNCAO_CONFIANCA ADD (HIS_IDC_INI NUMBER);
COMMENT ON COLUMN "CORPORATIVO"."DP_FUNCAO_CONFIANCA"."HIS_IDC_INI" IS 'Id identidade da pessoa que cadastrou';
ALTER TABLE CORPORATIVO.DP_FUNCAO_CONFIANCA ADD (HIS_IDC_FIM NUMBER);
COMMENT ON COLUMN "CORPORATIVO"."DP_FUNCAO_CONFIANCA"."HIS_IDC_FIM" IS 'Id identidade da pessoa que finalizou';

