ALTER SESSION SET current_schema=corporativo; 

CREATE SEQUENCE "CORPORATIVO"."CP_ARQUIVO_SEQ" 
  MINVALUE 1 
  MAXVALUE 999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  CACHE 20 
  NOORDER 
  NOCYCLE; 

CREATE TABLE "CORPORATIVO"."cp_arquivo" 
  ( 
     "id_arq"            NUMBER COMMENT 'Identificador do arquivo', 
     "id_orgao_usu"      NUMBER COMMENT 'Identificador do órgão usuário dono deste arquivo', 
     "conteudo_tp_arq"   VARCHAR2(128) COMMENT 'Content-Type do arquivo', 
     "conteudo_blob_arq" BLOB COMMENT 'Bytes do arquivo' 
  ); 

ALTER TABLE "CORPORATIVO"."cp_arquivo" 
  ADD CONSTRAINT "ARQUIVO_PK" PRIMARY KEY ("id_arq") ENABLE; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_SEQ" TO "SIGA"; 

GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT ON COMMIT refresh ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT query rewrite ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT debug ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 

GRANT flashback ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA"; 