ALTER TABLE CORPORATIVO.DP_LOTACAO ADD FOREIGN KEY (ID_LOCALIDADE) REFERENCES CORPORATIVO.CP_LOCALIDADE (ID_LOCALIDADE) ENABLE;

UPDATE CORPORATIVO.CP_LOCALIDADE SET NM_LOCALIDADE = "São Paulo" WHERE ID_LOCALIDADE = 24;