Insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR,DESCR_MARCADOR,ID_TP_MARCADOR,ORD_MARCADOR,GRUPO_MARCADOR) 
    values ('1008','Demanda Judicial Prioridade Baixa','6',null,'2');
Insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR,DESCR_MARCADOR,ID_TP_MARCADOR,ORD_MARCADOR,GRUPO_MARCADOR) 
    values ('1009','Demanda Judicial Prioridade Média','6',null,'2');
Insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR,DESCR_MARCADOR,ID_TP_MARCADOR,ORD_MARCADOR,GRUPO_MARCADOR) 
    values ('1010','Demanda Judicial Prioridade Alta','6',null,'2');


