-- CADASTRO DE SERVICO (SIGA-WEB)
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval, 'SIGA-WEB', 'Acesso via Web Browser', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA'), '2');
-- PERMISSAO DEFAULT DE ACESSO A TODOS PARA O SERVICO SIGA-WEB
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, HIS_DT_INI, ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) 
	values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, sysdate, '1', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-WEB'), '1');
