-------------------------------------------
--	SCRIPT:CFG SELF SVC
-------------------------------------------

Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,10,1);
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,6,100);
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,7,100);
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,8,100);
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,9,100);
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_TP_LOTACAO) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.NEXTVAL,sysdate,202,10,100);
