GRANT SELECT, INSERT, UPDATE, DELETE ON CORPORATIVO.CP_CONTRATO TO SIGA;
GRANT SELECT, INSERT, UPDATE, DELETE ON CORPORATIVO.CP_CONTRATO TO CORPORATIVO;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON CORPORATIVO.CP_CONTRATO TO CORPORATIVO_CON;
