-------------------------------------------
--	SCRIPT:CP_UNIDADE
-------------------------------------------

CREATE TABLE CORPORATIVO.CP_UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA NUMBER PRIMARY KEY, DESCR_UNIDADE_MEDIDA VARCHAR(10));
INSERT INTO CORPORATIVO.CP_UNIDADE_MEDIDA VALUES (1,'Ano');
INSERT INTO CORPORATIVO.CP_UNIDADE_MEDIDA VALUES (2,'Mes');
INSERT INTO CORPORATIVO.CP_UNIDADE_MEDIDA VALUES (3,'Dia');

GRANT SELECT ON CORPORATIVO.CP_UNIDADE_MEDIDA TO SIGA;
GRANT REFERENCES ON CORPORATIVO.CP_UNIDADE_MEDIDA TO SIGA;

COMMENT ON COLUMN CORPORATIVO.CP_UNIDADE_MEDIDA.ID_UNIDADE_MEDIDA IS 'Identificador da unidade de medida';
COMMENT ON COLUMN CORPORATIVO.CP_UNIDADE_MEDIDA.DESCR_UNIDADE_MEDIDA IS 'Descrição da unidade de medida';


GRANT REFERENCES ON CORPORATIVO.CP_IDENTIDADE TO SIGA;


