-------------------------------------------------
--	SCRIPT: CRIACAO DA TABELA DE LOG DE ACESSO
-------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=corporativo;

CREATE SEQUENCE  "CORPORATIVO"."CP_ACESSO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE "CORPORATIVO"."CP_ACESSO" (	
   	"ID_ACESSO" NUMBER(19,0) PRIMARY KEY, 
   	"ID_IDENTIDADE" NUMBER(19,0) NOT NULL, 
	"DT_INI" TIMESTAMP (6) NOT NULL, 
	"DT_FIM" TIMESTAMP (6) NULL, 
	"TP_ACESSO" NUMBER(1,0) NOT NULL, 
	"IP_AUDIT" VARCHAR2(256) NULL,
	constraint CP_ACESSO_IDENTIDADE_FK foreign key (ID_IDENTIDADE) references CORPORATIVO.CP_IDENTIDADE (ID_IDENTIDADE)
);

COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."ID_ACESSO" IS 'código do acesso';
COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."ID_IDENTIDADE" IS 'código da identidade que foi autenticada';
COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."DT_INI" IS 'data do início do acesso';
COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."DT_FIM" IS 'data do fim do acesso';
COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."TP_ACESSO" IS 'tipo do acesso (autenticação ou renovação automática ou logoff)';
COMMENT ON COLUMN "CORPORATIVO"."CP_ACESSO"."IP_AUDIT" IS 'ip que foi utilizado';

GRANT SELECT ON "CORPORATIVO"."CP_ACESSO_SEQ" TO "SIGA";
GRANT SELECT ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
GRANT INSERT ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";

-- GRANT ALTER ON "CORPORATIVO"."CP_ACESSO" TO "SIGA"; 
-- GRANT DELETE ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT INDEX ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT UPDATE ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT REFERENCES ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT ON COMMIT REFRESH ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT QUERY REWRITE ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT DEBUG ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";
-- GRANT FLASHBACK ON "CORPORATIVO"."CP_ACESSO" TO "SIGA";