ALTER SESSION SET CURRENT_SCHEMA=corporativo;

--------------------------------------------------------
--  DDL for Index na DP_PESSOA e IDENTIDADE para evitar Full Table Scan envio email
--------------------------------------------------------

--CREATE INDEX CORPORATIVO.CP_IDENTIDADE_IDPESSOA ON CORPORATIVO.CP_IDENTIDADE (ID_PESSOA);
CREATE INDEX CORPORATIVO.DP_PESSOA_CPF_ORGAO ON CORPORATIVO.DP_PESSOA (CPF_PESSOA, ID_ORGAO_USU);
--CREATE INDEX CORPORATIVO.DP_PESSOA_ORGAO ON CORPORATIVO.DP_PESSOA (ID_ORGAO_USU);