-- SEPARACAO DOS SERVICOS DE EXECUCAO EM LOTE
-- CADASTRO DOS SERVICOS SIGA-DOC-ASSLOTE, SIGA-DOC-RECLOTE, SIGA-DOC-ANOLOTE, SIGA-DOC-ARQLOTE, SIGA-DOC-TRALOTE
INSERT INTO CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	VALUES (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-RECLALOTE','Reclassificar em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');

