ALTER TABLE CORPORATIVO.CP_MODELO ADD (ID_ARQ number(19,0) NULL);
COMMENT ON COLUMN "CORPORATIVO"."CP_MODELO"."ID_ARQ" IS 'Identificador do arquivo';
ALTER TABLE CORPORATIVO.CP_MODELO ADD FOREIGN KEY (ID_ARQ) REFERENCES CORPORATIVO.CP_ARQUIVO (ID_ARQ) ENABLE;
