-- SEPARACAO DOS SERVICOS DE EXECUCAO EM LOTE
-- CADASTRO DOS SERVICOS SIGA-DOC-ASSLOTE, SIGA-DOC-RECLOTE, SIGA-DOC-ANOLOTE, SIGA-DOC-ARQLOTE, SIGA-DOC-TRALOTE
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-ASSLOTE','Assinar em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-ANOLOTE','Anotar em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-ARQLOTE','Arquivar em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-RECLOTE','Receber em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-TRALOTE','Tramitar em Lote',
		(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');

-- MIGRACAO DAS CONFIGURACOES SIGA-DOC-ASS-EXT
--    CRIACAO DAS CONFIGURACOES SIGA-DOC-ASSLOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, ID_SERVICO,  
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, HIS_ID_INI) 
		SELECT CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-ASSLOTE'),
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, CORPORATIVO.CP_CONFIGURACAO_SEQ.currval 
				FROM CORPORATIVO.CP_CONFIGURACAO 
		    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
			  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
			  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-ASS-EXT');

-- MIGRACAO DAS CONFIGURACOES SIGA-DOC-TRAMITE-LOTE
--    CRIACAO DAS CONFIGURACOES SIGA-DOC-ANOLOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, ID_SERVICO,  
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, HIS_ID_INI) 
		SELECT CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-ANOLOTE'),
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, CORPORATIVO.CP_CONFIGURACAO_SEQ.currval 
				FROM CORPORATIVO.CP_CONFIGURACAO 
		    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
			  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
			  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');
  
--    CRIACAO DAS CONFIGURACOES SIGA-DOC-ARQLOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, ID_SERVICO,  
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, HIS_ID_INI) 
		SELECT CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-ARQLOTE'),
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, CORPORATIVO.CP_CONFIGURACAO_SEQ.currval 
				FROM CORPORATIVO.CP_CONFIGURACAO 
		    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
			  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
			  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');
  
--    CRIACAO DAS CONFIGURACOES SIGA-DOC-RECLOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, ID_SERVICO,  
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, HIS_ID_INI) 
		SELECT CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-RECLOTE'),
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, CORPORATIVO.CP_CONFIGURACAO_SEQ.currval 
				FROM CORPORATIVO.CP_CONFIGURACAO 
		    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
			  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
			  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');

--    CRIACAO DAS CONFIGURACOES SIGA-DOC-TRALOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO, ID_SERVICO,  
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, HIS_ID_INI) 
		SELECT CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval, (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRALOTE'),
				HIS_DT_INI, ID_ORGAO_USU, ID_LOTACAO, ID_PESSOA, ID_SIT_CONFIGURACAO, ID_TP_CONFIGURACAO, ID_GRUPO, HIS_IDC_INI, CORPORATIVO.CP_CONFIGURACAO_SEQ.currval 
				FROM CORPORATIVO.CP_CONFIGURACAO 
		    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
			  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
			  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');
  
-- FINALIZACAO DAS CONFIGURACOES ANTIGAS SIGA-DOC-TRAMITE-LOTE
UPDATE CORPORATIVO.CP_CONFIGURACAO SET HIS_IDC_FIM=HIS_IDC_INI, HIS_DT_FIM = sysdate 
    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < sysdate) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > sysdate)
	  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM CORPORATIVO.CP_TIPO_CONFIGURACAO WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
	  AND ID_SERVICO = (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');
