CREATE TABLE "CORPORATIVO"."DP_NOTIFICAR_POR_EMAIL" 
   (	"ID_NOTIFICAR_POR_EMAIL" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE, 
	"NOME_DA_ACAO" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"NAO_CONFIGURAVEL" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"CONFIGURAVEL" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"DT_FIM_NOTIFICAR_POR_EMAIL" DATE, 
	"DT_INI_NOTIFICAR_POR_EMAIL" DATE, 
	"ID_NOTIFICAR_POR_EMAIL_INICIAL" NUMBER(10,0), 
	"IDE_NOTIFICAR_POR_EMAIL" VARCHAR2(256 BYTE), 
	"HIS_IDC_INI" NUMBER, 
	"HIS_IDC_FIM" NUMBER, 
	"RESTRINGIR" NUMBER, 
	 PRIMARY KEY ("ID_NOTIFICAR_POR_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORPORATIVO_DATA_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORPORATIVO_DATA_TS" ;

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (1, 'Cadastro de novo usuário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (2, 'Alterar minha senha', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (3, 'Esqueci minha senha', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (5, 'Responsável pela assinatura', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (6, 'Conssignatário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (7, 'Substituição', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (8, 'Documento tramitado para o meu usuário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (9, 'Documento tramitado para unidade', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (10, 'Tramitação de documentos marcados', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (11, 'Alteração de email', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO corporativo.dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (12, 'Documentos de marcadores', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);