-------------------------------------------
--	SCRIPT: CAMPOS CP_ORGAO_USUARIO
--	RESOLUÇÃO DO TRELLO 1390 (Tabela cp_orgao_usuario - incluir campos)
-------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=corporativo;

ALTER TABLE CORPORATIVO.CP_ORGAO_USUARIO ADD (HIS_DT_INI DATE);
ALTER TABLE CORPORATIVO.CP_ORGAO_USUARIO ADD (HIS_DT_FIM DATE);
ALTER TABLE CORPORATIVO.CP_ORGAO_USUARIO ADD (HIS_IDC_INI NUMBER);
ALTER TABLE CORPORATIVO.CP_ORGAO_USUARIO ADD (HIS_IDC_FIM NUMBER);
ALTER TABLE CORPORATIVO.CP_ORGAO_USUARIO ADD (HIS_ATIVO NUMBER(1,0) default 1 NOT NULL);

alter table CORPORATIVO.CP_ORGAO_USUARIO add constraint CP_ORG_USU_CP_IDENT_ID_INI_FK foreign key(HIS_IDC_INI) references CP_IDENTIDADE(ID_IDENTIDADE);
alter table CORPORATIVO.CP_ORGAO_USUARIO add constraint CP_ORG_USU_CP_IDENT_ID_FIM_FK foreign key(HIS_IDC_FIM) references CP_IDENTIDADE(ID_IDENTIDADE);
