ALTER SESSION SET CURRENT_SCHEMA=corporativo;
CREATE SEQUENCE  "CORPORATIVO"."CP_ARQUIVO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

  CREATE TABLE "CORPORATIVO"."CP_ARQUIVO" 
   (	"ID_ARQ" NUMBER, 
	"ID_ORGAO_USU" NUMBER, 
	"CONTEUDO_TP_ARQ" VARCHAR2(128), 
	"CONTEUDO_BLOB_ARQ" BLOB
   ) ;
   
  GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO_SEQ" TO "SIGA";

  GRANT ALTER ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT DELETE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT INDEX ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT INSERT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT SELECT ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT UPDATE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT REFERENCES ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT ON COMMIT REFRESH ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT QUERY REWRITE ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT DEBUG ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";
 
  GRANT FLASHBACK ON "CORPORATIVO"."CP_ARQUIVO" TO "SIGA";

