ALTER SESSION SET CURRENT_SCHEMA=corporativo;
	INSERT INTO "CORPORATIVO"."CP_SERVICO" (ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO) VALUES (CP_SERVICO_SEQ.nextval, 'SPSEMPAPEL-SIGA-WS', 'Acesso ao WebServices', (SELECT id_servico FROM "CORPORATIVO"."CP_SERVICO" WHERE SIGLA_SERVICO = 'SPSEMPAPEL-SIGA'), '2');
COMMIT;