--REM INSERTING into CORPORATIVO.CP_TIPO_MARCA
Insert into CORPORATIVO.CP_TIPO_MARCA (ID_TP_MARCA,DESCR_TP_MARCA) values (2,'SIGA-SR');
Insert into CORPORATIVO.CP_TIPO_MARCA (ID_TP_MARCA,DESCR_TP_MARCA) values (3,'SIGA-GC');

CREATE UNIQUE INDEX CORPORATIVO.SIGLA_SERVICO_IDX ON CORPORATIVO.CP_SERVICO(SIGLA_SERVICO);
