---CADASTRO DE SERVICO (SIGA-DOC-FE)
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-FE','Ferramentas','2','2');
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_PESSOA,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval,sysdate,'1','1','200',(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-FE'),'1');

---CADASTRO DE SERVICO (SIGA-DOC-FE-CFG)
Insert into CORPORATIVO.CP_SERVICO (ID_SERVICO,SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) values (CORPORATIVO.CP_SERVICO_SEQ.nextval,'SIGA-DOC-FE-CFG','Configurações',(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-FE'),'2');
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_PESSOA,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval,sysdate,'1','1','200',(SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-FE-CFG'),'1');

