alter table CORPORATIVO.DP_LOTACAO drop constraint SIGLA_LOTACAO_DP_LOTACAO_UK drop index;

CREATE UNIQUE INDEX CORPORATIVO.SIGLA_LOTACAO_DP_LOTACAO_UK on CORPORATIVO.DP_LOTACAO (
    CASE WHEN DATA_FIM_LOT IS NULL THEN 
        SIGLA_LOTACAO || '-' || ID_ORGAO_USU 
    END
);