INSERT INTO CORPORATIVO.CP_SERVICO
(ID_SERVICO,  SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO, LABEL_SERVICO)
VALUES(CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL,  'SIGA-DOC-FE-ESP', 'Cadastrar Espécies', 307, 2, NULL);