-- 2702
INSERT INTO corporativo.CP_SERVICO(ID_SERVICO, SIGLA_SERVICO, DESC_SERVICO, ID_SERVICO_PAI, ID_TP_SERVICO, LABEL_SERVICO) 
	VALUES (CORPORATIVO.CP_SERVICO_SEQ.NEXTVAL, 'SIGA-DOC-REL-DOCGERADOSQUANTITATIVO', 'Relatório de Saída de Documentos por Setor', 284, 2, null);
