package br.gov.jfrj.siga.integracao.ws.pubnet.mapping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.CancelarMaterialResponse.CancelarMaterialResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.ConsultaLicitacaoResponse.ConsultaLicitacaoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.ConsultaMaterialEnviadoResponse.ConsultaMaterialEnviadoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.ConsultaPermissoesPublicanteResponse.ConsultaPermissoesPublicanteResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.EnviaPublicacaoResponse.EnviaPublicacaoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.EnviarNovoEventoLicitacaoResponse.EnviarNovoEventoLicitacaoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.GeraTokenResponse.GeraTokenResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.ListaJustificativasCancelamentoResponse.ListaJustificativasCancelamentoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.ListaStatusPublicacaoResponse.ListaStatusPublicacaoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.MontaReciboNovoEventoResponse.MontaReciboNovoEventoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.MontaReciboPublicacaoCancelamentoResponse.MontaReciboPublicacaoCancelamentoResult;
import br.gov.jfrj.siga.integracao.ws.pubnet.mapping.MontaReciboPublicacaoResponse.MontaReciboPublicacaoResult;

/**
 * This class was generated by Apache CXF 3.2.4 2022-08-24T10:49:00.622-03:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", name = "pubnetSoap")
//@XmlSeeAlso({org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class})
public interface PubnetSoap {

	/**
	 * Cancela o envio que foi realizado.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/cancelarMaterial")
	@RequestWrapper(localName = "cancelarMaterial", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.CancelarMaterial")
	@ResponseWrapper(localName = "cancelarMaterialResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.CancelarMaterialResponse")
	@WebResult(name = "cancelarMaterialResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public CancelarMaterialResult cancelarMaterial(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName,
			@WebParam(name = "nome_arquivo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String nomeArquivo,
			@WebParam(name = "justificativa_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String justificativaIdentificador,
			@WebParam(name = "recibo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String recibo,
			@WebParam(name = "reciboHash", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String reciboHash);

	/**
	 * Consulta as materias/licitações enviadas pelo usuário.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/consultaMaterialEnviado")
	@RequestWrapper(localName = "consultaMaterialEnviado", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaMaterialEnviado")
	@ResponseWrapper(localName = "consultaMaterialEnviadoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaMaterialEnviadoResponse")
	@WebResult(name = "consultaMaterialEnviadoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public ConsultaMaterialEnviadoResult consultaMaterialEnviado(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName,
			@WebParam(name = "datainicio", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String datainicio,
			@WebParam(name = "datafim", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String datafim);

	/**
	 * Monta Recibo de envio, novo evento.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/montaReciboNovoEvento")
	@RequestWrapper(localName = "montaReciboNovoEvento", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboNovoEvento")
	@ResponseWrapper(localName = "montaReciboNovoEventoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboNovoEventoResponse")
	@WebResult(name = "montaReciboNovoEventoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public MontaReciboNovoEventoResult montaReciboNovoEvento(
			@WebParam(name = "anunciante_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String anuncianteIdentificador,
			@WebParam(name = "caderno_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String cadernoIdentificador,
			@WebParam(name = "retranca_codigo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String retrancaCodigo,
			@WebParam(name = "tipomaterial_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String tipomaterialIdentificador,
			@WebParam(name = "sequencial", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String sequencial,
			@WebParam(name = "hashMD5sintese", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String hashMD5Sintese,
			@WebParam(name = "licitacao_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int licitacaoIdentificador,
			@WebParam(name = "modalidade", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String modalidade,
			@WebParam(name = "evento", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String evento,
			@WebParam(name = "numeropublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String numeropublicacao,
			@WebParam(name = "processo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String processo,
			@WebParam(name = "datapublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String datapublicacao);

	/**
	 * Lista as possiveis justificativas que podem ser aplicadas ao cancelamento.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/listaJustificativasCancelamento")
	@RequestWrapper(localName = "listaJustificativasCancelamento", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ListaJustificativasCancelamento")
	@ResponseWrapper(localName = "listaJustificativasCancelamentoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ListaJustificativasCancelamentoResponse")
	@WebResult(name = "listaJustificativasCancelamentoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public ListaJustificativasCancelamentoResult listaJustificativasCancelamento(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName);
	
	/**
	 * Geração de token para acesso ao serviço, quando login/senha do usuário
	 * não for conhecida.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/geraToken")
	@RequestWrapper(localName = "geraToken", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.GeraToken")
	@ResponseWrapper(localName = "geraTokenResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.GeraTokenResponse")
	@WebResult(name = "geraTokenResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public GeraTokenResult geraToken(
			@WebParam(name = "login", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String login,
			@WebParam(name = "documento", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String documento,
			@WebParam(name = "email", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String email);

	/**
	 * Monta Recibo de envio, materia.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/montaReciboPublicacao")
	@RequestWrapper(localName = "montaReciboPublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboPublicacao")
	@ResponseWrapper(localName = "montaReciboPublicacaoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboPublicacaoResponse")
	@WebResult(name = "montaReciboPublicacaoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public MontaReciboPublicacaoResult montaReciboPublicacao(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName,
			@WebParam(name = "anunciante_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String anuncianteIdentificador,
			@WebParam(name = "caderno_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String cadernoIdentificador,
			@WebParam(name = "retranca_codigo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String retrancaCodigo,
			@WebParam(name = "tipomaterial_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String tipomaterialIdentificador,
			@WebParam(name = "sequencial", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String sequencial,
			@WebParam(name = "hashMD5sintese", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String hashMD5Sintese);

	/**
	 * Monta Recibo de cancelamento : materia/novo evento
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/montaReciboPublicacaoCancelamento")
	@RequestWrapper(localName = "montaReciboPublicacaoCancelamento", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboPublicacaoCancelamento")
	@ResponseWrapper(localName = "montaReciboPublicacaoCancelamentoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.MontaReciboPublicacaoCancelamentoResponse")
	@WebResult(name = "montaReciboPublicacaoCancelamentoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public MontaReciboPublicacaoCancelamentoResult montaReciboPublicacaoCancelamento(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName,
			@WebParam(name = "nome_arquivo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String nomeArquivo);

	/**
	 * Lista relação de itens que foram publicado/enviados para o tipo:LICITAÇÃO
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/consultaLicitacao")
	@RequestWrapper(localName = "consultaLicitacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaLicitacao")
	@ResponseWrapper(localName = "consultaLicitacaoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaLicitacaoResponse")
	@WebResult(name = "consultaLicitacaoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public ConsultaLicitacaoResult consultaLicitacao(
			@WebParam(name = "statuspublicacao_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String statuspublicacaoIdentificador,
			@WebParam(name = "dataenvioinicio", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String dataenvioinicio,
			@WebParam(name = "dataenviofim", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String dataenviofim,
			@WebParam(name = "caderno_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String cadernoIdentificador,
			@WebParam(name = "anunciante_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String anuncianteIdentificador,
			@WebParam(name = "retranca_codigo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String retrancaCodigo,
			@WebParam(name = "tipomateria_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String tipomateriaIdentificador,
			@WebParam(name = "modalidade_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String modalidadeIdentificador,
			@WebParam(name = "numeropublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String numeropublicacao,
			@WebParam(name = "processo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String processo);

	/**
	 * Envia novo evento de publicação.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/enviarNovoEventoLicitacao")
	@RequestWrapper(localName = "enviarNovoEventoLicitacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.EnviarNovoEventoLicitacao")
	@ResponseWrapper(localName = "enviarNovoEventoLicitacaoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.EnviarNovoEventoLicitacaoResponse")
	@WebResult(name = "enviarNovoEventoLicitacaoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public EnviarNovoEventoLicitacaoResult enviarNovoEventoLicitacao(
			@WebParam(name = "anunciante_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int anuncianteIdentificador,
			@WebParam(name = "caderno_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int cadernoIdentificador,
			@WebParam(name = "retranca_codigo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String retrancaCodigo,
			@WebParam(name = "tipomaterial_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int tipomaterialIdentificador,
			@WebParam(name = "licitacao_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int licitacaoIdentificador,
			@WebParam(name = "modalidade", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int modalidade,
			@WebParam(name = "evento_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") int eventoIdentificador,
			@WebParam(name = "sintese", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String sintese,
			@WebParam(name = "datapublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String datapublicacao,
			@WebParam(name = "recibo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String recibo,
			@WebParam(name = "reciboHash", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String reciboHash);

	/**
	 * Lista a relação de anunciante x caderno x retranca x tipo materia que o
	 * usuário logado pode enviar pelo sistema.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/consultaPermissoesPublicante")
	@RequestWrapper(localName = "consultaPermissoesPublicante", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaPermissoesPublicante")
	@ResponseWrapper(localName = "consultaPermissoesPublicanteResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ConsultaPermissoesPublicanteResponse")
	@WebResult(name = "consultaPermissoesPublicanteResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public ConsultaPermissoesPublicanteResult consultaPermissoesPublicante(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName);

	/**
	 * Lista os status de publicação cadastrados no sistema.
	 * 
	 * @param <T>
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/listaStatusPublicacao")
	@RequestWrapper(localName = "listaStatusPublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ListaStatusPublicacao")
	@ResponseWrapper(localName = "listaStatusPublicacaoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.ListaStatusPublicacaoResponse")
	@WebResult(name = "listaStatusPublicacaoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public ListaStatusPublicacaoResult listaStatusPublicacao(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName);

	/**
	 * Envia publicação do tipo:MATERIA.
	 */
	@WebMethod(action = "http://pubnet.imprensaoficial.com.br/wspubnet/enviaPublicacao")
	@RequestWrapper(localName = "enviaPublicacao", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.EnviaPublicacao")
	@ResponseWrapper(localName = "enviaPublicacaoResponse", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet", className = "br.com.imprensaoficial.pubnet.wspubnet.EnviaPublicacaoResponse")
	@WebResult(name = "enviaPublicacaoResult", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
	public EnviaPublicacaoResult enviaPublicacao(
			@WebParam(header = true, name = "AuthHeader", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") AuthHeader userName,
			@WebParam(name = "anunciante_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String anuncianteIdentificador,
			@WebParam(name = "caderno_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String cadernoIdentificador,
			@WebParam(name = "retranca_codigo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String retrancaCodigo,
			@WebParam(name = "tipomaterial_identificador", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String tipomaterialIdentificador,
			@WebParam(name = "sequencial", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String sequencial,
			@WebParam(name = "sintese", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String sintese,
			@WebParam(name = "recibo", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String recibo,
			@WebParam(name = "reciboHash", targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet") String reciboHash);
}
