package br.gov.jfrj.siga.integracao.ws.pubnet.mapping;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.gov.jfrj.siga.integracao.ws.pubnet.utils.PropriedadePubnet;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2022-08-24T10:49:00.653-03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "pubnet",
                  wsdlLocation = "https://pubnetdes.imprensaoficial.com.br/wspubnet/pubnet.asmx?wsdl",
                  targetNamespace = "http://pubnet.imprensaoficial.com.br/wspubnet")
public class Pubnet extends Service {
	
    private final static WebServiceException PUBNET_EXCEPTION;

    private final static URL WSDL_LOCATION;

    private final static QName SERVICE = new QName(PropriedadePubnet.URL_NAMESPACE, PropriedadePubnet.LOCAL_PART);
    
    private final static QName PUBNET_SOAP_QNAME = new QName(PropriedadePubnet.URL_NAMESPACE, PropriedadePubnet.LOCAL_PART_SOAP);
    
    private final static QName PUBNET_SOAP12_QNAME = new QName(PropriedadePubnet.URL_NAMESPACE, PropriedadePubnet.LOCAL_PART_SOAP12);
    
    static {
        URL url = null;
        WebServiceException we = null;
        try {
            url = new URL(PropriedadePubnet.URL_WSDL);
        } catch (MalformedURLException e) {
        	we = new WebServiceException(e);
        }
        WSDL_LOCATION = url;
        PUBNET_EXCEPTION = we;
    }

    public Pubnet(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Pubnet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pubnet() {
        super(getWsdlLocation(), SERVICE);
    }

    public Pubnet(WebServiceFeature ... features) {
        super(getWsdlLocation(), SERVICE, features);
    }

    public Pubnet(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Pubnet(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     *
     * @return
     *     returns PubnetSoap
     */
    @WebEndpoint(name = "pubnetSoap12")
    public PubnetSoap getPubnetSoap12() {
        return super.getPort(PUBNET_SOAP12_QNAME, PubnetSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PubnetSoap
     */
    @WebEndpoint(name = "pubnetSoap12")
    public PubnetSoap getPubnetSoap12(WebServiceFeature... features) {
        return super.getPort(PUBNET_SOAP12_QNAME, PubnetSoap.class, features);
    }


    /**
     *
     * @return
     *     returns PubnetSoap
     */
    @WebEndpoint(name = "pubnetSoap")
    public PubnetSoap getPubnetSoap() {
        return super.getPort(PUBNET_SOAP_QNAME, PubnetSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PubnetSoap
     */
    @WebEndpoint(name = "pubnetSoap")
    public PubnetSoap getPubnetSoap(WebServiceFeature... features) {
        return super.getPort(PUBNET_SOAP_QNAME, PubnetSoap.class, features);
    }
    
    private static URL getWsdlLocation() {
        if (PUBNET_EXCEPTION!= null) {
            throw PUBNET_EXCEPTION;
        }
        return WSDL_LOCATION;
    }

}
