package br.gov.jfrj.siga.matrix.sinc;

// Generated 03/04/2012 11:48:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import br.gov.jfrj.siga.model.Assemelhavel;
import br.gov.jfrj.siga.sinc.lib.Sincronizavel;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT", schema = "MATRIX")
public class Department implements java.io.Serializable, Sincronizavel {

    private String departCode;
    private String departDesc;

    public Department() {
    }

    public Department(String departCode, String departDesc) {
        this.departCode = departCode;
        this.departDesc = departDesc;
    }

    @Id
    @Column(name = "DEPART_CODE", unique = true, nullable = false, length = 4)
    public String getDepartCode() {
        return this.departCode;
    }

    public void setDepartCode(String departCode) {
        this.departCode = departCode;
    }

    @Column(name = "DEPART_DESC", nullable = false, length = 128)
    public String getDepartDesc() {
        return this.departDesc;
    }

    public void setDepartDesc(String departDesc) {
        this.departDesc = departDesc;
    }

    @Override
    public boolean semelhante(Assemelhavel obj, int profundidade) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Department other = (Department) obj;
        if (departDesc == null) {
            if (other.departDesc != null)
                return false;
        } else if (!departDesc.equals(other.departDesc))
            return false;
        return true;
    }

    @Transient
    @Override
    public Long getId() {
        return 0L;
    }

    @Transient
    @Override
    public String getIdExterna() {
        return departDesc.trim();
    }

    @Override
    public void setIdExterna(String idExterna) {
        departCode = idExterna;
    }

    @Transient
    @Override
    public Long getIdInicial() {
        return getId();
    }

    @Override
    public void setIdInicial(Long idInicial) {
    }

    @Transient
    @Override
    public Date getDataInicio() {
        return null;
    }

    @Transient
    @Override
    public void setDataInicio(Date dataInicio) {

    }

    @Transient
    @Override
    public Date getDataFim() {
        return null;
    }

    @Transient
    @Override
    public void setDataFim(Date dataFim) {
    }

    @Transient
    @Override
    public String getLoteDeImportacao() {
        return null;
    }

    @Transient
    @Override
    public void setLoteDeImportacao(String loteDeImportacao) {
    }

    @Transient
    @Override
    public int getNivelDeDependencia() {
        return 0;
    }

    @Transient
    @Override
    public String getDescricaoExterna() {
        return "LOTACAO: " + departDesc + " (" + departCode + ")";
    }

    public void copiarPropriedades(Department outro) {
        this.departCode = outro.departCode;
        this.departDesc = outro.departDesc;
    }
}
