package br.gov.jfrj.siga.matrix.sinc;

// Generated 03/04/2012 11:48:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import br.gov.jfrj.siga.model.Assemelhavel;
import br.gov.jfrj.siga.sinc.lib.Sincronizavel;

/**
 * JobTitle generated by hbm2java
 */
@Entity
@Table(name = "JOB_TITLE", schema = "MATRIX")
public class JobTitle implements java.io.Serializable, Sincronizavel {

	private String positionCode;
	private String positionDesc;

	public JobTitle() {
	}

	public JobTitle(String positionCode, String positionDesc) {
		this.positionCode = positionCode;
		this.positionDesc = positionDesc;
	}

	@Id
	@Column(name = "POSITION_CODE", unique = true, nullable = false, length = 4)
	public String getPositionCode() {
		return this.positionCode;
	}

	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	@Column(name = "POSITION_DESC", nullable = false, length = 128)
	public String getPositionDesc() {
		return this.positionDesc;
	}

	public void setPositionDesc(String positionDesc) {
		this.positionDesc = positionDesc;
	}

	@Override
	public boolean semelhante(Assemelhavel obj, int profundidade) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JobTitle other = (JobTitle) obj;
		if (positionDesc == null) {
			if (other.positionDesc != null)
				return false;
		} else if (!positionDesc.equals(other.positionDesc))
			return false;
		return true;
	}

	@Transient
	@Override
	public Long getId() {
		return 0L;
	}

	@Transient
	@Override
	public String getIdExterna() {
		return positionDesc.trim();
	}

	@Override
	public void setIdExterna(String idExterna) {
		positionCode = idExterna;
	}

	@Transient
	@Override
	public Long getIdInicial() {
		return getId();
	}

	@Override
	public void setIdInicial(Long idInicial) {
	}

	@Transient
	@Override
	public Date getDataInicio() {
		return null;
	}

	@Transient
	@Override
	public void setDataInicio(Date dataInicio) {

	}

	@Transient
	@Override
	public Date getDataFim() {
		return null;
	}

	@Transient
	@Override
	public void setDataFim(Date dataFim) {
	}

	@Transient
	@Override
	public String getLoteDeImportacao() {
		return null;
	}

	@Transient
	@Override
	public void setLoteDeImportacao(String loteDeImportacao) {
	}

	@Transient
	@Override
	public int getNivelDeDependencia() {
		return 0;
	}

	@Transient
	@Override
	public String getDescricaoExterna() {
		return "CARGO: " + positionDesc + " (" + positionCode + ")";
	}

	public void copiarPropriedades(JobTitle outro) {
		this.positionCode = outro.positionCode;
		this.positionDesc = outro.positionDesc;
	}

}
