-------------------------------------------
--	SCRIPT:CRIACAO DO BANCO
-------------------------------------------

ALTER SESSION SET CURRENT_SCHEMA=sigagc;

GRANT SELECT ON CORPORATIVO.CP_CONFIGURACAO_SEQ TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_CARGO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_FUNCAO_CONFIANCA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_PESSOA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_LOTACAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_ORGAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_ORGAO_USUARIO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_IDENTIDADE TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_GRUPO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_APLICACAO_FERIADO TO SIGAGC;
GRANT ALTER ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT DEBUG ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT DELETE ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT FLASHBACK ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT INDEX ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT INSERT ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT ON COMMIT REFRESH ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT QUERY REWRITE ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT UPDATE ON CORPORATIVO.CP_CONFIGURACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_CONFIGURACAO_SEQ TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_FERIADO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_FERIADO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_GRUPO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_IDENTIDADE TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_LOCALIDADE TO SIGAGC;
GRANT DELETE ON CORPORATIVO.CP_MARCA TO SIGAGC;
GRANT INSERT ON CORPORATIVO.CP_MARCA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_MARCA TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_MARCA TO SIGAGC;
GRANT UPDATE ON CORPORATIVO.CP_MARCA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_MARCADOR TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_MARCADOR TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_MARCA_SEQ TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_MODELO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_OCORRENCIA_FERIADO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_ORGAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_ORGAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_ORGAO_USUARIO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_ORGAO_USUARIO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_PAPEL TO SIGAGC;
GRANT DELETE ON CORPORATIVO.CP_PERSONALIZACAO TO SIGAGC;
GRANT INSERT ON CORPORATIVO.CP_PERSONALIZACAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.CP_PERSONALIZACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_PERSONALIZACAO TO SIGAGC;
GRANT UPDATE ON CORPORATIVO.CP_PERSONALIZACAO TO SIGAGC;
GRANT INSERT ON CORPORATIVO.CP_SERVICO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_SERVICO TO SIGAGC;
GRANT UPDATE ON CORPORATIVO.CP_SERVICO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_SERVICO_SEQ TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_SITUACAO_CONFIGURACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_CONFIGURACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_GRUPO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_IDENTIDADE TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_LOTACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_MARCA TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_MARCADOR TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_PAPEL TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_PESSOA TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_SERVICO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_TIPO_SERVICO_SITUACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.CP_UF TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_CARGO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_CARGO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_FUNCAO_CONFIANCA TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_FUNCAO_CONFIANCA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_LOTACAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_LOTACAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_PESSOA TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_PESSOA TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_PROVIMENTO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_PROVIMENTO TO SIGAGC;
GRANT DELETE ON CORPORATIVO.DP_SUBSTITUICAO TO SIGAGC;
GRANT INSERT ON CORPORATIVO.DP_SUBSTITUICAO TO SIGAGC;
GRANT REFERENCES ON CORPORATIVO.DP_SUBSTITUICAO TO SIGAGC;
GRANT SELECT ON CORPORATIVO.DP_SUBSTITUICAO TO SIGAGC;
GRANT UPDATE ON CORPORATIVO.DP_SUBSTITUICAO TO SIGAGC;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO SIGAGC;
GRANT select on corporativo.cp_tipo_lotacao to sigagc;
grant select on corporativo.cp_complexo to sigagc;


CREATE SEQUENCE SIGAGC.hibernate_sequence  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Function REMOVE_ACENTO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION SIGAGC.REMOVE_ACENTO 
    (acentuado in
    VARCHAR2)

--	Enter the parameters for the function in
--	the brackets above.  If this function has
--	no parameters then delete the line

--  ***************************************************
--	*                                                 *
--	*   Author                                        *
--	*   Creation Date                                 *
--	*   Comments                                      *
--	*                                                 *
--  ***************************************************

RETURN  VARCHAR2

IS

--	Enter all variables cursors and constants following
--	this line
sem_acento VARCHAR2(4000);

begin

--	Enter the code for the function following
--	this line

      sem_acento := CONVERT(TRANSLATE(UPPER( acentuado ),'ÃÃÃ','AON'),'US7ASCII');

	return	sem_acento;
			
exception

--	Enter the code to handle exception conditions
--	following this line


	when others then
		null;
			
end;
/ 

--------------------------------------------------------
--  DDL for Table GC_ACESSO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_ACESSO" 
   (	"ID_ACESSO" NUMBER(19,0), 
	"NOME_ACESSO" VARCHAR2(255 CHAR)
   );
--------------------------------------------------------
--  DDL for Table GC_ARQUIVO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_ARQUIVO" 
   (	"ID_CONTEUDO" NUMBER(19,0), 
	"CLASSIFICACAO" VARCHAR2(255 CHAR), 
	"CONTEUDO" BLOB, 
	"CONTEUDO_TIPO" VARCHAR2(255 CHAR), 
	"TITULO" VARCHAR2(255 CHAR)
   );
--------------------------------------------------------
--  DDL for Table GC_CONFIGURACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_CONFIGURACAO" 
   (	"ID_CONFIGURACAO_GC" NUMBER(19,0), 
	"ID_TIPO_INFORMACAO" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table GC_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_INFORMACAO" 
   (	"ID_INFORMACAO" NUMBER(19,0), 
	"ANO" NUMBER(10,0), 
	"DT_ELABORACAO_FIM" TIMESTAMP (6), 
	"HIS_DT_FIM" TIMESTAMP (6), 
	"HIS_DT_INI" TIMESTAMP (6), 
	"NUMERO" NUMBER(10,0), 
	"ID_ARQUIVO" NUMBER(19,0), 
	"ID_PESSOA_TITULAR" NUMBER(19,0), 
	"ID_ACESSO_EDICAO" NUMBER(19,0), 
	"HIS_IDC_INI" NUMBER(19,0), 
	"ID_INFORMACAO_PAI" NUMBER(19,0), 
	"ID_LOTACAO_TITULAR" NUMBER(19,0), 
	"ID_ORGAO_USUARIO" NUMBER(19,0), 
	"ID_TIPO_INFORMACAO" NUMBER(19,0), 
	"ID_ACESSO" NUMBER(19,0), 
	"ID_GRUPO" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table GC_MOVIMENTACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_MOVIMENTACAO" 
   (	"ID_MOVIMENTACAO" NUMBER(19,0), 
	"HIS_DT_INI" TIMESTAMP (6), 
	"ID_CONTEUDO" NUMBER(19,0), 
	"HIS_IDC_INI" NUMBER(19,0), 
	"ID_INFORMACAO" NUMBER(19,0), 
	"ID_LOTACAO_ATENDENTE" NUMBER(19,0), 
	"ID_LOTACAO_TITULAR" NUMBER(19,0), 
	"ID_MOVIMENTACAO_CANCELADORA" NUMBER(19,0), 
	"ID_MOVIMENTACAO_REF" NUMBER(19,0), 
	"ID_PESSOA_ATENDENTE" NUMBER(19,0), 
	"ID_PESSOA_TITULAR" NUMBER(19,0), 
	"ID_TIPO_MOVIMENTACAO" NUMBER(19,0), 
	"DESCRICAO" VARCHAR2(255 BYTE)
   );
--------------------------------------------------------
--  DDL for Table GC_TAG
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TAG" 
   (	"ID_TAG" NUMBER(19,0), 
	"CATEGORIA" VARCHAR2(10 CHAR), 
	"TITULO" VARCHAR2(256 CHAR), 
	"TIPO_ID_TIPO_TAG" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" 
   (	"ID_INFORMACAO" NUMBER(19,0), 
	"ID_TAG" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_INFORMACAO" 
   (	"ID_TIPO_INFORMACAO" NUMBER(19,0), 
	"NOME_TIPO_INFORMACAO" VARCHAR2(255 CHAR), 
	"ARQUIVO" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Table GC_TIPO_MOVIMENTACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" 
   (	"ID_TIPO_MOVIMENTACAO" NUMBER(19,0), 
	"NOME_TIPO_MOVIMENTACAO" VARCHAR2(255 CHAR)
   );
--------------------------------------------------------
--  DDL for Table GC_TIPO_TAG
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_TAG" 
   (	"ID_TIPO_TAG" NUMBER(19,0), 
	"NOME_TIPO_TAG" VARCHAR2(255 CHAR)
   );
--------------------------------------------------------
--  DDL for Table RI_CONFIGURACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."RI_CONFIGURACAO" 
   (	"ID_CONFIGURACAO_RI" NUMBER(19,0)
   );
--------------------------------------------------------
--  DDL for Index SYS_C00172399
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172399" ON "SIGAGC"."RI_CONFIGURACAO" ("ID_CONFIGURACAO_RI");
--------------------------------------------------------
--  DDL for Index SYS_C00172400
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172400" ON "SIGAGC"."GC_ACESSO" ("ID_ACESSO");
--------------------------------------------------------
--  DDL for Index SYS_C00172401
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172401" ON "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO");
--------------------------------------------------------
--  DDL for Index SYS_C00172402
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172402" ON "SIGAGC"."GC_CONFIGURACAO" ("ID_CONFIGURACAO_GC");
--------------------------------------------------------
--  DDL for Index SYS_C00172403
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172403" ON "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO");
--------------------------------------------------------
--  DDL for Index SYS_C00172404
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172404" ON "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO");
--------------------------------------------------------
--  DDL for Index SYS_C00172405
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172405" ON "SIGAGC"."GC_TAG" ("ID_TAG");
--------------------------------------------------------
--  DDL for Index SYS_C00172406
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172406" ON "SIGAGC"."GC_TAG_X_INFORMACAO" ("ID_INFORMACAO", "ID_TAG");
--------------------------------------------------------
--  DDL for Index SYS_C00172407
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172407" ON "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO");
--------------------------------------------------------
--  DDL for Index SYS_C00172408
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172408" ON "SIGAGC"."GC_TIPO_MOVIMENTACAO" ("ID_TIPO_MOVIMENTACAO");
--------------------------------------------------------
--  DDL for Index SYS_C00172409
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172409" ON "SIGAGC"."GC_TIPO_TAG" ("ID_TIPO_TAG");

--------------------------------------------------------
--  Constraints for Table GC_ACESSO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_ACESSO" MODIFY ("ID_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ACESSO" MODIFY ("NOME_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ACESSO" ADD PRIMARY KEY ("ID_ACESSO");
  
--------------------------------------------------------
--  Constraints for Table GC_ARQUIVO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_ARQUIVO" MODIFY ("ID_CONTEUDO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ARQUIVO" ADD PRIMARY KEY ("ID_CONTEUDO");
--------------------------------------------------------
--  Constraints for Table GC_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" MODIFY ("ID_CONFIGURACAO_GC" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD PRIMARY KEY ("ID_CONFIGURACAO_GC");
--------------------------------------------------------
--  Constraints for Table GC_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_PESSOA_TITULAR" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ACESSO_EDICAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("HIS_IDC_INI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_LOTACAO_TITULAR" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ORGAO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD PRIMARY KEY ("ID_INFORMACAO");
--------------------------------------------------------
--  Constraints for Table GC_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("HIS_IDC_INI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD PRIMARY KEY ("ID_MOVIMENTACAO");
--------------------------------------------------------
--  Constraints for Table GC_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG" MODIFY ("ID_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG" MODIFY ("TIPO_ID_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG" ADD PRIMARY KEY ("ID_TAG");
--------------------------------------------------------
--  Constraints for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" MODIFY ("ID_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD PRIMARY KEY ("ID_INFORMACAO", "ID_TAG");
--------------------------------------------------------
--  Constraints for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" MODIFY ("ID_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" MODIFY ("NOME_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" ADD PRIMARY KEY ("ID_TIPO_INFORMACAO");
--------------------------------------------------------
--  Constraints for Table GC_TIPO_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" MODIFY ("ID_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" MODIFY ("NOME_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" ADD PRIMARY KEY ("ID_TIPO_MOVIMENTACAO");
--------------------------------------------------------
--  Constraints for Table GC_TIPO_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" MODIFY ("ID_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" MODIFY ("NOME_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" ADD PRIMARY KEY ("ID_TIPO_TAG");
--------------------------------------------------------
--  Constraints for Table RI_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" MODIFY ("ID_CONFIGURACAO_RI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" ADD PRIMARY KEY ("ID_CONFIGURACAO_RI");
--------------------------------------------------------
--  Ref Constraints for Table GC_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD CONSTRAINT "FK5B6C283297A881AD" FOREIGN KEY ("ID_TIPO_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD CONSTRAINT "FK5B6C2832F6A487C3" FOREIGN KEY ("ID_CONFIGURACAO_GC")
	  REFERENCES "CORPORATIVO"."CP_CONFIGURACAO" ("ID_CONFIGURACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC14A981C" FOREIGN KEY ("ID_ACESSO")
	  REFERENCES "SIGAGC"."GC_ACESSO" ("ID_ACESSO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC4A634B1A" FOREIGN KEY ("ID_LOTACAO_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC5C8D8B16" FOREIGN KEY ("ID_ARQUIVO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC8DEEFE82" FOREIGN KEY ("ID_ACESSO_EDICAO")
	  REFERENCES "SIGAGC"."GC_ACESSO" ("ID_ACESSO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC9139CD43" FOREIGN KEY ("ID_INFORMACAO_PAI")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC97A881AD" FOREIGN KEY ("ID_TIPO_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCC8778546" FOREIGN KEY ("ID_PESSOA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCE2B26866" FOREIGN KEY ("ID_ORGAO_USUARIO")
	  REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCFC20D6A3" FOREIGN KEY ("HIS_IDC_INI")
	  REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "GC_INFORMACAO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "CORPORATIVO"."CP_GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3861DEBB381" FOREIGN KEY ("ID_TIPO_MOVIMENTACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_MOVIMENTACAO" ("ID_TIPO_MOVIMENTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3864101359E" FOREIGN KEY ("ID_CONTEUDO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3864A634B1A" FOREIGN KEY ("ID_LOTACAO_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3869B156615" FOREIGN KEY ("ID_LOTACAO_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386A3658F2C" FOREIGN KEY ("ID_MOVIMENTACAO_CANCELADORA")
	  REFERENCES "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386BC9A64C1" FOREIGN KEY ("ID_PESSOA_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386C8778546" FOREIGN KEY ("ID_PESSOA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386D38B6636" FOREIGN KEY ("ID_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386FC20D6A3" FOREIGN KEY ("HIS_IDC_INI")
	  REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "ID_MOVIMENTACAO_FK" FOREIGN KEY ("ID_MOVIMENTACAO_REF")
	  REFERENCES "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG" ADD CONSTRAINT "FK7D04AD97F23572CE" FOREIGN KEY ("TIPO_ID_TIPO_TAG")
	  REFERENCES "SIGAGC"."GC_TIPO_TAG" ("ID_TIPO_TAG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD CONSTRAINT "FK6DCF9EA8635922F0" FOREIGN KEY ("ID_TAG")
	  REFERENCES "SIGAGC"."GC_TAG" ("ID_TAG") ENABLE;
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD CONSTRAINT "FK6DCF9EA8D38B6636" FOREIGN KEY ("ID_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" ADD CONSTRAINT "TIPO_INFORMACAO_ARQUIVO_FK" FOREIGN KEY ("ARQUIVO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RI_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" ADD CONSTRAINT "FK830C72B7F6A4891E" FOREIGN KEY ("ID_CONFIGURACAO_RI")
	  REFERENCES "CORPORATIVO"."CP_CONFIGURACAO" ("ID_CONFIGURACAO") ENABLE;
	  
	  
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Criação', 1);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Concluído', 2);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Cancelado', 3);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Solicitação de revisão', 4);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Revisado', 5);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Notificação', 6);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Ciente', 7);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Classificação', 8);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Interesse', 9);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Edição', 10);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Visita', 11);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Cancelamento de movimentação', 12);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Anexação de arquivo', 13);
insert into SIGAGC.GC_TIPO_MOVIMENTACAO (NOME_TIPO_MOVIMENTACAO, ID_TIPO_MOVIMENTACAO) values ('Duplicado', 14);
insert into SIGAGC.GC_TIPO_INFORMACAO (ARQUIVO, NOME_TIPO_INFORMACAO, ID_TIPO_INFORMACAO) values (NULL, 'Registro de Conhecimento', 1);
insert into SIGAGC.GC_TIPO_TAG (NOME_TIPO_TAG, ID_TIPO_TAG) values ('Classificação', 1);
insert into SIGAGC.GC_TIPO_TAG (NOME_TIPO_TAG, ID_TIPO_TAG) values ('Marcador', 2);
insert into SIGAGC.GC_TIPO_TAG (NOME_TIPO_TAG, ID_TIPO_TAG) values ('Âncora', 3);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Público', 1);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Restrito ao órgão', 2);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Lotação e superiores', 3);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Lotação e inferiores', 4);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Lotação', 5);
insert into SIGAGC.GC_ACESSO (NOME_ACESSO, ID_ACESSO) values ('Pessoal', 6);
commit;
