-------------------------------------------
--	SCRIPT:CRIACAO DO BANCO
-------------------------------------------

ALTER SESSION SET CURRENT_SCHEMA=sigagc;

--------------------------------------------------------
--  DDL for Table GC_ACESSO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_ACESSO" 
   (	"ID_ACESSO" NUMBER(19,0), 
	"NOME_ACESSO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_ARQUIVO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_ARQUIVO" 
   (	"ID_CONTEUDO" NUMBER(19,0), 
	"CLASSIFICACAO" VARCHAR2(255 CHAR), 
	"CONTEUDO" BLOB, 
	"CONTEUDO_TIPO" VARCHAR2(255 CHAR), 
	"TITULO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" 
 LOB ("CONTEUDO") STORE AS BASICFILE (
  TABLESPACE "SIGAGC_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GC_CONFIGURACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_CONFIGURACAO" 
   (	"ID_CONFIGURACAO_GC" NUMBER(19,0), 
	"ID_TIPO_INFORMACAO" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_INFORMACAO" 
   (	"ID_INFORMACAO" NUMBER(19,0), 
	"ANO" NUMBER(10,0), 
	"DT_ELABORACAO_FIM" TIMESTAMP (6), 
	"HIS_DT_FIM" TIMESTAMP (6), 
	"HIS_DT_INI" TIMESTAMP (6), 
	"NUMERO" NUMBER(10,0), 
	"ID_ARQUIVO" NUMBER(19,0), 
	"ID_PESSOA_TITULAR" NUMBER(19,0), 
	"ID_ACESSO_EDICAO" NUMBER(19,0), 
	"HIS_IDC_INI" NUMBER(19,0), 
	"ID_INFORMACAO_PAI" NUMBER(19,0), 
	"ID_LOTACAO_TITULAR" NUMBER(19,0), 
	"ID_ORGAO_USUARIO" NUMBER(19,0), 
	"ID_TIPO_INFORMACAO" NUMBER(19,0), 
	"ID_ACESSO" NUMBER(19,0), 
	"ID_GRUPO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_MOVIMENTACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_MOVIMENTACAO" 
   (	"ID_MOVIMENTACAO" NUMBER(19,0), 
	"HIS_DT_INI" TIMESTAMP (6), 
	"ID_CONTEUDO" NUMBER(19,0), 
	"HIS_IDC_INI" NUMBER(19,0), 
	"ID_INFORMACAO" NUMBER(19,0), 
	"ID_LOTACAO_ATENDENTE" NUMBER(19,0), 
	"ID_LOTACAO_TITULAR" NUMBER(19,0), 
	"ID_MOVIMENTACAO_CANCELADORA" NUMBER(19,0), 
	"ID_MOVIMENTACAO_REF" NUMBER(19,0), 
	"ID_PESSOA_ATENDENTE" NUMBER(19,0), 
	"ID_PESSOA_TITULAR" NUMBER(19,0), 
	"ID_TIPO_MOVIMENTACAO" NUMBER(19,0), 
	"DESCRICAO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_TAG
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TAG" 
   (	"ID_TAG" NUMBER(19,0), 
	"CATEGORIA" VARCHAR2(10 CHAR), 
	"TITULO" VARCHAR2(256 CHAR), 
	"TIPO_ID_TIPO_TAG" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" 
   (	"ID_INFORMACAO" NUMBER(19,0), 
	"ID_TAG" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_INFORMACAO" 
   (	"ID_TIPO_INFORMACAO" NUMBER(19,0), 
	"NOME_TIPO_INFORMACAO" VARCHAR2(255 CHAR), 
	"ARQUIVO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_TIPO_MOVIMENTACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" 
   (	"ID_TIPO_MOVIMENTACAO" NUMBER(19,0), 
	"NOME_TIPO_MOVIMENTACAO" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table GC_TIPO_TAG
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."GC_TIPO_TAG" 
   (	"ID_TIPO_TAG" NUMBER(19,0), 
	"NOME_TIPO_TAG" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Table RI_CONFIGURACAO
--------------------------------------------------------

  CREATE TABLE "SIGAGC"."RI_CONFIGURACAO" 
   (	"ID_CONFIGURACAO_RI" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SIGAGC_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172399
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172399" ON "SIGAGC"."RI_CONFIGURACAO" ("ID_CONFIGURACAO_RI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172400
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172400" ON "SIGAGC"."GC_ACESSO" ("ID_ACESSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172401
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172401" ON "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172402
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172402" ON "SIGAGC"."GC_CONFIGURACAO" ("ID_CONFIGURACAO_GC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172403
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172403" ON "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172404
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172404" ON "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172405
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172405" ON "SIGAGC"."GC_TAG" ("ID_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172406
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172406" ON "SIGAGC"."GC_TAG_X_INFORMACAO" ("ID_INFORMACAO", "ID_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172407
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172407" ON "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172408
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172408" ON "SIGAGC"."GC_TIPO_MOVIMENTACAO" ("ID_TIPO_MOVIMENTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_C00172409
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_C00172409" ON "SIGAGC"."GC_TIPO_TAG" ("ID_TIPO_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000184228C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAGC"."SYS_IL0000184228C00003$$" ON "SIGAGC"."GC_ARQUIVO" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  Constraints for Table GC_ACESSO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_ACESSO" MODIFY ("ID_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ACESSO" MODIFY ("NOME_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ACESSO" ADD PRIMARY KEY ("ID_ACESSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_ARQUIVO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_ARQUIVO" MODIFY ("ID_CONTEUDO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_ARQUIVO" ADD PRIMARY KEY ("ID_CONTEUDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" MODIFY ("ID_CONFIGURACAO_GC" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD PRIMARY KEY ("ID_CONFIGURACAO_GC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_PESSOA_TITULAR" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ACESSO_EDICAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("HIS_IDC_INI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_LOTACAO_TITULAR" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ORGAO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" MODIFY ("ID_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD PRIMARY KEY ("ID_INFORMACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("HIS_IDC_INI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" MODIFY ("ID_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD PRIMARY KEY ("ID_MOVIMENTACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG" MODIFY ("ID_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG" MODIFY ("TIPO_ID_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG" ADD PRIMARY KEY ("ID_TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" MODIFY ("ID_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" MODIFY ("ID_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD PRIMARY KEY ("ID_INFORMACAO", "ID_TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" MODIFY ("ID_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" MODIFY ("NOME_TIPO_INFORMACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" ADD PRIMARY KEY ("ID_TIPO_INFORMACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_TIPO_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" MODIFY ("ID_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" MODIFY ("NOME_TIPO_MOVIMENTACAO" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_MOVIMENTACAO" ADD PRIMARY KEY ("ID_TIPO_MOVIMENTACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GC_TIPO_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" MODIFY ("ID_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" MODIFY ("NOME_TIPO_TAG" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."GC_TIPO_TAG" ADD PRIMARY KEY ("ID_TIPO_TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RI_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" MODIFY ("ID_CONFIGURACAO_RI" NOT NULL ENABLE);
  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" ADD PRIMARY KEY ("ID_CONFIGURACAO_RI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SIGAGC_IDX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD CONSTRAINT "FK5B6C283297A881AD" FOREIGN KEY ("ID_TIPO_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_CONFIGURACAO" ADD CONSTRAINT "FK5B6C2832F6A487C3" FOREIGN KEY ("ID_CONFIGURACAO_GC")
	  REFERENCES "CORPORATIVO"."CP_CONFIGURACAO" ("ID_CONFIGURACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC14A981C" FOREIGN KEY ("ID_ACESSO")
	  REFERENCES "SIGAGC"."GC_ACESSO" ("ID_ACESSO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC4A634B1A" FOREIGN KEY ("ID_LOTACAO_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC5C8D8B16" FOREIGN KEY ("ID_ARQUIVO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC8DEEFE82" FOREIGN KEY ("ID_ACESSO_EDICAO")
	  REFERENCES "SIGAGC"."GC_ACESSO" ("ID_ACESSO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC9139CD43" FOREIGN KEY ("ID_INFORMACAO_PAI")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FC97A881AD" FOREIGN KEY ("ID_TIPO_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_INFORMACAO" ("ID_TIPO_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCC8778546" FOREIGN KEY ("ID_PESSOA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCE2B26866" FOREIGN KEY ("ID_ORGAO_USUARIO")
	  REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "FK8B6611FCFC20D6A3" FOREIGN KEY ("HIS_IDC_INI")
	  REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
  ALTER TABLE "SIGAGC"."GC_INFORMACAO" ADD CONSTRAINT "GC_INFORMACAO_GRUPO_FK" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "CORPORATIVO"."CP_GRUPO" ("ID_GRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_MOVIMENTACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3861DEBB381" FOREIGN KEY ("ID_TIPO_MOVIMENTACAO")
	  REFERENCES "SIGAGC"."GC_TIPO_MOVIMENTACAO" ("ID_TIPO_MOVIMENTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3864101359E" FOREIGN KEY ("ID_CONTEUDO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3864A634B1A" FOREIGN KEY ("ID_LOTACAO_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F3869B156615" FOREIGN KEY ("ID_LOTACAO_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386A3658F2C" FOREIGN KEY ("ID_MOVIMENTACAO_CANCELADORA")
	  REFERENCES "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386BC9A64C1" FOREIGN KEY ("ID_PESSOA_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386C8778546" FOREIGN KEY ("ID_PESSOA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386D38B6636" FOREIGN KEY ("ID_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "FK3157F386FC20D6A3" FOREIGN KEY ("HIS_IDC_INI")
	  REFERENCES "CORPORATIVO"."CP_IDENTIDADE" ("ID_IDENTIDADE") ENABLE;
  ALTER TABLE "SIGAGC"."GC_MOVIMENTACAO" ADD CONSTRAINT "ID_MOVIMENTACAO_FK" FOREIGN KEY ("ID_MOVIMENTACAO_REF")
	  REFERENCES "SIGAGC"."GC_MOVIMENTACAO" ("ID_MOVIMENTACAO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TAG
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG" ADD CONSTRAINT "FK7D04AD97F23572CE" FOREIGN KEY ("TIPO_ID_TIPO_TAG")
	  REFERENCES "SIGAGC"."GC_TIPO_TAG" ("ID_TIPO_TAG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TAG_X_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD CONSTRAINT "FK6DCF9EA8635922F0" FOREIGN KEY ("ID_TAG")
	  REFERENCES "SIGAGC"."GC_TAG" ("ID_TAG") ENABLE;
  ALTER TABLE "SIGAGC"."GC_TAG_X_INFORMACAO" ADD CONSTRAINT "FK6DCF9EA8D38B6636" FOREIGN KEY ("ID_INFORMACAO")
	  REFERENCES "SIGAGC"."GC_INFORMACAO" ("ID_INFORMACAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GC_TIPO_INFORMACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."GC_TIPO_INFORMACAO" ADD CONSTRAINT "TIPO_INFORMACAO_ARQUIVO_FK" FOREIGN KEY ("ARQUIVO")
	  REFERENCES "SIGAGC"."GC_ARQUIVO" ("ID_CONTEUDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RI_CONFIGURACAO
--------------------------------------------------------

  ALTER TABLE "SIGAGC"."RI_CONFIGURACAO" ADD CONSTRAINT "FK830C72B7F6A4891E" FOREIGN KEY ("ID_CONFIGURACAO_RI")
	  REFERENCES "CORPORATIVO"."CP_CONFIGURACAO" ("ID_CONFIGURACAO") ENABLE;
