[@entrevista]
	[#if !esconderDest!false]
		[@grupo]
			[@grupo]
				[@selecao titulo="Tipo de Autoridade" var="tipoAutoridade" opcoes="[Nenhum];Auditor da Justiça Militar;Bispo e Arcebispo;Cardeal;Chefe de Gabinete Civil;Chefe de Gabinete Militar da Presidência da República;Consultor-Geral da República;Corregedor do Tribunal Regional Federal;Dirigente administrativo e Procurador;Embaixador;Governador de Estado e do Distrito Federal;Juiz Federal;Juiz em geral;Membro do Congresso Nacional;Membro do Supremo Tribunal Federal;Membro do Tribunal Superior;Membro do Tribunal de Contas da União;Membro do Tribunal Regional Federal;Membro do Tribunal de Justiça;Membro da Assembléia Legislativa;Ministro de Estado;Monsenhor, Cônego;Prefeito;Presidente da República;Presidente do Supremo Tribunal Federal;Presidente do Tribunal Superior;Presidente do Tribunal Regional Federal;Presidente do Tribunal de Justiça;Presidente da Assembléia Legislativa;Presidente do Tribunal de Contas da União;Procurador-Geral da República;Procurador-Geral junto ao Tribunal;Secretário de Estado do Governo Estadual;Reitor de Universidade;Vice-Presidente da República;Oficial General das Forças Armadas;[Outros]" reler="sim" /]
					[#if func.verificaGenero(tipoAutoridade)=='F']
						[@selecao titulo="Gênero da Autoridade" var="genero" opcoes="M;F" reler="sim" /]
					[#else]
						[#assign genero = func.verificaGenero(tipoAutoridade) /]
					[/#if]
		                [#assign tratamento = func.tratamento(tipoAutoridade,genero) /]
				[#if tratamento??]
                                        [@grupo]
                                                [@mensagem titulo="Forma de tratamento" texto="${tratamento.formaDeTratamento} (${tratamento.abreviatura})" /]
                                        [/@grupo]
	                      	[/#if]
                        [/@grupo]
			[#if tratamento??]
                                [@grupo]
                                        [@selecao titulo="Especificar manualmente o vocativo" var="especificarVocativo" opcoes="Não/Sim" reler="sim" /]
                                [/@grupo]
                      	[/#if]
			[#if !tratamento?? || especificarVocativo == 'Sim']
                                [@grupo]
                                        [@texto titulo="Vocativo" var="vocativo" largura="45" /]
                                [/@grupo]
                        [#else]
                                [@oculto var="vocativo" valor="${tratamento.vocativo}" /]
                        [/#if]
                [/@grupo]
		[@grupo titulo="Texto a ser inserido no corpo do ofício"]
			[@grupo]
				[@editor titulo="" var="texto_oficio" /]
			[/@grupo]
		[/@grupo]
                [@grupo]
                        [@texto titulo="Fecho (de acordo com o vocativo)" var="fecho" largura="50" /]
                [/@grupo]

			[@grupo titulo="Dados do destinatário"]
                                <!-- Tratamento -->
				[#if tratamento??]
					[@grupo]
                                                [@caixaverif titulo="Especificar manualmente a forma de endereçamento" var="especificarEnderecamento" reler="sim" /]
					[/@grupo]
                                [/#if]
				[#if !tratamento?? || especificarEnderecamento == 'Sim']
					[@grupo]
                                                [@texto titulo="Forma de endereçamento"	var="enderecamento_dest" largura="45" /]
					[/@grupo]
                                [#else]
					[@oculto var="enderecamento_dest" valor="${tratamento.formaDeEnderecamento}" /]
                                [/#if]

				<!-- Nome -->
				[#if (doc.destinatario.descricao)??]
					[@grupo]
                                                [@caixaverif titulo="Especificar manualmente o nome do destinatário" var="especificarNome" reler="sim" /]
					[/@grupo]
                                [/#if]
				[#if !(doc.destinatario.descricao)?? || especificarNome == 'Sim']
					[@grupo]
                                                [@texto titulo="Nome" var="nome_dest" largura="60" /]
					[/@grupo]
                                [#else]
					[@oculto var="nome_dest" valor="${doc.destinatario.descricao}" /]
                                [/#if]

				<!-- Cargo -->
				[#if (doc.destinatario.cargo.nomeCargo)??]
					[@grupo]
                                                [@caixaverif titulo="Especificar manualmente o cargo do destinatário" var="especificarCargo" reler="sim" /]
					[/@grupo]
                                [/#if]
				[#if !(doc.destinatario.cargo.nomeCargo)?? || especificarCargo == 'Sim']
					[@grupo]
                                                [@texto titulo="Cargo" var="cargo_dest" largura="60" /]
					[/@grupo]
                                [#else]
					[@oculto var="cargo_dest" valor="${doc.destinatario.cargo.nomeCargo}" /]
                                [/#if]				

				<!-- Órgão -->
				[#if (doc.lotaDestinatario.descricao)??]
        		                [#assign orgaoAux = doc.lotaDestinatario.descricao /]
                                [#else]
        				[#if (orgaoExternoDestinatarioSel.descricao)??]
                		                [#assign orgaoAux = orgaoExternoDestinatarioSel.descricao /]
                                        [/#if]
                                [/#if]


				[#if orgaoAux??]
					[@grupo]
                                                [@caixaverif titulo="Especificar manualmente o órgão do destinatário" var="especificarOrgao" reler="sim" /]
					[/@grupo]
                                [/#if]
				[#if !orgaoAux?? || especificarOrgao == 'Sim']
					[@grupo]
                                                [@texto titulo="Órgão" var="orgao_dest" largura="60" /]
					[/@grupo]
                                [#else]
					[@oculto var="orgao_dest" valor="${orgaoAux}" /]
                                [/#if]	

                                [@memo titulo="Endereço" var="endereco_dest" linhas="4"	colunas="60" /]
			[/@grupo]
		[@selecao titulo="Tamanho da letra" var="tamanhoLetra" opcoes="Normal;Pequeno;Grande" /]
	[/#if]
[/@entrevista]

[@documento margemDireita="3cm"]
	[#if param.tamanhoLetra! == "Normal"]
		[#assign tl = "11pt" /]
	[#elseif param.tamanhoLetra! == "Pequeno"]
		[#assign tl = "9pt" /]
	[#elseif param.tamanhoLetra! == "Grande"]
		[#assign tl = "13pt" /]
	[#else]		
		[#assign tl = "11pt"]
	[/#if]

	[#if !(func.contains(fecho,'.')) && !(func.contains(fecho,','))]
		[#assign virgula ="," /]
       	[/#if]

        [#assign rpp][@rodapeDestinatario tl=tl/][/#assign]
        
        [@estiloBrasaoCentralizado tipo="OFÍCIO" tamanhoLetra=tl formatarOrgao=true rodapePrimeiraPagina=rpp]
		<div style="font-family: Arial; font-size: 10pt;">
		<p>&nbsp;</p>
		[#if !vocativo??]
		<p align="left" style="TEXT-INDENT: 2cm">${vocativo},</p>
		[/#if]
		<p><span style="font-size: ${tl}"> ${texto_oficio} </span>[#if fecho??] <span style="font-size: ${tl}"><center>${fecho}${virgula!}</center></span>[/#if]</p>
		</div>
        [/@estiloBrasaoCentralizado]
[/@documento]
