
package bluecrystal.service.v1.icpbr;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IcpbrService", targetNamespace = "http://icpbr.v1.service.bluecrystal/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IcpbrService {


    /**
     * 
     * @param signingTime
     * @param origHashb64
     * @param certb64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashSignedAttribADRB21", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.HashSignedAttribADRB21")
    @ResponseWrapper(localName = "hashSignedAttribADRB21Response", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.HashSignedAttribADRB21Response")
    public String hashSignedAttribADRB21(
        @WebParam(name = "origHashb64", targetNamespace = "")
        String origHashb64,
        @WebParam(name = "signingTime", targetNamespace = "")
        XMLGregorianCalendar signingTime,
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signingTime
     * @param origHashb64
     * @param x509
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashSignedAttribADRB10", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.HashSignedAttribADRB10")
    @ResponseWrapper(localName = "hashSignedAttribADRB10Response", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.HashSignedAttribADRB10Response")
    public String hashSignedAttribADRB10(
        @WebParam(name = "origHashb64", targetNamespace = "")
        String origHashb64,
        @WebParam(name = "signingTime", targetNamespace = "")
        XMLGregorianCalendar signingTime,
        @WebParam(name = "x509", targetNamespace = "")
        String x509)
        throws Exception_Exception
    ;

    /**
     * 
     * @param psb64
     * @param signCmsb64
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateSignatureByPolicy", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ValidateSignatureByPolicy")
    @ResponseWrapper(localName = "validateSignatureByPolicyResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ValidateSignatureByPolicyResponse")
    public boolean validateSignatureByPolicy(
        @WebParam(name = "signCmsb64", targetNamespace = "")
        String signCmsb64,
        @WebParam(name = "psb64", targetNamespace = "")
        String psb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signingTime
     * @param origHashb64
     * @param certb64
     * @param signB64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "composeEnvelopeADRB10", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ComposeEnvelopeADRB10")
    @ResponseWrapper(localName = "composeEnvelopeADRB10Response", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ComposeEnvelopeADRB10Response")
    public String composeEnvelopeADRB10(
        @WebParam(name = "signB64", targetNamespace = "")
        String signB64,
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64,
        @WebParam(name = "origHashb64", targetNamespace = "")
        String origHashb64,
        @WebParam(name = "signingTime", targetNamespace = "")
        XMLGregorianCalendar signingTime)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signingTime
     * @param origHashb64
     * @param certb64
     * @param signB64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "composeEnvelopeADRB21", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ComposeEnvelopeADRB21")
    @ResponseWrapper(localName = "composeEnvelopeADRB21Response", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ComposeEnvelopeADRB21Response")
    public String composeEnvelopeADRB21(
        @WebParam(name = "signB64", targetNamespace = "")
        String signB64,
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64,
        @WebParam(name = "origHashb64", targetNamespace = "")
        String origHashb64,
        @WebParam(name = "signingTime", targetNamespace = "")
        XMLGregorianCalendar signingTime)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signCmsb64
     * @return
     *     returns bluecrystal.service.v1.icpbr.SignCompare
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignCompare", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignCompare")
    @ResponseWrapper(localName = "extractSignCompareResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignCompareResponse")
    public SignCompare extractSignCompare(
        @WebParam(name = "signCmsb64", targetNamespace = "")
        String signCmsb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signCmsb64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignerCert", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignerCert")
    @ResponseWrapper(localName = "extractSignerCertResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignerCertResponse")
    public String extractSignerCert(
        @WebParam(name = "signCmsb64", targetNamespace = "")
        String signCmsb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param certb64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertSubject", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.GetCertSubject")
    @ResponseWrapper(localName = "getCertSubjectResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.GetCertSubjectResponse")
    public String getCertSubject(
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param certb64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertSubjectCn", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.GetCertSubjectCn")
    @ResponseWrapper(localName = "getCertSubjectCnResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.GetCertSubjectCnResponse")
    public String getCertSubjectCn(
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param certb64
     * @return
     *     returns java.util.List<bluecrystal.service.v1.icpbr.NameValue>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parseCertificate", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ParseCertificate")
    @ResponseWrapper(localName = "parseCertificateResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ParseCertificateResponse")
    public List<NameValue> parseCertificate(
        @WebParam(name = "certb64", targetNamespace = "")
        String certb64)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sign
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extractSignature", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignature")
    @ResponseWrapper(localName = "extractSignatureResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ExtractSignatureResponse")
    public String extractSignature(
        @WebParam(name = "sign", targetNamespace = "")
        String sign)
        throws Exception_Exception
    ;

    /**
     * 
     * @param signingTime
     * @param origHashb64
     * @param verifyCrlOcsp
     * @param signCmsb64
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateSign", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ValidateSign")
    @ResponseWrapper(localName = "validateSignResponse", targetNamespace = "http://icpbr.v1.service.bluecrystal/", className = "bluecrystal.service.v1.icpbr.ValidateSignResponse")
    public boolean validateSign(
        @WebParam(name = "signCmsb64", targetNamespace = "")
        String signCmsb64,
        @WebParam(name = "origHashb64", targetNamespace = "")
        String origHashb64,
        @WebParam(name = "signingTime", targetNamespace = "")
        XMLGregorianCalendar signingTime,
        @WebParam(name = "verifyCrlOcsp", targetNamespace = "")
        boolean verifyCrlOcsp)
        throws Exception_Exception
    ;

}
