package br.gov.jfrj.siga.sr.model;

public enum SrSubTipoConfiguracao {

	DESIGNACAO_PRE_ATENDENTE, 
	DESIGNACAO_ATENDENTE, 
	DESIGNACAO_POS_ATENDENTE, 
	DESIGNACAO_PESQUISA_SATISFACAO, 

	ACORDO_PRAZO_PRE_ATENDENTE,
	ACORDO_PRAZO_ATENDENTE
}
