
CREATE TABLE "SIGASR"."SR_PESQUISA"
	(
		"ID_PESQUISA" NUMBER(19,0) NOT NULL,
		"HIS_ATIVO"            NUMBER(10,0),
		"HIS_DT_FIM" TIMESTAMP (6),
		"HIS_DT_INI" TIMESTAMP (6) NOT NULL,
		"HIS_ID_INI"               NUMBER(19,0),
		"NOME_PESQUISA" VARCHAR2(255 CHAR) NOT NULL,
		"DESCR_PESQUISA"  VARCHAR2(255 CHAR),
		PRIMARY KEY ("ID_PESQUISA")
	);
CREATE SEQUENCE SR_PESQUISA_SEQ;

CREATE TABLE "SIGASR"."SR_TIPO_PERGUNTA"
	(
		"ID_TIPO_PERGUNTA" NUMBER(19,0) NOT NULL,
		"NOME_TIPO_PERGUNTA" VARCHAR2(255 CHAR) NOT NULL,
		"DESCR_TIPO_PERGUNTA"  VARCHAR2(255 CHAR),
		PRIMARY KEY ("ID_TIPO_PERGUNTA")
	);
	
CREATE TABLE "SIGASR"."SR_PERGUNTA"
	(
		"ID_PERGUNTA" NUMBER(19,0) NOT NULL,
		"HIS_ATIVO"            NUMBER(10,0),
		"HIS_DT_FIM" TIMESTAMP (6),
		"HIS_DT_INI" TIMESTAMP (6) NOT NULL,
		"HIS_ID_INI"               NUMBER(19,0),
		"DESCR_PERGUNTA"  VARCHAR2(255 CHAR),
		"ORDEM_PERGUNTA"      NUMBER(19,0),
		"ID_TIPO_PERGUNTA" NUMBER(19,0) NOT NULL,
		"ID_PESQUISA" NUMBER(19,0),
		PRIMARY KEY ("ID_PERGUNTA"),
		CONSTRAINT "PERGUNTA_PESQUISA_FK" 
			FOREIGN KEY ("ID_PESQUISA") 
			REFERENCES "SIGASR"."SR_PESQUISA" ("ID_PESQUISA"),
		CONSTRAINT "PERGUNTA_TIPO_FK" 
			FOREIGN KEY ("ID_TIPO_PERGUNTA") 
			REFERENCES "SIGASR"."SR_TIPO_PERGUNTA" ("ID_TIPO_PERGUNTA")
	);
CREATE SEQUENCE SR_PERGUNTA_SEQ;
