
alter session set current_schema = corporativo;

insert into corporativo.cp_servico(id_servico, sigla_servico, desc_servico, id_servico_pai, id_tp_servico) values (corporativo.cp_servico_seq.nextval, 'SIGA-SR-EDTCONH', 'Criar Conhecimentos', (select id_servico from corporativo.cp_servico where sigla_servico = 'SIGA-SR'), 2);
commit;

alter session set current_schema = sigasr;

alter table SR_SOLICITACAO ADD (
  "ID_DESIGNACAO" NUMBER(19,0),
  FOREIGN KEY ("ID_DESIGNACAO")
	  REFERENCES "SIGASR"."SR_CONFIGURACAO" ("ID_CONFIGURACAO_SR") ENABLE
);
alter table SR_MOVIMENTACAO ADD (
  "ID_DESIGNACAO" NUMBER(19,0),
  FOREIGN KEY ("ID_DESIGNACAO")
	  REFERENCES "SIGASR"."SR_CONFIGURACAO" ("ID_CONFIGURACAO_SR") ENABLE
);

alter session set current_schema = corporativo;
grant references on dp_pessoa to sigasr;
grant references on dp_lotacao to sigasr;
grant references on cp_complexo to sigasr;
grant references on cp_orgao_usuario to sigasr;
alter session set current_schema = sigasr;

alter table sr_solicitacao add(
	"ID_TITULAR" NUMBER(19,0), 
	"ID_LOTA_TITULAR" NUMBER(19,0),
  FOREIGN KEY ("ID_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_CADASTRANTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_CADASTRANTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_SOLICITANTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_SOLICITANTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_INTERLOCUTOR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_COMPLEXO")
	  REFERENCES "CORPORATIVO"."CP_COMPLEXO" ("ID_COMPLEXO") ENABLE,
  FOREIGN KEY ("ID_ORGAO_USU")
	  REFERENCES "CORPORATIVO"."CP_ORGAO_USUARIO" ("ID_ORGAO_USU") ENABLE
);
alter table sr_movimentacao add(
	"ID_TITULAR" NUMBER(19,0), 
	"ID_LOTA_TITULAR" NUMBER(19,0),
  FOREIGN KEY ("ID_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_TITULAR")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_CADASTRANTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_CADASTRANTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_PESSOA" ("ID_PESSOA") ENABLE,
  FOREIGN KEY ("ID_LOTA_ATENDENTE")
	  REFERENCES "CORPORATIVO"."DP_LOTACAO" ("ID_LOTACAO") ENABLE,
  FOREIGN KEY ("ID_ACAO")
	  REFERENCES "SIGASR"."SR_ACAO" ("ID_ACAO") ENABLE, 
  FOREIGN KEY ("ID_ITEM_CONFIGURACAO")
	  REFERENCES "SIGASR"."SR_ITEM_CONFIGURACAO" ("ID_ITEM_CONFIGURACAO") ENABLE, 
  FOREIGN KEY ("ID_SOLICITACAO_REFERENCIA")
	  REFERENCES "SIGASR"."SR_SOLICITACAO" ("ID_SOLICITACAO") ENABLE, 
  FOREIGN KEY ("ID_MOV_FINALIZADORA")
	  REFERENCES "SIGASR"."SR_MOVIMENTACAO" ("ID_MOVIMENTACAO") ENABLE
);


alter table sigasr.sr_movimentacao drop (
  DT_INI_AGENDAMENTO, HOR_INI_AGENDAMENTO
);
alter table sigasr.sr_configuracao drop (
  FORMA_ACOMPANHAMENTO, GRAVIDADE, TENDENCIA, URGENCIA, SLA_PRE_ATENDIMENTO_QUANT, ID_UNIDADE_PRE_ATENDIMENTO, SLA_ATENDIMENTO_QUANT, ID_UNIDADE_ATENDIMENTO, SLA_POS_ATENDIMENTO_QUANT, ID_UNIDADE_POS_ATENDIMENTO, MARGEM_SEGURANCA, OBSERVACAO_SLA, FG_DIVULGAR_SLA, FG_NOTIFICAR_GESTOR, FG_NOTIFICAR_SOLICITANTE, FG_NOTIFICAR_CADASTRANTE, FG_NOTIFICAR_INTERLOCUTOR, FG_NOTIFICAR_ATENDENTE
);
