ALTER SESSION SET CURRENT_SCHEMA = sigasr;

-- OS_FS0006 Itens 3: Alterando a tabela SR_ITEM_CONFIGURACAO para conter um novo campo
ALTER TABLE SR_ITEM_CONFIGURACAO ADD (
	DESCR_SIMILARIDADE CLOB
); 

-- OS_FS0006 Item 3: Criando tabela SR_GESTOR_ITEM para os Gestores do Item de Configuração
CREATE TABLE SR_GESTOR_ITEM (
	ID_GESTOR_ITEM NUMBER(19, 0) NOT NULL, 
	ID_PESSOA NUMBER(19, 0), 
	ID_LOTACAO NUMBER(19, 0), 
	ID_ITEM_CONFIGURACAO NUMBER(19, 0) NOT NULL, 
	CONSTRAINT SR_GESTOR_ITEM_PK PRIMARY KEY (ID_GESTOR_ITEM) ENABLE 
);

-- Sequence para a tabela SR_GESTOR_ITEM
CREATE SEQUENCE SR_GESTOR_ITEM_SEQ 
	INCREMENT BY 1
	MAXVALUE 9999999999999999999999999999 
	MINVALUE 1 
	CACHE 20;