/*******************************************************************************
 * Copyright (c) 2006 - 2011 SJRJ.
 * 
 *     This file is part of SIGA.
 * 
 *     SIGA is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     SIGA is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with SIGA.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package br.gov.jfrj.siga;

import java.util.ArrayList;

import junit.framework.TestCase;

import org.bouncycastle.util.encoders.Base64;

public class ServiceTest extends TestCase {

	private static byte[] PKCS7 = Base64
			.decode("MIIRcgYJKoZIhvcNAQcCoIIRYzCCEV8CAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHAaCCEBwwggQ4MIIDIKADAgECAgEVMA0GCSqGSIb3DQEBBQUAMIG0MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE9MDsGA1UECxM0SW5zdGl0dXRvIE5hY2lvbmFsIGRlIFRlY25vbG9naWEgZGEgSW5mb3JtYWNhbyAtIElUSTERMA8GA1UEBxMIQnJhc2lsaWExCzAJBgNVBAgTAkRGMTEwLwYDVQQDEyhBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhMB4XDTA1MTIxOTEzMDAwMFoXDTExMDYxOTIzNTkwMFowUDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxLDAqBgNVBAMTI0F1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxl2KdITcvLfbf+j1CGahfGPnytXzybyc3OUE+Ozzh1IHie9phPALBm1uGT40RsLOzzJ0Mvkm95g2og/WwG2rFXP6d8R0MdVZ3Am4/Ctf6rn7OS/3UL+dQN++nplwqHa58Z4B0jpiMOKqI8kvzBTE53hb8oBt6OnrLKe7pfe5QVorjOIESxNXlbBKeiHnr0pImgMavUbJ6j/YOLjxR0BPd4R6ZbyXnoafCddf5nAMrA8yniufier2f7tVTGU+uij7ER7c5Q17yJVd+1EuNOnmeu+RczAn+Dw+7cKmxBQmAOX8ZGm5QIHRNvhz3NVWq74NNOgTK3JXjtXEnAs4VLvp6wIDAPe/o4G3MIG0MD0GA1UdHwQ2MDQwMqAwoC6GLGh0dHA6Ly9hY3JhaXouaWNwYnJhc2lsLmdvdi5ici9MQ1JhY3JhaXouY3JsMBIGA1UdIAQLMAkwBwYFYEwBARMwHQYDVR0OBBYEFL452trBdyXgrr0azqRbn8B6YPxlMB8GA1UdIwQYMBaAFIr68VeEERM1kEL6V0lUaQ2kxPA3MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQC7bYQkwhyTpDkT+mIDcjbr4mMKHK7BThQ5Z2TUbGonYCIjXU1muOgQdzxbSAVMpkUVrLDAFlhWoe9ZqjuLJEIMJeLiraJWc90Dcakym4zr0TZrmx+Ufld3hVSgulujN2KjqGqNFIKFfjsyIga74HZvQO+16N0giGQSWcjbLKxrQWE/tp+qqv8WMfhnWcMXF8k8g9Df676dUgIgYXsXH9EJ58jGjv7X/t7gg+w52AJomewATfEqvW3PyYL5Z3xZHyJ55bBwQO3t+tXW9cdJ6oDyfRDBo1Z9id4NaqSVyvtn1npu7oHJB8dEXpX9tIWnDqdmRgdmzsk7fD7fCbIm9ztOMIIFlTCCBH2gAwIBAgISMjAwNjA0MDcxNTM2NDYwMDAxMA0GCSqGSIb3DQEBBQUAMFAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMSwwKgYDVQQDEyNBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYTAeFw0wNjA0MDcxNTUzMzZaFw0xMTA1MzExNTUzMzZaMHAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTUwMwYDVQQLEyxBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYSAtIEFDLUpVUzEVMBMGA1UEAxMMQUMgQ0FJWEEtSlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPeks/OhVO9rsPjWGLmx0wb0B5MfDsOsoEOsnO/Yh6jAiJ0Br+fUCAIWq0ehN4AWMuiemNvGdJRqJW2I42ME5WPfgPgYNMLQAopooipRo9S8C0BJm1ci0ATXbDvp68lsBHFVlo1ZmyQttnz7Vb1Mlruq6S5u6seezp2zSTFjVwzp9XVaYnutz1uD1IeCEPIdkgBRTlXP95JjacX6xnG7g2hZ2DvY1E8wqNZqyyQB/qyQf1gQj7z93g51d5C1FUCSVQRarwI3zEQhfi5UrhACi4wZdBsNzk7GlTLcgKLKvxNLyPG804qj8hEeOUuc5FTU1visVIeNnknAGTxIHJ/DGQIDAQABo4ICRzCCAkMwEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBS+OdrawXcl4K69Gs6kW5/AemD8ZTAdBgNVHQ4EFgQUDNDX/gMFm70hiQQ/Esavo6rXni4wDgYDVR0PAQH/BAQDAgEGMIIBnwYDVR0gBIIBljCCAZIwQQYGYEwBAgEWMDcwNQYIKwYBBQUHAgEWKWh0dHA6Ly93d3cuYWNqdXMuZ292LmJyL2FjanVzL2RwY2FqdXMucGRmMEEGBmBMAQICBTA3MDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFjanVzLmdvdi5ici9hY2p1cy9kcGNhanVzLnBkZjBBBgZgTAECAxMwNzA1BggrBgEFBQcCARYpaHR0cDovL3d3dy5hY2p1cy5nb3YuYnIvYWNqdXMvZHBjYWp1cy5wZGYwQQYGYEwBAmUFMDcwNQYIKwYBBQUHAgEWKWh0dHA6Ly93d3cuYWNqdXMuZ292LmJyL2FjanVzL2RwY2FqdXMucGRmMEEGBmBMAQJmBDA3MDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFjanVzLmdvdi5ici9hY2p1cy9kcGNhanVzLnBkZjBBBgZgTAECZwYwNzA1BggrBgEFBQcCARYpaHR0cDovL3d3dy5hY2p1cy5nb3YuYnIvYWNqdXMvZHBjYWp1cy5wZGYwOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL3d3dy5hY2p1cy5nb3YuYnIvYWNqdXMvYWNqdXN2MS5jcmwwDQYJKoZIhvcNAQEFBQADggEBAHJhUoT96zSCDM68Gc7u40gotmTFoxN3JFIBOhi7aO2qABGdyRTJUq4+LzwGXk0BljF4G+sMpBZRAuy2a3sfPYFQggnK2iMlacRaLMkxjxhYEAMvUTptatQvsyqJAZHh/a9VKwpv98b6y1N1ZzRxQaof55w/aC5YrCzal8gUSl6qJOeDF9nbarbN7FT2B5NpE34hOfLctuJG8WKr4nF4eRQR8baxpiBeYaAQAK0TZ14JCLipeAnivAoR+7OsIT9gk6JF+C2fQDkAWd/GX+PPsnSGJvUntoz/CKCkL+YS/e1kh3EqUMEXYmTKZm9lwDpzZSPVdpRieCqQNtcjXm5R2L8wggZDMIIFK6ADAgECAgRENcU5MA0GCSqGSIb3DQEBBQUAMHAxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTUwMwYDVQQLEyxBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYSAtIEFDLUpVUzEVMBMGA1UEAxMMQUMgQ0FJWEEtSlVTMB4XDTA5MDMxMjE5MzE1OVoXDTExMDUzMTE1NTMzNlowgdIxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTUwMwYDVQQLEyxBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZGEgSnVzdGljYSAtIEFDLUpVUzEkMCIGA1UECxMbQ2VydC1KVVMgSW5zdGl0dWNpb25hbCAtIEEzMQ0wCwYDVQQLEwRTSlJKMREwDwYDVQQLEwhTZXJ2aWRvcjEvMC0GA1UEAxMmUkVOQVRPIERPIEFNQVJBTCBDUklWQU5PIE1BQ0hBRE86MTM2MzUwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAN0PmwRfC5lAmzhJGv/s6rt9g6czWV7OfkkhaXVwDUfhUtXyM9DkM4Hwcp/5HimKJaJbb2HMqNC53nFbqm0tfbm4YTixbmU/SCw0H35nf2gP36zMQrnlScJTDCd3ToWi0otsa43/d7k/1YvR6pcogL8fjhoIl9oCpY/B9/3PleN/AgMBAAGjggMEMIIDADAOBgNVHQ8BAf8EBAMCBeAwWAYDVR0gBFEwTzBNBgZgTAECAxMwQzBBBggrBgEFBQcCARY1aHR0cDovL2ljcC5jYWl4YS5nb3YuYnIvcmVwb3NpdG9yaW8vZHBjYWNjYWl4YWp1cy5wZGYwKQYDVR0lBCIwIAYIKwYBBQUHAwIGCCsGAQUFBwMEBgorBgEEAYI3FAICMIHQBgNVHREEgcgwgcWBE2NyaXZhbm9AamZyai5qdXMuYnKgPgYFYEwBAwGgNQQzMTYxMjE5NjgwMDQ4OTYyMzc2MDAwMDAwMDAwMDAwMDAwMDAwMDczNTc2MTgzRElDIFJKoDQGBWBMAQMFoCsEKTA3NTU1OTE3MDMwMjAxNjAxNjlSSU8gREUgSkFORUlSTyAgICAgIFJKoBcGBWBMAQMGoA4EDDAwMDAwMDAwMDAwMKAfBgorBgEEAYI3FAIDoBEMD3RhaEBqZnJqLmp1cy5icjCCAU0GA1UdHwSCAUQwggFAMIGuoIGroIGohjJodHRwOi8vaWNwLmNhaXhhLmdvdi5ici9yZXBvc2l0b3Jpby9hY2NhaXhhanVzLmNybIY0aHR0cDovL2ljcDIuY2FpeGEuZ292LmJyL3JlcG9zaXRvcmlvMi9hY2NhaXhhanVzLmNybIY8aHR0cDovL3JlcG9zaXRvcmlvLmljcGJyYXNpbC5nb3YuYnIvbGNyL2NhaXhhL2FjY2FpeGFqdXMuY3JsMIGMoIGJoIGGpIGDMIGAMQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE1MDMGA1UECxMsQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIGRhIEp1c3RpY2EgLSBBQy1KVVMxFTATBgNVBAMTDEFDIENBSVhBLUpVUzEOMAwGA1UEAxMFQ1JMMTIwHwYDVR0jBBgwFoAUDNDX/gMFm70hiQQ/Esavo6rXni4wCQYDVR0TBAIwADAZBgkqhkiG9n0HQQAEDDAKGwRWNy4xAwIDqDANBgkqhkiG9w0BAQUFAAOCAQEART9XAjd7gzObZbRsO/nbE+hgOYIf8tXeD54lMx1niN2nSgr5xAy0WFuwvzHPfquwG1lCQ80irSQYzqdi/l+MlMjGa8R2uBXSSCSCG7YNk4tuMF+zO3EdrnvUdyp2wpZ9si2hz5q4ybVHRxTgKCBtg3AIZrv2Q+TDEM3UbXop6cjtHACx6Og+RA2+V1+B6JF1XYRpSAt5yDZrP5SdPlG/mxnWeILWcbSoJ1KGxuj5VbPotCyLAv/kZsobzhmE6TSgWjL3j0mVk1xbiatClH9TzCLiQVGtzx5GX67ZbdpyjXWfS23e8y3Y8wime15yQ6efLeBcstizkmFw+PsrCBw62TGCAR4wggEaAgEBMHgwcDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNTAzBgNVBAsTLEF1dG9yaWRhZGUgQ2VydGlmaWNhZG9yYSBkYSBKdXN0aWNhIC0gQUMtSlVTMRUwEwYDVQQDEwxBQyBDQUlYQS1KVVMCBEQ1xTkwCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASBgMKfa3Yg7qz03gzd8YVm2nmSNWLv6cgyvUAV4zUWQczij5klyZ+QW1r+PAB6zWW0Nb+126K55YANsI1G+PLNnAsPYQ60JOIor0MrpXWl+VyyMNrCW3xxhx0DIpwBj3JEaJqPe0+ImNIXiOL3cneVOUBWIEgRWva6cP0+3TBwAi5u");

	public void testCriarInstanciaDeProcesso() throws Exception {
		ArrayList<String> keys = new ArrayList<String>();
		ArrayList<String> values = new ArrayList<String>();
		{ // Adiciona no contexto a via Geral
			keys.add("doc_document");
			values.add("RJ-MEM-2007/00595-A");
		}
		for (int n = 0; n < 3; n++) { // Adiciona no contexto a via 'n'
			keys.add("doc_" + (char) ('a' + n));
			values.add("RJ-MEM-2007/00595" + "-" + (char) ('A' + n));
		}
		Service.getWfService().criarInstanciaDeProcesso("testeNovo",
				"RJ13635@RJSESIE", "RJ13635@RJSESIE", keys, values);
	}

	public void testTransferir() throws Exception {
		assertTrue(Service.getExService().isAssinado("RJ-MEM-2007/00595-A",
				"RJ13635@RJSESIE"));

		// Service.getExService().transferir("RJ-MEM-2007/00595-A", "@RJSESIE",
		// "RJ13635@RJSESIE");
	}

	public void testRecuperarCPF() {
		String sCPF = Service.getCdService().recuperarCPF(PKCS7);

		assertEquals(sCPF, "00489623760");
	}
}
