-------------------------------------------
--	SCRIPT:REVISAR E OUTROS
-------------------------------------------

insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR, DESCR_MARCADOR, ID_TP_MARCADOR) VALUES (36,'Ativo',1);
insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR, DESCR_MARCADOR, ID_TP_MARCADOR) VALUES (37,'Novo',1);
insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR, DESCR_MARCADOR, ID_TP_MARCADOR) VALUES (38,'Popular',1);
insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR, DESCR_MARCADOR, ID_TP_MARCADOR) VALUES (39,'Revisar',1);
insert into CORPORATIVO.CP_MARCADOR (ID_MARCADOR, DESCR_MARCADOR, ID_TP_MARCADOR) VALUES (40,'Tomar Ciência',1);