-------------------------------------------
--	SCRIPT:IDX DEADLOCK
-------------------------------------------

alter session set current_schema=SIGA;
create index IXCF_DOC_CP_ORGAO_DEST_FK on EX_DOCUMENTO(ID_ORGAO_DESTINATARIO);
create index IXCF_DOC_CP_ORGAO_FK on EX_DOCUMENTO(ID_ORGAO);
create index IXCF_DOC_TITULAR_PESSOA_FK on EX_DOCUMENTO(ID_TITULAR);
create index IXCF_DOC_CADASTRANTE_PESSOA_FK on EX_DOCUMENTO(ID_CADASTRANTE);
create index IXCF_DOC_SUBSCRITOR_PESSOA_FK on EX_DOCUMENTO(ID_SUBSCRITOR);
create index IXCF_DOC_NIVEL_ACESSO_FK on EX_DOCUMENTO(ID_NIVEL_ACESSO);
create index IXCF_DOC_CLASSIFICACAO_FK on EX_DOCUMENTO(ID_CLASSIFICACAO);
create index IXCF_DOC_LOTA_TIT_LOTACAO_FK on EX_DOCUMENTO(ID_LOTA_TITULAR);
create index IXCF_DOCUMENTO_MODELO_FK on EX_DOCUMENTO(ID_MOD);
create index IXCF_MOV_DP_LOTA_SIN_CAD_FK on EX_MOVIMENTACAO(ID_LOTA_CADASTRANTE);
create index IXCF_MOV_DP_LOTA_SIN_SUB_FK on EX_MOVIMENTACAO(ID_LOTA_SUBSCRITOR);
create index IXCF_MOV_DP_PESSOA_SIN_CAD_FK on EX_MOVIMENTACAO(ID_CADASTRANTE);
create index IXCF_MOV_DP_PESSOA_SIN_SUB_FK on EX_MOVIMENTACAO(ID_SUBSCRITOR);
create index IXCF_MOV_ORGAO_FK on EX_MOVIMENTACAO(ID_ORGAO);
create index IXCF_MOV_NIVEL_ACESSO_FK on EX_MOVIMENTACAO(ID_NIVEL_ACESSO);
create index IXCF_MOV_MOV_CANCELADA_FK on EX_MOVIMENTACAO(ID_MOV_CANCELADORA);
create index IXCF_MOV_DEST_FIM_LOTA_FK on EX_MOVIMENTACAO(ID_LOTA_DESTINO_FINAL);
create index IXCF_MOV_DEST_FIM_PESSOA_FK on EX_MOVIMENTACAO(ID_DESTINO_FINAL);
create index IXCF_MOV_DOC_FK on EX_MOVIMENTACAO(ID_DOC);
create index IXCF_MOV_DOC_PAI_FK on EX_MOVIMENTACAO(ID_DOC_PAI);
create index IXCF_MOV_DOC_REF_FK on EX_MOVIMENTACAO(ID_DOC_REF);
create index IXCF_MOV_ESTADO_DOC_FK on EX_MOVIMENTACAO(ID_ESTADO_DOC);
create index IXCF_MOV_LOTA_TIT_LOTA_FK on EX_MOVIMENTACAO(ID_LOTA_TITULAR);
create index IXCF_MOV_PESSOA_RESP_FK on EX_MOVIMENTACAO(ID_RESP);
create index IXCF_MOV_TITULAR_PESSOA_FK on EX_MOVIMENTACAO(ID_TITULAR);
create index IXCF_MOV_TP_DESPACHO_FK on EX_MOVIMENTACAO(ID_TP_DESPACHO);
create index IXCF_MOV_TP_MOV_FK on EX_MOVIMENTACAO(ID_TP_MOV);
create index IXCF_SYS_C009983 on EX_MOVIMENTACAO(ID_PAPEL);