--PROIBICAO DE CRIAR DOCUMENTOS UTILIZADOS PELO SISTEMA
  --(Certidao de desentranhamento)
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,HIS_IDC_INI) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval,sysdate,'2','2','1');
Insert into SIGA.EX_CONFIGURACAO (ID_CONFIGURACAO_EX,ID_MOD) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.currval,(SELECT ID_MOD FROM SIGA.EX_MODELO WHERE NM_MOD = 'Certidão de desentranhamento' AND HIS_ATIVO = 1));

  --(Certidao de encerramento de volume)
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,HIS_IDC_INI) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.nextval,sysdate,'2','2','1');
Insert into SIGA.EX_CONFIGURACAO (ID_CONFIGURACAO_EX,ID_MOD) values (CORPORATIVO.CP_CONFIGURACAO_SEQ.currval,(SELECT ID_MOD FROM SIGA.EX_MODELO WHERE NM_MOD = 'Certidão de encerramendo de volume' AND HIS_ATIVO = 1));
