-------------------------------------------
--	SCRIPT:CLASS DOC
-------------------------------------------

--EX_CLASSIFICACAO
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD (HIS_IDC_INI NUMBER);
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD (HIS_IDC_FIM NUMBER);
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD (HIS_ATIVO NUMBER);
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD (CODIFICACAO VARCHAR2(11));

ALTER TABLE SIGA.EX_CLASSIFICACAO RENAME COLUMN ID_REG_INI TO HIS_ID_INI;
ALTER TABLE SIGA.EX_CLASSIFICACAO RENAME COLUMN DT_INI_REG TO HIS_DT_INI;
ALTER TABLE SIGA.EX_CLASSIFICACAO RENAME COLUMN DT_FIM_REG TO HIS_DT_FIM;
ALTER TABLE SIGA.EX_CLASSIFICACAO RENAME COLUMN FACILITADOR_CLASS TO OBS;

COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.HIS_IDC_INI IS 'ID da identidade da pessoa que criou o registro';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.HIS_IDC_FIM IS 'ID da identidade da pessoa que finalizou o registro';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.CODIFICACAO IS 'Código formatado da classificação documental';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.OBS IS 'Observação da classificação documental';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.HIS_ID_INI IS 'ID do primeiro registro da série histórica';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.HIS_DT_INI IS 'Data de início do registro';
COMMENT ON COLUMN SIGA.EX_CLASSIFICACAO.HIS_DT_FIM IS 'Data de finalização do registro';


--EX_VIA
ALTER TABLE SIGA.EX_VIA ADD (HIS_IDC_INI NUMBER);
ALTER TABLE SIGA.EX_VIA ADD (HIS_IDC_FIM NUMBER);
ALTER TABLE SIGA.EX_VIA ADD (HIS_ATIVO NUMBER);


ALTER TABLE SIGA.EX_VIA RENAME COLUMN ID_TMP_CORRENTE TO ID_TEMPORAL_ARQ_COR;
ALTER TABLE SIGA.EX_VIA RENAME COLUMN ID_TMP_INTERMEDIARIO TO ID_TEMPORAL_ARQ_INT;
ALTER TABLE SIGA.EX_VIA RENAME COLUMN ID_TP_DESTINACAO TO ID_DESTINACAO;
ALTER TABLE SIGA.EX_VIA RENAME COLUMN ID_REG_INI TO HIS_ID_INI;
ALTER TABLE SIGA.EX_VIA RENAME COLUMN DT_INI_REG TO HIS_DT_INI;
ALTER TABLE SIGA.EX_VIA RENAME COLUMN DT_FIM_REG TO HIS_DT_FIM;

COMMENT ON COLUMN SIGA.EX_VIA.HIS_IDC_INI IS 'ID da identidade da pessoa que criou o registro';
COMMENT ON COLUMN SIGA.EX_VIA.HIS_IDC_FIM IS 'ID da identidade da pessoa que finalizou o registro';
COMMENT ON COLUMN SIGA.EX_VIA.HIS_ID_INI IS 'ID do primeiro registro da série histórica';
COMMENT ON COLUMN SIGA.EX_VIA.HIS_DT_INI IS 'Data de início do registro';
COMMENT ON COLUMN SIGA.EX_VIA.HIS_DT_FIM IS 'Data de finalização do registro';


--EX_TIPO_DESTINACAO

--RENAME EX_TIPO_DESTINACAO TO EX_DESTINACAO;

--EX_TEMPORALIDADE

ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (VALOR_TEMPORALIDADE NUMBER);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (ID_UNIDADE_MEDIDA NUMBER);

ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_ID_INI NUMBER);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_DT_INI DATE);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_DT_FIM DATE);

ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_IDC_INI NUMBER);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_IDC_FIM NUMBER);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD (HIS_ATIVO NUMBER);

--EX_MODELO
ALTER TABLE SIGA.EX_MODELO ADD (HIS_ID_INI NUMBER);
ALTER TABLE SIGA.EX_MODELO ADD (HIS_DT_INI DATE);
ALTER TABLE SIGA.EX_MODELO ADD (HIS_DT_FIM DATE);

ALTER TABLE SIGA.EX_MODELO ADD (HIS_IDC_INI NUMBER);
ALTER TABLE SIGA.EX_MODELO ADD (HIS_IDC_FIM NUMBER);
ALTER TABLE SIGA.EX_MODELO ADD (HIS_ATIVO NUMBER);

--ATUALIZACAO DE DADOS
UPDATE SIGA.EX_CLASSIFICACAO SET his_ativo = 0 WHERE his_dt_fim IS NOT NULL;
UPDATE SIGA.EX_CLASSIFICACAO SET his_ativo = 1 WHERE his_dt_fim IS NULL;

--SCRIPT PARA CONVERTER OS DADOS PARA NOVO FORMATO

DECLARE
  CURSOR TODAS_CLASSIFICACOES IS SELECT * FROM SIGA.EX_CLASSIFICACAO ORDER BY ID_CLASSIFICACAO;
BEGIN
  DBMS_OUTPUT.ENABLE(100000);
  
  FOR EX_CLASS IN TODAS_CLASSIFICACOES LOOP
      --dbms_output.put_line( 'ID_CLASSIFICACAO: ' || EX_CLASS.id_classificacao || ' CLASS:' || to_char(EX_CLASS.cod_assunto,'FM00') || '.' || to_char(EX_CLASS.cod_classe,'FM00') || '.' || to_char(EX_CLASS.cod_subclasse,'FM00') || '.' || to_char(EX_CLASS.cod_atividade,'FM00'));
      IF EX_CLASS.COD_ASSUNTO IS NOT NULL THEN
             UPDATE SIGA.EX_CLASSIFICACAO CLA SET CODIFICACAO = to_char(EX_CLASS.cod_assunto,'FM00') || '.' || to_char(EX_CLASS.cod_classe,'FM00') || '.' || to_char(EX_CLASS.cod_subclasse,'FM00') || '.' || to_char(EX_CLASS.cod_atividade,'FM00') WHERE cla.id_classificacao = EX_CLASS.ID_CLASSIFICACAO;
      END IF ;
      IF EX_CLASS.COD_ASSUNTO IS NULL THEN
        UPDATE SIGA.EX_CLASSIFICACAO CLA SET CODIFICACAO = to_char(EX_CLASS.cod_assunto_principal,'FM0') || to_char(EX_CLASS.cod_assunto_secundario,'FM0') || '.' || to_char(EX_CLASS.cod_classe,'FM0') || to_char(EX_CLASS.cod_subclasse,'FM00') || '.' || to_char(EX_CLASS.cod_atividade,'FM00') WHERE cla.id_classificacao = EX_CLASS.ID_CLASSIFICACAO;
      END IF ;
      
  END LOOP ;
END ;
/

--DESATIVA TODAS AS VIAS DAS CLASSIFICACOES DESATIVADAS
UPDATE (select via.his_ativo via_his_ativo,cla.his_ativo cla_his_ativo,via.his_dt_fim via_his_dt_fim,cla.his_dt_fim cla_his_dt_fim from SIGA.ex_via via inner join SIGA.ex_classificacao cla on via.id_classificacao = cla.id_classificacao where via.his_dt_fim is null AND cla.his_dt_fim is not null) set via_his_ativo = cla_his_ativo,via_his_dt_fim=cla_his_dt_fim;

UPDATE SIGA.EX_VIA SET his_ativo = 0 WHERE his_dt_fim IS NOT NULL;
UPDATE SIGA.EX_VIA SET his_ativo = 1 WHERE his_dt_fim IS NULL;

UPDATE SIGA.EX_TEMPORALIDADE SET his_ativo = 1;
UPDATE SIGA.EX_TEMPORALIDADE SET his_id_ini = id_temporalidade where his_id_ini is null;

UPDATE SIGA.EX_MODELO SET his_ativo = 1;
UPDATE SIGA.EX_MODELO SET his_id_ini = id_mod where his_id_ini is null;


--CONSTRAINTS


ALTER TABLE SIGA.EX_CLASSIFICACAO MODIFY (CODIFICACAO NOT NULL);

ALTER TABLE SIGA.EX_CLASSIFICACAO ADD FOREIGN KEY (HIS_IDC_INI) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD FOREIGN KEY (HIS_IDC_FIM) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_CLASSIFICACAO ADD FOREIGN KEY (HIS_ID_INI) REFERENCES SIGA.EX_CLASSIFICACAO(ID_CLASSIFICACAO);
ALTER TABLE SIGA.EX_CLASSIFICACAO MODIFY (HIS_ATIVO NOT NULL);

ALTER TABLE SIGA.EX_VIA ADD FOREIGN KEY (HIS_IDC_INI) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_VIA ADD FOREIGN KEY (HIS_IDC_FIM) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_VIA ADD FOREIGN KEY (HIS_ID_INI) REFERENCES SIGA.EX_VIA(ID_VIA);
ALTER TABLE SIGA.EX_VIA MODIFY (HIS_ATIVO NOT NULL);

ALTER TABLE SIGA.EX_TEMPORALIDADE ADD FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES CORPORATIVO.CP_UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD FOREIGN KEY (HIS_IDC_INI) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_TEMPORALIDADE ADD FOREIGN KEY (HIS_IDC_FIM) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_TEMPORALIDADE MODIFY (HIS_ATIVO NOT NULL);

ALTER TABLE SIGA.EX_MODELO ADD FOREIGN KEY (HIS_IDC_INI) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_MODELO ADD FOREIGN KEY (HIS_IDC_FIM) REFERENCES CORPORATIVO.CP_IDENTIDADE(ID_IDENTIDADE);
ALTER TABLE SIGA.EX_MODELO MODIFY (HIS_ATIVO NOT NULL);


--EXCLUSOES

ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_ASSUNTO_PRINCIPAL;
ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_ASSUNTO_SECUNDARIO;
ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_CLASSE;
ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_SUBCLASSE;
ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_ATIVIDADE;
ALTER TABLE SIGA.EX_CLASSIFICACAO DROP COLUMN COD_ASSUNTO;

ALTER TABLE SIGA.EX_VIA DROP COLUMN FG_MAIOR;

--ALTER TABLE SIGA.EX_TIPO_DESTINACAO DROP COLUMN FACILITADOR_DEST;

ALTER TABLE SIGA.EX_TEMPORALIDADE DROP COLUMN PERMANENCIA_ARQUIVO;





