ALTER TABLE SIGA.EX_FORMA_DOCUMENTO ADD (IS_PERMITEREQUERENTE NUMBER(1,0));

ALTER TABLE SIGA.EX_DOCUMENTO ADD CNPJ_REQUERENTE NUMBER(14,0) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD CPF_REQUERENTE NUMBER(11,0) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD NM_REQUERENTE VARCHAR2(60) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD MATRICULA_REQUERENTE NUMBER(8,0) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD TP_LOGRADOURO_REQUERENTE VARCHAR2(100) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD LOGRADOURO_REQUERENTE VARCHAR2(300) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD NUM_LOGRADOURO_REQUERENTE VARCHAR(100) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD COMPLEMENTO_LOGRADOURO_REQUERENTE VARCHAR2(100) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD BAIRRO_REQUERENTE VARCHAR2(50) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD CIDADE_REQUERENTE VARCHAR2(30) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD UF_REQUERENTE varchar(2) DEFAULT NULL;
ALTER TABLE SIGA.EX_DOCUMENTO ADD CEP_REQUERENTE VARCHAR8) DEFAULT NULL;