--Transferindo os blobs para uma tabela separada 

ALTER TABLE SIGA.EX_MODELO ADD (ID_ARQ number(19,0) NULL);
COMMENT ON COLUMN "SIGA"."EX_MODELO"."ID_ARQ" IS 'Identificador do arquivo';
ALTER TABLE SIGA.EX_MODELO ADD FOREIGN KEY (ID_ARQ) REFERENCES CORPORATIVO.CP_ARQUIVO (ID_ARQ) ENABLE;

ALTER TABLE SIGA.EX_DOCUMENTO ADD (ID_ARQ number(19,0) NULL);
COMMENT ON COLUMN "SIGA"."EX_DOCUMENTO"."ID_ARQ" IS 'Identificador do arquivo';
ALTER TABLE SIGA.EX_DOCUMENTO ADD FOREIGN KEY (ID_ARQ) REFERENCES CORPORATIVO.CP_ARQUIVO (ID_ARQ) ENABLE;

ALTER TABLE SIGA.EX_MOVIMENTACAO ADD (ID_ARQ number(19,0) NULL);
COMMENT ON COLUMN "SIGA"."EX_MOVIMENTACAO"."ID_ARQ" IS 'Identificador do arquivo';
ALTER TABLE SIGA.EX_MOVIMENTACAO ADD FOREIGN KEY (ID_ARQ) REFERENCES CORPORATIVO.CP_ARQUIVO (ID_ARQ) ENABLE;

ALTER TABLE SIGA.EX_PREENCHIMENTO ADD (ID_ARQ number(19,0) NULL);
COMMENT ON COLUMN "SIGA"."EX_PREENCHIMENTO"."ID_ARQ" IS 'Identificador do arquivo';
ALTER TABLE SIGA.EX_PREENCHIMENTO ADD FOREIGN KEY (ID_ARQ) REFERENCES CORPORATIVO.CP_ARQUIVO (ID_ARQ) ENABLE;
