  CREATE TABLE "SIGA"."EX_SEQUENCIA" 
   (	"ID_SEQ" NUMBER(15,0),  
		"ANO_EMISSAO" NUMBER(4,0), 
		"NUMERO" NUMBER(10,0), 
		"NR_INICIAL" NUMBER(15,0) DEFAULT 1, 
		"NR_FINAL" NUMBER(15,0), 
		"FL_ATIVO" CHAR(1 BYTE) DEFAULT 1,
		"TIPO_SEQUENCIA"  NUMBER(2,0),
		"ZERAR_INICIO_ANO" CHAR(1 BYTE) DEFAULT 1
   ) ;
   
   
--------------------------------------------------------
--  DDL for Sequence EX_SEQUENCIA_SEQ
--------------------------------------------------------

  CREATE SEQUENCE  "SIGA"."EX_SEQUENCIA_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;   
--------------------------------------------------------
--  DDL for Index EX_SEQUENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGA"."EX_SEQUENCIA_PK" ON "SIGA"."EX_SEQUENCIA" ("ID_SEQ");

--------------------------------------------------------
--  Constraints for Table EX_SEQUENCIA
--------------------------------------------------------

  ALTER TABLE "SIGA"."EX_SEQUENCIA" ADD CONSTRAINT "EX_SEQUENCIA_PK" PRIMARY KEY ("ID_SEQ");
  ALTER TABLE "SIGA"."EX_SEQUENCIA" MODIFY ("NR_INICIAL" NOT NULL ENABLE);
  ALTER TABLE "SIGA"."EX_SEQUENCIA" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SIGA"."EX_SEQUENCIA" MODIFY ("ANO_EMISSAO" NOT NULL ENABLE);
  ALTER TABLE "SIGA"."EX_SEQUENCIA" MODIFY ("ID_SEQ" NOT NULL ENABLE);

--------------------------------------------------------
--  FINAL DO SCRIPT DE ESTRUTURA
--------------------------------------------------------	  

--ALTER TABLE SIGA.EX_DOCUMENTO DROP COLUMN CHAVE_DOC;

 CREATE TABLE "SIGA"."EX_PROTOCOLO" 
   (	
		"ID_PROTOCOLO" NUMBER(15,0), 
		"ID_DOC" NUMBER(10,0),
		"NUMERO" NUMBER(15,0),		
		"DATA" DATE
   ) ;
   
CREATE SEQUENCE  "SIGA"."EX_PROTOCOLO_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;   

CREATE UNIQUE INDEX "SIGA"."EX_PROTOCOLO_PK" ON "SIGA"."EX_PROTOCOLO" ("ID_PROTOCOLO");

ALTER TABLE "SIGA"."EX_PROTOCOLO" ADD CONSTRAINT "EX_PROTOCOLO_PK" PRIMARY KEY ("ID_PROTOCOLO");

ALTER TABLE "SIGA"."EX_PROTOCOLO" MODIFY ("ID_DOC" NOT NULL ENABLE);
ALTER TABLE "SIGA"."EX_PROTOCOLO" MODIFY ("NUMERO" NOT NULL ENABLE);
ALTER TABLE "SIGA"."EX_PROTOCOLO" MODIFY ("DATA" NOT NULL ENABLE);

ALTER TABLE "SIGA"."EX_DOCUMENTO" ADD (ID_PROTOCOLO NUMBER(15,0));
