Insert into SIGA.EX_TIPO_DOCUMENTO (ID_TP_DOC,DESCR_TIPO_DOCUMENTO) values (4,'Capturado');

Insert into SIGA.EX_FORMA_DOCUMENTO (ID_FORMA_DOC,DESCR_FORMA_DOC,SIGLA_FORMA_DOC,ID_TIPO_FORMA_DOC) values (SIGA.EX_FORMA_DOCUMENTO_SEQ.nextval,'Documento Capturado','CAP',1);

Insert into SIGA.EX_TP_FORMA_DOC (ID_FORMA_DOC,ID_TP_DOC) values (SIGA.EX_FORMA_DOCUMENTO_SEQ.currval,4);