ALTER TABLE SIGA.EX_COMPETENCIA MODIFY (ID_LOTACAO number(10,0));
ALTER TABLE SIGA.EX_DOCUMENTO MODIFY (ID_LOTA_DESTINATARIO number(10,0));
ALTER TABLE SIGA.EX_DOCUMENTO MODIFY (ID_LOTA_SUBSCRITOR number(10,0));
ALTER TABLE SIGA.EX_DOCUMENTO MODIFY (ID_LOTA_CADASTRANTE number(10,0));
ALTER TABLE SIGA.EX_MOVIMENTACAO MODIFY (ID_LOTA_DESTINO_FINAL number(10,0));
ALTER TABLE SIGA.EX_MOVIMENTACAO MODIFY (ID_LOTA_RESP number(10,0));
ALTER TABLE SIGA.EX_MOVIMENTACAO MODIFY (ID_LOTA_SUBSCRITOR number(10,0));
ALTER TABLE SIGA.EX_MOVIMENTACAO MODIFY (ID_LOTA_CADASTRANTE number(10,0));