package models;

public enum SrSubTipoConfiguracao {

	DESIGNACAO_PRE_ATENDENTE, 
	DESIGNACAO_ATENDENTE, 
	DESIGNACAO_POS_ATENDENTE, 
	DESIGNACAO_PESQUISA_SATISFACAO, 
	DESIGNACAO_EQUIPE_QUALIDADE,
	DESIGNACAO_PRAZO_PRE_ATENDENTE,
	DESIGNACAO_PRAZO_ATENDENTE,
	DESIGNACAO_LISTAS_PRIORIDADE
}
