package models;

public enum SrSubTipoConfiguracao {

	DESIGNACAO_PRE_ATENDENTE, 
	DESIGNACAO_ATENDENTE, 
	DESIGNACAO_POS_ATENDENTE, 
	DESIGNACAO_PESQUISA_SATISFACAO, 
	DESIGNACAO_EQUIPE_QUALIDADE

}
