CREATE INDEX CORPORATIVO.CP_TOKEN_ID_REF ON CP_TOKEN (ID_REF);

INSERT INTO CORPORATIVO.CP_TIPO_TOKEN (ID_TP_TOKEN, DESCR_TP_TOKEN) VALUES ('2', 'Token para Reset PIN');
INSERT INTO CORPORATIVO.CP_TIPO_CONFIGURACAO (ID_TP_CONFIGURACAO, DSC_TP_CONFIGURACAO,ID_SIT_CONFIGURACAO) VALUES (208, 'PIN como Segundo Fator de Autenticação',2);
