Insert into corporativo.cp_marcador (ID_MARCADOR,DESCR_MARCADOR,ID_FINALIDADE_MARCADOR,ORD_MARCADOR,GRUPO_MARCADOR,
		ID_COR, ID_ICONE, HIS_ID_INI, HIS_DT_INI, HIS_IDC_INI, HIS_ATIVO, LISTAVEL_PESQUISA_DEFAULT) 
    values ('76','Aguardando Conclusão','1','140','7',
    		null, null, 76, CURRENT_TIMESTAMP, 1, 1, 1);
