CREATE TABLE `dp_notificar_por_email` ( 
  `ID_NOTIFICAR_POR_EMAIL` INT UNSIGNED NOT NULL,
  `NOME_DA_ACAO` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `NAO_CONFIGURAVEL` INT UNSIGNED DEFAULT NULL,
  `CONFIGURAVEL` INT UNSIGNED DEFAULT NULL,
  `DT_FIM_NOTIFICAR_POR_EMAIL` datetime DEFAULT NULL,
  `DT_INI_NOTIFICAR_POR_EMAIL` datetime DEFAULT NULL,
  `ID_NOTIFICAR_POR_EMAIL_INICIAL` INT UNSIGNED DEFAULT NULL,
  `IDE_NOTIFICAR_POR_EMAIL` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HIS_IDC_INI` INT UNSIGNED DEFAULT NULL,
  `HIS_IDC_FIM` INT UNSIGNED DEFAULT NULL,
  `RESTRINGIR` INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`ID_NOTIFICAR_POR_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
 
INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (1, 'Cadastro de novo usuário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (2, 'Alterar minha senha', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (3, 'Esqueci minha senha', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (5, 'Responsável pela assinatura', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (6, 'Conssignatário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (7, 'Substituição', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 1);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (8, 'Documento tramitado para o meu usuário', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (9, 'Documento tramitado para unidade', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (10, 'Tramitação de documentos marcados', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (11, 'Alteração de email', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);

INSERT INTO dp_notificar_por_email (ID_NOTIFICAR_POR_EMAIL, NOME_DA_ACAO, NAO_CONFIGURAVEL, CONFIGURAVEL, DT_FIM_NOTIFICAR_POR_EMAIL, DT_INI_NOTIFICAR_POR_EMAIL, ID_NOTIFICAR_POR_EMAIL_INICIAL, IDE_NOTIFICAR_POR_EMAIL, HIS_IDC_INI, HIS_IDC_FIM, RESTRINGIR) 
VALUES (12, 'Documentos de marcadores', 0, 1, '07/10/21', '26/10/21', 1, 1, 1, 1, 0);