-- PERMISSAO DEFAULT DE ACESSO A TODOS PARA O SERVICO SIGA-WEB DE PESQUISA AVANCADA
Insert into corporativo.cp_configuracao (HIS_DT_INI, ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI)
values (current_timestamp(), '1', '200', (SELECT max(ID_SERVICO) FROM corporativo.cp_servico WHERE SIGLA_SERVICO = 'SIGA-DOC-PESQ'), '1');