-- CADASTRO DE SERVICO SIGA-DOC-RECLALOTE
INSERT INTO CORPORATIVO.CP_SERVICO (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO)
VALUES ('SIGA-DOC-RECLALOTE','RECLASSIFICAR EM LOTE',
        (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC'),'2');

-- PERMISSAO DEFAULT NAO PODE A TODOS PARA O SERVICO SIGA-DOC-RECLALOTE
INSERT INTO CORPORATIVO.CP_CONFIGURACAO (HIS_DT_INI,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,HIS_IDC_INI)
VALUES (current_timestamp(), '2', '200', (SELECT ID_SERVICO FROM CORPORATIVO.CP_SERVICO WHERE SIGLA_SERVICO = 'SIGA-DOC-RECLALOTE'), '1');	