Insert into corporativo.cp_tipo_configuracao (ID_TP_CONFIGURACAO,DSC_TP_CONFIGURACAO,ID_SIT_CONFIGURACAO) values (44,'Delegar Visualização', 2);

ALTER TABLE corporativo.dp_substituicao ADD (TP_SUBSTITUICAO char(1));

CREATE TABLE corporativo.dp_visualizacao 
   (	
    ID_VISUALIZACAO INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	ID_TITULAR INT UNSIGNED, 
	ID_DELEG INT UNSIGNED, 
	DT_INI_DELEG DATE, 
	DT_FIM_DELEG DATE, 
	DT_INI_REG DATE, 
	DT_FIM_REG DATE, 
	ID_REG_INI INT UNSIGNED,
	PRIMARY KEY (ID_VISUALIZACAO)
   ) ;
   
CREATE TABLE corporativo.dp_visualizacao_acesso 
   (	
   	ID_VISUALIZACAO_ACESSO INT UNSIGNED NOT NULL AUTO_INCREMENT,
   	ID_VISUALIZACAO INT UNSIGNED, 
	ID_TITULAR INT UNSIGNED, 
	ID_DELEG INT UNSIGNED, 
	DT_ACESSO DATE, 
	ID_DOC INT UNSIGNED,
	PRIMARY KEY (ID_VISUALIZACAO_ACESSO)
   ) ;
   
