CREATE TABLE `cp_contrato` (
  `ID_ORGAO_USU` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DT_CONTRATO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_ORGAO_USU`),
  KEY `cp_contrato_pk` (`ID_ORGAO_USU`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;