-- SEPARACAO DOS SERVICOS DE EXECUCAO EM LOTE
-- CADASTRO DOS SERVICOS SIGA-DOC-ASSLOTE, SIGA-DOC-RECLOTE, SIGA-DOC-ANOLOTE, SIGA-DOC-ARQLOTE, SIGA-DOC-TRALOTE
Insert into corporativo.cp_servico (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values ('SIGA-DOC-ASSLOTE','Assinar em Lote',
		2,'2');
Insert into corporativo.cp_servico (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values ('SIGA-DOC-ANOLOTE','Anotar em Lote',
		2,'2');
Insert into corporativo.cp_servico (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values ('SIGA-DOC-ARQLOTE','Arquivar em Lote',
		2,'2');
Insert into corporativo.cp_servico (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values ('SIGA-DOC-RECLOTE','Receber em Lote',
		2,'2');
Insert into corporativo.cp_servico (SIGLA_SERVICO,DESC_SERVICO,ID_SERVICO_PAI,ID_TP_SERVICO) 
	values ('SIGA-DOC-TRALOTE','Tramitar em Lote',
		2,'2');

-- FINALIZACAO DAS CONFIGURACOES ANTIGAS SIGA-DOC-TRAMITE-LOTE
UPDATE corporativo.cp_configuracao SET HIS_IDC_FIM=HIS_IDC_INI, HIS_DT_FIM = CURRENT_TIMESTAMP 
    WHERE (HIS_DT_INI IS NULL OR HIS_DT_INI < CURRENT_TIMESTAMP) AND (HIS_DT_FIM  IS NULL OR HIS_DT_FIM > CURRENT_TIMESTAMP)
	  AND ID_TP_CONFIGURACAO = (SELECT ID_TP_CONFIGURACAO FROM corporativo.cp_tipo_configuracao WHERE DSC_TP_CONFIGURACAO = 'Utilizar Serviço')
	  AND ID_SERVICO = (SELECT ID_SERVICO FROM corporativo.cp_servico WHERE SIGLA_SERVICO = 'SIGA-DOC-TRAMITE-LOTE');
