package br.gov.jfrj.siga.cp.model.enm;

public enum CpParamCfg {
	PESSOA, LOTACAO, TIPO_DE_LOTACAO, CARGO, FUNCAO, ORGAO, PERFIL, SERVICO, PESSOA_OBJETO, LOTACAO_OBJETO,
	CARGO_OBJETO, FUNCAO_OBJETO, ORGAO_OBJETO, SITUACAO;
}
