--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Fevereiro-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRUPOVEICULO
--------------------------------------------------------

  CREATE TABLE "SIGATP"."GRUPOVEICULO" 
   (	"ID" NUMBER(19,0), 
	"NOME" VARCHAR2(255 CHAR), 
	"FINALIDADE" VARCHAR2(255 CHAR), 
	"CARACTERISTICAS" VARCHAR2(500 CHAR), 
	"LETRA" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGATP" ;
REM INSERTING into SIGATP.GRUPOVEICULO
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (4,'VEÍCULO DE REPRESENTAÇÃO','TRANSPORTE DOS PRESIDENTES, DOS VICE-PRESIDENTES E DOS
CORREGEDORES DOS TRIBUNAIS REGIONAIS FEDERAIS','VEÍCULOS DE MÉDIO PORTE, TIPO SEDAN, COR PRETA, COM
CAPACIDADE DE TRANSPORTE DE ATÉ 5 (CINCO) PASSAGEIROS, MOTOR DE POTÊNCIA MÍNIMA
DE 116 CV E MÁXIMA DE 159 CV (GASOLINA) E ITENS DE SEGURANÇA CONDIZENTES COM
O SERVIÇO','A');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (5,'VEÍCULO DE TRANSPORTE INSTITUCIONAL','TRANSPORTE, EM OBJETO DE SERVIÇO, DOS JUÍZES DE SEGUNDO GRAU E
DOS JUÍZES DIRETORES DE FORO E DIRETORES DE SUBSEÇÕES JUDICIÁRIAS','VEÍCULOS DE MÉDIO PORTE, TIPO SEDAN, COR PRETA, COM
CAPACIDADE DE TRANSPORTE DE ATÉ 5 (CINCO) PASSAGEIROS, MOTOR DE POTÊNCIA MÍNIMA
DE 116 CV E MÁXIMA DE 159 CV (GASOLINA) E ITENS DE SEGURANÇA CONDIZENTES COM
O SERVIÇO','B');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (6,'VEÍCULO DE SERVIÇO COMUM','TRANSPORTE, EM OBJETO DE SERVIÇO, DE JUÍZES DE PRIMEIRO GRAU E
SERVIDORES NO DESEMPENHO DE ATIVIDADES EXTERNAS DE INTERESSE DA ADMINISTRAÇÃO','VEÍCULOS DE PEQUENO PORTE, COM CAPACIDADE DE ATÉ 5 (CINCO)
OCUPANTES, MOTOR COM POTÊNCIA MÍNIMA DE 80 CV E MÁXIMA DE 112 CV (GASOLINA)
E ITENS DE SEGURANÇA CONDIZENTES COM O SERVIÇO','C');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (7,'VEÍCULO DE TRANSPORTE COLETIVO E DE APOIO ÀS ATIVIDADES','TRANSPORTE, EM OBJETO DE SERVIÇO, DE MAGISTRADOS E SERVIDORES NO','PICK-UPS CABINE DUPLA, VANS COM CAPACIDADE MÍNIMA DE 12
(DOZE) OCUPANTES, MICROÔNIBUS E ÔNIBUS, MOTOR COM POTÊNCIA CONDIZENTE COM O
SERVIÇO','D');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (8,'VEÍCULO DE TRANSPORTE DE CARGA LEVE','TRANSPORTE DE CARGAS LEVES NO DESEMPENHO DE ATIVIDADES EXTERNAS
DE INTERESSE DA ADMINISTRAÇÃO','FURGÕES, PICK-UPS DE CABINE SIMPLES, REBOQUES E SEMIREBOQUES,
MOTOR DE POTÊNCIA CONDIZENTE COM O SERVIÇO','E');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (9,'VEÍCULO DE TRANSPORTE DE CARGA PESADA','TRANSPORTE DE CARGAS PESADAS','VEÍCULOS TIPO CAMINHÃO, MOTOR DE POTÊNCIA CONDIZENTE COM O','F');
Insert into SIGATP.GRUPOVEICULO (ID,NOME,FINALIDADE,CARACTERISTICAS,LETRA) values (10,'VEÍCULO DE SERVIÇO DE APOIO ESPECIAL','ATENDIMENTO, EM CARÁTER DE SOCORRO MÉDICO OU DE APOIO ÀS','AMBULÂNCIAS E VEÍCULOS COM DISPOSITIVO DE ALARME E LUZ','G');
--------------------------------------------------------
--  DDL for Index SYS_C00247774
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGATP"."SYS_C00247774" ON "SIGATP"."GRUPOVEICULO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGATP" ;
--------------------------------------------------------
--  Constraints for Table GRUPOVEICULO
--------------------------------------------------------

  ALTER TABLE "SIGATP"."GRUPOVEICULO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SIGATP"."GRUPOVEICULO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SIGATP"  ENABLE;
 
  ALTER TABLE "SIGATP"."GRUPOVEICULO" MODIFY ("NOME" NOT NULL ENABLE);
