-- TRF
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,DT_FIM_VIG_CONFIGURACAO,HIS_DT_INI,ID_ORGAO_USU,ID_LOTACAO,ID_CARGO,ID_FUNCAO_CONFIANCA,ID_PESSOA,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_GRUPO,NM_EMAIL,DESC_FORMULA,ID_TP_LOTACAO,ID_IDENTIDADE,HIS_IDC_INI,HIS_IDC_FIM,HIS_DT_FIM,HIS_ID_INI,ID_COMPLEXO,ID_ORGAO_OBJETO)
values (corporativo.cp_configuracao_seq.nextval,null,null,sysdate,3,null,null,null,null,'5','400',null,null,null,null,null,null,null,null,null,corporativo.cp_configuracao_seq.currval,'25',null);
-- TRF CCJF
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,DT_FIM_VIG_CONFIGURACAO,HIS_DT_INI,ID_ORGAO_USU,ID_LOTACAO,ID_CARGO,ID_FUNCAO_CONFIANCA,ID_PESSOA,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_GRUPO,NM_EMAIL,DESC_FORMULA,ID_TP_LOTACAO,ID_IDENTIDADE,HIS_IDC_INI,HIS_IDC_FIM,HIS_DT_FIM,HIS_ID_INI,ID_COMPLEXO,ID_ORGAO_OBJETO)
values (corporativo.cp_configuracao_seq.nextval,null,null,sysdate,3,(select id_lotacao from corporativo.dp_lotacao where sigla_lotacao = 'CCJF'),null,null,null,'1','400',null,null,null,null,null,null,null,null,null,corporativo.cp_configuracao_seq.currval,'26',null);
-- JFRJ 
Insert into CORPORATIVO.CP_CONFIGURACAO (ID_CONFIGURACAO,DT_INI_VIG_CONFIGURACAO,DT_FIM_VIG_CONFIGURACAO,HIS_DT_INI,ID_ORGAO_USU,ID_LOTACAO,ID_CARGO,ID_FUNCAO_CONFIANCA,ID_PESSOA,ID_SIT_CONFIGURACAO,ID_TP_CONFIGURACAO,ID_SERVICO,ID_GRUPO,NM_EMAIL,DESC_FORMULA,ID_TP_LOTACAO,ID_IDENTIDADE,HIS_IDC_INI,HIS_IDC_FIM,HIS_DT_FIM,HIS_ID_INI,ID_COMPLEXO,ID_ORGAO_OBJETO)
values (corporativo.cp_configuracao_seq.nextval,null,null,sysdate,1,null,null,null,null,'5','400',null,null,null,null,null,null,null,null,null,corporativo.cp_configuracao_seq.currval,'1',null);

