create sequence CORPORATIVO.SEQ_IDENTIDADE
minvalue 1
maxvalue 9999999999
start with 2
increment by 1
nocache
cycle;

Insert into CORPORATIVO.CP_IDENTIDADE (ID_IDENTIDADE, ID_TP_IDENTIDADE,ID_PESSOA,DATA_CRIACAO_IDENTIDADE,DATA_EXPIRACAO_IDENTIDADE,DATA_CANCELAMENTO_IDENTIDADE,ID_ORGAO_USU,LOGIN_IDENTIDADE,SENHA_IDENTIDADE,SENHA_IDENTIDADE_CRIPTO,SENHA_IDENTIDADE_CRIPTO_SINC,HIS_ID_INI,HIS_DT_INI,HIS_IDC_INI,HIS_DT_FIM,HIS_IDC_FIM,HIS_ATIVO)
 SELECT (CORPORATIVO.SEQ_IDENTIDADE.Nextval), 1,ID_PESSOA,to_date('26/08/14','DD/MM/RR'), null, null, ID_ORGAO_USU, SESB_PESSOA || MATRICULA, '9ae76b90c76756854ad048d9fd62cb75', null, null, 1, to_date('26/08/14','DD/MM/RR'),1,null,null,1 FROM CORPORATIVO.DP_PESSOA;

drop sequence CORPORATIVO.SEQ_IDENTIDADE;