ALTER TABLE `sigawf`.`wf_movimentacao` 
ADD COLUMN `DEFT_TP_PRIORIDADE_DE` VARCHAR(12) NULL DEFAULT NULL AFTER `DEFT_ID_PARA`,
ADD COLUMN `DEFT_TP_PRIORIDADE_PARA` VARCHAR(12) NULL DEFAULT NULL AFTER `DEFT_TP_PRIORIDADE_DE`,
CHANGE COLUMN `MOVI_TP_DESIGNACAO` `MOVI_TP_DESIGNACAO` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Numa designação, indica o tipo de designação da movimentação' ;

ALTER TABLE `sigawf`.`wf_procedimento` 
CHANGE COLUMN `PROC_TP_PRIORIDADE` `PROC_TP_PRIORIDADE` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Prioridade do procedimento' ,
CHANGE COLUMN `PROC_ST_CORRENTE` `PROC_ST_CORRENTE` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Status atual do procedimento' ,
CHANGE COLUMN `PROC_CD_PRINCIPAL` `PROC_CD_PRINCIPAL` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Código do principal relacionado ao procedimento, no caso de um documento, é algo do tipo JFRJ-MEM-2020/000001' ,
CHANGE COLUMN `PROC_TP_PRINCIPAL` `PROC_TP_PRINCIPAL` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Tipo do principal do procedimento' ;

ALTER TABLE `sigawf`.`wf_def_responsavel` 
CHANGE COLUMN `DEFR_TP` `DEFR_TP` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Tipo da definição de responsável' ;

ALTER TABLE `sigawf`.`wf_def_variavel` 
CHANGE COLUMN `DEFV_TP` `DEFV_TP` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Tipo da definição de variável' ,
CHANGE COLUMN `DEFV_TP_ACESSO` `DEFV_TP_ACESSO` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Tipo de acesso da definição de variável' ;

ALTER TABLE `sigawf`.`wf_variavel` 
CHANGE COLUMN `VARI_NM` `VARI_NM` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Nome da variável' ;
