ALTER TABLE `sigawf`.`wf_def_procedimento` 
ADD COLUMN `DEFP_TP_PRINCIPAL` VARCHAR(45) NOT NULL DEFAULT 'DOCUMENTO' COMMENT 'Tipo de principal aceito pelo diagrama' AFTER `GRUP_ID_EDICAO`;

ALTER TABLE `sigawf`.`wf_def_procedimento` 
ADD COLUMN `DEFP_TP_VINCULO_PRINCIPAL` VARCHAR(45) NULL DEFAULT 'OBRIGATORIO_E_EXCLUSIVO' COMMENT 'Tipo de vínculo com o principal' AFTER `DEFP_TP_PRINCIPAL`;

UPDATE `sigawf`.`wf_procedimento` SET PROC_TP_PRINCIPAL = 'DOCUMENTO' WHERE PROC_TP_PRINCIPAL = 'DOC';